Repository artsy/reaction, pull requests merged in 2018-12, with the labels that each got.

#1622 [PATCH makeoffer] Get the offer price from myLastOffer, not Order
  src/Apps/Order/Components/OfferSummaryItem.tsx
  src/__generated__/OfferSummaryItem_order.graphql.ts
  src/__generated__/routes_ReviewQuery.graphql.ts
Labels: Jira Synced

#1625 Countdown timer
  package.json
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/__stories__/OrderApp.story.tsx
  src/Components/WithCurrentTime.tsx
  src/Styleguide/Components/CountdownTimer.tsx
  src/Styleguide/Components/Timer.tsx
  src/Styleguide/Components/__stories__/CountdownTimer.story.tsx
  src/Styleguide/Components/__tests__/CountdownTimer.test.tsx
  src/Styleguide/Components/__tests__/Timer.test.tsx
  src/Styleguide/Elements/icons/TimerIcon.tsx
  src/Utils/getCurrentTimeAsIsoString.ts
  src/__generated__/Respond_order.graphql.ts
  src/__generated__/routes_RespondQuery.graphql.ts
  yarn.lock
Labels: Jira Synced

#1627 @alloy => Make sure not to fetch follow suggestions unless specified
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Components/FollowButton/FollowArtistButton.tsx
  src/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/__generated__/ArtistInfoQuery.graphql.ts
  src/__generated__/ArtistInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarArtists_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarArtists_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/FollowArtistButton_artist.graphql.ts
  src/__generated__/RelatedArtistsListQuery.graphql.ts
  src/__generated__/RelatedArtists_Test_Query.graphql.ts
  src/__generated__/TooltipsDataLoaderQuery.graphql.ts
  src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
  src/__generated__/routes_RelatedArtistsQuery.graphql.ts
Labels: Jira Synced

#1630 Parameterize copy in TransactionDetailsSummaryItem
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Components/__stories__/TransactionDetailsSummaryItem.story.tsx
  src/Apps/Order/Components/__tests__/TransactionDetailsSummary.test.tsx
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/TransactionDetailsSummaryItemOfferProperties.graphql.ts
  src/__generated__/TransactionDetailsSummaryItemStoryQuery.graphql.ts
  src/__generated__/TransactionDetailsSummaryItemTestQuery.graphql.ts
  src/__generated__/TransactionDetailsSummaryItem_order.graphql.ts
  src/__generated__/routes_OfferQuery.graphql.ts
  src/__generated__/routes_PaymentQuery.graphql.ts
  src/__generated__/routes_RespondQuery.graphql.ts
  src/__generated__/routes_ReviewQuery.graphql.ts
  src/__generated__/routes_ShippingQuery.graphql.ts
  src/__generated__/routes_StatusQuery.graphql.ts
Labels: Jira Synced

#1629 Refactor redirect logic
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/Order/redirects.tsx
  src/Apps/Order/routes.tsx
  src/Apps/__stories__/OrderApp.story.tsx
  src/__generated__/routes_OrderQuery.graphql.ts
Labels: Jira Synced

#1609 DISCO-514: Add sidebar components for Buy Now / Make offer artworks
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/__stories__/ArtworkSidebar/ArtworkSidebarCommercial.story.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarCommercial.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCommercial.ts
  src/__generated__/ArtworkSidebarCommercialOrderMutation.graphql.ts
  src/__generated__/ArtworkSidebarCommercial_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercial_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#1639 Test the respond page
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Styleguide/Components/__tests__/CountdownTimer.test.tsx
  src/Styleguide/Components/__tests__/Timer.test.tsx
  src/Utils/__mocks__/getCurrentTimeAsIsoString.ts
Labels: Jira Synced

#1648 [FIX analytics] fixes an issue where Artworks impressions not tracked on Collect and Collections pages
  src/Components/Artwork/GridItem.tsx
  src/__generated__/ArtworkContextArtistQuery.graphql.ts
  src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkContextFairQuery.graphql.ts
  src/__generated__/ArtworkContextFair_Test_Query.graphql.ts
  src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
  src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
  src/__generated__/ArtworkFilterArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkGridExampleQuery.graphql.ts
  src/__generated__/ArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkGrid_Test_Query.graphql.ts
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectArtworkGridQuery.graphql.ts
  src/__generated__/CollectArtworkGridTestQuery.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/ComparablesQuery.graphql.ts
  src/__generated__/ComparablesViewQuery.graphql.ts
  src/__generated__/GeneArtworksContentQuery.graphql.ts
  src/__generated__/GeneContentsArtworksQuery.graphql.ts
  src/__generated__/GridItem_artwork.graphql.ts
  src/__generated__/SaveArtworkQuery.graphql.ts
  src/__generated__/TagArtworksContentQuery.graphql.ts
  src/__generated__/TagContentsArtworksQuery.graphql.ts
  src/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
Labels: Jira Synced

#1649 add cultural maker display
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarArtists.test.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarArtists.ts
  src/__generated__/ArtworkSidebarArtists_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarArtists_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#1657 Use totalListPrice for list price in /offer
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
  src/__generated__/OfferMutation.graphql.ts
  src/__generated__/Offer_order.graphql.ts
  src/__generated__/routes_OfferQuery.graphql.ts
Labels: Jira Synced

#1659 [FIX tracking] Fix tracking on artwork pages
  src/Apps/Artwork/Components/ArtworkDetails/index.tsx
  src/Apps/Collect/Components/Collection/Header/index.tsx
  src/Styleguide/Components/ReadMore.tsx
Labels: Jira Synced

#1661 @mzikherman => Revert "Support collecting institution works"
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCommercial.ts
  src/__generated__/ArtworkSidebarCommercial_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercial_artwork.graphql.ts
  src/__generated__/ArtworkSidebarPartnerInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarPartnerInfo_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Merge On Green

#1665 [FIX artwork] Properly transition to different images
  src/Apps/Artwork/Components/ImageCarousel.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
Labels: Merge On Green

#1666 [FIX artwork] Fix back arrow
  src/Apps/Artwork/Components/ImageCarousel.tsx
Labels: Merge On Green

#1667 [PATCH artwork] Update artwork count
  package.json
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextAuction.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/AuctionArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/FairArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerShowArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
  src/__generated__/ArtistArtworkGrid_artwork.graphql.ts
  src/__generated__/ArtworkContextArtistQuery.graphql.ts
  src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkContextFairQuery.graphql.ts
  src/__generated__/ArtworkContextFair_Test_Query.graphql.ts
  src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
  src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
  src/__generated__/AuctionArtworkGrid_artwork.graphql.ts
  src/__generated__/FairArtworkGrid_artwork.graphql.ts
  src/__generated__/PartnerArtworkGrid_artwork.graphql.ts
  src/__generated__/PartnerShowArtworkGrid_artwork.graphql.ts
  src/__generated__/RelatedWorksArtworkGridQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_Test_Query.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_artwork.graphql.ts
Labels: Merge On Green

#1674 Adds empty review/reject component and route
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/Order/redirects.tsx
  src/Apps/Order/routes.tsx
  src/Apps/__stories__/OrderApp.story.tsx
  src/__generated__/Reject_order.graphql.ts
  src/__generated__/routes_RejectQuery.graphql.ts
Labels: Jira Synced

#1677 Add accept offer mutation and corresponding status screen
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/acceptOffer.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/index.ts
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/Order/routes.tsx
  src/__generated__/AcceptOfferMutation.graphql.ts
  src/__generated__/Accept_order.graphql.ts
  src/__generated__/routes_AcceptQuery.graphql.ts
Labels: Jira Synced

#1690 Create reject review screen
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/__generated__/Reject_order.graphql.ts
  src/__generated__/routes_RejectQuery.graphql.ts
Labels: Jira Synced

#1660 First pass in fixing createToken stripe not showing errors
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Artsy/Router/Components/Boot.tsx
Labels: Jira Synced

#1679 Replace onClick={href} with a normal <a href="..."> in EntityHeader
  src/Apps/Collections/Components/CollectionsGrid.tsx
  src/Styleguide/Components/EntityHeader.tsx
Labels: Jira Synced

#1608 Add h1, h2 to artist head for SEO
  src/Apps/Artist/Components/ArtistHeader.tsx
Labels: Jira Synced

#1699 Show error modal on accept offer review page if charge capture fails
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/acceptOffer.ts
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
Labels: Jira Synced

#1694 Hook up counter offer mutation on respond page
  data/schema.graphql
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Utils/flushPromiseQueue.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/Respond_order.graphql.ts
  src/__generated__/routes_RespondQuery.graphql.ts
Labels: Jira Synced

#1701 the select for the next available max bid should respect your current max bid
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.ts
  src/__generated__/ArtworkSidebarBidAction_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCurrentBidInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCurrentBidInfo_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#1700 Buyer can reject an offer and see a status page
  __mocks__/react-relay.js
  data/schema.graphql
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/rejectOffer.ts
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/__stories__/OrderApp.story.tsx
  src/__generated__/RejectOfferMutation.graphql.ts
  src/__generated__/Reject_order.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/Status_order.graphql.ts
  src/__generated__/routes_RejectQuery.graphql.ts
  src/__generated__/routes_StatusQuery.graphql.ts
Labels: Jira Synced

#1709 @damassi => Add Meta tags to artwork page
  .storybook/webpack.config.js
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkMeta.tsx
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/ArtworkMeta_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  typings/sharify.d.ts
Labels: Merge On Green

#1713 starting work to display RelatedArtists on Artwork page
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
  src/Styleguide/Components/AuctionCard.tsx
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/ArtworkRelatedArtists_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#1720 [PATCH bnmo] fix extra # and submitted offer copy
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
Labels: Jira Synced

#1718 [Artwork] Implement share modal functionality
  package.json
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkDetails/index.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ActionButtons.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArrowButton.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/Share.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__stories__/ArtworkActions.story.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__stories__/ArtworkImageBrowser.story.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.test.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar/ArtworkSidebarArtists.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar/ArtworkSidebarBidActionStory.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar/ArtworkSidebarClassification.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar/ArtworkSidebarCommercial.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar/ArtworkSidebarExtraLinks.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar/ArtworkSidebarMetadata.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar/ArtworkSidebarPageviews.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar/ArtworkSidebarPartnerInfo.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar/ArtworkSidebarSizeInfo.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebar/ArtworkSidebarTitleInfo.story.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/AuctionArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/FairArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerShowArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/Header.tsx
  src/Apps/Artwork/Components/__stories__/ArtworkImageBrowser/ActionButtons.story.tsx
  src/Apps/Artwork/Components/__stories__/Share.story.tsx
  src/Assets/Icons/Bell.tsx
  src/Assets/Icons/Heart.tsx
  src/Components/Artwork/Save.tsx
  src/__generated__/ArtworkActions_artwork.graphql.ts
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/ArtworkImageBrowser_artwork.graphql.ts
  src/__generated__/ArtworkSharePanel_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#1715 @ds300 => Add support for using current time from Gravity to offset timer
  src/Components/WithCurrentTime.tsx
  src/Styleguide/Components/AuctionCard.tsx
  src/Styleguide/Components/Timer.tsx
  src/Utils/__tests__/time.test.ts
  src/Utils/time.ts
Labels: Merge On Green

#1717 [PATCH publishing] fix z-index on news sub-menu
  src/Components/Publishing/Nav/NewsNav.tsx
  src/Components/Publishing/Nav/__tests__/__snapshots__/NewsNav.test.tsx.snap
Labels: Merge On Green

#1711 Refactor shouldRedirect logic for Make Offer & add unit test coverage
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/Order/__tests__/getRedirect.test.ts
  src/Apps/Order/getRedirect.ts
  src/Apps/Order/redirects.tsx
  src/Apps/Order/routes.tsx
Labels: Jira Synced

#1727 Remove invisible spinner
  src/Apps/Order/Routes/Respond/index.tsx
Labels: Jira Synced

#1724 [PATCH bnmo] Redirect to respond from status page if awaiting buyer response
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/Order/redirects.tsx
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#1726 [PATCH publishing] EOY Culture sticky headers
  src/Components/Publishing/EditorialFeature/Components/Eoy2018Culture.tsx
Labels: Jira Synced

#1716 [FIX bnmo] Round offer values to two decimal places
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
Labels: Jira Synced

#1731 Fix/offer history button
  src/Apps/Order/Components/OfferHistoryItem.tsx
  src/Apps/Order/Components/__tests__/OfferHistoryItem.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Components/StaticCollapse.tsx
Labels: Jira Synced

#1736 Fetch awaitingResponseFrom in response from counter offer submit mutation
  src/Apps/Order/Routes/Counter/index.tsx
  src/__generated__/CounterSubmitMutation.graphql.ts
Labels: Jira Synced

#1741 [PATCH ArtworkBanner] update spacing
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkBanner/Banner.tsx
Labels: Merge On Green

#1719 [PATCH publishing] adds social embed to sections
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
Labels: Jira Synced, Merge On Green

#1739 Validate offer amount
  package.json
  src/Apps/Order/Components/OfferInput.tsx
  src/Apps/Order/Components/__stories__/OfferInput.story.tsx
  src/Apps/Order/Components/__tests__/OfferInput.test.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Components/Input.tsx
  src/Components/__stories__/Input.story.tsx
  yarn.lock
Labels: Jira Synced

#1747 [TRIVIAL] Fix indentation on EOY tooltip links
  src/Components/Publishing/ToolTip/LinkWithTooltip.tsx
Labels: Merge On Green

#1751 [Artwork] Add Bell icon when artwork is in auction and not closed
  src/Apps/Artwork/Components/ArtworkBanner/Banner.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__stories__/ArtworkActions.story.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkActions.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSharePanel.fixture.ts
  src/Assets/Icons/Bell.tsx
  src/Assets/Icons/Heart.tsx
  src/Components/Artwork/Save.tsx
  src/__generated__/ArtistsQuery.graphql.ts
  src/__generated__/ArtworkActions_artwork.graphql.ts
  src/__generated__/ArtworkContextArtistQuery.graphql.ts
  src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkContextFairQuery.graphql.ts
  src/__generated__/ArtworkContextFair_Test_Query.graphql.ts
  src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
  src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
  src/__generated__/ArtworkFilterArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkGridExampleQuery.graphql.ts
  src/__generated__/ArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkGrid_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectArtworkGridQuery.graphql.ts
  src/__generated__/CollectArtworkGridTestQuery.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/ComparablesQuery.graphql.ts
  src/__generated__/ComparablesViewQuery.graphql.ts
  src/__generated__/FillwidthQuery.graphql.ts
  src/__generated__/GeneArtworksContentQuery.graphql.ts
  src/__generated__/GeneContentsArtistsQuery.graphql.ts
  src/__generated__/GeneContentsArtworksQuery.graphql.ts
  src/__generated__/RecentlyViewedQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_Test_Query.graphql.ts
  src/__generated__/SaveArtworkQuery.graphql.ts
  src/__generated__/Save_artwork.graphql.ts
  src/__generated__/TagArtworksContentQuery.graphql.ts
  src/__generated__/TagContentsArtworksQuery.graphql.ts
  src/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
Labels: Jira Synced

#1752 [Share] Fix unneeded call
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Components/Artwork/Save.tsx
  src/__generated__/ArtistsQuery.graphql.ts
  src/__generated__/ArtworkContextArtistQuery.graphql.ts
  src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkContextFairQuery.graphql.ts
  src/__generated__/ArtworkContextFair_Test_Query.graphql.ts
  src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
  src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
  src/__generated__/ArtworkFilterArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkGridExampleQuery.graphql.ts
  src/__generated__/ArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkGrid_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectArtworkGridQuery.graphql.ts
  src/__generated__/CollectArtworkGridTestQuery.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/ComparablesQuery.graphql.ts
  src/__generated__/ComparablesViewQuery.graphql.ts
  src/__generated__/FillwidthQuery.graphql.ts
  src/__generated__/GeneArtworksContentQuery.graphql.ts
  src/__generated__/GeneContentsArtistsQuery.graphql.ts
  src/__generated__/GeneContentsArtworksQuery.graphql.ts
  src/__generated__/RecentlyViewedQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_Test_Query.graphql.ts
  src/__generated__/SaveArtworkQuery.graphql.ts
  src/__generated__/Save_artwork.graphql.ts
  src/__generated__/TagArtworksContentQuery.graphql.ts
  src/__generated__/TagContentsArtworksQuery.graphql.ts
  src/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
Labels: Merge On Green

#1753 [PATCH OtherAuctions] - responsive view for other auctions.
  src/Styleguide/Components/ArtistCard.tsx
  src/Styleguide/Components/AuctionCard.tsx
Labels: Jira Synced

#1754 [PATCH Sidebar] - make commercial buttons bigger.
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Styleguide/Components/ArtistCard.tsx
Labels: Jira Synced

#1757 [Artwork] Add conditions of sale link
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Styleguide/Components/Footer.tsx
Labels: Jira Synced, Merge On Green

#1759 [PATCH recentlyViewed] Fix mobile scrolling
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Styleguide/Components/Carousel.tsx
  src/Styleguide/Components/RecentlyViewed.tsx
Labels: Jira Synced

#1760 [PATCH artwork] Fix issue where rapid selects selects image background
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Styleguide/Components/Carousel.tsx
Labels: Merge On Green

#1761 [PATCH artwork] Pass mediator to related grids to trigger modal when saving
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/AuctionArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/FairArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerShowArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
Labels: Jira Synced

#1762 [PATCH artwork] Hide grids if no content
  src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/AuctionArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/FairArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerShowArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/index.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
  src/__generated__/ArtistArtworkGrid_artwork.graphql.ts
  src/__generated__/ArtworkContextArtistQuery.graphql.ts
  src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkContextFairQuery.graphql.ts
  src/__generated__/ArtworkContextFair_Test_Query.graphql.ts
  src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
  src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
  src/__generated__/AuctionArtworkGrid_artwork.graphql.ts
  src/__generated__/FairArtworkGrid_artwork.graphql.ts
  src/__generated__/PartnerArtworkGrid_artwork.graphql.ts
  src/__generated__/PartnerShowArtworkGrid_artwork.graphql.ts
  src/__generated__/RelatedWorksArtworkGridQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_Test_Query.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_artwork.graphql.ts
Labels: Jira Synced

#1763 [PATCH artwork] Fix mobile lightbox
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
Labels: Merge On Green

#1764 [PATCH artwork] Fix auth in ArtistCardFollow
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Styleguide/Components/ArtistCard.tsx
Labels: Jira Synced, Merge On Green

#1765 [PATCH artwork] Add slight delay to follow artist panel swap
  src/Styleguide/Components/FollowArtistPopover/FollowArtistPopoverRow.tsx
Labels: Merge On Green

#1769 [PATCH BidActions] - User should be able to watch live bidding when registration is closed and live bidding is in progress
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkBanner/Banner.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarBidAction.ts
Labels: Jira Synced

#1767 Misc UI fixes for counteroffer pages
  src/Apps/Order/Components/ArtworkSummaryItem.tsx
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/Counter/index.tsx
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/__stories__/OrderApp.story.tsx
  src/__generated__/Counter_order.graphql.ts
  src/__generated__/Reject_order.graphql.ts
  src/__generated__/routes_CounterQuery.graphql.ts
  src/__generated__/routes_RejectQuery.graphql.ts
  src/__stories__/config.js
Labels: Jira Synced

#1768 Fix 'Back to Artsy' link
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/__tests__/getRedirect.test.ts
  src/Apps/Order/getRedirect.ts
  src/Apps/Order/redirects.tsx
  src/Apps/Order/routes.tsx
  src/Apps/__tests__/Fixtures/Order.ts
Labels: Jira Synced

#1766 [PATCH artwork] Fix share messages
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/ArtworkSharePanel_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#1771 [PATCH artwork] Fix safari mail issue
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
Labels: Jira Synced, Merge On Green
