Repository artsy/reaction, pull requests merged in 2018-11, with the labels that each got.

#1474 Fix a bug where the sort option is always set to "-decayed_merch" on both Collect and Collection
  src/Apps/Collect/__tests__/routes.test.tsx
  src/Apps/Collect/routes.tsx
Labels: Jira Synced

#1475 User should see see the same results after a page refresh on the collection page
  src/Apps/Collect/CollectionApp.tsx
  src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
  src/Apps/Collect/routes.tsx
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionApp_collection.graphql.ts
  src/__generated__/CollectionFilterContainer_collection.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Jira Synced

#1482 Automatically opt-in mobile users who sign up from an editorial page to the daily newsletter
  src/Components/Publishing/Banner/Banner.tsx
Labels: Jira Synced

#1479 Add Sentry to Reaction
  package.json
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Artsy/Router/Components/Boot.tsx
  src/Artsy/Router/Components/__test__/Boot.test.tsx
  src/Components/ErrorBoundary.tsx
  src/Utils/__test__/errors.test.ts
  src/Utils/__test__/logger.test.ts
  src/Utils/errors.tsx
  src/Utils/logger.ts
  typings/sharify.d.ts
  yarn.lock
Labels: Jira Synced

#1493 [PATCH makeOffer] Add a helpful message to “offer” step
  src/Apps/Order/Routes/Offer/index.tsx
Labels: Jira Synced

#1496 add metadata description for collect and collection page
  src/Apps/Collect/CollectApp.tsx
  src/Apps/Collect/CollectMediumMetadata.ts
  src/Apps/Collect/CollectionApp.tsx
  src/Apps/Collect/__tests__/CollectMediumMetadata.test.ts
  src/Apps/Collect/__tests__/CollectionApp.test.tsx
Labels: Jira Synced

#1504 small visual fix for works for you render
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artwork/ArtworkApp.tsx
Labels: Jira Synced

#1503 [FIX OfferAmount] Switch to offerAmount and pass amount and currencyCode
  data/schema.graphql
  src/Apps/Order/Components/__stories__/TransactionSummary.story.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/__generated__/OfferMutation.graphql.ts
Labels: Jira Synced

#1510 Add offer stepper to Shipping/Payment/Review
  src/Apps/Order/Components/OrderStepper.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Apps/__stories__/OrderApp.story.tsx
  src/Styleguide/Components/Stepper.tsx
  src/Styleguide/Components/Tabs.tsx
  src/__generated__/Payment_order.graphql.ts
  src/__generated__/Review_order.graphql.ts
  src/__generated__/Shipping_order.graphql.ts
  src/__generated__/routes_PaymentQuery.graphql.ts
  src/__generated__/routes_ReviewQuery.graphql.ts
  src/__generated__/routes_ShippingQuery.graphql.ts
Labels: Jira Synced

#1525 [FEATURE publishing] add pixel tracking code on articles for sponsors
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/Fixtures/Components.ts
  src/Components/Publishing/__tests__/Article.test.tsx
Labels: Jira Synced

#1529 Offer status page
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/__stories__/OrderApp.story.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/Status_order.graphql.ts
  src/__generated__/routes_StatusQuery.graphql.ts
Labels: Jira Synced

#1530 Visual part of Extra links for all type of works
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
  src/Apps/Artwork/Components/__stories__/ArtworkSidebar/ArtworkSidebarExtraLinks.story.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarExtraLinks.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarExtraLinks.ts
  src/__generated__/ArtworkSidebarExtraLinks_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarExtraLinks_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#1538 Fix elements that were specifying lineHeight={18}; specify lineHeight as 1.1em instead.
  src/Apps/Order/Components/AddressForm.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Components/Payment/PaymentForm.tsx
Labels: Jira Synced

#1533 [FIX readmore] Fixes an issue where /collection/ story "read more" appearing after the credit line
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Jira Synced

#1548 Add analytics tracking for "read more" in Collection pages
  src/Apps/Collect/CollectionApp.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/Styleguide/Components/ReadMore.tsx
Labels: Jira Synced

#1537 Fix instagram embeds
  src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
  src/Components/Publishing/Sections/SocialEmbed.tsx
  src/Components/Publishing/Sections/__tests__/SocialEmbed.test.tsx
  src/Components/Publishing/__tests__/Article.test.tsx
  yarn.lock
Labels: Jira Synced

#1546 Collections groupings
  data/schema.graphql
  src/Apps/Collect/CollectApp.tsx
  src/Apps/Collect/Components/Collection/Header/index.tsx
  src/Apps/Collections/CollectionsApp.tsx
  src/Apps/Collections/Components/CollectionsGrid.tsx
  src/Apps/Collections/Components/__tests__/CollectionsGrid.test.tsx
  src/Apps/Collections/__tests__/CollectionsApp.test.tsx
  src/Apps/Collections/routes.tsx
  src/Apps/__test__/Fixtures/CollectionsFixture.ts
  src/Apps/__tests__/Fixtures/Collections.ts
  src/__generated__/CollectionsAppQuery.graphql.ts
  src/__generated__/CollectionsApp_categories.graphql.ts
  src/__generated__/CollectionsApp_collections.graphql.ts
  src/__generated__/routes_MarketingCollectionsAppQuery.graphql.ts
Labels: Jira Synced

#1553 Implement action icons
  .env.oss
  src/Apps/Artwork/Components/ActionButton.tsx
  src/Apps/Artwork/Components/ArtworkImages.tsx
  src/Apps/Artwork/Components/ImageCarousel.tsx
  src/Apps/Artwork/Components/Share.tsx
  src/Apps/Artwork/Components/__stories__/ActionButtons.story.tsx
  src/Apps/Artwork/Components/__stories__/ArtworkImages.story.tsx
  src/Apps/Artwork/Components/__stories__/ImageCarousel.story.tsx
Labels: Jira Synced

#1551 @sweir27 => Show Bid badge and sale info on an artwork when sale is in a preview state
  src/Components/Artwork/Details.tsx
  src/Components/Artwork/GridItem.tsx
  src/Components/Artwork/__tests__/Details.test.tsx
  src/__generated__/ArtistsQuery.graphql.ts
  src/__generated__/ArtworkFilterArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkGridExampleQuery.graphql.ts
  src/__generated__/ArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkGrid_Test_Query.graphql.ts
  src/__generated__/ArtworkMetadataQuery.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/CollectArtworkGridQuery.graphql.ts
  src/__generated__/CollectArtworkGridTestQuery.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/ComparablesQuery.graphql.ts
  src/__generated__/ComparablesViewQuery.graphql.ts
  src/__generated__/Details_Test_Query.graphql.ts
  src/__generated__/Details_artwork.graphql.ts
  src/__generated__/FillwidthQuery.graphql.ts
  src/__generated__/GeneArtworksContentQuery.graphql.ts
  src/__generated__/GeneContentsArtistsQuery.graphql.ts
  src/__generated__/GeneContentsArtworksQuery.graphql.ts
  src/__generated__/GridItem_artwork.graphql.ts
  src/__generated__/InquiryArtworkQuery.graphql.ts
  src/__generated__/RecentlyViewedQuery.graphql.ts
  src/__generated__/SaveArtworkQuery.graphql.ts
  src/__generated__/TagArtworksContentQuery.graphql.ts
  src/__generated__/TagContentsArtworksQuery.graphql.ts
  src/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
Labels: Jira Synced

#1520 Update with latest MP/Exchange and remove offerTotalCents
  src/Apps/Order/Components/TransactionSummary.tsx
  src/Apps/Order/Components/__stories__/TransactionSummary.story.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/initialOffer.ts
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/OfferMutation.graphql.ts
  src/__generated__/Offer_order.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/TransactionSummary_order.graphql.ts
  src/__generated__/routes_OfferQuery.graphql.ts
  src/__generated__/routes_PaymentQuery.graphql.ts
  src/__generated__/routes_ReviewQuery.graphql.ts
  src/__generated__/routes_ShippingQuery.graphql.ts
  src/__generated__/routes_StatusQuery.graphql.ts
Labels: Merge On Green

#1549 [FIX display] Fixes an issue where display logo is not centered properly
  src/Components/Publishing/Display/Canvas/CanvasText.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayCanvas.test.tsx.snap
Labels: Jira Synced, Merge On Green

#1550 [PATCH collection] add header tag to collection pages
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Jira Synced, Merge On Green

#1558 @damassi => Add props to Timer for optional label display, create AuctionTimer
  src/Styleguide/Components/AuctionTimer.tsx
  src/Styleguide/Components/Timer.tsx
  src/Styleguide/Components/__stories__/AuctionTimer.story.tsx
  src/Styleguide/Components/__stories__/Timer.story.tsx
  src/__generated__/AuctionTimerQuery.graphql.ts
  src/__generated__/AuctionTimer_sale.graphql.ts
  yarn.lock
Labels: Merge On Green

#1559 Adds a link to the partner in an artwork page under 'about this work'
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/__generated__/ArtworkDetailsAboutTheWorkFromPartner_artwork.graphql.ts
  src/__generated__/ArtworkDetailsQuery.graphql.ts
  src/__generated__/ArtworkDetails_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced

#1561 minor convert relative links to DevTools to absolute path
  src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarClassification.test.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarExtraLinks.test.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarMetadata.test.tsx
  src/Apps/Collect/Components/Base/__tests__/CollectArtworkGrid.test.tsx
  src/Apps/Collect/__tests__/CollectionApp.test.tsx
  src/Apps/Collect/__tests__/routes.test.tsx
  src/Apps/Collections/__tests__/CollectionsApp.test.tsx
  src/Components/Artwork/__tests__/Details.test.tsx
  src/Components/ArtworkGrid/__tests__/ArtworkGrid.test.tsx
Labels: Merge On Green

#1560 [FEATURE SEO] Update meta and title tag for Collections index page
  src/Apps/Collections/CollectionsApp.tsx
Labels: Jira Synced

#1565 DISCO-513: Prefer partner info to `collecting_institution` field in artwork sidebar
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
Labels: Jira Synced

#1563 [PATCH publishing] increase the size on sponors logo height
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  src/Components/Publishing/Partner/PartnerInline.tsx
Labels: Jira Synced

#1574 Offer review UI
  src/Apps/Order/Components/CreditCardDetails.tsx
  src/Apps/Order/Components/ShippingAddress.tsx
  src/Apps/Order/Components/ShippingAndPaymentReview.tsx
  src/Apps/Order/Components/__stories__/ShippingAndPaymentDetails.story.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Styleguide/Components/StepSummaryItem.tsx
  src/Styleguide/Elements/icons/CreditCardIcon.tsx
  src/__generated__/ShippingAndPaymentDetailsQuery.graphql.ts
  src/__generated__/ShippingAndPaymentReview_order.graphql.ts
  src/__generated__/routes_ReviewQuery.graphql.ts
Labels: Jira Synced

#1576 [FEATURE Publishing] Conditionally apply cover overlay
  src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayCanvas.test.tsx.snap
Labels: Jira Synced

#1597 [PATCH package] Bump relay network lib to fix silent errors issue
  package.json
  yarn.lock
Labels: Jira Synced

#1599 Add spec for Responsive Artwork Page (RAP) PartnerInfo component
  src/Apps/Artwork/Components/__tests__/ArtworkSidebar/ArtworkSidebarPartnerInfo.test.tsx
  src/__generated__/ArtworkSidebarPartnerInfo_Test_Query.graphql.ts
Labels: Jira Synced

#1601 [PATCH collections] fixes spacing on the collections page
  src/Apps/Collections/Components/CollectionsGrid.tsx
Labels: Jira Synced

#1598 Slideshow updates for EOY
  src/Components/Publishing/Fixtures/Components.ts
  src/Components/Publishing/Sections/ImageSetPreview.tsx
  src/Components/Publishing/Sections/ImageSetPreview/ImageSetLabel.tsx
  src/Components/Publishing/Sections/ImageSetPreview/ImageSetPreview.tsx
  src/Components/Publishing/Sections/ImageSetPreview/ImageSetPreviewClassic.tsx
  src/Components/Publishing/Sections/ImageSetPreview/__tests__/ImageSetPreview.test.tsx
  src/Components/Publishing/Sections/ImageSetPreview/__tests__/ImageSetPreviewClassic.test.tsx
  src/Components/Publishing/Sections/ImageSetPreview/__tests__/__snapshots__/ImageSetPreview.test.tsx.snap
  src/Components/Publishing/Sections/ImageSetPreview/__tests__/__snapshots__/ImageSetPreviewClassic.test.tsx.snap
  src/Components/Publishing/Sections/ImageSetPreview/index.ts
  src/Components/Publishing/Sections/__tests__/__snapshots__/ImageSetPreview.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/__stories__/ImageSetPreview.story.tsx
  src/Components/Publishing/index.tsx
Labels: Merge On Green

#1595 Article Nav accepts color props
  src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/index.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Nav/Nav.tsx
  src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  src/Components/Publishing/__stories__/Nav.story.tsx
Labels: Jira Synced, Merge On Green

#1600 My last offer transaction summary
  data/schema.graphql
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Components/__stories__/TransactionDetailsSummaryItem.story.tsx
  src/Apps/Order/Components/__tests__/TransactionDetailsSummary.test.tsx
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/__stories__/OrderApp.story.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/Status_order.graphql.ts
  src/__generated__/TransactionDetailsSummaryItemStoryQuery.graphql.ts
  src/__generated__/TransactionDetailsSummaryItemTestQuery.graphql.ts
  src/__generated__/TransactionDetailsSummaryItem_order.graphql.ts
  src/__generated__/routes_OfferQuery.graphql.ts
  src/__generated__/routes_PaymentQuery.graphql.ts
  src/__generated__/routes_RespondQuery.graphql.ts
  src/__generated__/routes_ReviewQuery.graphql.ts
  src/__generated__/routes_ShippingQuery.graphql.ts
  src/__generated__/routes_StatusQuery.graphql.ts
Labels: Jira Synced

#1605 Switch to use addInitialOfferToOrder
  data/schema.graphql
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/initialOffer.ts
  src/__generated__/OfferMutation.graphql.ts
Labels: Jira Synced
