Repository artsy/reaction, pull requests merged in 2019-10, with the labels that each got.

#2863 [Refactor] Replace router code with @artsy/arc
  package.json
  src/Apps/Artist/Components/ArtistCollectionsRail/index.tsx
  src/Artsy/Router/Utils/RenderStatus.tsx
  src/Artsy/Router/Utils/historyMiddlewares.ts
  src/Artsy/Router/__tests__/buildClientApp.test.tsx
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Artsy/Router/index.ts
  src/__generated__/buildClientAppTestQuery.graphql.ts
  src/__generated__/buildServerAppTestQuery.graphql.ts
  yarn.lock
Labels: Version: Major

#2866 [Lib] Remove unused router packages
  package.json
  yarn.lock
Labels: Version: Patch

#2865 [Collection/Id] Re-add missing price sort
  src/Apps/Collect2/Routes/Collection/index.tsx
Labels: Version: Patch

#2845 Fix ArtistCollectionsRail's fetching of collections' artworks
  src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionEntity.tsx
  src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionEntity.test.tsx
  src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesEntity.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesRail.test.tsx
  src/Apps/__tests__/Fixtures/Collections.ts
  src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionEntity.test.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
  src/__generated__/ArtistCollectionEntity_collection.graphql.ts
  src/__generated__/ArtistCollectionsRailQuery.graphql.ts
  src/__generated__/ArtistSeriesEntity_member.graphql.ts
  src/__generated__/CollectionRefetch2Query.graphql.ts
  src/__generated__/CollectionsHubRailsStoryQuery.graphql.ts
  src/__generated__/RelatedCollectionEntity_collection.graphql.ts
Labels: Jira Synced, Version: Patch

#2848 [GROW-1547] increment correctly at smaller breakpoints
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesEntity.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesRail.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionEntity.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionsRail.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
  src/Components/v2/Carousel.tsx
Labels: Jira Synced, Version: Patch

#2870 [Router] Make user path a bit safer
  src/Artsy/Router/buildClientApp.tsx
Labels: Merge On Green, Version: Patch

#2878 @damassi => [Nav] Move notifications dropdown fetching to client
  src/Components/NavBar/Menus/NotificationsMenu.tsx
  src/Components/NavBar/NotificationsBadge.tsx
Labels: Jira Synced, Version: Patch

#2881 [Refactor] Replace QueryRender with SystemQueryRenderer
  src/Apps/Artist/Components/ArtistCollectionsRail/index.tsx
  src/Apps/Artist/Components/MarketDataSummary/index.tsx
  src/Apps/Artist/Components/MarketInsights/index.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkBanner/index.tsx
  src/Apps/Artwork/Components/ArtworkDetails/index.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/Apps/Artwork/Components/OtherAuctions.tsx
  src/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx
  src/Apps/Artwork/Components/__stories__/OtherAuctions.story.tsx
  src/Apps/Artwork/Components/__stories__/OtherWorks.story.tsx
  src/Apps/Auction/Components/AuctionFAQ.tsx
  src/Apps/Collect2/Routes/Collection/Components/__stories__/CollectionsHubRails.story.tsx
  src/Apps/WorksForYou/index.tsx
  src/Artsy/Relay/RootQueryRenderer.tsx
  src/Artsy/Relay/SystemQueryRenderer.tsx
  src/Components/CollectionsRail/index.tsx
  src/Components/Gene/index.tsx
  src/Components/NavBar/Menus/NotificationsMenu.tsx
  src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
  src/Components/Onboarding/Steps/Artists/PopularArtists.tsx
  src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
  src/Components/Onboarding/Steps/Genes/SuggestedGenes.tsx
  src/Components/Payment/UserSettingsPayments.tsx
  src/Components/Publishing/ToolTip/TooltipsDataLoader.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/Tag/index.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/Components/v2/AuctionTimer.tsx
  src/Components/v2/FollowArtistPopover/index.tsx
  src/Components/v2/RecentlyViewed.tsx
  src/Components/v2/__stories__/CollectionsHubsHomepageNav.story.tsx
  src/Components/v2/__stories__/CollectionsHubsNav.story.tsx
  src/DevTools/MockRelayRenderer.tsx
  src/DevTools/__tests__/MockRelayRendererFixtures.tsx
Labels: Version: Minor

#2874 Collection hubs QA
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
Labels: Jira Synced, Version: Patch

#2884 Add hooks for cypress in the PaymentPicker
  src/Apps/Order/Components/PaymentPicker.tsx
Labels: Version: Minor

#2885 [Refactor] Update Utils/time to use `fetchQuery`
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Components/WithCurrentTime.tsx
  src/Components/v2/__tests__/CountdownTimer.test.tsx
  src/Components/v2/__tests__/Timer.test.tsx
  src/Utils/__tests__/time.test.ts
  src/Utils/time.ts
  src/__generated__/timeQuery.graphql.ts
  src/setup_jest.ts
Labels: Version: Patch

#2887 [Refactor] Replace mobile LoginForm `metaphysics` calls with `fetchQuery`
  src/Components/Authentication/FormSwitcher.tsx
  src/Components/Authentication/Mobile/LoginForm.tsx
  src/Components/Authentication/Mobile/SignUpForm.tsx
  src/Components/Authentication/__tests__/helpers.test.ts
  src/Components/Authentication/helpers.ts
  src/Utils/__tests__/metaphysics.test.ts
  src/Utils/__tests__/time.test.ts
  src/Utils/metaphysics.ts
  src/Utils/time.ts
  src/__generated__/helpersEmailQuery.graphql.ts
Labels: Version: Patch

#2875 Confirm Bid Page Layout
  src/Apps/Auction/Components/BidForm.tsx
  src/Apps/Auction/Components/LotInfo.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__stories__/Register.story.tsx
  src/Apps/Auction/routes.tsx
  src/__generated__/BidForm_saleArtwork.graphql.ts
  src/__generated__/LotInfo_artwork.graphql.ts
  src/__generated__/LotInfo_saleArtwork.graphql.ts
  src/__generated__/routes_BidQuery.graphql.ts
Labels: Jira Synced, Version: Minor

#2888 @damassi => [Artist] Port meta tags and structured data from Force
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/ArtistMeta.tsx
  src/Apps/Artist/Components/__tests__/ArtistMeta.test.tsx
  src/Components/v2/Seo/Person.tsx
  src/__generated__/ArtistApp_artist.graphql.ts
  src/__generated__/ArtistMeta_artist.graphql.ts
  src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Labels: Version: Minor

#2890 [Refactor] Alias SystemQueryRenderer as QueryRenderer for linting
  src/Apps/Artist/Components/ArtistCollectionsRail/index.tsx
  src/Apps/Artist/Components/MarketDataSummary/index.tsx
  src/Apps/Artist/Components/MarketInsights/index.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkBanner/index.tsx
  src/Apps/Artwork/Components/ArtworkDetails/index.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/Apps/Artwork/Components/OtherAuctions.tsx
  src/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx
  src/Apps/Artwork/Components/__stories__/OtherAuctions.story.tsx
  src/Apps/Artwork/Components/__stories__/OtherWorks.story.tsx
  src/Apps/Auction/Components/AuctionFAQ.tsx
  src/Apps/Collect2/Routes/Collection/Components/__stories__/CollectionsHubRails.story.tsx
  src/Apps/WorksForYou/index.tsx
  src/Components/CollectionsRail/index.tsx
  src/Components/Gene/index.tsx
  src/Components/NavBar/Menus/NotificationsMenu.tsx
  src/Components/Onboarding/Steps/Artists/ArtistSearchResults.tsx
  src/Components/Onboarding/Steps/Artists/PopularArtists.tsx
  src/Components/Onboarding/Steps/Genes/GeneSearchResults.tsx
  src/Components/Onboarding/Steps/Genes/SuggestedGenes.tsx
  src/Components/Payment/UserSettingsPayments.tsx
  src/Components/Publishing/ToolTip/TooltipsDataLoader.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/Tag/index.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/Components/v2/AuctionTimer.tsx
  src/Components/v2/FollowArtistPopover/index.tsx
  src/Components/v2/RecentlyViewed.tsx
  src/Components/v2/__stories__/CollectionsHubsHomepageNav.story.tsx
  src/Components/v2/__stories__/CollectionsHubsNav.story.tsx
  src/DevTools/__tests__/MockRelayRendererFixtures.tsx
Labels: Merge On Green, Version: Patch

#2891 Update `time` util to not cache at relay layer
  src/Utils/time.ts
Labels: Version: Patch

#2882 Fillwidth doesn't fail when image is absent
  src/Utils/fillwidth.ts
Labels: Version: Patch

#2892 [GROW-1587] Ensure content below collection header image respond to image resize at small breakpoint
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
Labels: Jira Synced, Version: Patch

#2893 Swap name prompt in address form based on billing prop
  src/Apps/Order/Components/AddressForm.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
Labels: Version: Patch

#2889 Add secure payment trust signal component
  src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/Apps/Artwork/Components/TrustSignals/SecurePayment.tsx
  src/Apps/Artwork/Components/TrustSignals/TrustSignal.tsx
  src/Apps/Artwork/Components/TrustSignals/__stories__/TrustSignals.story.tsx
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/__generated__/SecurePayment_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Minor

#2880 Grow-1482 collection rail images are insecure and oversized
  src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionEntity.tsx
  src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionEntity.test.tsx
  src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
  src/Apps/__tests__/Fixtures/Collections.ts
  src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionEntity.test.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
  src/Utils/resizer.ts
  src/__generated__/ArtistCollectionEntity_collection.graphql.ts
  src/__generated__/ArtistCollectionsRailQuery.graphql.ts
  src/__generated__/CollectionRefetch2Query.graphql.ts
  src/__generated__/RelatedCollectionEntity_collection.graphql.ts
Labels: Jira Synced, Version: Patch

#2897 [Publising/Text] Update react-html-parser to use DOMParser
  package.json
  src/Components/Publishing/Sections/Text.tsx
  yarn.lock
Labels: Merge On Green, Version: Patch

#2899 Revert dropping htmlparser2 for now due to difficulty running Force test suite
  package.json
  src/Components/Publishing/Sections/Text.tsx
  yarn.lock
Labels: Merge On Green, Version: Patch

#2900 Drop htmlparser2 and parse5 deps from runtime deps
  package.json
  src/Components/Publishing/Constants.ts
  src/Components/Publishing/Sections/Text.tsx
  yarn.lock
Labels: Merge On Green, Version: Patch

#2901 [Publishing] Do not include test fixtures in main exports and bundles
  src/Components/Publishing/index.tsx
Labels: Version: Patch

#2898 [GROW-1580] truncate featured collection description by line count vs characters
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
Labels: Jira Synced, Version: Patch

#2895 [GROW-1587] ensure custom collection header image height is correct at small breakpoint
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
Labels: Jira Synced, Version: Patch

#2902 Collections breadcrumb navigation bug fix
  src/Apps/Collect2/Routes/Collections/Components/CollectionsGrid.tsx
Labels: Jira Synced, Version: Patch

#2903 Add DOMParser polyfill for the server
  package.json
  src/Components/Publishing/Constants.ts
  src/Polyfills/DOMParser.ts
  yarn.lock
Labels: Version: Patch

#2905 [Publishing] Revert SystemQueryRenderer change
  src/Components/Publishing/ToolTip/TooltipsDataLoader.tsx
Labels: Merge On Green, Version: Patch

#2896 Trust signals 2
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
  src/Apps/Artwork/Components/TrustSignals/SecurePayment.tsx
  src/Apps/Artwork/Components/TrustSignals/VerifiedSeller.tsx
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_artwork.graphql.ts
  src/__generated__/AuthenticityCertificate_artwork.graphql.ts
  src/__generated__/VerifiedSeller_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Minor

#2906 Trust signal followup
  src/Apps/Artwork/Components/TrustSignals/VerifiedSeller.tsx
  src/Apps/Artwork/Components/TrustSignals/__stories__/TrustSignals.story.tsx
Labels: Version: Patch

#2908 Use h1 element for page title
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
Labels: Version: Patch

#2910 Remove snapping effect from mobile carousels because it causes weirdness in iOS 13.
  src/Components/v2/Carousel.tsx
Labels: Jira Synced, Version: Patch

#2904 Fixes margins on XS default collection headers
  src/Apps/Collect2/Routes/Collection/Components/Header/DefaultHeader.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/DefaultHeader.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/__snapshots__/DefaultHeader.test.tsx.snap
  src/Components/Modal/ModalWrapper.tsx
  src/Components/Publishing/__stories__/InvertedCSS.story.tsx
  src/Utils/Hooks/useWindowSize.ts
  src/Utils/viewport.ts
Labels: Jira Synced, Version: Patch

#2879 PURCHASE-1433, PURCHASE-1534: Informative error messages and maxHeight for image carousel
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
Labels: Jira Synced, Version: Patch

#2912 @damassi => [Test] Convert artist shows to use renderRelayTree
  src/Apps/Artist/Routes/Shows/__tests__/Shows.test.tsx
  src/__generated__/Shows_Test_Query.graphql.ts
Labels: Version: Patch

#2915 Use `name` from MP for artist series rail, instead of hardcoded text.
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesRail.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
  src/__generated__/ArtistSeriesRail_collectionGroup.graphql.ts
  src/__generated__/CollectionRefetch2Query.graphql.ts
  src/__generated__/CollectionsHubRailsStoryQuery.graphql.ts
Labels: Merge On Green, Version: Patch

#2913 @damassi => Move more specs to `renderRelayTree`
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkActions.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkImageBrowser.fixture.ts
  src/Components/NavBar/Menus/__tests__/NotificationsMenu.test.tsx
  src/__generated__/ArtworkActions_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowser_Test_Query.graphql.ts
Labels: Version: Patch

#2909 Define redirects on Confirm Bid route
  .vscode/settings.json
  src/Apps/Auction/__fixtures__/routes_BidQuery.ts
  src/Apps/Auction/__tests__/routes.test.ts
  src/Apps/Auction/getRedirect.ts
  src/Apps/Auction/routes.tsx
  src/__generated__/routes_BidQuery.graphql.ts
Labels: Jira Synced

#2914 SEO Improvements to the Artist page
  src/Apps/Artist/Routes/Overview/__tests__/Index.fixture.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarExtraLinks.test.tsx
  src/Components/v2/ArtistBio.tsx
  src/Components/v2/__tests__/ArtistBio.test.tsx
Labels: Jira Synced, Version: Minor

#2920 [Order] Don't refer to graphql-js at runtime.
  src/Apps/Order/Utils/commitMutation.tsx
Labels: Jira Synced, Version: Patch

#2923 Don't overwrite the User-Agent header for relay operations
  src/Artsy/Relay/createRelaySSREnvironment.ts
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2921 [Collection] Pass COLLECT_HUBS a/b test to context
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/__stories__/Collect.story.tsx
Labels: Version: Patch

#2924 Fixes carousel for iOS 13
  src/Components/v2/Carousel.tsx
Labels: Version: Patch

#2925 [SEO] Publishing titles use h1
  .gitignore
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/News/NewsHeadline.tsx
  src/Components/Publishing/News/__tests__/__snapshots__/NewsHeadline.test.tsx.snap
  src/Components/Publishing/Series/SeriesTitle.tsx
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesTitle.test.tsx.snap
  src/Components/Publishing/Video/VideoInfoBlock.tsx
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoCover.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoInfoBlock.test.tsx.snap
Labels: Version: Patch

#2926 [createRelaySSREnvironment] Lazy load deps so they can be stripped.
  src/Artsy/Relay/createRelaySSREnvironment.ts
Labels: Version: Patch

#2918 Auct 465 pricing stub
  src/Apps/Auction/Components/BidForm.tsx
  src/Apps/Auction/Components/PricingTransparency.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__stories__/ConfirmBid.story.tsx
  src/Apps/Auction/Routes/__stories__/Register.story.tsx
  src/Apps/Auction/__fixtures__/routes_BidQuery.ts
  src/Apps/Auction/__tests__/routes.test.ts
Labels: Version: Patch

#2919 Add a check for window obj before useLayoutEffect hook
  src/Utils/Hooks/useWindowSize.ts
Labels: Version: Patch

#2929 Revert "@damassi => [Artist] Port meta tags and structured data from Force"
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/ArtistMeta.tsx
  src/Apps/Artist/Components/__tests__/ArtistMeta.test.tsx
  src/Components/v2/Seo/Person.tsx
  src/__generated__/ArtistApp_artist.graphql.ts
  src/__generated__/ArtistMeta_artist.graphql.ts
  src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Labels: Version: Patch

#2927 [Carousel] Fix incorrect invocation of `Flickity.prototype.destroy()`
  package.json
  src/Components/v2/Carousel.tsx
  yarn.lock
Labels: Merge On Green, Version: Patch

#2931 Return default object on server from useWindowSize, instead of null
  src/Utils/Hooks/useWindowSize.ts
Labels: Merge On Green, Version: Patch

#2933 [Carousel] Ensure we only import flickity on client
  src/Components/v2/Carousel.tsx
Labels: Merge On Green, Version: Patch

#2934 [Carousel] Type `new Flickity(…)` and document SSR import issue.
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Components/v2/Carousel.tsx
Labels: Version: Trivial

#2935 [Revert] Move arc router code back into reaction
  package.json
  src/Apps/Order/redirects.tsx
  src/Artsy/Router/Utils/RenderStatus.tsx
  src/Artsy/Router/Utils/createRouteConfig.ts
  src/Artsy/Router/Utils/historyMiddlewares.ts
  src/Artsy/Router/__tests__/buildClientApp.test.tsx
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Artsy/Router/index.ts
  src/__generated__/buildClientAppTestQuery.graphql.ts
  src/__generated__/buildServerAppTestQuery.graphql.ts
  yarn.lock
Labels: Version: Minor

#2932 [GROW-1598] Excluded featured artist ids
  data/schema.graphql
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/__generated__/CollectionRefetch2Query.graphql.ts
  src/__generated__/Collection_viewer.graphql.ts
Labels: Jira Synced, Version: Patch

#2922 Grow-1677 Analytics tracking for hub entry points
  src/Artsy/Analytics/Schema/Values.ts
  src/Components/v2/CollectionsHubsHomepageNav.tsx
  src/Components/v2/CollectionsHubsNav.tsx
  src/Components/v2/ImageLink.tsx
Labels: Jira Synced, Version: Patch

#2936 Require login for bid confirm route
  src/Apps/Auction/__fixtures__/routes_BidQuery.ts
  src/Apps/Auction/__tests__/routes.test.ts
  src/Apps/Auction/getRedirect.ts
  src/Apps/Auction/routes.tsx
Labels: Jira Synced, Version: Minor

#2942 [Collection Hubs] only display Related Collections Rail on non-hubs collections
  src/Apps/Collect2/Routes/Collection/index.tsx
Labels: Merge On Green, Version: Patch

#2941 this hopefully fixes the broken login flow on mobile
  src/Components/Authentication/__tests__/helpers.test.ts
  src/Components/Authentication/helpers.ts
Labels: Merge On Green, Version: Patch

#2928 Submit bid via new ConfirmBid page
  src/Apps/Auction/Components/BidForm.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
  src/Apps/Auction/Routes/__stories__/ConfirmBid.story.tsx
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/Apps/Auction/Routes/__tests__/Utils/ConfirmBidTestPage.tsx
  src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
  src/Apps/Auction/__tests__/routes.test.ts
  src/Apps/Auction/getRedirect.ts
  src/Apps/Auction/routes.tsx
  src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
  src/__generated__/ConfirmBidValidTestQuery.graphql.ts
  src/__generated__/routes_ConfirmBidQuery.graphql.ts
Labels: Jira Synced, Version: Minor

#2938 Loosen rules on phone numbers in AddressForm for international numbers.
  src/Apps/Auction/Routes/__tests__/Register.test.tsx
  src/Apps/Order/Components/AddressForm.tsx
Labels: Jira Synced, Version: Minor

#2943 Remove pageview tracking from hubs modules
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesRail.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionsRail.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
Labels: Jira Synced, Version: Patch

#2946 [Router] Remove double render
  src/Artsy/Router/buildServerApp.tsx
Labels: Version: Patch

#2944 Create typeSupport & simplify relay fixture creation
  src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
  src/Apps/Auction/__fixtures__/routes_RegisterQuery.ts
  src/Apps/Auction/__tests__/routes.test.ts
  src/Apps/__tests__/Fixtures/Auction/Routes/Register/index.ts
  src/Components/v2/__tests__/ArtistBio.test.tsx
  src/Utils/typeSupport.ts
Labels: Version: Minor

#2940 Enable collection hubs rails for everyone!
  src/Apps/Collect2/Routes/Collection/index.tsx
Labels: Jira Synced, Version: Patch

#2939 Restore meta data, fix product structured data issues on artist…
  data/schema.graphql
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/ArtistMeta.tsx
  src/Apps/Artist/Components/__tests__/ArtistMeta.test.tsx
  src/Components/v2/Seo/Person.tsx
  src/__generated__/ArtistApp_artist.graphql.ts
  src/__generated__/ArtistMeta_artist.graphql.ts
  src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#2947 Pre-populate the selected bid with a value from the query string
  src/Apps/Auction/Components/BidForm.tsx
  src/Apps/Auction/Components/__stories__/LotInfo.story.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__stories__/ConfirmBid.story.tsx
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/Apps/Auction/Routes/__tests__/Utils/ConfirmBidTestPage.tsx
Labels: Merge On Green, Version: Patch

#2950 Ensure makesOffer isn't null before getting length
  src/Apps/Artist/Components/ArtistMeta.tsx
Labels: Merge On Green, Version: Patch

#2952 Be defensive about list price accessors
  src/Apps/Artist/Components/ArtistMeta.tsx
Labels: Merge On Green

#2844 [GROW-1513] Collection hub nav ab
  .storybook/webpack.config.js
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Artsy/Analytics/Schema/index.ts
  src/Components/v2/CollectionsHubsNav.tsx
  typings/sharify.d.ts
Labels: Jira Synced, Version: Patch

#2953 remove pricing transparency query param, make a story for it
  src/Apps/Auction/Components/__stories__/PricingTransparency.story.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__stories__/ConfirmBid.story.tsx
Labels: Version: Patch

#2954 [Collection Hubs Entry Points] Moves Experiment Viewed to collect app
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Components/v2/CollectionsHubsNav.tsx
Labels: Version: Patch

#2955 [NavBar] Rename `Magazine` to `Editorial`
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/__tests__/NavBar.test.tsx
Labels: Jira Synced, Version: Patch

#2956 Add analytics calls to ConfirmBid route
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
  src/Apps/Auction/routes.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
  src/__generated__/ConfirmBidValidTestQuery.graphql.ts
  src/__generated__/routes_ConfirmBidQuery.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Minor

#2958 Collection SeoProducts description
  src/Apps/Collect2/Components/SeoProductsForArtworks.tsx
Labels: Merge On Green, Version: Patch

#2960 Fix title of Confirm Bid route
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2949 Grow 1563 Add analytics tracking to Nav Bar
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
Labels: Jira Synced, Version: Patch

#2957 QA for Grow 1577 Analytics tracking for hub entry points
  src/Components/v2/CollectionsHubsHomepageNav.tsx
Labels: Jira Synced, Version: Patch

#2962 Remove Magazine from mobile nav
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/DefaultHeader.test.tsx
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBar/__tests__/NavBarTracking.test.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Footer.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Nav/Nav.tsx
  src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
Labels: Version: Patch

#2963 Conditions of sale --> Conditions of Sale in Auction FAQ
  src/Apps/Auction/Components/AuctionFAQ.tsx
Labels: Version: Patch

#2961 WIP: Add retargetting tracking to confirm bid
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/Artsy/Analytics/Schema/AuctionInfo.ts
  src/Artsy/Analytics/Schema/CriteoInfo.ts
  src/Artsy/Analytics/Schema/Interaction.ts
  src/Artsy/Analytics/Schema/index.ts
Labels: Jira Synced, Version: Patch

#2959 Article meta component
  src/Components/Publishing/ArticleMeta.tsx
  src/Components/Publishing/__tests__/ArticleMeta.test.tsx
  typings/sharify.d.ts
Labels: Jira Synced, Version: Patch
