Repository artsy/reaction, pull requests merged in 2019-09, with the labels that each got.

#2761 De-randomize subtitles in homepage hubs nav to eliminate hydration mismatches
  src/Components/v2/CollectionsHubsHomepageNav.tsx
Labels: Version: Patch

#2759 Invert Header Text to Match Side Frame Text on Artsy Vanguard Headers
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/VideoHeader.tsx
Labels: Jira Synced, Version: Patch

#2764 Scroll top on close Vanguard
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
Labels: Jira Synced, Version: Patch

#2760 Analytics tracking default header Grow-1450
  src/Apps/Collect2/Components/Collection/Header/DefaultHeader.tsx
  src/Apps/Collect2/Components/Collection/Header/__tests__/DefaultHeader.test.tsx
  src/Apps/Collect2/Components/Collection/Header/__tests__/Header.test.tsx
  src/Apps/Collect2/Components/Collection/Header/__tests__/__snapshots__/DefaultHeader.test.tsx.snap
  src/Apps/Collect2/Components/Collection/Header/index.tsx
  src/Artsy/Analytics/Schema/Values.ts
Labels: Jira Synced, Version: Patch

#2767 Sync MP schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#2766 Ensure carousel arrows are the same size and long titles line-break
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
Labels: Jira Synced, Version: Patch

#2758 Setup safer/more robust linking process for reaction/force
  .gitignore
  README.md
  package.json
  scripts/publish-on-change.js
  scripts/quicklink-to-project.sh
  yarn.lock
Labels: Version: Trivial

#2771 Add bottom margin to viewports > XS on bidder registration form
  src/Apps/Auction/Routes/Register/index.tsx
Labels: Version: Minor

#2772 Defensively access images' aspect ratio in Recently Viewed rail
  src/Components/v2/RecentlyViewed.tsx
Labels: Jira Synced, Version: Patch

#2776 Allow images without zoom
  src/Components/v2/Lightbox/Lightbox.tsx
Labels: Version: Patch

#2775 PURCHASE-1472 - Checks for availability before showing VAT
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
  src/__generated__/ArtworkSidebarCommercial_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2782 Add Default Mobile Styling to Vanguard 2019 Article Series
  2
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2786 Vanguard QA
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/FrameText.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
Labels: Version: Patch

#2783 Add intercom to order app
  src/Apps/Order/OrderApp.tsx
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/Order/redirects.tsx
  src/Apps/Order/routes.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/OrderApp_order.graphql.ts
  src/__generated__/routes_OrderQuery.graphql.ts
Labels: Version: Patch

#2788 Handle Nav Bar and Side Frame Text When Slideshow is Open
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/FrameText.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
  src/Components/Publishing/Nav/Nav.tsx
  src/Components/Publishing/Sections/FullscreenViewer/FullScreenProvider.tsx
Labels: Jira Synced, Version: Patch

#2785 [PageLoader] Add page loader to router
  src/Artsy/Router/Utils/RenderStatus.tsx
Labels: Version: Patch

#2787 @damassi => [QueryString] When parsing query strings for apps, coerce Ints and Bools
  src/Artsy/Router/Utils/__tests__/queryStringParsing.test.ts
  src/Artsy/Router/Utils/queryStringParsing.ts
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
Labels: Version: Patch

#2773 PURCHASE-1470: Reuse SetupIntent for make offer
  data/schema.graphql
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/__generated__/ReviewSubmitOfferOrderMutation.graphql.ts
Labels: Jira Synced, Version: Patch

#2791 Collection hub title
  src/Apps/Collect2/Components/Collection/Header/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
Labels: Jira Synced, Version: Patch

#2795 Prevent Side Frame from overlapping with Article Content
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
Labels: Jira Synced, Version: Patch

#2796 Remove padding from article content on mobile
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
Labels: Jira Synced, Version: Patch

#2798 align captions on artist image and artist artworks
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Sections/Caption.tsx
  src/Components/Publishing/Sections/__tests__/__snapshots__/Caption.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Image.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Video.test.tsx.snap
Labels: Jira Synced, Merge On Green, Version: Patch

#2797 replace up/down arrows with underline on read more button
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2800 Switch to using metaphysics field for tax information
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
  src/__generated__/ArtworkSidebarCommercial_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Patch

#2789 [Refactor] Replace <ArtworkFilter> in /collect -> Take 2
  .vscode/settings.json
  package.json
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Utils/urlBuilder.ts
  src/Apps/Collect2/collectRoutes.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
  src/Artsy/Router/RouterLink.tsx
  src/Artsy/Router/Utils/RenderStatus.tsx
  src/Artsy/Router/Utils/Route.tsx
  src/Artsy/Router/__tests__/RouterLink.test.tsx
  src/Artsy/Router/__tests__/buildClientApp.test.tsx
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Artsy/SystemContext.tsx
  src/Artsy/__tests__/SystemContext.test.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid2.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGridSort.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterZeroState.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/SizeRangeFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/SortFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/MediumFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/SizeRangeFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/SortFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/WaysToBuyFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/index.tsx
  src/Components/v2/ArtworkFilter/Utils/__tests__/hasFilters.test.tsx
  src/Components/v2/ArtworkFilter/Utils/__tests__/isDefaultFilter.test.tsx
  src/Components/v2/ArtworkFilter/Utils/__tests__/rangeToTuple.test.tsx
  src/Components/v2/ArtworkFilter/Utils/__tests__/urlFragmentFromState.test.tsx
  src/Components/v2/ArtworkFilter/Utils/hasFilters.tsx
  src/Components/v2/ArtworkFilter/Utils/isDefaultFilter.tsx
  src/Components/v2/ArtworkFilter/Utils/rangeToTuple.tsx
  src/Components/v2/ArtworkFilter/Utils/urlFragmentFromState.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterContext.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/fixtures/ArtworkFilter.fixture.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/Utils/Hooks/useForceUpdate.ts
  src/__generated__/ArtworkFilterQuery.graphql.ts
  src/__generated__/ArtworkFilter_viewer.graphql.ts
  src/__generated__/Collect_viewer.graphql.ts
  src/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  yarn.lock
Labels: Version: Major

#2818 Add Artsy Engineering footer
  README.md
Labels: Version: Trivial

#2794 PURCHASE-1456 Add BankTransferExperiment
  src/Apps/Order/Components/BankTransferExperiment.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Artsy/Analytics/Schema/Values.ts
Labels: Jira Synced, Version: Patch

#2811 Grow 1498 fix the broken scrolling in small size
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
Labels: Jira Synced, Version: Patch

#2814 [GROW-1501]: fixes word wrapping in ie
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
Labels: Jira Synced, Version: Patch

#2816 [Search] Replace old artwork filter with new generic implementation
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/Collect2/Utils/urlBuilder.ts
  src/Apps/Search/Components/ZeroState.tsx
  src/Apps/Search/FilterState.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/ColorFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/FilterContainer.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/MediumFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/PriceRangeFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/SizeRangeFilters.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/TimePeriodFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/WaysToBuyFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/__tests__/FilterContainer.test.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/__tests__/MediumFilter.test.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/__tests__/TimePeriodFilter.test.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/index.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsFilterContainer.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsMobileActionSheet.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/__tests__/SearchResultsArtworkGrid.test.tsx
  src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
  src/Apps/Search/Routes/Artworks/index.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/__tests__/FilterState.test.ts
  src/Apps/Search/routes.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/Utils/urlBuilder.tsx
  src/__generated__/SearchResultsArtworkGridQuery.graphql.ts
  src/__generated__/SearchResultsArtworkGridTestQuery.graphql.ts
  src/__generated__/SearchResultsArtworkGrid_filtered_artworks.graphql.ts
  src/__generated__/SearchResultsArtworks_viewer.graphql.ts
  src/__generated__/SearchResultsFilterContainer_viewer.graphql.ts
  src/__generated__/SearchResultsRefetchQuery.graphql.ts
  src/__generated__/SearchResultsRefetch_viewer.graphql.ts
  src/__generated__/routes_SearchResultsArtworksQuery.graphql.ts
Labels: Version: Patch

#2821 [ArtworkFilter] Fix aggregations
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/MediumFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/index.tsx
  src/__generated__/RegisterInvalidTestQuery.graphql.ts
Labels: Version: Patch

#2823 Vanguard sharing
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
Labels: Version: Patch

#2824 Handle case for payment_method_confirmation_failed
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitOfferOrder.ts
  src/Apps/Order/Routes/__tests__/Review.test.tsx
Labels: Version: Patch

#2827 [Lib] Upgrade storybooks@5.2
  package.json
  yarn.lock
Labels: Merge On Green, Version: Patch

#2829 Don't tie `yalc` publishing to `yarn watch`
  package.json
  scripts/quicklink-to-project.sh
Labels: Version: Trivial

#2830 Collect2 app passes strict null checks
  src/Apps/Collect2/Components/SeoProductsForArtworks.tsx
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/DefaultHeader.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/__stories__/CollectionsHubRails.story.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/Collect2/Routes/Collections/Components/CollectionsGrid.tsx
Labels: Jira Synced, Version: Patch

#2832 Collect null QA
  2
  src/Apps/Collect2/Components/SeoProductsForArtworks.tsx
Labels: Version: Patch

#2834 Update fake hubs data with more accurate fake images
  src/Components/v2/CollectionsHubsHomepageNav.tsx
  src/Components/v2/CollectionsHubsNav.tsx
Labels: Version: Patch

#2835 Add error log
  src/Artsy/Router/Utils/RenderStatus.tsx
Labels: Version: Patch

#2837 Revert "Add error log"
  src/Artsy/Router/Utils/RenderStatus.tsx
Labels: Version: Patch

#2838 Handle collections header flicker
  src/Apps/Collect2/Routes/Collection/Components/Header/DefaultHeader.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
Labels: Jira Synced, Version: Patch

#2840 [GROW-1506] use unique key
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
Labels: Version: Patch

#2839 PURCHASE-1091: Buyer receives a more friendly, informative error when their card is declined in checkout
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
Labels: Jira Synced, Version: Patch

#2841 [Vanguard] Corrections footer
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Footer.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
Labels: Jira Synced, Version: Patch

#2842 Persist telephone from bidder registration form to user profile
  src/Apps/Auction/Components/RegistrationForm.tsx
  src/Apps/Auction/Components/__stories__/RegistrationForm.story.tsx
  src/Apps/Auction/Components/__tests__/RegistrationForm.test.tsx
  src/Apps/Auction/Routes/Register/index.tsx
  src/Apps/Auction/Routes/__fixtures__/MutationResults/createCreditCard.ts
  src/Apps/Auction/Routes/__fixtures__/MutationResults/createCreditCardAndUpdatePhone.ts
  src/Apps/Auction/Routes/__tests__/Register.test.tsx
  src/Apps/Auction/Routes/__tests__/Utils/RegisterTestPage.tsx
  src/__generated__/RegisterCreateCreditCardAndUpdatePhoneMutation.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#2836 @eessex => [Error Handling] Only serve non 2XX pages on principalField errors
  src/Artsy/Relay/createRelaySSREnvironment.ts
  src/Artsy/Relay/middleware/metaphysicsErrorHandlerMiddleware.ts
  src/Artsy/Relay/middleware/principalFieldErrorHandlerMiddleware.ts
  src/Artsy/Relay/middleware/searchBarImmediateResolveMiddleware.ts
  src/Artsy/Router/Utils/Route.tsx
Labels: Version: Major

#2850 Add codemod command to simplify running codemods in reaction
  package.json
  scripts/codemod.sh
Labels: Version: Trivial

#2851 Increase Test Coverage of 2019 Vanguard Article Series
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/__tests__/ArtistWrapper.test.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/index.test.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
  src/Components/Publishing/EditorialFeature/Fixtures/Vanguard2019.ts
Labels: Jira Synced, Version: Patch

#2765 Point collection hubs entry points at marketingHubCollections for real data
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/collectRoutes.tsx
  src/Apps/__tests__/Fixtures/Collect/CollectAppFixture.ts
  src/Components/v2/CollectionsHubsHomepageNav.tsx
  src/Components/v2/CollectionsHubsNav.tsx
  src/Components/v2/__stories__/CollectionsHubsHomepageNav.story.tsx
  src/Components/v2/__stories__/CollectionsHubsNav.story.tsx
  src/__generated__/Collect_marketingCollections.graphql.ts
  src/__generated__/Collect_marketingHubCollections.graphql.ts
  src/__generated__/CollectionsHubsHomepageNavQuery.graphql.ts
  src/__generated__/CollectionsHubsHomepageNav_marketingHubCollections.graphql.ts
  src/__generated__/CollectionsHubsNavQuery.graphql.ts
  src/__generated__/CollectionsHubsNav_marketingHubCollections.graphql.ts
  src/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2853 @joeyAghion => [RelatedArtworks] Be defensive about missing layer
  src/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx
  src/Apps/Artwork/Components/__tests__/OtherWorks.test.tsx
Labels: Version: Patch

#2854 @pepopowitz => [Artwork] Be defensive in SEO meta tag component to artworks w/o part…
  src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.test.tsx
Labels: Version: Patch

#2855 @damassi => Couple of artist page/Sentry issues
  src/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx
  src/Apps/Artist/routes.tsx
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistArtworkFilter_artist.graphql.ts
  src/__generated__/OverviewQuery.graphql.ts
Labels: Version: Patch, sentry-fix

#2856 @damassi => Few more Sentry bugs
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/__tests__/ArtistWrapper.test.tsx
Labels: Version: Patch, sentry-fix

#2857 @damassi => [Artist] Defer collection rail to client
  src/Apps/Artist/Routes/Overview/index.tsx
Labels: Merge On Green, Version: Patch

#2858 @damassi => Couple of more defers on the artist page
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
Labels: Version: Patch

#2852 Remove deprecated display components/functionality
  src/Components/Publishing/Display/Canvas/CanvasContainer.tsx
  src/Components/Publishing/Display/Canvas/CanvasSlideshow.tsx
  src/Components/Publishing/Display/Canvas/CanvasText.tsx
  src/Components/Publishing/Display/Canvas/CanvasVideo.tsx
  src/Utils/__tests__/resizer.test.ts
  src/Utils/resizer.ts
Labels: Version: Patch

#2861 @damassi => [Filter] Be defensive about missing filtered artworks
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/__generated__/ArtworkFilterQuery.graphql.ts
  src/__generated__/ArtworkFilter_viewer.graphql.ts
  src/__generated__/CollectionRefetch2Query.graphql.ts
  src/__generated__/Collection_viewer.graphql.ts
  src/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Labels: Version: Patch, sentry-fix

#2862 @eessex => [Artwork] Be defensive about missing partner in additional info section
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
Labels: Merge On Green, Version: Patch, sentry-fix

#2809 PURCHASE-1416 - Adds AuctionFAQ
  data/schema.graphql
  src/Apps/Auction/Components/AuctionFAQ.tsx
  src/Apps/Auction/Components/__tests__/AuctionFAQ.test.tsx
  src/Apps/Auction/__tests__/routes.test.ts
  src/Apps/Auction/routes.tsx
  src/Components/Auction/AuctionRegistrationModal.tsx
  src/Components/v2/__stories__/AuctionFAQ.story.tsx
  src/__generated__/AuctionFAQQuery.graphql.ts
  src/__generated__/AuctionFAQ_Query.graphql.ts
  src/__generated__/AuctionFAQ_viewer.graphql.ts
Labels: Jira Synced, Version: Patch
