Repository artsy/reaction, pull requests merged in 2019-03, with the labels that each got.

#2092 Bump palette
  package.json
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
  yarn.lock
Labels: Merge On Green

#2077 View-in-room: Select default image when "view in room" is clicked
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Components/v2/Lightbox/Lightbox.tsx
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/ArtworkImageBrowser_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Patch

#2090 Fix input padding
  src/Components/Input.tsx
  src/Components/Search/SearchInputContainer.tsx
  src/Components/__tests__/__snapshots__/Input.test.tsx.snap
Labels: Merge On Green, Version: Patch

#2093 First pass static <NavBar /> UI
  src/Components/NavBar/index.tsx
  src/Components/__stories__/NavBar.story.tsx
Labels: Version: Minor

#2085 Artist Collections Rail initial setup
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/__tests__/Fixtures/Collections.ts
  src/Components/Artist/CollectionsRail/CollectionEntity.tsx
  src/Components/Artist/CollectionsRail/CollectionsRail.tsx
  src/Components/__stories__/ArtistCollectionsRail.story.tsx
  src/Components/v2/Carousel.tsx
  typings/sharify.d.ts
Labels: Jira Synced, Version: Patch

#2086 Match comp for active preview items
  src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/RelatedArtworks.tsx
  src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
  src/Components/Search/Previews/Grids/PreviewGridItem.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/Search/__tests__/SearchBar.test.tsx
Labels: Jira Synced, Version: Patch

#2100 /accept charge failure handling
  src/Apps/Order/Dialogs.tsx
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/acceptOffer.ts
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Components/Modal/ModalDialog.tsx
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/Accept_order.graphql.ts
  src/__generated__/routes_AcceptQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2096 Collapse artwork details on artwork page into one section
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsChecklist.tsx
  src/Apps/Artwork/Components/ArtworkDetails/index.tsx
  src/Components/Search/Previews/Grids/PreviewGridItem.tsx
  src/__generated__/ArtworkDetailsAdditionalInfo_artwork.graphql.ts
  src/__generated__/ArtworkDetailsChecklist_artwork.graphql.ts
  src/__generated__/ArtworkDetailsQuery.graphql.ts
  src/__generated__/ArtworkDetails_Test_Query.graphql.ts
  src/__generated__/ArtworkDetails_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Patch

#2099 sync metaphystics schema and use new randomizationSeed argument
  data/schema.graphql
  src/Components/CollectionsRail/index.tsx
  src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
  src/Components/__stories__/CollectionsRail.story.tsx
  src/__generated__/CollectionsRailQuery.graphql.ts
Labels: Version: Patch

#2101 Remove restriction on layout for EditorialFeatures
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/Layouts/ArticleWithFullScreen.tsx
  src/Components/Publishing/__tests__/Article.test.tsx
Labels: Version: Patch

#2104 DISCO-788: Add the placeholder on XS too
  src/Components/Search/SearchBar.tsx
Labels: Version: Patch

#2103 @jonallured => [Autosuggest] Unselect keyboard when you bring the mouse in to previews
  src/Components/Search/state.ts
Labels: Jira Synced, Version: Patch

#2102 Disco 786 xs placeholder
  src/Components/Search/SearchBar.tsx
  src/Components/Search/Suggestions/SuggestionItem.tsx
  src/Components/Search/__tests__/SearchBar.test.tsx
Labels: Version: Patch

#2106 SearchBar - Don't show suggestions container at xs when there is no query.
  src/Components/Search/SearchBar.tsx
Labels: Jira Synced, Version: Patch

#2105 Break out Nav components
  src/Components/NavBar/Menus/MoreNavMenu.tsx
  src/Components/NavBar/Menus/NotificationMenu.tsx
  src/Components/NavBar/Menus/UserMenu.tsx
  src/Components/NavBar/Menus/index.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
  src/Components/NavBar/index.tsx
Labels: Skip Release

#2112 [Toolchain] Update Storybooks v5
  .storybook/webpack.config.js
  package.json
  src/__generated__/routes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Version: Patch

#2113 [Refactor] Update SystemContext API to support `useContext`
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/PriceRangeFilter.tsx
  src/Apps/Artist/Routes/RelatedArtists/RelatedArtistsList.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkBanner/index.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkDetails/index.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPageviews.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextArtist.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextAuction.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextFair.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextPartnerShow.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
  src/Apps/Artwork/Components/__stories__/OtherWorks.story.tsx
  src/Apps/Collect/Components/Base/CollectArtworkGrid.tsx
  src/Apps/Collect/Components/Base/CollectFilterContainer.tsx
  src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
  src/Apps/Collect/Components/Filters/PriceRangeFilter.tsx
  src/Apps/Collect/Components/Filters/SizeRangeFilters.tsx
  src/Apps/Collect/Components/Filters/SortFilter.tsx
  src/Apps/Collect/Components/Filters/WaysToBuyFilter.tsx
  src/Apps/Comparables/ComparablesView.tsx
  src/Apps/Comparables/Filter/AttributionClassFilter.tsx
  src/Apps/Comparables/Filter/MediumFilter.tsx
  src/Apps/Order/Components/OfferNote.tsx
  src/Apps/Order/Components/StickyFooter.tsx
  src/Apps/Order/Components/__tests__/StickyFooter.test.tsx
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/Order/routes.tsx
  src/Artsy/Router/Components/__tests__/Boot.test.tsx
  src/Artsy/SystemContext.tsx
  src/Artsy/index.tsx
  src/Components/Artwork/Metadata.tsx
  src/Components/CollectionsRail/index.tsx
  src/Components/Payment/UserSettingsPayments.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/index.tsx
  src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/v2/AuctionTimer.tsx
  src/Components/v2/FollowArtistPopover/index.tsx
  src/Components/v2/Footer.tsx
  src/Components/v2/RecentlyViewed.tsx
Labels: Version: Minor

#2117 Show artwork "additional info" component if any of the fields exist
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
Labels: Version: Patch

#2121 add tabIndex={0} to preview links to get Safari to specify e.relatedTarget on blur
  src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
  src/Components/Search/Previews/Grids/PreviewGridItem.tsx
Labels: Version: Patch

#2110 Update title meta for collections
  src/Apps/Collect/CollectMediumMetadata.ts
  src/Apps/Collect/CollectionApp.tsx
  src/Apps/Collect/__tests__/CollectApp.test.tsx
  src/Apps/Collect/__tests__/CollectMediumMetadata.test.ts
  src/Apps/Collect/__tests__/CollectionApp.test.tsx
Labels: Jira Synced, Version: Patch

#2114 Refactor spinner function
  src/Artsy/Relay/renderWithLoadProgress.tsx
Labels: Version: Patch

#2115 Set static preview height & use flex to vertically center 'no results'
  src/Components/Search/Previews/Grids/ArtistSearch/NoResults.tsx
  src/Components/Search/Previews/index.tsx
  src/Components/Search/SearchBar.tsx
Labels: Jira Synced, Version: Patch

#2124 @pepopowitz => [Autosuggest] Ensure suggestions remain when suggestion is selected
  src/Components/Search/SearchBar.tsx
Labels: Jira Synced, Version: Patch

#2126 Artist insights 2.0 - Update biennial badge label
  src/Apps/__tests__/Fixtures/SelectedCareerAchievements.ts
  src/Components/v2/__tests__/SelectedCareerAchievements.test.tsx
Labels: Version: Patch

#2127 Return correct error
  src/Artsy/Relay/renderWithLoadProgress.tsx
Labels: Version: Patch

#2123 v2 => [Refactor] Update SystemContext API to support `useContext`
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/PriceRangeFilter.tsx
  src/Apps/Artist/Routes/RelatedArtists/RelatedArtistsList.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkBanner/index.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkDetails/index.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPageviews.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextArtist.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextAuction.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextFair.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextPartnerShow.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
  src/Apps/Artwork/Components/__stories__/OtherWorks.story.tsx
  src/Apps/Collect/Components/Base/CollectArtworkGrid.tsx
  src/Apps/Collect/Components/Base/CollectFilterContainer.tsx
  src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
  src/Apps/Collect/Components/Filters/PriceRangeFilter.tsx
  src/Apps/Collect/Components/Filters/SizeRangeFilters.tsx
  src/Apps/Collect/Components/Filters/SortFilter.tsx
  src/Apps/Collect/Components/Filters/WaysToBuyFilter.tsx
  src/Apps/Comparables/ComparablesView.tsx
  src/Apps/Comparables/Filter/AttributionClassFilter.tsx
  src/Apps/Comparables/Filter/MediumFilter.tsx
  src/Apps/Order/Components/OfferNote.tsx
  src/Apps/Order/Components/StickyFooter.tsx
  src/Apps/Order/Components/__tests__/StickyFooter.test.tsx
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/Order/routes.tsx
  src/Artsy/Router/Components/__tests__/Boot.test.tsx
  src/Artsy/SystemContext.tsx
  src/Artsy/index.tsx
  src/Components/Artwork/Metadata.tsx
  src/Components/CollectionsRail/index.tsx
  src/Components/Payment/UserSettingsPayments.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/index.tsx
  src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/v2/AuctionTimer.tsx
  src/Components/v2/FollowArtistPopover/index.tsx
  src/Components/v2/Footer.tsx
  src/Components/v2/RecentlyViewed.tsx
Labels: Version: Patch

#2129 [NavBar] Connect NotificationsMenu to relay
  src/Artsy/Relay/renderWithLoadProgress.tsx
  src/Components/NavBar/Menus/NotificationMenu.tsx
  src/Components/NavBar/Menus/NotificationsMenu.tsx
  src/Components/NavBar/Menus/UserMenu.tsx
  src/Components/NavBar/Menus/index.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
  src/Utils/BreakpointVisualizer.tsx
  src/__generated__/NotificationsMenuQuery.graphql.ts
Labels: Skip Release

#2132 [NavBar] Style mobile nav
  src/Components/NavBar/MobileNavMenu/MobileToggleIcon.tsx
  src/Components/NavBar/MobileNavMenu/index.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
Labels: Skip Release

#2138 explicitly add redirectTo property for fb auth flow
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Labels: Jira Synced, Version: Patch

#2137 @dblandin => [SearchResults] Create shell for search2, with a tab navigation
  data/schema.graphql
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/__tests__/SearchApp.test.tsx
  src/Apps/Search/routes.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/__generated__/NavigationTabs_searchableConnection.graphql.ts
  src/__generated__/SearchApp_viewer.graphql.ts
  src/__generated__/routes_SearchBarTopLevelQuery.graphql.ts
Labels: Version: Patch

#2140 [Icons Upgrade] Fix incompatabilities
  package.json
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
  src/Apps/Collect/Components/Filters/SortFilter.tsx
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Components/Artist/MarketInsights/__tests__/__snapshots__/MarketInsights.test.tsx.snap
  src/Components/__stories__/Icons.story.tsx
  src/Components/__tests__/__snapshots__/PasswordInput.test.tsx.snap
  src/Components/v2/Carousel.tsx
  src/Components/v2/__tests__/CountdownTimer.test.tsx
  yarn.lock
Labels: Version: Major

#2143 Pin palette dep
  package.json
  yarn.lock
Labels: Version: Trivial

#2136 Pass props.color to /video credits
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Video/VideoAbout.tsx
Labels: Version: Patch

#2147 Lockfile got out of date...
  yarn.lock
Labels: Merge On Green, Version: Trivial

#2148 @dblandin => [SearchResults] Add basic contents for a tab
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/Routes/Artists/__tests__/SearchResultsArtists.test.tsx
  src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
  src/Apps/Search/Routes/Artworks/__tests__/SearchResultsArtworks.test.tsx
  src/Apps/Search/routes.tsx
  src/__generated__/SearchResultsArtistsRoute_viewer.graphql.ts
  src/__generated__/SearchResultsArtworksRoute_viewer.graphql.ts
  src/__generated__/routes_SearchResultsArtistsQuery.graphql.ts
  src/__generated__/routes_SearchResultsArtworksQuery.graphql.ts
Labels: Version: Minor

#2064 Lazy-load images in the artwork grid
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/AuctionArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/FairArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerShowArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
  src/Apps/Collect/Components/Base/CollectArtworkGrid.tsx
  src/Apps/WorksForYou/WorksForYouFeed.tsx
  src/Components/Artwork/GridItem.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/Components/ArtworkGrid/__stories__/ArtworkGridFixture.ts
  src/__generated__/ArtworkContextArtistQuery.graphql.ts
  src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkContextFairQuery.graphql.ts
  src/__generated__/ArtworkContextFair_Test_Query.graphql.ts
  src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
  src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
  src/__generated__/ArtworkFilterArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkGridExampleQuery.graphql.ts
  src/__generated__/ArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkGrid_Test_Query.graphql.ts
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectArtworkGridQuery.graphql.ts
  src/__generated__/CollectArtworkGridTestQuery.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/ComparablesQuery.graphql.ts
  src/__generated__/ComparablesViewQuery.graphql.ts
  src/__generated__/GeneArtworksContentQuery.graphql.ts
  src/__generated__/GeneContentsArtworksQuery.graphql.ts
  src/__generated__/GridItem_artwork.graphql.ts
  src/__generated__/RelatedWorksArtworkGridQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_Test_Query.graphql.ts
  src/__generated__/SaveArtworkQuery.graphql.ts
  src/__generated__/TagArtworksContentQuery.graphql.ts
  src/__generated__/TagContentsArtworksQuery.graphql.ts
  src/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
  yarn.lock
Labels: Jira Synced, Version: Minor

#2151 DISCO-738: Conditionally open mobile sign up when saving artwork
  src/Components/Artwork/Save.tsx
Labels: Version: Patch

#2125 Artist insights 2.0 - Some artists with 1 badge don't have insights displayed
  src/Components/v2/SelectedCareerAchievements.tsx
  src/Components/v2/__tests__/SelectedCareerAchievements.test.tsx
Labels: Version: Patch

#2156 test copy fix
  src/Components/v2/__tests__/SelectedCareerAchievements.test.tsx
Labels: Merge On Green, Version: Patch

#2154 Pass ArtistCard onClick to <Link> component.
  src/Components/v2/ArtistCard.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2153 GROW-1135: resize full-width images to 2000
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Header/Layouts/Components/FeatureFullscreenHeader.tsx
  src/Components/Publishing/Sections/Image.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2159 updating artsy for galleries link
  src/Components/v2/Footer.tsx
Labels: Version: Patch

#2111 Artwork page - Some artist names are taking up two lines in sidebar
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
Labels: Version: Patch

#2152 Add images to ArtistCollectionRail
  src/Apps/__tests__/Fixtures/Collections.ts
  src/Components/Artist/ArtistCollectionsRail/ArtistCollectionEntity.tsx
  src/Components/Artist/ArtistCollectionsRail/__tests__/ArtistCollectionEntity.test.tsx
  src/__generated__/ArtistCollectionEntity_collection.graphql.ts
  src/__generated__/ArtistCollectionsRailQuery.graphql.ts
Labels: Version: Patch

#2161 Wire up test to report results to ci
  .circleci/config.yml
  package.json
  yarn.lock
Labels: Jira Synced

#2164 DISCO-849: Fix the link to related artists
  src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
Labels: Version: Patch

#2162 DISCO-851: Always show related categories for artist
  src/Apps/Artist/Routes/Overview/index.tsx
Labels: Version: Minor

#2166 Update test job
  .circleci/config.yml
  package.json
Labels: Version: Patch

#2169 switch tracking event property for marketing
  src/Apps/Artwork/ArtworkApp.tsx
Labels: Version: Patch

#2168 @dblandin => Adds all other entity tabs
  data/schema.graphql
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/Routes/Articles/SearchResultsArticles.tsx
  src/Apps/Search/Routes/Auctions/SearchResultsAuctions.tsx
  src/Apps/Search/Routes/Categories/SearchResultsCategories.tsx
  src/Apps/Search/Routes/Collections/SearchResultsCollections.tsx
  src/Apps/Search/Routes/Galleries/SearchResultsGalleries.tsx
  src/Apps/Search/Routes/Shows/SearchResultsShows.tsx
  src/Apps/Search/routes.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/__generated__/ArtistShowsQuery.graphql.ts
  src/__generated__/CVItemQuery.graphql.ts
  src/__generated__/SearchResultsArticlesQuery.graphql.ts
  src/__generated__/SearchResultsArticles_viewer.graphql.ts
  src/__generated__/SearchResultsAuctionsQuery.graphql.ts
  src/__generated__/SearchResultsAuctions_viewer.graphql.ts
  src/__generated__/SearchResultsCategoriesQuery.graphql.ts
  src/__generated__/SearchResultsCategories_viewer.graphql.ts
  src/__generated__/SearchResultsCollectionsQuery.graphql.ts
  src/__generated__/SearchResultsCollections_viewer.graphql.ts
  src/__generated__/SearchResultsGalleriesQuery.graphql.ts
  src/__generated__/SearchResultsGalleries_viewer.graphql.ts
  src/__generated__/SearchResultsShowsQuery.graphql.ts
  src/__generated__/SearchResultsShows_viewer.graphql.ts
  src/__generated__/routes_SearchResultsArticlesQuery.graphql.ts
  src/__generated__/routes_SearchResultsAuctionsQuery.graphql.ts
  src/__generated__/routes_SearchResultsCategoriesQuery.graphql.ts
  src/__generated__/routes_SearchResultsCollectionsQuery.graphql.ts
  src/__generated__/routes_SearchResultsGalleriesQuery.graphql.ts
  src/__generated__/routes_SearchResultsShowsQuery.graphql.ts
Labels: Version: Minor

#2170 DISCO-852: Hide genes once again
  src/Apps/Artist/Routes/Overview/index.tsx
Labels: Merge On Green, Version: Patch

#2165 Fix bid icon colors
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
Labels: Version: Patch

#2157 Use the Palette CheckIcon
  src/Assets/Checkmark.tsx
  src/Components/Checkbox.tsx
Labels: Version: Patch

#2171 Add generic item component for search results page
  src/Apps/Search/Components/GenericSearchResultItem.tsx
  src/Apps/Search/Routes/Articles/SearchResultsArticles.tsx
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/Routes/Artists/__tests__/SearchResultsArtists.test.tsx
  src/Apps/Search/Routes/Auctions/SearchResultsAuctions.tsx
  src/Apps/Search/Routes/Categories/SearchResultsCategories.tsx
  src/Apps/Search/Routes/Collections/SearchResultsCollections.tsx
  src/Apps/Search/Routes/Galleries/SearchResultsGalleries.tsx
  src/Apps/Search/Routes/Shows/SearchResultsShows.tsx
  src/Apps/Search/SearchApp.tsx
  src/__generated__/SearchApp_viewer.graphql.ts
  src/__generated__/SearchResultsArticlesQuery.graphql.ts
  src/__generated__/SearchResultsArticles_viewer.graphql.ts
  src/__generated__/SearchResultsArtistsRoute_viewer.graphql.ts
  src/__generated__/SearchResultsAuctionsQuery.graphql.ts
  src/__generated__/SearchResultsAuctions_viewer.graphql.ts
  src/__generated__/SearchResultsCategoriesQuery.graphql.ts
  src/__generated__/SearchResultsCategories_viewer.graphql.ts
  src/__generated__/SearchResultsCollectionsQuery.graphql.ts
  src/__generated__/SearchResultsCollections_viewer.graphql.ts
  src/__generated__/SearchResultsGalleriesQuery.graphql.ts
  src/__generated__/SearchResultsGalleries_viewer.graphql.ts
  src/__generated__/SearchResultsShowsQuery.graphql.ts
  src/__generated__/SearchResultsShows_viewer.graphql.ts
  src/__generated__/routes_SearchBarTopLevelQuery.graphql.ts
  src/__generated__/routes_SearchResultsArticlesQuery.graphql.ts
  src/__generated__/routes_SearchResultsArtistsQuery.graphql.ts
  src/__generated__/routes_SearchResultsAuctionsQuery.graphql.ts
  src/__generated__/routes_SearchResultsCategoriesQuery.graphql.ts
  src/__generated__/routes_SearchResultsCollectionsQuery.graphql.ts
  src/__generated__/routes_SearchResultsGalleriesQuery.graphql.ts
  src/__generated__/routes_SearchResultsShowsQuery.graphql.ts
Labels: Merge On Green

#2173 update viewed product analytics event
  src/Artsy/Analytics/Schema/Values.ts
Labels: Version: Patch

#2172 set up artist collections rail test
  src/Apps/Artist/Routes/Overview/index.tsx
Labels: Jira Synced, Version: Patch

#2178 @dblandin => [SearchResults] Add 'more' tab
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/Routes/More/SearchResultsMore.tsx
  src/Apps/Search/Routes/More/__tests__/SearchResultsMore.test.tsx
  src/Apps/Search/routes.tsx
  src/__generated__/SearchResultsMoreQuery.graphql.ts
  src/__generated__/SearchResultsMore_viewer.graphql.ts
  src/__generated__/routes_SearchResultsMoreQuery.graphql.ts
Labels: Version: Patch

#2175 Add h1/h2 to artwork pages
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarTitleInfo.tsx
Labels: Jira Synced, Version: Patch

#2179 Refactor commitMutation usage
  src/Apps/Order/Dialogs.tsx
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/Counter/index.tsx
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Utils/__tests__/commitMutation.test.tsx
  src/Apps/Order/Utils/commitMutation.tsx
  src/DevTools/createTestEnv.tsx
  src/__generated__/commitMutationTest1Mutation.graphql.ts
Labels: Version: Patch

#2186 run prettier
  src/Apps/Order/Utils/commitMutation.tsx
Labels: Merge On Green, Version: Patch

#2188 move jest.unmock call
  src/Apps/Order/Utils/__tests__/commitMutation.test.tsx
  src/Apps/Order/Utils/commitMutation.tsx
Labels: Merge On Green

#2182 DISCO-853: Yank autosuggest previews
  src/Components/Search/AutosuggestManager.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/NoResults.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/RelatedArtworks.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/__tests__/MarketingCollections.test.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/__tests__/index.test.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/index.tsx
  src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
  src/Components/Search/Previews/Grids/PreviewGridItem.tsx
  src/Components/Search/Previews/index.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/Search/__tests__/SearchBar.test.tsx
  src/Components/Search/state.ts
  src/Components/__stories__/Search.story.tsx
  src/__generated__/ArtistSearchPreviewQuery.graphql.ts
  src/__generated__/ArtistSearchPreview_viewer.graphql.ts
  src/__generated__/MarketingCollectionsPreview_marketingCollections.graphql.ts
  src/__generated__/MerchandisableArtworksPreviewQuery.graphql.ts
  src/__generated__/MerchandisableArtworks_viewer.graphql.ts
  src/__generated__/PreviewGridItem_artwork.graphql.ts
  src/__generated__/RelatedArtworksPreview_viewer.graphql.ts
  src/__generated__/TestsQuery.graphql.ts
Labels: Version: Patch

#2187 @dblandin => [SearchResults] Add institution to More tab
  data/schema.graphql
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/Routes/More/SearchResultsMore.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/__generated__/SearchResultsMoreQuery.graphql.ts
  src/__generated__/SearchResultsMore_viewer.graphql.ts
  src/__generated__/routes_SearchResultsMoreQuery.graphql.ts
Labels: Version: Patch

#2191 Remove h1 css reset from Boot now that Palette covers it
  src/Artsy/Router/Components/Boot.tsx
Labels: Version: Patch

#2190 Render a gray box for search result items without an image
  src/Apps/Search/Components/GenericSearchResultItem.tsx
  src/Apps/Search/Routes/Articles/SearchResultsArticles.tsx
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/Routes/Auctions/SearchResultsAuctions.tsx
  src/Apps/Search/Routes/Categories/SearchResultsCategories.tsx
  src/Apps/Search/Routes/Collections/SearchResultsCollections.tsx
  src/Apps/Search/Routes/Galleries/SearchResultsGalleries.tsx
  src/Apps/Search/Routes/More/SearchResultsMore.tsx
  src/Apps/Search/Routes/Shows/SearchResultsShows.tsx
Labels: Merge On Green, Version: Minor

#2193 Thread through description to search result items
  data/schema.graphql
  src/Apps/Search/Components/GenericSearchResultItem.tsx
  src/Apps/Search/Routes/Auctions/SearchResultsAuctions.tsx
  src/Apps/Search/Routes/Categories/SearchResultsCategories.tsx
  src/Apps/Search/Routes/Collections/SearchResultsCollections.tsx
  src/Apps/Search/Routes/Galleries/SearchResultsGalleries.tsx
  src/Apps/Search/Routes/More/SearchResultsMore.tsx
  src/Apps/Search/Routes/Shows/SearchResultsShows.tsx
  src/__generated__/SearchResultsAuctionsQuery.graphql.ts
  src/__generated__/SearchResultsAuctions_viewer.graphql.ts
  src/__generated__/SearchResultsCategoriesQuery.graphql.ts
  src/__generated__/SearchResultsCategories_viewer.graphql.ts
  src/__generated__/SearchResultsCollectionsQuery.graphql.ts
  src/__generated__/SearchResultsCollections_viewer.graphql.ts
  src/__generated__/SearchResultsGalleriesQuery.graphql.ts
  src/__generated__/SearchResultsGalleries_viewer.graphql.ts
  src/__generated__/SearchResultsMoreQuery.graphql.ts
  src/__generated__/SearchResultsMore_viewer.graphql.ts
  src/__generated__/SearchResultsShowsQuery.graphql.ts
  src/__generated__/SearchResultsShows_viewer.graphql.ts
  src/__generated__/routes_SearchResultsAuctionsQuery.graphql.ts
  src/__generated__/routes_SearchResultsCategoriesQuery.graphql.ts
  src/__generated__/routes_SearchResultsCollectionsQuery.graphql.ts
  src/__generated__/routes_SearchResultsGalleriesQuery.graphql.ts
  src/__generated__/routes_SearchResultsMoreQuery.graphql.ts
  src/__generated__/routes_SearchResultsShowsQuery.graphql.ts
Labels: Version: Minor

#2195 Fix OrderApp stories
  src/Apps/__stories__/OrderApp.story.tsx
  src/Apps/__tests__/Fixtures/Order.ts
Labels: Version: Patch

#2180 Add back artwork structured data
  src/Apps/Artwork/Components/ArtworkMeta.tsx
  src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.fixture.ts
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.test.tsx
  src/Apps/Collect/CollectApp.tsx
  src/Apps/Collect/CollectionApp.tsx
  src/Apps/Collect/Components/Seo/SeoProductsForArtworks.tsx
  src/Apps/Collect/__tests__/CollectApp.test.tsx
  src/Apps/Collect/__tests__/CollectionApp.test.tsx
  src/Apps/Collections/CollectionsApp.tsx
  src/Apps/Collections/__tests__/CollectionsApp.test.tsx
  src/Components/v2/Seo/BreadCrumbList.tsx
  src/Components/v2/Seo/CreativeWork.tsx
  src/Components/v2/Seo/Product.tsx
  src/Components/v2/Seo/index.tsx
  src/__generated__/ArtworkMeta_artwork.graphql.ts
  src/__generated__/SeoDataForArtwork_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2197 Use palette image for lazy loading
  src/Components/Artwork/GridItem.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
Labels: Merge On Green, Version: Minor

#2194 [Router] Add queryParam support
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
  src/Apps/Search/routes.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/Artsy/Router/Components/PreloadLink.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Components/v2/RouteTabs.tsx
  src/__generated__/routes_SearchResultsArtworksQuery.graphql.ts
Labels: Version: Patch

#2198 @dblandin => [SearchResults] Add zero state to all tabs
  src/Apps/Search/Components/ZeroState.tsx
  src/Apps/Search/Routes/Articles/SearchResultsArticles.tsx
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/Routes/Artists/__tests__/SearchResultsArtists.test.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsFilterContainer.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx
  src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
  src/Apps/Search/Routes/Auctions/SearchResultsAuctions.tsx
  src/Apps/Search/Routes/Categories/SearchResultsCategories.tsx
  src/Apps/Search/Routes/Collections/SearchResultsCollections.tsx
  src/Apps/Search/Routes/Galleries/SearchResultsGalleries.tsx
  src/Apps/Search/Routes/More/SearchResultsMore.tsx
  src/Apps/Search/Routes/More/__tests__/SearchResultsMore.test.tsx
  src/Apps/Search/Routes/Shows/SearchResultsShows.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
Labels: Version: Patch

#2160 Improve error message for failed charge in BN flow
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitOrder.ts
  src/Apps/Order/Routes/__tests__/Review.test.tsx
Labels: Version: Patch

#2098 Hide artist insights on artwork page behind button
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/__tests__/ArtistInfo.test.tsx
  src/__generated__/ArtistInfoQuery.graphql.ts
  src/__generated__/ArtistInfo_Test_Query.graphql.ts
  src/__generated__/ArtistInfo_artist.graphql.ts
Labels: Version: Patch

#2201 @dblandin => [SearchResults] Add send feedback component, for logged in users only
  src/Apps/Search/Components/SendFeedback.tsx
  src/Apps/Search/Components/ZeroState.tsx
  src/__generated__/SendFeedbackSearchResultsMutation.graphql.ts
Labels: Version: Minor

#2203 @mzikherman => [SearchResults] Add tests for sending feedback
  src/Apps/Search/Components/__tests__/SendFeedback.test.tsx
Labels: Version: Patch

#2206 Ensure SEO parsing doesn't fail if no dimensions
  src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.test.tsx
Labels: Version: Patch

#2202 DISCO-846: Fix other artwork page follows
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/v2/ArtistCard.tsx
Labels: Jira Synced, Version: Patch

#2204 @pepopowitz => [SearchResults] Add meta tags
  src/Apps/Search/Components/SearchMeta.tsx
  src/Apps/Search/Components/__tests__/SearchMeta.test.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/__tests__/SearchApp.test.tsx
Labels: Jira Synced, Version: Patch

#2211 Add feature flag for lazy-loading
  .storybook/webpack.config.js
  src/Components/Artwork/GridItem.tsx
  typings/sharify.d.ts
Labels: Merge On Green, Version: Minor

#2212 Sync schema with upstream changes
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#2210 @damassi => [SearchResults] Implement analytics
  src/Apps/Search/Components/GenericSearchResultItem.tsx
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/FilterState.tsx
  src/Apps/Search/Routes/Articles/SearchResultsArticles.tsx
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/ColorFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/MediumFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/PriceRangeFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/SizeRangeFilters.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/TimePeriodFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/WaysToBuyFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsFilterContainer.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx
  src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
  src/Apps/Search/Routes/Auctions/SearchResultsAuctions.tsx
  src/Apps/Search/Routes/Categories/SearchResultsCategories.tsx
  src/Apps/Search/Routes/Collections/SearchResultsCollections.tsx
  src/Apps/Search/Routes/Galleries/SearchResultsGalleries.tsx
  src/Apps/Search/Routes/More/SearchResultsMore.tsx
  src/Apps/Search/Routes/Shows/SearchResultsShows.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/Artsy/Analytics/Schema/ContextPage.ts
  src/Artsy/Analytics/Schema/Values.ts
  src/Artsy/Router/Components/Boot.tsx
  src/__generated__/SearchResultsArticlesQuery.graphql.ts
  src/__generated__/SearchResultsArticles_viewer.graphql.ts
  src/__generated__/SearchResultsArtistsQuery.graphql.ts
  src/__generated__/SearchResultsArtists_viewer.graphql.ts
  src/__generated__/SearchResultsArtworks_viewer.graphql.ts
  src/__generated__/SearchResultsAuctionsQuery.graphql.ts
  src/__generated__/SearchResultsAuctions_viewer.graphql.ts
  src/__generated__/SearchResultsCategoriesQuery.graphql.ts
  src/__generated__/SearchResultsCategories_viewer.graphql.ts
  src/__generated__/SearchResultsCollectionsQuery.graphql.ts
  src/__generated__/SearchResultsCollections_viewer.graphql.ts
  src/__generated__/SearchResultsFilterContainer_viewer.graphql.ts
  src/__generated__/SearchResultsGalleriesQuery.graphql.ts
  src/__generated__/SearchResultsGalleries_viewer.graphql.ts
  src/__generated__/SearchResultsMoreQuery.graphql.ts
  src/__generated__/SearchResultsMore_viewer.graphql.ts
  src/__generated__/SearchResultsRefetch_viewer.graphql.ts
  src/__generated__/SearchResultsShowsQuery.graphql.ts
  src/__generated__/SearchResultsShows_viewer.graphql.ts
  src/__generated__/routes_SearchResultsArticlesQuery.graphql.ts
  src/__generated__/routes_SearchResultsArtistsQuery.graphql.ts
  src/__generated__/routes_SearchResultsAuctionsQuery.graphql.ts
  src/__generated__/routes_SearchResultsCategoriesQuery.graphql.ts
  src/__generated__/routes_SearchResultsCollectionsQuery.graphql.ts
  src/__generated__/routes_SearchResultsGalleriesQuery.graphql.ts
  src/__generated__/routes_SearchResultsMoreQuery.graphql.ts
  src/__generated__/routes_SearchResultsShowsQuery.graphql.ts
Labels: Version: Patch

#2213 [TRIVIAL] Remove null states from publishing Icons
  src/Components/Publishing/Icon/IconLayoutBasic.tsx
  src/Components/Publishing/Icon/IconLayoutFullscreen.tsx
  src/Components/Publishing/Icon/IconLayoutSplit.tsx
  src/Components/Publishing/Icon/IconLayoutText.tsx
Labels: Merge On Green, Version: Patch

#2215 Sync metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#2218 @damassi => [Collect] Fix radio buttons which double fire when clicking the label
  src/Apps/Collect/CollectApp.tsx
  src/Apps/Collect/Components/Base/CollectRefetch.tsx
  src/Apps/Collect/Components/Filters/MediumFilter.tsx
  src/Apps/Collect/Components/Filters/TimePeriodFilter.tsx
  src/Apps/Collect/FilterState.tsx
  src/Artsy/Analytics/Schema/Values.ts
Labels: Version: Patch

#2200 [Refactor] Remove PreloadLink
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Collect/__tests__/routes.test.tsx
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/__tests__/SearchApp.test.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/Artsy/Relay/createRelaySSREnvironment.ts
  src/Artsy/Router/Boot.tsx
  src/Artsy/Router/Components/PreloadLink.tsx
  src/Artsy/Router/Components/__tests__/PreloadLink.test.tsx
  src/Artsy/Router/__stories__/Router.story.tsx
  src/Artsy/Router/__tests__/Boot.test.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Artsy/Router/index.ts
  src/Artsy/SystemContext.tsx
  src/Components/v2/RouteTabs.tsx
  src/Components/v2/SelectedExhibitions.tsx
  src/Components/v2/__tests__/SelectedExhibitions.test.tsx
Labels: Version: Minor

#2217 [TRIVIAL] export FeatureTextAsset
  src/Components/Publishing/Header/Layouts/Components/FeatureTextHeader.tsx
Labels: Merge On Green, Version: Patch

#2219 @mzikherman => [SearchResults] Fix analytics for nav tabs
  src/Apps/Search/Components/NavigationTabs.tsx
Labels: Version: Patch

#2220 @damassi => [SearchResults] Correct URL behavior for filter interactions
  src/Apps/Search/FilterState.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/MediumFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/TimePeriodFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx
  src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
Labels: Merge On Green, Version: Patch

#2221 @damassi => Some search results QA
  src/Apps/Search/Components/GenericSearchResultItem.tsx
  src/Apps/Search/Components/SendFeedback.tsx
  src/Apps/Search/FilterState.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsFilterContainer.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx
  src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
  src/Apps/Search/__tests__/FilterState.test.ts
  src/Apps/Search/routes.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/__generated__/ArtworkContextArtistQuery.graphql.ts
  src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkContextFairQuery.graphql.ts
  src/__generated__/ArtworkContextFair_Test_Query.graphql.ts
  src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
  src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
  src/__generated__/ArtworkFilterArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkGridExampleQuery.graphql.ts
  src/__generated__/ArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkGrid_Test_Query.graphql.ts
  src/__generated__/ArtworkGrid_artworks.graphql.ts
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectArtworkGridQuery.graphql.ts
  src/__generated__/CollectArtworkGridTestQuery.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/ComparablesViewQuery.graphql.ts
  src/__generated__/GeneArtworksContentQuery.graphql.ts
  src/__generated__/GeneContentsArtworksQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_Test_Query.graphql.ts
  src/__generated__/SearchResultsArtworkGridQuery.graphql.ts
  src/__generated__/SearchResultsArtworkGridTestQuery.graphql.ts
  src/__generated__/SearchResultsArtworks_viewer.graphql.ts
  src/__generated__/SearchResultsFilterContainer_viewer.graphql.ts
  src/__generated__/SearchResultsRefetchQuery.graphql.ts
  src/__generated__/SearchResultsRefetch_viewer.graphql.ts
  src/__generated__/TagArtworksContentQuery.graphql.ts
  src/__generated__/TagContentsArtworksQuery.graphql.ts
  src/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
  src/__generated__/routes_SearchResultsArtworksQuery.graphql.ts
Labels: Version: Patch

#2224 @damassi => [Search] Allow pagination to be set from URL, and modify URL on artists tab
  data/schema.graphql
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/routes.tsx
  src/__generated__/SearchResultsArtistsQuery.graphql.ts
  src/__generated__/SearchResultsArtists_viewer.graphql.ts
  src/__generated__/routes_SearchResultsArtistsQuery.graphql.ts
Labels: Version: Patch

#2208 Track clicks on "view insights" button on artist insights module
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/__tests__/ArtistInfo.test.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/ArtistInfo_Test_Query.graphql.ts
Labels: Version: Patch

#2225 [RadioGroup] Add deselectable option
  package.json
  src/Apps/Collect/Components/Filters/MediumFilter.tsx
  src/Apps/Collect/Components/Filters/TimePeriodFilter.tsx
  src/Apps/Collect/Components/Filters/__tests__/MediumFilter.test.tsx
  src/Apps/Collect/Components/Filters/__tests__/TimePeriodFilter.test.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/MediumFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/TimePeriodFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/__tests__/MediumFilter.test.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/__tests__/TimePeriodFilter.test.tsx
  yarn.lock
Labels: Version: Patch

#2227 @mzikherman => [Search] Bring back Filter for xs breakpoint
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/FilterContainer.tsx
Labels: Version: Patch

#2229 @damassi => [SearchResults] Remove individual entity tabs in favor of one common one
  src/Apps/Comparables/ComparablesView.tsx
  src/Apps/Comparables/Filter.tsx
  src/Apps/Comparables/Filter/AttributionClassFilter.tsx
  src/Apps/Comparables/Filter/MediumFilter.tsx
  src/Apps/Comparables/Filter/__tests__/Filter.test.tsx
  src/Apps/Comparables/index.tsx
  src/Apps/Search/Routes/Articles/SearchResultsArticles.tsx
  src/Apps/Search/Routes/Auctions/SearchResultsAuctions.tsx
  src/Apps/Search/Routes/Categories/SearchResultsCategories.tsx
  src/Apps/Search/Routes/Collections/SearchResultsCollections.tsx
  src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
  src/Apps/Search/Routes/Entity/__tests__/SearchResultsEntity.test.tsx
  src/Apps/Search/Routes/Galleries/SearchResultsGalleries.tsx
  src/Apps/Search/Routes/More/SearchResultsMore.tsx
  src/Apps/Search/routes.tsx
  src/Apps/__stories__/Comparables.story.tsx
  src/__generated__/ComparablesQuery.graphql.ts
  src/__generated__/ComparablesViewQuery.graphql.ts
  src/__generated__/Filter_viewer.graphql.ts
  src/__generated__/SearchResultsArticlesQuery.graphql.ts
  src/__generated__/SearchResultsArticles_viewer.graphql.ts
  src/__generated__/SearchResultsAuctionsQuery.graphql.ts
  src/__generated__/SearchResultsAuctions_viewer.graphql.ts
  src/__generated__/SearchResultsCategories_viewer.graphql.ts
  src/__generated__/SearchResultsCollectionsQuery.graphql.ts
  src/__generated__/SearchResultsEntityQuery.graphql.ts
  src/__generated__/SearchResultsEntity_viewer.graphql.ts
  src/__generated__/SearchResultsGalleriesQuery.graphql.ts
  src/__generated__/SearchResultsGalleries_viewer.graphql.ts
  src/__generated__/SearchResultsMoreQuery.graphql.ts
  src/__generated__/SearchResultsMore_viewer.graphql.ts
  src/__generated__/SearchResultsShowsQuery.graphql.ts
  src/__generated__/SearchResultsShows_viewer.graphql.ts
  src/__generated__/routes_SearchResultsArticlesQuery.graphql.ts
  src/__generated__/routes_SearchResultsAuctionsQuery.graphql.ts
  src/__generated__/routes_SearchResultsCategoriesQuery.graphql.ts
  src/__generated__/routes_SearchResultsCollectionsQuery.graphql.ts
  src/__generated__/routes_SearchResultsEntityQuery.graphql.ts
  src/__generated__/routes_SearchResultsGalleriesQuery.graphql.ts
  src/__generated__/routes_SearchResultsMoreQuery.graphql.ts
Labels: Version: Patch

#2231 Update spacer
  src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
Labels: Version: Patch
