Repository artsy/reaction, pull requests merged in 2019-05, with the labels that each got.

#2358 [NavBar] Fix notification count
  src/Artsy/SystemContext.tsx
  src/Components/NavBar/NotificationsBadge.tsx
Labels: Version: Patch

#2357 User can see and click on feedback link in FAQ Modal
  src/Apps/Artwork/Components/PricingContextModal.tsx
  src/Apps/Artwork/Components/__tests__/PricingContextModal.test.tsx
Labels: Version: Patch

#2359 Carousel arrows now fade and fixes first slide highlighting
  src/Components/v2/CarouselV2.tsx
Labels: Version: Patch

#2360 Fully roll out artist recommendations
  src/Apps/Artist/Components/NavigationTabs.tsx
  src/Apps/Artist/Components/__tests__/NavigationTabs.test.tsx
  src/Apps/Artist/Routes/Overview/__tests__/Index.fixture.tsx
  src/Apps/Artist/Routes/Overview/__tests__/index.test.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artist/Routes/RelatedArtists/RelatedArtistsList.tsx
  src/Apps/Artist/Routes/RelatedArtists/__tests__/RelatedArtists.test.tsx
  src/Apps/Artist/Routes/RelatedArtists/index.tsx
  src/Apps/Artist/routes.tsx
  src/__generated__/RelatedArtistsListQuery.graphql.ts
  src/__generated__/RelatedArtistsList_artist.graphql.ts
  src/__generated__/RelatedArtists_Test_Query.graphql.ts
  src/__generated__/RelatedArtists_viewer.graphql.ts
  src/__generated__/routes_RelatedArtistsQuery.graphql.ts
Labels: Version: Minor

#2361 Add Script to Support Ads Hosted on Hashtag Labs' Ad Server
  src/Components/Publishing/Ads/AdScript.tsx
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/Fixtures/Articles.ts
  src/Components/Publishing/Typings.ts
  src/Components/Publishing/__tests__/Article.test.tsx
Labels: Jira Synced, Version: Patch

#2363 Move question icon next to chart title and change color
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/PricingContextModal.tsx
Labels: Version: Patch

#2364 Update <Carousel /> with BaseCarousel
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Components/v2/CarouselV3.tsx
  src/Components/v2/__stories__/CarouselV3.story.tsx
  src/Components/v2/__tests__/Carousel.test.tsx
Labels: Version: Minor

#2365 DISCO-920 - Artwork page images do not use <img> with alt text
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Components/v2/Lightbox/Lightbox.tsx
  src/Components/v2/__stories__/Lightbox.story.tsx
Labels: Jira Synced, Version: Patch

#2366 Add space between 2nd and 3rd paragraph in FAQ modal
  src/Apps/Artwork/Components/PricingContextModal.tsx
Labels: Version: Patch

#2368 Moves ad script component below article layout component
  src/Components/Publishing/Article.tsx
Labels: Merge On Green, Version: Patch

#2367 [NavBar] Add test coverage
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/Menus/MoreNavMenu.tsx
  src/Components/NavBar/Menus/NotificationsMenu.tsx
  src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBar/Menus/__tests__/MoreNavMenu.test.tsx
  src/Components/NavBar/Menus/__tests__/NotificationsMenu.test.tsx
  src/Components/NavBar/Menus/__tests__/UserMenu.test.tsx
  src/Components/NavBar/NavItem.tsx
  src/Components/NavBar/Utils/__tests__/auth.test.ts
  src/Components/NavBar/__tests__/NavBar.test.tsx
  src/Components/NavBar/__tests__/NavItem.test.tsx
  src/Components/NavBar/__tests__/NotificationsBadge.test.tsx
Labels: Skip Release

#2351 User can click browse link to go to filtered collect page
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/__stories__/PricingContext.story.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Artwork/Utils/__tests__/createCollectUrl.test.tsx
  src/Apps/Artwork/Utils/createCollectUrl.tsx
  src/Apps/Collect/routes.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/PricingContextStoryQuery.graphql.ts
  src/__generated__/PricingContextTestQuery.graphql.ts
  src/__generated__/PricingContext_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
Labels: Version: Patch

#2376 DISCO-974 - Expand price by default on collect and artist page
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Collect/Components/Filters/FilterContainer.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2377 Render artwork page artist info component server-side
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/__tests__/ArtistInfo.test.tsx
  src/Apps/__tests__/Fixtures/Artist/Components/ArtistInfo.tsx
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2371 Uses <Img> instead of <div> for SSR artwork image
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.test.tsx
  src/Components/v2/Lightbox/Lightbox.tsx
  src/Components/v2/__stories__/Lightbox.story.tsx
Labels: Jira Synced, Version: Patch

#2355 Hide partner name on artwork page for benefit and gallery auctions
  src/Apps/Artwork/Components/ArtworkBanner/index.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkBanner.ts
  src/Components/v2/AuctionCard.tsx
  src/Components/v2/__stories__/AuctionCard.story.tsx
  src/Components/v2/__tests__/AuctionCard.test.tsx
  src/__generated__/ArtworkBannerQuery.graphql.ts
  src/__generated__/ArtworkBanner_Test_Query.graphql.ts
  src/__generated__/ArtworkBanner_artwork.graphql.ts
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkDetailsAboutTheWorkFromPartner_artwork.graphql.ts
  src/__generated__/ArtworkDetailsQuery.graphql.ts
  src/__generated__/ArtworkDetails_Test_Query.graphql.ts
  src/__generated__/AuctionCard_sale.graphql.ts
  src/__generated__/OtherAuctionsQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Merge On Green, Version: Patch

#2369 @pepopowitz => Better /collect pagination
  src/Apps/Collect/CollectApp.tsx
  src/Apps/Collect/Components/Base/CollectArtworkGrid.tsx
  src/Apps/Collect/Components/Base/CollectFilterContainer.tsx
  src/Apps/Collect/Components/Base/CollectRefetch.tsx
  src/Apps/Collect/FilterState.tsx
  src/Apps/Collect/__tests__/FilterState.test.tsx
  src/Apps/Collect/routes.tsx
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectApp_viewer.graphql.ts
  src/__generated__/CollectFilterContainer_viewer.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectRefetch_viewer.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
Labels: Version: Patch

#2379 Pass dimension_range through the CollectApp viewer + update dimension_range to match size_score
  src/Apps/Artwork/Utils/__tests__/createCollectUrl.test.tsx
  src/Apps/Artwork/Utils/createCollectUrl.tsx
  src/Apps/Collect/CollectApp.tsx
  src/Apps/Collect/Components/Base/CollectFilterContainer.tsx
  src/Apps/Collect/Components/Base/CollectRefetch.tsx
  src/Apps/Collect/FilterState.tsx
  src/Apps/Collect/__tests__/FilterState.test.tsx
  src/Apps/Collect/__tests__/routes.test.tsx
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectApp_viewer.graphql.ts
  src/__generated__/CollectFilterContainer_viewer.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectRefetch_viewer.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
Labels: Version: Patch

#2380 Use the current URL to determine the paginated URL in a shared component
  src/Apps/Collect/Components/Base/CollectArtworkGrid.tsx
Labels: Merge On Green

#2378 Removes lab feature requirement for pricing context
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/__stories__/PricingContext.story.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Artwork/routes.tsx
  src/__generated__/PricingContextStoryQuery.graphql.ts
  src/__generated__/PricingContextTestQuery.graphql.ts
  src/__generated__/PricingContext_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2384 DISCO-1005: preserve pagination on collections page
  src/Apps/Collect/CollectionApp.tsx
  src/Apps/Collect/Components/Base/CollectArtworkGrid.tsx
  src/Apps/Collect/Components/Base/CollectRefetch.tsx
  src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
  src/Apps/Collect/Components/Collection/CollectionRefetch.tsx
  src/Apps/Collect/routes.tsx
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionApp_collection.graphql.ts
  src/__generated__/CollectionFilterContainer_collection.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/CollectionRefetch_collection.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Version: Patch

#2388 Creates patch for react-flickity-component to fix flicker
  patches/react-flickity-component+3.2.0.patch
Labels: Version: Patch

#2356 Removes slick from ArtworkImageBrowser
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.test.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Components/v2/CarouselV3.tsx
  src/Components/v2/__stories__/CarouselV3.story.tsx
  src/Components/v2/__tests__/Carousel.test.tsx
Labels: Version: Minor

#2375 Insert htl ads in standard layout articles hidden behind Allowlist Flag
  .storybook/webpack.config.js
  src/Components/Publishing/Display/Canvas/index.tsx
  src/Components/Publishing/Display/DisplayPanel.tsx
  src/Components/Publishing/Display/__tests__/DisplayCanvas.test.tsx
  src/Components/Publishing/Display/__tests__/DisplayPanel.test.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayPanel.test.tsx.snap
  src/Components/Publishing/Fixtures/Components.ts
  src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/Typings.ts
  src/Components/Publishing/__stories__/Display.story.tsx
  typings/sharify.d.ts
Labels: Jira Synced, Version: Patch

#2389 [GROW-1227] - change existing title & breadcrumb placements
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Jira Synced, Version: Patch

#2390 Removes accidental console.log
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
Labels: Version: Patch

#2386 Auth footer updates
  src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
  src/Components/Authentication/Desktop/LoginForm.tsx
  src/Components/Authentication/Desktop/ModalManager.tsx
  src/Components/Authentication/Desktop/SignUpForm.tsx
  src/Components/Authentication/Footer.tsx
  src/Components/Authentication/FormSwitcher.tsx
  src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
  src/Components/Authentication/Mobile/LoginForm.tsx
  src/Components/Authentication/Mobile/SignUpForm.tsx
  src/Components/Authentication/TermsOfServiceCheckbox.tsx
  src/Components/Authentication/Types.ts
  src/Components/Authentication/__tests__/Desktop/SignUpForm.test.tsx
  src/Components/Authentication/__tests__/FormSwitcher.test.tsx
  src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
  src/Components/Authentication/commonElements.tsx
  src/Components/__stories__/Authentication.story.tsx
Labels: Version: Patch

#2391 hides new ads behind admin and env feature flags
  .storybook/webpack.config.js
  src/Components/Publishing/Ads/EnabledAd.ts
  src/Components/Publishing/Ads/__tests__/isHTLAdEnabled.test.ts
  src/Components/Publishing/Display/Canvas/index.tsx
  src/Components/Publishing/Display/DisplayPanel.tsx
  src/Components/Publishing/Display/__tests__/DisplayCanvas.test.tsx
  src/Components/Publishing/Display/__tests__/DisplayPanel.test.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayPanel.test.tsx.snap
  typings/sharify.d.ts
Labels: Version: Patch

#2395 Passes ref and fixes image height
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
Labels: Merge On Green, Version: Patch

#2396 Enable smallCarousel pageDots & draggable only when length > 1
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Components/v2/CarouselV3.tsx
Labels: Version: Patch

#2392 DISCO-1004: Preserve pagination in browser history on artist page
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterRefetch.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/PriceRangeFilter.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artist/Routes/Overview/state.ts
  src/Apps/Artist/routes.tsx
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetch_artist.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkFilter_artist.graphql.ts
  src/__generated__/Overview_artist.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2398 Update renovate to use new lib workflow
  renovate.json
Labels: Version: Trivial

#2404 Adds disabled text to priceRange filters
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/PriceRangeFilter.tsx
  src/Apps/Collect/Components/Filters/PriceRangeFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/PriceRangeFilter.tsx
Labels: Merge On Green, Version: Minor

#2406 Remove "Emitting Types" section from README
  README.md
Labels: Version: Patch

#2393 Add reCAPTCHA events to Auth forms
  src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
  src/Components/Authentication/Desktop/LoginForm.tsx
  src/Components/Authentication/Desktop/SignUpForm.tsx
  src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
  src/Components/Authentication/Mobile/LoginForm.tsx
  src/Components/Authentication/Mobile/SignUpForm.tsx
  src/Components/Authentication/__tests__/Desktop/ForgotPasswordForm.test.tsx
  src/Components/Authentication/__tests__/Desktop/LoginForm.test.tsx
  src/Components/Authentication/__tests__/Desktop/SignUpForm.test.tsx
  src/Components/Authentication/__tests__/Mobile/ForgotPasswordForm.test.tsx
  src/Components/Authentication/__tests__/Mobile/LoginForm.test.tsx
  src/Components/Authentication/__tests__/Mobile/ResetPasswordForm.test.tsx
  src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
  src/Components/Authentication/__tests__/fixtures.ts
  src/Typings/global.d.ts
  src/Utils/__tests__/repcaptcha.test.ts
  src/Utils/repcaptcha.ts
  src/setup_jest.ts
  typings/sharify.d.ts
Labels: Jira Synced, Version: Minor

#2407 Check if user exists before diving
  src/Components/Publishing/Ads/EnabledAd.ts
Labels: Version: Patch

#2409 Changes adUnit and adDimension props from required to optional
  src/Components/Publishing/Display/Canvas/index.tsx
  src/Components/Publishing/Display/DisplayPanel.tsx
  src/Components/Publishing/Typings.ts
Labels: Merge On Green, Version: Patch

#2410 [NavBar] Misc QA
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
Labels: Version: Patch

#2408 [CarouselV3] Update react-flickity-component@3.3.0
  package.json
  patches/react-flickity-component+3.2.0.patch
  src/Components/v2/CarouselV3.tsx
  yarn.lock
Labels: Version: Patch

#2402 Add featured artist module to collection header
  src/Apps/Collect/CollectionApp.tsx
  src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
  src/Apps/Collect/Components/Collection/Header/index.tsx
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionApp_collection.graphql.ts
  src/__generated__/CollectionFilterContainer_collection.graphql.ts
  src/__generated__/Header_artworks.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2412 Do not fire reCAPTCHA actions unless sd.key is present
  src/Utils/__tests__/repcaptcha.test.ts
  src/Utils/repcaptcha.ts
Labels: Version: Patch

#2416 Rename folder for case-sensitivity
  src/Components/v2/CarouselV2.tsx
  src/Utils/Hooks/useDidMount.ts
Labels: Merge On Green, Version: Patch

#2417 [NavBar] Fix padding around spinner fetch
  src/Artsy/Relay/renderWithLoadProgress.tsx
  src/Components/NavBar/Menus/NotificationsMenu.tsx
Labels: Merge On Green, Version: Patch

#2413 Move new hosted ads to their own components in Standard Articles
  src/Components/Publishing/Display/Canvas/index.tsx
  src/Components/Publishing/Display/DisplayPanel.tsx
  src/Components/Publishing/Display/NewDisplayCanvas.tsx
  src/Components/Publishing/Display/NewDisplayPanel.tsx
  src/Components/Publishing/Display/__tests__/DisplayCanvas.test.tsx
  src/Components/Publishing/Display/__tests__/DisplayPanel.test.tsx
  src/Components/Publishing/Display/__tests__/NewDisplayCanvas.test.tsx
  src/Components/Publishing/Display/__tests__/NewDisplayPanel.test.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayoutNewAds.test.tsx
  src/Components/Publishing/__stories__/Display.story.tsx
Labels: Version: Patch

#2418 [NavBar] Fix typo
  src/Components/NavBar/Menus/NotificationsMenu.tsx
Labels: Merge On Green, Version: Patch

#2420 Make FillwidthItem more forgiving of empty artwork images
  src/Components/Artwork/FillwidthItem.tsx
  src/Components/Artwork/__tests__/FillwidthItem.test.tsx
Labels: Version: Patch

#2419 [DISCO-1023] Adds parens to result counts.
  src/Apps/Search/Components/NavigationTabs.tsx
Labels: Jira Synced, Version: Patch

#2414 DISCO 1029 - Consolidate url history management in state containers
  src/Apps/Artist/Routes/Overview/state.ts
  src/Apps/Collect/Components/Base/CollectArtworkGrid.tsx
  src/Apps/Collect/Components/Base/CollectRefetch.tsx
  src/Apps/Collect/Components/Collection/CollectionRefetch.tsx
  src/Apps/Collect/FilterState.tsx
  src/Apps/Search/FilterState.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx
  src/Apps/Search/__tests__/FilterState.test.ts
Labels: Jira Synced, Version: Patch

#2421 Address feedback for #2420
  src/Components/Artwork/FillwidthItem.tsx
  src/Components/Artwork/__tests__/FillwidthItem.test.tsx
Labels: Merge On Green, Version: Patch

#2424 update schema on bid and buy now conversion tracking for criteo
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/__generated__/ArtworkSidebarCommercial_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Review_order.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  src/__generated__/routes_ReviewQuery.graphql.ts
Labels: Version: Patch

#2423 Dont display pageDots if only one image
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
Labels: Version: Patch

#2422 DISCO-1035 - Set the `major_periods` state property correctly when constructing the Artist, Collect, and Search apps.
  src/Apps/Artist/Routes/Overview/state.ts
  src/Apps/Collect/FilterState.tsx
  src/Apps/Collect/__tests__/FilterState.test.tsx
  src/Apps/Search/FilterState.tsx
  src/Apps/Search/__tests__/FilterState.test.ts
Labels: Jira Synced, Version: Patch

#2425 PURCHASE-1102 Remove handling of `null` from the `amount` helper in MP
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Components/__tests__/TransactionDetailsSummary.test.tsx
Labels: Jira Synced, Version: Patch

#2415 DISCO-1041 - Remove unused mediators
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
  src/Apps/Collect/Components/Base/CollectArtworkGrid.tsx
  src/Apps/Collect/Components/Base/CollectFilterContainer.tsx
  src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
  src/Apps/Collect/Components/Filters/ColorFilter.tsx
  src/Apps/Collect/Components/Filters/FilterContainer.tsx
  src/Apps/Collect/Components/Filters/MediumFilter.tsx
  src/Apps/Collect/Components/Filters/PriceRangeFilter.tsx
  src/Apps/Collect/Components/Filters/SizeRangeFilters.tsx
  src/Apps/Collect/Components/Filters/SortFilter.tsx
  src/Apps/Collect/Components/Filters/TimePeriodFilter.tsx
  src/Apps/Collect/Components/Filters/WaysToBuyFilter.tsx
  src/Apps/Collect/Components/Filters/__tests__/FilterContainer.test.tsx
  src/Apps/Collect/FilterState.tsx
  src/Apps/Collect/__tests__/FilterState.test.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/FilterContainer.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/__tests__/FilterContainer.test.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsFilterContainer.tsx
Labels: Jira Synced

#2426 [Lib] Bump @types/react-tracking@6.0.0
  package.json
  yarn.lock
Labels: Version: Patch

#2427 Signup form includes recaptcha_token on handleSubmit
  src/Components/Authentication/Desktop/SignUpForm.tsx
  src/Components/Authentication/Mobile/SignUpForm.tsx
  src/Components/Authentication/__tests__/Desktop/SignUpForm.test.tsx
  src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2428 [Schema] Sync schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#2431 Collection header qa refactor
  src/Apps/Collect/Components/Collection/Header/index.tsx
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/Header_artworks.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#2434 [Tracking] Remove unneeded custom tracking context
  package.json
  src/Artsy/Analytics/Schema/Label.ts
  src/Artsy/Analytics/TrackingContext.tsx
  src/Artsy/Analytics/__tests__/useTracking.test.tsx
  src/Artsy/Analytics/index.ts
  src/Artsy/Analytics/useTracking.ts
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/Menus/UserMenu.tsx
  src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBar/Menus/__tests__/MoreNavMenu.test.tsx
  src/Components/NavBar/Menus/__tests__/UserMenu.test.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NotificationsBadge.tsx
  src/Components/NavBar/Utils/__tests__/authentication.test.ts
  src/Components/NavBar/Utils/authentication.ts
  src/Components/NavBar/__tests__/NavBar.test.tsx
  src/Components/NavBar/__tests__/NavBarTracking.test.tsx
  src/Components/NavBar/__tests__/NotificationsBadge.test.tsx
Labels: Version: Minor

#2437 Removes Enabled Ad Feature Flags from client
  src/Components/Publishing/Ads/EnabledAd.ts
  src/Components/Publishing/Ads/__tests__/EnabledAd.test.ts
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/Display/NewDisplayCanvas.tsx
  src/Components/Publishing/Display/NewDisplayPanel.tsx
  src/Components/Publishing/Display/__tests__/NewDisplayCanvas.test.tsx
  src/Components/Publishing/Display/__tests__/NewDisplayPanel.test.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/Fixtures/Components.ts
  src/Components/Publishing/Layouts/ClassicLayout.tsx
  src/Components/Publishing/Layouts/NewsLayout.tsx
  src/Components/Publishing/Layouts/SeriesLayout.tsx
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/Layouts/VideoLayout.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayoutNewAds.test.tsx
  src/Components/Publishing/Typings.ts
  src/Components/Publishing/__stories__/Display.story.tsx
Labels: Merge On Green, Version: Patch

#2438 Clean up renovate config to remove redundant options
  renovate.json
Labels: Merge On Green, Version: Trivial

#2439 Select default time period filter selection via RadioGroup instead of Radio
  src/Apps/Collect/Components/Filters/TimePeriodFilter.tsx
Labels: Jira Synced, Version: Patch

#2430 DISCO-1032 Apply `medium` filter in path instead of querystring on /collect
  src/Apps/Artist/Routes/Overview/state.ts
  src/Apps/Collect/AnalyticsProvider.tsx
  src/Apps/Collect/FilterState.tsx
  src/Apps/Collect/__tests__/urlBuilder.test.ts
  src/Apps/Collect/routes.tsx
  src/Apps/Collect/urlBuilder.ts
  src/Apps/Search/FilterState.tsx
Labels: Jira Synced, Version: Patch

#2442 [NavBar] Address QA items
  package.json
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/Menus/MoreNavMenu.tsx
  src/Components/NavBar/Menus/NotificationsMenu.tsx
  src/Components/NavBar/Menus/__tests__/MoreNavMenu.test.tsx
  src/Components/NavBar/Menus/__tests__/NotificationsMenu.test.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
  src/Components/NavBar/NotificationsBadge.tsx
  src/Components/NavBar/__tests__/NavBar.test.tsx
  src/Components/NavBar/__tests__/NavBarTracking.test.tsx
  src/Components/NavBar/__tests__/NavItem.test.tsx
  src/Components/__stories__/NavBar.story.tsx
  src/Utils/BreakpointVisualizer.tsx
  src/Utils/Hooks/useMedia.ts
  yarn.lock
Labels: Jira Synced, Version: Patch

#2446 [Lib] Bump react-tracking@7.0.1 + types
  package.json
  yarn.lock
Labels: Merge On Green, Version: Patch

#2447 [NavBar] QA round 2
  package.json
  src/Artsy/Analytics/useTracking.ts
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
  src/Components/NavBar/__tests__/NavBar.test.tsx
  src/Components/NavBar/__tests__/NavBarTracking.test.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/Search/SearchInputContainer.tsx
  src/Utils/Hooks/useMedia.ts
Labels: Version: Patch

#2451 DISCO-1053 - Remove major_periods filter properly from FilterState in /collect & /collection/:id apps
  src/Apps/Collect/FilterState.tsx
Labels: Jira Synced, Version: Patch

#2457 Sync metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#2453 Add new ads to News landing page
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/Display/DisplayTargeting.tsx
  src/Components/Publishing/Layouts/NewsLayout.tsx
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/Layouts/__tests__/NewsLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Typings.ts
Labels: Jira Synced, Version: Patch

#2460 Add hover to mobile nav items
  data/schema.graphql
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/__stories__/NavBar.story.tsx
Labels: Merge On Green, Version: Patch

#2465 Use Artsy forks instead of Alloy's
  package.json
  yarn.lock
Labels: Merge On Green

#2468 Updates search results skeleton styling
  src/Apps/Collect/Components/Filters/FilterContainer.tsx
  src/Apps/Collect/Components/Filters/WaysToBuyFilter.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/FilterSidebar.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/GridItem.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/Header.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/index.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/FilterContainer.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/WaysToBuyFilter.tsx
Labels: Version: Patch

#2462 Match on Bar instead of BarBox to make tests work
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
Labels: Version: Patch

#2463 Enable New ads on series landing pages
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/NewDisplayCanvas.test.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/Layouts/NewsLayout.tsx
  src/Components/Publishing/Layouts/SeriesLayout.tsx
  src/Components/Publishing/Layouts/__tests__/NewsLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Layouts/__tests__/SeriesLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Typings.ts
Labels: Jira Synced, Version: Patch

#2387 If a user has multiple saved credit cards, returning to the Payment page on an order should automatically choose the card associated with the order
  src/Apps/Order/Components/PaymentPicker.tsx
  src/Apps/Order/Components/__tests__/PaymentPicker.test.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/createCreditCard.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/PaymentPickerCreateCreditCardMutation.graphql.ts
  src/__generated__/PaymentPickerTestQuery.graphql.ts
  src/__generated__/PaymentPicker_order.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/routes_NewPaymentQuery.graphql.ts
  src/__generated__/routes_PaymentQuery.graphql.ts
Labels: Version: Patch

#2469 Sync with some metaphysics id changes
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#2473 [NavBar] Fix click-area
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/Menus/MoreNavMenu.tsx
  src/Components/NavBar/Menus/UserMenu.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
  src/Components/NavBar/NotificationsBadge.tsx
  src/Components/NavBar/__tests__/NavBar.test.tsx
  src/Components/NavBar/__tests__/NavBarTracking.test.tsx
  src/Components/NavBar/__tests__/NavItem.test.tsx
  src/Utils/Hooks/useMedia.ts
Labels: Version: Patch

#2475 replace use of SmallSelect with SelectSmall
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Collect/Components/Filters/SortFilter.tsx
Labels: Version: Patch

#2470 [Ad Server] add new ads for video layout pages
  src/Components/Publishing/Layouts/SeriesLayout.tsx
  src/Components/Publishing/Layouts/VideoLayout.tsx
  src/Components/Publishing/Layouts/__tests__/VideoLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
Labels: Jira Synced, Version: Patch

#2477 Sync schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#2481 [NavBar] Fix notification count for zero notifications
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/__tests__/NavBarTracking.test.tsx
Labels: Version: Patch

#2482 Sync MP schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#2483 [Lib] Fix type-checking between Reaction / Palette
  package.json
  yarn.lock
Labels: Version: Patch

#2480 Prevent right click on artwork images
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Artsy/SystemContext.tsx
  src/Components/Artwork/FillwidthItem.tsx
  src/Components/Artwork/GridItem.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/Components/v2/Lightbox/Lightbox.tsx
  src/DevTools/MockRouter.tsx
  src/Utils/__tests__/user.test.ts
  src/Utils/user.ts
Labels: Jira Synced, Version: Patch

#2484 [Tooling] Update apollo.config to match Emission
  apollo.config.js
Labels: Skip Release

#2485 Add price/-price to SortFilter for collections
  src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
  src/Apps/Collect/Components/Filters/FilterContainer.tsx
  src/Apps/Collect/Components/Filters/SortFilter.tsx
  src/Apps/Collect/Components/Filters/SortFilterSortTypes.tsx
  src/Apps/Collect/Components/Filters/__tests__/FilterContainer.test.tsx
  src/Apps/Collect/Components/Filters/__tests__/SortFilter.test.tsx
  src/Apps/Collect/Components/Filters/__tests__/SortFilterSortTypes.test.tsx
  src/Apps/Order/Components/__tests__/PaymentPicker.test.tsx
Labels: Jira Synced, Version: Patch
