Repository artsy/reaction, pull requests merged in 2019-11, with the labels that each got.

#2951 [PURCHASE-1578] Adds `<Tags>` component for genes
  package.json
  src/Apps/Artist/Routes/Overview/Components/Genes.tsx
  src/Apps/Artist/Routes/Overview/Components/__tests__/Genes.test.tsx
  src/Components/NavBar/NavItem.tsx
  src/__generated__/GenesTestQuery.graphql.ts
  yarn.lock
Labels: Jira Synced, Version: Patch

#2966 Update buyer's premium copy and location
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarCurrentBidInfo.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarAuctionPartnerInfo.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCurrentBidInfo.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.ts
  src/__generated__/ArtworkSidebarAuctionPartnerInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarAuctionPartnerInfo_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCurrentBidInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCurrentBidInfo_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebarStoryQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2970 [GROW-1639] close collection hubs entry points a/b test on the collect page
  .storybook/webpack.config.js
  src/Apps/Collect2/Routes/Collect/index.tsx
  typings/sharify.d.ts
Labels: Jira Synced, Version: Patch

#2969 Safe access to artwork image in `ArtworkSummaryItem`
  src/Apps/Order/Components/ArtworkSummaryItem.tsx
Labels: Jira Synced, Version: Patch

#2971 Sync schema
  data/schema.graphql
Labels: Version: Patch

#2975 @alloy => [v2] Get storybooks working
  package.json
  yarn.lock
Labels: Version: Patch

#2977 [MP v2] Remove mock resolvers and add more typings to tests
  package.json
  src/Apps/Artist/Components/__tests__/ArtistHeader.test.tsx
  src/Apps/Artist/Components/__tests__/NavigationTabs.test.tsx
  src/Apps/Artist/Routes/Articles/__tests__/Articles.test.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/Apps/Artist/Routes/CV/__tests__/CV.test.tsx
  src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistRecommendations.test.tsx
  src/Apps/Artist/Routes/Overview/Components/__tests__/Genes.test.tsx
  src/Apps/Artist/Routes/Overview/__tests__/CurrentEvent.test.tsx
  src/Apps/Artist/Routes/Overview/__tests__/Genes.test.tsx
  src/Apps/Artwork/Components/ArtworkBanner/__tests__/ArtworkBanner.test.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebar.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarArtists.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarAuctionPartnerInfo.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarBidAction.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarClassification.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCurrentBidInfo.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarExtraLinks.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarMetadata.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPartnerInfo.test.tsx
  src/Apps/Artwork/Components/TrustSignals/__tests__/AuthenticityCertificate.test.tsx
  src/Apps/Artwork/Components/TrustSignals/__tests__/SecurePayment.test.tsx
  src/Apps/Artwork/Components/TrustSignals/__tests__/VerifiedSeller.test.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Auction/Components/__tests__/AuctionFAQ.test.tsx
  src/Apps/Auction/__tests__/routes.test.ts
  src/Apps/Auction/routes.tsx
  src/Apps/Collect2/Routes/Collections/__tests__/CollectionsApp.test.tsx
  src/Apps/Order/Components/__tests__/OfferHistoryItem.test.tsx
  src/Apps/Order/Components/__tests__/TransactionDetailsSummary.test.tsx
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/Order/routes.tsx
  src/Apps/__tests__/Fixtures/Collections.ts
  src/Components/Artwork/__tests__/Details.test.tsx
  src/Components/ArtworkGrid/__tests__/ArtworkGrid.test.tsx
  src/Components/Search/__tests__/SearchBar.test.tsx
  src/Components/v2/FollowArtistPopover/index.tsx
  src/Components/v2/__tests__/ArtistBio.test.tsx
  src/Components/v2/__tests__/SelectedCareerAchievements.test.tsx
  src/DevTools/__tests__/MockRelayRenderer.mocked.test.tsx
  src/DevTools/__tests__/MockRelayRenderer.test.tsx
  src/DevTools/__tests__/MockRelayRendererFixtures.tsx
  src/DevTools/__tests__/renderRelayTree.test.tsx
  src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
  src/__generated__/MockRelayRendererFixturesBadQuery.graphql.ts
  src/__generated__/MockRelayRendererFixturesQuery.graphql.ts
  src/__generated__/routes_ConfirmBidQuery.graphql.ts
  src/__generated__/routes_OrderQuery.graphql.ts
  src/__generated__/routes_RegisterQuery.graphql.ts
Labels: Version: Patch

#2978 Re-enable storybooks
  src/__stories__/storiesOf.js
Labels: Version: Patch

#2981 [MP v2] Migrate WorksForYou app
  src/Apps/WorksForYou/WorksForYouArtistFeed.tsx
  src/Apps/WorksForYou/WorksForYouFeed.tsx
  src/Components/Artwork/Save.tsx
Labels: Jira Synced, Version: Patch

#2982 [v2] Migrate Editorial to MPv2
  src/Components/Publishing/Fixtures/Components.ts
  src/Components/Publishing/ToolTip/ArtistToolTip.tsx
  src/Components/Publishing/ToolTip/GeneToolTip.tsx
  src/Components/Publishing/ToolTip/LinkWithTooltip.tsx
  src/Components/Publishing/ToolTip/ToolTip.tsx
  src/Components/Publishing/ToolTip/TooltipsDataLoader.tsx
  src/Components/Publishing/ToolTip/__tests__/LinkWithTooltip.test.jsx
  src/Components/Publishing/ToolTip/__tests__/LinkWithTooltip.test.tsx
Labels: Jira Synced, Version: Patch

#2976 @alloy => V2 artist app
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionEntity.tsx
  src/Apps/Artist/Components/ArtistMeta.tsx
  src/Apps/Artist/Components/MarketDataSummary/MarketDataSummary.tsx
  src/Apps/Artist/Components/MarketInsights/MarketInsights.tsx
  src/Apps/Artist/Components/NavigationTabs.tsx
  src/Apps/Artist/Routes/Articles/ArtistArticles.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/CV/CVItem.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artist/Routes/Shows/ArtistShows.tsx
  src/Apps/Artist/Routes/Shows/index.tsx
  src/Apps/Artist/routes.tsx
  src/Apps/Artwork/Components/OtherAuctions.tsx
  src/Apps/Artwork/Components/__stories__/OtherAuctions.story.tsx
  src/Apps/__stories__/ArtistApp.story.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid2.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/GalleryFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/InstitutionFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistArtworkFilter_artist.graphql.ts
  src/__generated__/ArtworkFilterArtworkGrid2Query.graphql.ts
  src/__generated__/ArtworkFilterArtworkGrid2_filtered_artworks.graphql.ts
  src/__generated__/OtherAuctionsQuery.graphql.ts
  src/__generated__/OtherAuctionsStoryQuery.graphql.ts
  src/__generated__/OtherAuctions_sales.graphql.ts
  src/__generated__/OverviewQuery.graphql.ts
  src/__generated__/Overview_artist.graphql.ts
Labels: Version: Patch

#2986 [v2] migrate /collection/:id
  src/Apps/Collect2/Components/SeoProductsForArtworks.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesEntity.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesRail.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/DefaultHeader.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/DefaultHeader.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/__snapshots__/DefaultHeader.test.tsx.snap
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/fixtures/artworks.ts
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/__stories__/Collect.story.tsx
  src/Apps/__tests__/Fixtures/Collections.ts
  src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionEntity.test.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
  src/Components/v2/RecentlyViewed.tsx
  src/__generated__/CollectionRefetch2Query.graphql.ts
  src/__generated__/Collection_viewer.graphql.ts
  src/__generated__/DefaultHeader_headerArtworks.graphql.ts
  src/__generated__/SeoProductsForArtworks_artworks.graphql.ts
Labels: Version: Patch

#2988 Migrate Auction app to Metaphysics V2
  src/Apps/Auction/Components/LotInfo.tsx
  src/Apps/Auction/Components/__stories__/LotInfo.story.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/Register/index.tsx
  src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidder.ts
  src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
  src/Apps/Auction/Routes/__fixtures__/MutationResults/createCreditCardAndUpdatePhone.ts
  src/Apps/Auction/Routes/__stories__/Register.story.tsx
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/Apps/Auction/Routes/__tests__/Register.test.tsx
  src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
  src/Apps/Auction/__fixtures__/routes_RegisterQuery.ts
  src/Apps/Auction/__tests__/routes.test.ts
  src/Apps/Auction/getRedirect.ts
  src/Apps/Auction/routes.tsx
  src/Apps/__tests__/Fixtures/Auction/Routes/Register/index.ts
  src/__generated__/ConfirmBidValidTestQuery.graphql.ts
  src/__generated__/LotInfo_artwork.graphql.ts
  src/__generated__/LotInfo_saleArtwork.graphql.ts
  src/__generated__/RegisterCreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/__generated__/RegisterValidTestQuery.graphql.ts
  src/__generated__/routes_ConfirmBidQuery.graphql.ts
  src/__generated__/routes_RegisterQuery.graphql.ts
Labels: Version: Patch

#2984 @xtina-starr => [WIP] [v2] Get collect rendering
  src/Apps/Collect2/Components/SeoProductsForArtworks.tsx
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/collectRoutes.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid2.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/__generated__/ArtworkFilterArtworkGrid2Query.graphql.ts
  src/__generated__/ArtworkFilterQuery.graphql.ts
  src/__generated__/ArtworkFilter_viewer.graphql.ts
  src/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Labels: Version: Patch

#2989 Collections tests pass
  src/Apps/Collect2/Routes/Collections/__tests__/CollectionsApp.test.tsx
  src/Apps/Collect2/Routes/Collections/index.tsx
  src/Apps/Collect2/collectRoutes.tsx
  src/__generated__/CollectionsAppTestQuery.graphql.ts
  src/__generated__/Collections_marketingCategories.graphql.ts
  src/__generated__/collectRoutes_MarketingCollectionsAppQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2983 [MP v2] Migrate Search app's artworks tab
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/Routes/Artworks/index.tsx
  src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
  src/Apps/Search/SearchApp.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid2.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  src/Components/v2/ArtworkFilter/Utils/isDefaultFilter.tsx
  src/Components/v2/ArtworkFilter/Utils/rangeToTuple.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/__generated__/ArtworkFilterQuery.graphql.ts
  src/__generated__/ArtworkFilter_viewer.graphql.ts
  src/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
  src/__stories__/config.js
Labels: Jira Synced, Version: Patch

#2993 @alloy => Artist app tests for v2
  src/Apps/Artist/Routes/Articles/__tests__/Articles.test.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/Apps/Artist/Routes/CV/__tests__/CV.test.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artist/Routes/Shows/__tests__/Shows.test.tsx
  src/Apps/Artist/routes.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/ArticlesFixture.ts
  src/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
  src/Apps/__tests__/Fixtures/Artist/Routes/CV.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/ShowsFixture.ts
  src/DevTools/createMockNetworkLayer/index.ts
Labels: Version: Patch

#2990 Allow users to register+bid
  data/schema.graphql
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
  src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
Labels: Jira Synced

#2991 [MP v2] Finish Search migration
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/Routes/Artists/__tests__/SearchResultsArtists.test.tsx
  src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
  src/Apps/Search/Routes/Entity/__tests__/SearchResultsEntity.test.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/__tests__/SearchApp.test.tsx
Labels: Jira Synced, Version: Patch

#2987 [WIP] MP v2 migration artwork app
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkBanner/index.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.test.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Apps/Artwork/Components/ArtworkMeta.tsx
  src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
  src/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/index.tsx
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/__stories__/OtherWorks.story.tsx
  src/Apps/Artwork/Components/__stories__/PricingContext.story.tsx
  src/Apps/Artwork/Components/__tests__/OtherWorks.test.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkActions.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkBanner.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkDetails.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkImageBrowser.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkRelatedArtists.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarArtists.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarBidAction.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCommercial.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarExtraLinks.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarMetadata.ts
  src/Apps/__tests__/Fixtures/Artwork/FullArtwork.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/MutationResults.ts
  src/Apps/__tests__/Fixtures/Artworks.ts
  src/Components/Gene/GeneArtworksContent.tsx
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/PricingContextStoryQuery.graphql.ts
  src/__generated__/PricingContextTestQuery.graphql.ts
  src/__generated__/PricingContext_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Patch

#2996 @alloy => [v2] Finish artist app
  src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionEntity.test.tsx
  src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Components/MarketInsights/MarketInsights.tsx
  src/Apps/Artist/Components/MarketInsights/__tests__/Fixtures/Artists.fixture.ts
  src/Apps/Artist/Components/__tests__/ArtistMeta.test.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Apps/Artist/Routes/Overview/Components/__tests__/ArtistRecommendations.test.tsx
  src/Apps/Artist/Routes/Overview/Components/__tests__/Genes.test.tsx
  src/Apps/Artist/Routes/Overview/__tests__/index.test.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/__tests__/Fixtures/Artist/Components/ArtistHeader.tsx
  src/Apps/__tests__/Fixtures/Artist/Components/NavigationTabs.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/Overview/Genes.tsx
  src/Apps/__tests__/Fixtures/Collections.ts
Labels: Version: Patch

#2998 Fix type errors in order app v2
  package.json
  patches/found+0.4.9.patch
  src/Apps/Order/Components/ItemReview.tsx
  src/Apps/Order/Components/__stories__/ItemReview.story.tsx
  src/Apps/Order/Components/__stories__/TransactionDetailsSummaryItem.story.tsx
  src/Apps/Order/Components/__tests__/OfferHistoryItem.test.tsx
  src/Apps/Order/Components/__tests__/PaymentPicker.test.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Utils/commitMutation.tsx
  src/Apps/Order/__tests__/OrderApp.test.tsx
  yarn.lock
Labels: Version: Patch

#2992 PLATFORM-1962: Migrate Payment “app”
  src/Apps/Order/Components/CreditCardDetails.tsx
  src/Apps/Order/Components/CreditCardSummaryItem.tsx
  src/Apps/Order/Components/PaymentPicker.tsx
  src/Apps/Order/Components/__stories__/CreditCardDetails.story.tsx
  src/Components/Payment/SavedCreditCards.tsx
  src/Components/Payment/UserSettingsPayments.tsx
  src/Components/Payment/__tests__/SavedCreditCards.test.tsx
  src/Components/Payment/__tests__/UserSettingsPayments.test.tsx
  src/Components/__stories__/Payment.story.tsx
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/CreditCardSummaryItem_order.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/PaymentFormCreateCreditCardMutation.graphql.ts
  src/__generated__/PaymentMultipleCreditCardsQuery.graphql.ts
  src/__generated__/PaymentNoCreditCardsQuery.graphql.ts
  src/__generated__/PaymentPickerCreateCreditCardMutation.graphql.ts
  src/__generated__/PaymentPickerTestQuery.graphql.ts
  src/__generated__/PaymentPicker_me.graphql.ts
  src/__generated__/PaymentPicker_order.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/UserSettingsPaymentsCreditCard.graphql.ts
  src/__generated__/UserSettingsPaymentsQuery.graphql.ts
  src/__generated__/UserSettingsPayments_me.graphql.ts
  src/__generated__/routes_AcceptQuery.graphql.ts
  src/__generated__/routes_CounterQuery.graphql.ts
  src/__generated__/routes_NewPaymentQuery.graphql.ts
  src/__generated__/routes_PaymentQuery.graphql.ts
  src/__generated__/routes_RespondQuery.graphql.ts
  src/__generated__/routes_ReviewQuery.graphql.ts
  src/__generated__/routes_StatusQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2999 MP v2 migration Order app
  src/Apps/Order/Components/__tests__/PaymentPicker.test.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/createCreditCard.ts
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/__tests__/Fixtures/Order.ts
Labels: Jira Synced, Version: Patch

#3002 [MP v2] Make test suite green
  __mocks__/react-relay.js
  package.json
  patches/found+0.4.9.patch
  src/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
  src/Apps/Artist/Routes/Overview/__tests__/Index.fixture.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artwork/Components/ArtworkBanner/__tests__/ArtworkBanner.test.tsx
  src/Apps/Artwork/Components/ArtworkBanner/index.tsx
  src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.fixture.ts
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.test.tsx
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesEntity.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesRail.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionEntity.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionsRail.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
  src/Apps/Collect2/Routes/Collections/__tests__/CollectionsApp.test.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/Overview/CurrentEvent.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkBanner.ts
  src/Apps/__tests__/Fixtures/Collections.ts
  src/Artsy/Router/RouterLink.tsx
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Components/Artwork/__tests__/Details.test.tsx
  src/Components/ArtworkGrid/__stories__/ArtworkGridFixture.ts
  src/Components/ArtworkGrid/__tests__/ArtworkGrid.test.tsx
  src/Components/FollowButton/FollowGeneButton.tsx
  src/Components/FollowButton/__tests__/FollowArtistButton.test.tsx
  src/Components/FollowButton/__tests__/FollowGeneButton.test.tsx
  src/Components/NavBar/NotificationsBadge.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/MediumFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.test.tsx
  src/Components/v2/ArtworkFilter/Utils/__tests__/urlFragmentFromState.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/fixtures/ArtworkFilter.fixture.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/Components/v2/FollowArtistPopover/__tests__/FollowArtistPopover.test.tsx
  src/DevTools/__tests__/MockRelayRendererFixtures.tsx
  src/DevTools/__tests__/createTestEnv.test.tsx
  src/DevTools/__tests__/renderRelayTree.test.tsx
  src/__generated__/ArtistRecommendationsPaginationQuery.graphql.ts
  src/__generated__/ArtistRecommendationsRendererQuery.graphql.ts
  src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
  src/__generated__/ArtistRecommendations_artist.graphql.ts
  src/__generated__/ArtworkBannerQuery.graphql.ts
  src/__generated__/ArtworkBanner_Test_Query.graphql.ts
  src/__generated__/ArtworkBanner_artwork.graphql.ts
  src/__generated__/ArtworkFilterQuery.graphql.ts
  src/__generated__/MockRelayRendererFixturesArtistQuery.graphql.ts
  src/__generated__/OverviewQuery.graphql.ts
  src/__generated__/SeoDataForArtwork_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  src/setup_jest.ts
  typings/found.d.ts
  yarn.lock
Labels: Version: Patch

#3003 [MP v2] Fix Collection featured artist header
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/DefaultHeader.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/fixtures/artworks.ts
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/__generated__/CollectionRefetch2Query.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/Header_artworks.graphql.ts
  src/__generated__/Header_collection.graphql.ts
Labels: Version: Patch

#3004 @alloy => [v2] Gene and Tag pagination fixes
  src/Components/ArtworkFilter/Headline.tsx
  src/Components/Gene/GeneArtworks.tsx
  src/Components/Gene/GeneArtworksContent.tsx
  src/Components/Gene/index.tsx
  src/Components/Tag/TagArtworks.tsx
  src/Components/Tag/TagArtworksContent.tsx
  src/Components/Tag/index.tsx
  src/Components/__stories__/Gene.story.tsx
  src/__generated__/GeneArtworksContent_filtered_artworks.graphql.ts
  src/__generated__/GeneArtworksPaginationQuery.graphql.ts
  src/__generated__/GeneArtworks_gene.graphql.ts
  src/__generated__/GeneContentsArtworksQuery.graphql.ts
  src/__generated__/TagArtworksContent_filtered_artworks.graphql.ts
  src/__generated__/TagArtworksPaginationQuery.graphql.ts
  src/__generated__/TagArtworks_tag.graphql.ts
  src/__generated__/TagContentsArtworksQuery.graphql.ts
Labels: Merge On Green, Version: Patch

#3005 @sweir27 => [v2] Use correct id for edition set in BNMO mutations
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Labels: Version: Patch

#3000 User should be notified of an outbid or (any non-winning status) when attempting to confirm a bid
  src/Apps/Auction/Components/BidForm.tsx
  src/Apps/Auction/Routes/ConfirmBid/BidderPositionQuery.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
Labels: Jira Synced

#3008 @joeyAghion => [v2] Strictly support and generate snake case filter params in URLs
  src/Apps/Artist/routes.tsx
  src/Apps/Collect2/Utils/urlBuilder.ts
  src/Apps/Collect2/collectRoutes.tsx
  src/Apps/Search/routes.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/Utils/__tests__/urlBuilder.test.tsx
  src/Components/v2/ArtworkFilter/Utils/urlBuilder.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterContext.test.tsx
Labels: Version: Patch

#3009 @eessex => [v2] Correct title for medium-based collect pages
  src/Apps/Collect2/Routes/Collect/Components/CollectMediumMetadata.ts
  src/Apps/Collect2/Routes/Collect/index.tsx
Labels: Version: Patch

#3010 Ensure user agent gets passed from SSR Relay Environment
  src/Artsy/Router/buildServerApp.tsx
Labels: Jira Synced, Version: Patch

#3012 [Payment] Fix CC removal by using internalID
  src/Components/Payment/SavedCreditCards.tsx
  src/Components/Payment/__tests__/SavedCreditCards.test.tsx
Labels: Version: Patch

#3013 [schema] Sync with latest removal
  data/schema.graphql
Labels: Version: Patch

#2967 Moved artist insights to the right PURCHASE-1608
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Components/v2/ArtistInsight.tsx
  src/Components/v2/SelectedCareerAchievements.tsx
Labels: Jira Synced, Version: Patch

#3014 PaymentForm __id -> id
  src/Components/Payment/PaymentForm.tsx
Labels: Version: Patch

#3016 [MP v2] Remove left-over `__id` usage
  src/Apps/Artist/Routes/CV/__tests__/CV.test.tsx
  src/Apps/Artwork/Components/__tests__/ArtistInfo.test.tsx
  src/Apps/__tests__/Fixtures/Artist/Components/ArtworkFilter.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/ArticlesFixture.ts
  src/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
  src/Apps/__tests__/Fixtures/Artist/Routes/CV.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/CVFixture.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/RelatedArtistsFixture.ts
  src/Apps/__tests__/Fixtures/Artists.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtistInfo.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkRelatedArtists.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSharePanel.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarPartnerInfo.ts
  src/Apps/__tests__/Fixtures/Artwork/OtherWorks/ArtworkContexts/ArtworkContextArtist.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/OtherWorks/ArtworkContexts/ArtworkContextAuction.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/OtherWorks/ArtworkContexts/ArtworkContextFair.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/OtherWorks/ArtworkContexts/ArtworkContextPartnerShow.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/OtherWorks/ArtworkContexts/RelatedWorksArtworkGrid.fixture.ts
  src/Apps/__tests__/Fixtures/Artworks.ts
  src/Apps/__tests__/Fixtures/Carousel.ts
  src/Apps/__tests__/Fixtures/Collect/CollectAppFixture.ts
  src/Apps/__tests__/Fixtures/Collect/CollectionAppFixture.ts
  src/Apps/__tests__/Fixtures/MarketInsights.ts
  src/Apps/__tests__/Fixtures/Partners.ts
  src/Apps/__tests__/Fixtures/Search/SearchAppFixture.ts
  src/Components/Artwork/Fillwidth.tsx
  src/Components/NavBar/Menus/__tests__/NotificationsMenu.test.tsx
  src/Components/Onboarding/ItemLink.tsx
  src/Components/Onboarding/Steps/Genes/SuggestedGenes.tsx
  src/Components/Publishing/Sections/ImageCollection.tsx
  src/Components/Publishing/ToolTip/ArtistToolTip.tsx
  src/Components/Publishing/Typings.ts
  src/Components/__stories__/FollowButton.story.tsx
  src/Components/__tests__/Artwork.test.tsx
  src/Components/v2/FollowArtistPopover/__tests__/FollowArtistPopover.test.tsx
  src/DevTools/createMockNetworkLayer/index.ts
  src/Utils/fillwidth.ts
  src/__generated__/ArtistInfo_Test_Query.graphql.ts
Labels: Version: Patch

#2964 Track ad impressions and clicks on 3rd party served ads
  src/Artsy/Analytics/Schema/Values.ts
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Fixtures/Components.ts
  src/Components/Publishing/Layouts/NewsLayout.tsx
  src/Components/Publishing/Layouts/SeriesLayout.tsx
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/Layouts/VideoLayout.tsx
  src/Components/Publishing/Layouts/__tests__/ArticleWithFullScreen.test.tsx
  src/Components/Publishing/Layouts/__tests__/FeatureLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/SeriesLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/VideoLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
  src/Components/Publishing/__tests__/Article.test.tsx
Labels: Jira Synced, Version: Patch

#3011 User without an existing credit card should be able to bid and register
  src/Apps/Auction/Components/BidForm.tsx
  src/Apps/Auction/Components/CreditCardInstructions.tsx
  src/Apps/Auction/Components/RegistrationForm.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/Register/index.tsx
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/Apps/Auction/Routes/__tests__/Utils/ConfirmBidTestPage.tsx
  src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
  src/Apps/Auction/routes.tsx
  src/__generated__/ConfirmBidValidTestQuery.graphql.ts
  src/__generated__/ConfirmBid_me.graphql.ts
  src/__generated__/routes_ConfirmBidQuery.graphql.ts
Labels: Jira Synced

#3022 Meta: Merge recent auctions team product work into master
  src/Apps/Auction/Components/BidForm.tsx
  src/Apps/Auction/Components/CreditCardInstructions.tsx
  src/Apps/Auction/Components/RegistrationForm.tsx
  src/Apps/Auction/Routes/ConfirmBid/BidderPositionQuery.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/Register/index.tsx
  src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/Apps/Auction/Routes/__tests__/Utils/ConfirmBidTestPage.tsx
  src/Apps/Auction/__fixtures__/routes_ConfirmBidQuery.ts
  src/Apps/Auction/routes.tsx
  src/DevTools/createTestEnv.tsx
  src/__generated__/ArtistInfo_Test_Query.graphql.ts
  src/__generated__/BidForm_me.graphql.ts
  src/__generated__/BidForm_saleArtwork.graphql.ts
  src/__generated__/BidderPositionQuery.graphql.ts
  src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
  src/__generated__/ConfirmBidValidTestQuery.graphql.ts
  src/__generated__/ConfirmBid_me.graphql.ts
  src/__generated__/routes_ConfirmBidQuery.graphql.ts
Labels: Jira Synced, Version: Minor

#3015 [PURCHASE-1610] Allow offer metadata for artworks with min-price
  src/Apps/Artist/Components/ArtistMeta.tsx
  src/Apps/Artist/Components/__tests__/ArtistMeta.test.tsx
  src/__generated__/ArtistMeta_artist.graphql.ts
  src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#3024 Remove Bank Transfer Experiment
  src/Apps/Order/Components/BankTransferExperiment.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Artsy/Analytics/Schema/Values.ts
Labels: Jira Synced, Version: Patch

#3019 Artwork `aggregateOffer` metadata
  src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.fixture.ts
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.test.tsx
  src/__generated__/SeoDataForArtwork_Test_Query.graphql.ts
  src/__generated__/SeoDataForArtwork_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#3026 Do not include seller in structured data when no partner profile image
  src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.test.tsx
Labels: Version: Patch

#3020 Create gene links view
  src/Components/Gene/GeneRelatedLinks.tsx
  src/Components/Gene/__tests__/GeneRelatedLinks.test.tsx
  src/__generated__/GeneRelatedLinksQuery.graphql.ts
  src/__generated__/GeneRelatedLinks_Test_Query.graphql.ts
  src/__generated__/GeneRelatedLinks_gene.graphql.ts
Labels: Version: Minor

#3025 Remove impression event
  src/Components/v2/CollectionsHubsHomepageNav.tsx
Labels: Version: Patch

#3029 Include partner's name on copy stating bidders agree to Artsy's COS
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarExtraLinks.test.tsx
  src/Apps/Auction/Routes/__stories__/ConfirmBid.story.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarExtraLinks.ts
  src/__generated__/ArtworkSidebarExtraLinks_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarExtraLinks_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebarStoryQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#3028 Track validation errors and registration submitted events
  src/Apps/Auction/Components/BidForm.tsx
  src/Apps/Auction/Components/RegistrationForm.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__fixtures__/MutationResults/createBidderPosition.ts
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
Labels: Jira Synced, Version: Minor

#3018 Add modal to "Certificate of Authenticity" Badges with explanation of COA
  src/Apps/Artwork/Components/TrustSignals/AuthenticityCertificate.tsx
  src/Apps/Artwork/Components/TrustSignals/TrustSignal.tsx
  src/Apps/Artwork/Components/TrustSignals/__tests__/AuthenticityCertificate.test.tsx
Labels: Jira Synced, Version: Patch

#3031 Refactors Display Ad Component to Handle Analytics Firing
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
Labels: Version: Patch

#3027 Grow-1479 Blank thumbnail on collections with generated banner
  src/Apps/Collect2/Routes/Collections/Components/CollectionsGrid.tsx
Labels: Jira Synced, Version: Patch

#3032 Fix for SaleArtwork/Sale without a partner
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarExtraLinks.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarExtraLinks.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#3033 User can see buyer's premium cost on web
  src/Apps/Auction/Components/BidForm.tsx
  src/Apps/Auction/Components/PricingTransparency.tsx
  src/Apps/Auction/Components/__stories__/PricingTransparency.story.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/Apps/Auction/Routes/__tests__/Utils/ConfirmBidTestPage.tsx
  src/DevTools/createTestEnv.tsx
  src/__generated__/BidForm_saleArtwork.graphql.ts
  src/__generated__/ConfirmBidValidTestQuery.graphql.ts
  src/__generated__/PricingTransparencyQuery.graphql.ts
  src/__generated__/routes_ConfirmBidQuery.graphql.ts
  typings/sharify.d.ts
Labels: Jira Synced, Version: Minor

#3034 Track "selected max bid" events on the confirm bid page
  src/Apps/Auction/Components/BidForm.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/Artsy/Analytics/Schema/AuctionInfo.ts
  src/Artsy/Analytics/Schema/Values.ts
Labels: Jira Synced, Version: Minor

#3035 Fixes a bug where your max bid is not pre-selected on the new confirm bid page
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
Labels: Jira Synced, Version: Patch
