Repository artsy/reaction, pull requests merged in 2019-08, with the labels that each got.

#2647 Collections Default Header Bug Fix
  src/Apps/Collect/CollectionApp.tsx
  src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
  src/Apps/Collect/Components/Collection/Header/DefaultHeader.tsx
  src/Apps/Collect/Components/Collection/Header/__tests__/DefaultHeader.test.tsx
  src/Apps/Collect/Components/Collection/Header/__tests__/__snapshots__/DefaultHeader.test.tsx.snap
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionApp_collection.graphql.ts
  src/__generated__/CollectionFilterContainer_collection.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2646 PURCHASE-1282: Updates offer views to handle non-USD currencies
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/Offer_order.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/Respond_order.graphql.ts
  src/__generated__/routes_OfferQuery.graphql.ts
  src/__generated__/routes_RespondQuery.graphql.ts
Labels: Version: Patch

#2654 Use actual data in Vanguard Scaffold
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/TableOfContents.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
Labels: Jira Synced, Version: Patch

#2643 Add redirects to AuctionApp bidder registration flow
  src/Apps/Auction/__tests__/AuctionApp.test.tsx
  src/Apps/Auction/routes.tsx
  src/Apps/__tests__/Fixtures/Sale.ts
  src/__generated__/routes_AuctionQuery.graphql.ts
Labels: Version: Minor

#2655 Revert #2640 due to stitching edge case
  data/schema.graphql
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarClassification.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarClassification.test.tsx
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.fixture.ts
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.test.tsx
  src/Apps/Artwork/Components/__stories__/PricingContext.story.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Collect/Components/Seo/SeoProductsForArtworks.tsx
  src/Apps/Order/Components/ItemReview.tsx
  src/Apps/Order/Components/__stories__/ItemReview.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarMetadata.ts
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/ArtworkImageBrowser_artwork.graphql.ts
  src/__generated__/ArtworkSidebarClassification_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarClassification_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCommercial_artwork.graphql.ts
  src/__generated__/ArtworkSidebarMetadata_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/ItemReview_artwork.graphql.ts
  src/__generated__/PricingContextStoryQuery.graphql.ts
  src/__generated__/PricingContextTestQuery.graphql.ts
  src/__generated__/PricingContext_artwork.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/SeoDataForArtwork_artwork.graphql.ts
  src/__generated__/SeoProductsForArtworks_artworks.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_ReviewQuery.graphql.ts
  src/__generated__/routes_StatusQuery.graphql.ts
Labels: Version: Patch

#2648 Grow-1391,Collections carousel tweaks QA for artist series and related collections
  src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionsRail.tsx
  src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
Labels: Jira Synced, Version: Patch

#2639 @yuki24 => [Collect] Remove unneeded medium aggregation call
  src/Apps/Collect/CollectApp.tsx
  src/Apps/Collect/Components/Base/CollectFilterContainer.tsx
  src/Apps/Collect/Components/Filters/FilterContainer.tsx
  src/Apps/Collect/Components/Filters/MediumFilter.tsx
  src/Apps/Collect/Components/Seo/SeoProductsForArtworks.tsx
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectApp_viewer.graphql.ts
  src/__generated__/CollectFilterContainer_viewer.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/SeoProductsForArtworks_artworks.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Version: Patch

#2635 Auct-463 auction registration modal
  src/Apps/Auction/Components/RegistrationForm.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/Components/Auction/AuctionRegistrationModal.tsx
  src/Components/Auction/ConditionsOfSaleCheckbox.tsx
  src/Components/Auction/__stories__/AuctionRegistrationModal.story.tsx
  src/Components/Auction/__tests__/AuctionRegistrationModal.test.tsx
Labels: Version: Minor

#2662 Add Inverted Text CSS to Storybooks
  src/Assets/ArtsyVanguard/NewlyEstablished.tsx
  src/Assets/ArtsyVanguard/VanguardAssets.tsx
  src/Components/__stories__/InvertedCSS.story.tsx
Labels: Jira Synced, Version: Patch

#2664 [Vanguard] Display video in headers/intro
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/VideoBackground.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
Labels: Jira Synced, Version: Patch

#2661 [ArtworkFilter v2] More progress
  package.json
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid2.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGridSort.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/Components/v2/__stories__/ArtworkFilter.story.tsx
  src/__generated__/ArtworkFilter_viewer.graphql.ts
  yarn.lock
Labels: Version: Patch

#2657 GROW-1453: this moves CollectionsHubRail into the CollectionApp
  src/Apps/Collect/CollectionApp.tsx
  src/Apps/Collect/__tests__/CollectionApp.test.tsx
  src/Components/CollectionsHubRails/index.tsx
  src/Components/__stories__/CollectionsRails.story.tsx
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionApp_collection.graphql.ts
  src/__generated__/CollectionsHubRails_linkedCollections.graphql.ts
  src/__generated__/CollectionsHubRails_marketingCollection.graphql.ts
  src/__generated__/CollectionsRailsQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Jira Synced

#2670 Upload Artsy Vanguard 2019 SVG Files
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Assets/Emerging.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Assets/GettingTheirDue.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Assets/NewlyEstablished.tsx
Labels: Jira Synced, Version: Patch

#2668 PURCHASE-1285: Updates Artwork Details display
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkDetails.ts
Labels: Version: Patch

#2673 Handle xs breakpoint with metadata field
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
Labels: Merge On Green, Version: Patch

#2667 [Vanguard] Table of Contents
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Blobs/Emerging.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Blobs/GettingTheirDue.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Blobs/NewlyEstablished.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/TableOfContents.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/__tests__/TableOfContents.test.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/index.test.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
  src/Components/Publishing/EditorialFeature/Fixtures/Vanguard2019.ts
  src/Components/Publishing/__stories__/EditorialFeature.story.tsx
  src/Components/Publishing/__stories__/InvertedCSS.story.tsx
  src/Components/__stories__/InvertedCSS.story.tsx
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2672 Fix render implementation in AuctionApp routes
  src/Apps/Auction/routes.tsx
Labels: Merge On Green, Version: Patch

#2676 adds latest svgs from wax
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Blobs/Intro.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Blobs/Rollover.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Blobs/SectionHeaders.tsx
Labels: Merge On Green, Version: Patch

#2674 @damassi => [Artist] Consolidate aggregations and grid request for filter, when possible
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterRefetch.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artist/Routes/Overview/state.ts
  src/Apps/Artist/routes.tsx
  src/Apps/__tests__/Fixtures/Artist/Components/ArtworkFilter.tsx
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetch_artist.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkFilter_artist.graphql.ts
  src/__generated__/Overview_artist.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
Labels: Version: Patch

#2677 Update Metaphysics GraphQL schema
  data/schema.graphql
Labels: Merge On Green, Version: Minor

#2678 GROW-1370: add analytics tracking to FeaturedCollections module
  src/Artsy/Analytics/Schema/Values.ts
  src/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
  src/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
  src/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
Labels: Jira Synced, Version: Patch

#2679 [Vanguard] SectionsList can accommodate custom widths
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/Sections/ImageCollection.tsx
  src/Components/Publishing/Sections/SectionContainer.tsx
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/SectionContainer.test.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
Labels: Jira Synced, Version: Patch

#2683 Extract tooltip provider from fullscreen logic
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/Constants.ts
  src/Components/Publishing/Layouts/ArticleWithFullScreen.tsx
  src/Components/Publishing/ToolTip/TooltipsDataProvider.tsx
  src/Components/Publishing/__tests__/Constants.test.ts
Labels: Merge On Green, Version: Patch

#2682 Refactor ConditionsOfSaleCheckbox to use palette checkbox
  src/Apps/Auction/Components/RegistrationForm.tsx
  src/Components/Auction/AuctionRegistrationModal.tsx
  src/Components/Auction/ConditionsOfSaleCheckbox.tsx
  src/Components/Auction/__tests__/AuctionRegistrationModal.test.tsx
Labels: Merge On Green, Version: Minor

#2684 [Vanguard] Add creative credits
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
Labels: Version: Patch

#2686 Bump react to 16.8.4
  package.json
  yarn.lock
Labels: Merge On Green, Version: Patch

#2687 [CollectionHubs] various hubs qa
  src/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
  src/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionsHubRails_linkedCollections.graphql.ts
  src/__generated__/CollectionsHubRails_marketingCollection.graphql.ts
  src/__generated__/CollectionsRailsQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Version: Patch

#2688 Adds SVGs To Artist Header
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Blobs/Emerging.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Blobs/GettingTheirDue.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Blobs/Intro.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Blobs/NewlyEstablished.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
Labels: Jira Synced, Version: Patch

#2689 Adds prop to hide ads from feature articles for vanguard development
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
Labels: Merge On Green, Version: Patch

#2692 Refactor svg blobs on artist headers
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
Labels: Version: Patch

#2690 Refactor slideshows & add to vanguard
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/Layouts/ArticleWithFullScreen.tsx
  src/Components/Publishing/Layouts/__tests__/ArticleWithFullScreen.test.tsx
  src/Components/Publishing/Sections/Artwork.tsx
  src/Components/Publishing/Sections/Image.tsx
  src/Components/Publishing/Sections/ImageCollection.tsx
  src/Components/Publishing/Sections/ImageSetPreview/ImageSetPreview.tsx
  src/Components/Publishing/Sections/ImageWrapper.tsx
  src/Components/Publishing/Sections/Sections.tsx
Labels: Version: Patch

#2694 [TRIVIAL] Update fixture to use correct naming for related_article_ids
  src/Components/Publishing/Fixtures/Articles.ts
Labels: Merge On Green, Version: Patch

#2691 [GROW-1355]: Address OtherCollectionsRail QA items
  src/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
  src/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
Labels: Jira Synced, Version: Patch

#2681 [Vanguard] Article truncation
  src/Components/Publishing/Byline/Share.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
  src/Components/Publishing/Sections/ArtworkCaption.tsx
  src/Components/Publishing/Sections/ImageSetPreview/ImageSetLabel.tsx
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
Labels: Version: Patch

#2697 [TRIVIAL] Put back super article related_articles
  src/Components/Publishing/Fixtures/Articles.ts
Labels: Version: Patch

#2695 [Carousel] Pass index / props down to render items
  src/Components/v2/Carousel.tsx
  src/Components/v2/__stories__/Carousel.story.tsx
Labels: Version: Patch

#2696 Call modal onClose only after show has been set to false
  src/Components/Auction/AuctionRegistrationModal.tsx
  src/Components/Auction/__tests__/AuctionRegistrationModal.test.tsx
Labels: Version: Patch

#2705 [Router] Add in interstitial loading state
  package.json
  src/Apps/Collect2/Routes/Collect/CollectionApp.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/Collect2/collectRoutes.tsx
  src/Apps/Search/routes.tsx
  src/Artsy/Relay/renderWithLoadProgress.tsx
  src/Artsy/Router/Utils/RenderStatus.tsx
  src/Artsy/Router/Utils/Route.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Components/ArtworkFilter/Dropdown.tsx
  src/Components/Authentication/FormSwitcher.tsx
  src/Components/Modal/Modal.tsx
  src/Components/Modal/ModalWrapper.tsx
  src/Components/Publishing/Display/Canvas/CanvasVideo.tsx
  src/Components/Publishing/Layouts/NewsLayout.tsx
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Video/Player/VideoPlayer.tsx
  src/Components/QuickInput.tsx
  src/Components/StepMarker/index.tsx
Labels: Merge On Green, Version: Minor

#2706 [Router] Fix zIndex #trivial
  src/Apps/Collect2/Components/Base/CollectArtworkGrid.tsx
  src/Apps/Collect2/Components/Base/CollectFilterContainer.tsx
  src/Artsy/Router/Utils/RenderStatus.tsx
Labels: Merge On Green, Version: Patch

#2707 [Collect] Fix text alignment
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Routes/Collections/index.tsx
Labels: Version: Patch

#2711 Mark components with clear artsy/palette equivalents as deprecated
  src/Components/Checkbox.tsx
  src/Components/Input.tsx
  src/Components/Modal/Modal.tsx
  src/Components/ProgressIndicator.tsx
  src/Components/Publishing/ReadMore/ReadMoreButton.tsx
  src/Components/Publishing/ReadMore/ReadMoreWrapper.tsx
  src/Components/Spinner.tsx
  src/Components/Text.tsx
  src/Components/TextArea.tsx
  src/Components/TextLink.tsx
  src/Components/Title.tsx
  src/Components/Tooltip.tsx
Labels: Version: Trivial

#2710 Updates palette and mocks setInterval in tests using TimeRemaining
  package.json
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Components/v2/__tests__/CountdownTimer.test.tsx
  yarn.lock
Labels: Version: Patch

#2709 [Collections] Relocate CollectionsHub rails
  package.json
  src/Apps/Artwork/Components/__stories__/ArtistInfo.story.tsx
  src/Apps/Collect2/Routes/Collect/CollectionApp.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesEntity.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesRail.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionEntity.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionsRail.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/__stories__/CollectionsHubRails.story.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/Apps/__stories__/Collect.story.tsx
  src/Apps/__stories__/Search.story.tsx
  src/Artsy/Router/RouterLink.tsx
  src/DevTools/MockRouterProvider.tsx
  src/__generated__/CollectionApp_collection.graphql.ts
  src/__generated__/CollectionsHubRailsStoryQuery.graphql.ts
Labels: Version: Patch

#2717 [CollectionHubs] adds item_number to analytics tracking
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionEntity.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
  src/Artsy/Analytics/Schema/index.ts
Labels: Version: Patch

#2716 Add Video in SVG Blobs on Primary and Sub Series Headers
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Blobs/Intro.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/VanguardVideoBackground.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/VideoBackground.tsx
Labels: Jira Synced, Version: Patch

#2701 [Vanguard] scroll to sections based on slug
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/__tests__/ArtistWrapper.test.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/index.test.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
Labels: Version: Patch

#2719 [Router] Add ErrorPage handler
  src/Apps/Collect2/Routes/Collections/index.tsx
  src/Artsy/Router/Utils/RenderStatus.tsx
  src/Artsy/Router/Utils/Route.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
Labels: Version: Minor

#2720 Bring back the cool ascii banner text in the README
  README.md
Labels: Merge On Green, Version: Trivial

#2722 Remove debug text #trivial
  src/Apps/Collect2/Routes/Collections/index.tsx
Labels: Merge On Green, Version: Patch

#2698 GROW 1362 - Add hub entry points to collect page
  .storybook/webpack.config.js
  src/Apps/Collect2/Components/Filters/FilterContainer.tsx
  src/Apps/Collect2/Components/Filters/SortFilter.tsx
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/collectRoutes.tsx
  src/Apps/__tests__/Fixtures/Collect/CollectAppFixture.ts
  src/Components/v2/AutoScalingImageLink.tsx
  src/Components/v2/CollectionsHubsNav.tsx
  src/Components/v2/__stories__/AutoScalingImageLink.story.tsx
  src/Components/v2/__stories__/CollectionsHubsNav.story.tsx
  src/__generated__/Collect_marketingCollections.graphql.ts
  src/__generated__/CollectionsHubsNavQuery.graphql.ts
  src/__generated__/CollectionsHubsNav_marketingCollections.graphql.ts
  src/__generated__/collectRoutes_CollectAppQuery.graphql.ts
  typings/sharify.d.ts
Labels: Jira Synced, Version: Patch

#2721 Handle <RouterLink> behavior better
  src/Apps/Collect2/Routes/Collection/Components/__stories__/CollectionsHubRails.story.tsx
  src/Artsy/Router/RouterLink.tsx
  src/Artsy/Router/__tests__/RouterLink.test.tsx
  src/Components/v2/__stories__/AutoScalingImageLink.story.tsx
  src/Components/v2/__stories__/CollectionsHubsNav.story.tsx
  src/DevTools/MockRouterProvider.tsx
Labels: Version: Patch

#2702 Auction post-registration modal (migrating from force)
  src/Components/Auction/PostRegistrationModal.tsx
  src/Components/Auction/__stories__/AuctionRegistrationModal.story.tsx
  src/Components/Auction/__stories__/PostRegistrationModal.story.tsx
  src/Components/Auction/__tests__/PostRegistrationModal.test.tsx
Labels: Jira Synced, Version: Minor

#2723 [CollectionsHubsNav] Restyle collection hub nav according to new designs
  src/Components/v2/AutoScalingImageLink.tsx
  src/Components/v2/CollectionsHubsNav.tsx
  src/Components/v2/CollectionsHubsNavItem.tsx
  src/Components/v2/__stories__/AutoScalingImageLink.story.tsx
  src/Components/v2/__stories__/CollectionsHubsNavItem.story.tsx
Labels: Merge On Green, Version: Patch

#2714 [Refactor] Replace <ArtworkFilter> in /collect
  .vscode/settings.json
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionEntity.test.tsx
  src/Apps/Collect2/Utils/urlBuilder.ts
  src/Apps/Collect2/collectRoutes.tsx
  src/Artsy/Router/RouterLink.tsx
  src/Artsy/Router/Utils/Route.tsx
  src/Artsy/Router/__tests__/RouterLink.test.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid2.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGridSort.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterZeroState.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/SizeRangeFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/SortFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/ColorFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/MediumFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/SizeRangeFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/SortFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/TimePeriodFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/WaysToBuyFilter.test.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/index.tsx
  src/Components/v2/ArtworkFilter/Utils/__tests__/hasFilters.test.tsx
  src/Components/v2/ArtworkFilter/Utils/__tests__/isDefaultFilter.test.tsx
  src/Components/v2/ArtworkFilter/Utils/__tests__/rangeToTuple.test.tsx
  src/Components/v2/ArtworkFilter/Utils/__tests__/urlFragmentFromState.test.tsx
  src/Components/v2/ArtworkFilter/Utils/hasFilters.tsx
  src/Components/v2/ArtworkFilter/Utils/isDefaultFilter.tsx
  src/Components/v2/ArtworkFilter/Utils/rangeToTuple.tsx
  src/Components/v2/ArtworkFilter/Utils/urlFragmentFromState.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterContext.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/fixtures/ArtworkFilter.fixture.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/__generated__/ArtworkFilterQuery.graphql.ts
  src/__generated__/ArtworkFilter_viewer.graphql.ts
  src/__generated__/Collect_viewer.graphql.ts
  src/__generated__/collectRoutes_ArtworkFilterQuery.graphql.ts
Labels: Version: Minor

#2728 [ArtworkFilter] Ensure page is reset to 1 on filter change #trivial
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterContext.test.tsx
Labels: Merge On Green, Version: Patch

#2725 PURCHASE-1386 - Adds VAT included in price to Artworks
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
  src/__generated__/ArtworkSidebarCommercial_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2731 Revert "[ArtworkFilter] Ensure page is reset to 1 on filter change #trivial"
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterContext.test.tsx
Labels: Version: Patch

#2734 New PR for improving CSS
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/ArtistSeriesEntity.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/__tests__/ArtistSeriesEntity.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
Labels: Jira Synced, Version: Patch

#2729 Add Reponsiveness to Primary and Subseries SVG Videos
  package.json
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/VanguardVideoBackground.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/VanguardVideoPrimarySeries.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/VanguardVideoSubseries.tsx
  yarn.lock
Labels: Jira Synced, Version: Patch

#2743 Update Targeting Data in Ad Server
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/DisplayTargeting.tsx
  src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
  src/Components/Publishing/Fixtures/Articles.ts
  src/Components/Publishing/Fixtures/Components.ts
  src/Components/Publishing/Layouts/NewsLayout.tsx
  src/Components/Publishing/Layouts/SeriesLayout.tsx
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/Layouts/VideoLayout.tsx
  src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/VideoLayout.test.tsx
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2752 Update ImageLink to use a fixed aspect ratio and avoid jitter
  src/Components/v2/CollectionsHubsNav.tsx
  src/Components/v2/ImageLink.tsx
  src/Components/v2/__stories__/ImageLink.story.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2749 Create Collection Hubs entrypoint nav component for homepage
  src/Components/v2/CollectionsHubsHomepageNav.tsx
  src/Components/v2/CollectionsHubsNav.tsx
  src/Components/v2/__stories__/CollectionsHubsHomepageNav.story.tsx
  src/__generated__/CollectionsHubsHomepageNavQuery.graphql.ts
  src/__generated__/CollectionsHubsHomepageNav_marketingCollections.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Minor

#2753 [CollectionHubsRails] minor UI fixes
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
Labels: Version: Patch

#2747 Add STRIPE_PUBISHABLE_KEY to .env.oss
  .env.oss
  src/__stories__/config.js
Labels: Version: Trivial

#2754 @mzikherman => [Error Handling] Correct default if no status codes provided
  src/Artsy/Router/Utils/Route.tsx
Labels: Version: Patch

#2755 Expose CollectionsHubsHomepageNav so that Force can use it
  src/Components/v2/index.tsx
Labels: Merge On Green

#2751 PURCHASE-1428: Get failed payment flow working with case where payment intent of a already confirmed setupintent fails when seller accepts offer
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/fixFailedPayment.ts
  src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
  src/__generated__/NewPaymentRouteSetOrderPaymentMutation.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/Status_order.graphql.ts
  src/__generated__/routes_StatusQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2740 PURCHASE-1432: Improve error messaging for generic declines on the payment page
  src/Apps/Order/Components/PaymentPicker.tsx
  src/Apps/Order/Components/__mocks__/PaymentPicker.tsx
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
Labels: Jira Synced, Version: Patch

#2727 Add analytic event tracking to auction registration route
  package.json
  src/Apps/Auction/Components/RegistrationForm.tsx
  src/Apps/Auction/Components/__stories__/RegistrationForm.story.tsx
  src/Apps/Auction/Components/__tests__/RegistrationForm.test.tsx
  src/Apps/Auction/Routes/Register/index.tsx
  src/Apps/Auction/Routes/__stories__/Register.story.tsx
  src/Apps/Auction/Routes/__tests__/RegisterRouteAnalytics.test.tsx
  src/Apps/Auction/__tests__/redirects.test.ts
  src/Apps/Auction/__tests__/utils.ts
  src/Apps/Auction/redirects.ts
  src/Apps/Auction/routes.tsx
  src/Apps/Order/Utils/trackPageViewWrapper.tsx
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/__tests__/Fixtures/Auction/Routes/Register/index.ts
  src/Artsy/Analytics/Schema/Values.ts
  src/DevTools/MockRelayRenderer.tsx
  src/__generated__/RegisterCreateBidderMutation.graphql.ts
  src/__generated__/Register_me.graphql.ts
  src/__generated__/Register_sale.graphql.ts
  src/__generated__/redirects_sale.graphql.ts
  src/__generated__/routes_RegisterQuery.graphql.ts
  yarn.lock
Labels: Jira Synced, Version: Minor

#2762 Rename "Credit card number*" to "Credit card" to fix scan cc on mobile
  src/Apps/Auction/Components/RegistrationForm.tsx
Labels: Jira Synced, Merge On Green, Version: Trivial
