Repository artsy/reaction, pull requests merged in 2019-04, with the labels that each got.

#2240 Gate pricing context
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Artwork/routes.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/__generated__/PricingContextTestQuery.graphql.ts
  src/__generated__/PricingContext_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Patch

#2241 @cavvia => [Search] Make sure to get artwork tab count from filter endpoint aggregation
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/__tests__/SearchApp.test.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/__generated__/SearchApp_viewer.graphql.ts
  src/__generated__/routes_SearchBarTopLevelQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2239 @pepopowitz => [Gene] Relax paging check which stops paging early
  src/Components/Gene/GeneArtworksContent.tsx
  src/Components/__stories__/Gene.story.tsx
Labels: Jira Synced, Version: Patch

#2243 Show fallback icon when search result item has no image url
  src/Apps/Search/Components/FallbackIcon.tsx
  src/Apps/Search/Components/GenericSearchResultItem.tsx
Labels: Jira Synced, Version: Patch

#2245 Force search result items of City type to use FallbackIcon
  src/Apps/Search/Components/GenericSearchResultItem.tsx
Labels: Merge On Green, Version: Patch

#2228 Check for null media keys in RelatedArticleCard
  src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/__tests__/index.test.tsx
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/ArticleCard.tsx
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/ArticleCard.test.tsx
Labels: Jira Synced, Version: Patch

#2251 @mzikherman => [Search] Tweak styling of feedback component
  src/Apps/Search/Components/SendFeedback.tsx
Labels: Jira Synced, Version: Patch

#2237 Border on BNMO status page is too thick (mobile only)
  src/Apps/Order/Routes/Status/index.tsx
Labels: Merge On Green, Version: Patch

#2250 @dblandin => [Search] Tweak display of count within tabs
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/__tests__/SearchApp.test.tsx
Labels: Jira Synced, Version: Patch

#2236 Artist recommendations
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/Apps/__stories__/ArtistApp.story.tsx
  src/Utils/__tests__/getUser.test.ts
  src/Utils/getUser.ts
  src/__generated__/ArtistRecommendationsQuery.graphql.ts
  src/__generated__/ArtistRecommendations_artist.graphql.ts
Labels: Jira Synced, Version: Patch

#2254 Fixed error modal for insufficient funds on accept page
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/acceptOffer.ts
Labels: Version: Patch

#2247 DISCO-886: Search bar QA
  src/Components/Search/SearchBar.tsx
  src/Components/Search/Suggestions/SuggestionItem.tsx
  src/Components/Search/__tests__/SearchBar.test.tsx
  src/__generated__/SearchBarRefetchQuery.graphql.ts
  src/__generated__/SearchBarSuggestQuery.graphql.ts
  src/__generated__/SearchBarTestQuery.graphql.ts
  src/__generated__/SearchBar_viewer.graphql.ts
Labels: Jira Synced, Version: Patch

#2257 @dblandin => Adjusted zero state
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/__tests__/SearchApp.test.tsx
  src/Apps/__stories__/Apps.story.tsx
Labels: Jira Synced, Version: Patch

#2258 @dblandin => [SearchResults] Respond to /search instead of /search2
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/Components/SearchMeta.tsx
  src/Apps/Search/Components/__tests__/SearchMeta.test.tsx
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx
  src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
  src/Apps/Search/routes.tsx
  src/Apps/__stories__/Apps.story.tsx
Labels: Merge On Green, Version: Minor

#2259 @dblandin => [SearchResults] Some tweaks to calling out when hovering over an item
  src/Apps/Search/Components/GenericSearchResultItem.tsx
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
  src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
  src/Apps/Search/SearchApp.tsx
  src/Components/v2/RouteTabs.tsx
Labels: Version: Patch

#2260 @mzikherman => [Autosuggest] Use term when linking to search results
  src/Components/Search/SearchBar.tsx
Labels: Merge On Green

#2253 Add basic docs for createTestEnv
  src/DevTools/README.md
Labels: Version: Patch

#2261 User can see top three recommended artists
  src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/__generated__/ArtistRecommendationsQuery.graphql.ts
  src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
  src/__generated__/ArtistRecommendations_artist.graphql.ts
Labels: Jira Synced, Version: Minor

#2262 Re-sync schema from metaphysics
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#2263 @mzikherman => Bring back ze footah
  src/Apps/Search/SearchApp.tsx
Labels: Jira Synced, Version: Patch

#2268 @dblandin => [Autosuggest] Fix tracking of whether results were returned for a query
  src/Components/Search/SearchBar.tsx
Labels: Version: Patch

#2269 @damassi => [SearchResults] Add loading spinner when navigating to entity tab
  src/Apps/Search/routes.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/Artsy/Router/Utils/Route.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2272 @mzikherman => [Search] Preserve keyword when resetting filter on mobile
  src/Apps/Search/FilterState.tsx
Labels: Merge On Green

#2265 User sees informational modal when they click the question mark next to the bar chart description
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/PricingContextModal.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Artwork/Components/__tests__/PricingContextModal.test.tsx
Labels: Merge On Green, Version: Patch

#2273 Downsize artwork image
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/ArtworkImageBrowser_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2281 [TRIVIAL] Remove null state from IconImageFullscreen
  src/Components/Publishing/Icon/IconImageFullscreen.tsx
Labels: Version: Patch

#2280 Fix Storybooks plugins webpack config
  .storybook/webpack.config.js
Labels: Version: Patch

#2284 @damassi => Couple misc search results QA items
  src/Apps/Search/FilterState.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/FilterContainer.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/TimePeriodFilter.tsx
Labels: Jira Synced

#2283 [Carousel] Add arrow render callback
  src/Components/v2/Carousel.tsx
  src/Components/v2/__stories__/Carousel.story.tsx
Labels: Version: Minor

#2285 createTestEnv docs follow-up
  src/DevTools/README.md
Labels: Version: Trivial

#2279 address qa items for artist collections rail
  src/Components/Artist/ArtistCollectionsRail/ArtistCollectionEntity.tsx
  src/Components/Artist/ArtistCollectionsRail/ArtistCollectionsRail.tsx
  src/Components/Artist/ArtistCollectionsRail/__tests__/ArtistCollectionEntity.test.tsx
  src/Components/Artist/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
Labels: Jira Synced

#2290 [Toolchain] Make Storybooks hooks-safe
  .storybook/webpack.config.js
Labels: Merge On Green, Version: Patch

#2274 send product_id attribute with key transaction events
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/ArtworkSidebarBidAction_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarBidAction_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/Review_order.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  src/__generated__/routes_ReviewQuery.graphql.ts
Labels: Merge On Green, Version: Patch

#2275 Add option to save payment during BNMO orders
  src/Apps/Order/Components/CreditCardDetails.tsx
  src/Apps/Order/Components/PaymentPicker.tsx
  src/Apps/Order/Components/__mocks__/PaymentPicker.tsx
  src/Apps/Order/Components/__tests__/PaymentPicker.test.tsx
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/Order/routes.tsx
  src/Apps/__stories__/OrderApp.story.tsx
  src/Components/Payment/__tests__/SavedCreditCards.test.tsx
  src/__generated__/NewPaymentRouteCreateCreditCardMutation.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/NewPayment_me.graphql.ts
  src/__generated__/NewPayment_order.graphql.ts
  src/__generated__/PaymentPickerCreateCreditCardMutation.graphql.ts
  src/__generated__/PaymentPickerTestQuery.graphql.ts
  src/__generated__/PaymentPicker_me.graphql.ts
  src/__generated__/PaymentPicker_order.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/Payment_me.graphql.ts
  src/__generated__/Payment_order.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  src/__generated__/routes_NewPaymentQuery.graphql.ts
  src/__generated__/routes_PaymentQuery.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#2287 Show 0 instead of null for lowest bucket
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
Labels: Version: Patch

#2294 Preserve search term in SearchBar, based on window.location.search
  src/Components/Search/SearchBar.tsx
  src/Components/Search/__tests__/SearchBar.test.tsx
Labels: Jira Synced, Version: Patch

#2292 [PATCH] fix qa items
  src/Components/Artist/ArtistCollectionsRail/ArtistCollectionEntity.tsx
  src/Components/Artist/ArtistCollectionsRail/ArtistCollectionsRail.tsx
  src/Components/Artist/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
Labels: Jira Synced, Version: Patch

#2282 Fixes OtherAuction component copy
  src/Apps/Artwork/Components/OtherAuctions.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextAuction.tsx
  src/Apps/Artwork/Components/__stories__/OtherAuctions.story.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
  src/Components/v2/AuctionCard.tsx
  src/Components/v2/__tests__/AuctionCard.test.tsx
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkContextAuction_viewer.graphql.ts
  src/__generated__/AuctionCard_sale.graphql.ts
  src/__generated__/OtherAuctionsQuery.graphql.ts
  src/__generated__/OtherAuctions_sales.graphql.ts
Labels: Jira Synced, Version: Patch

#2293 Lazy load more images on Artist and Artwork pages
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterArtworkGrid.tsx
  src/Components/Artwork/FillwidthItem.tsx
  src/Components/v2/RecentlyViewed.tsx
Labels: Version: Patch

#2298 Fixes search bar button press getting redirected to homepage
  src/Components/Search/SearchBar.tsx
Labels: Jira Synced, Version: Patch

#2248 Adds the bid count to Artist/Artwork page Artwork grids
  docs/getting_started.md
  src/Components/Artwork/Details.tsx
  src/Components/Artwork/GridItem.tsx
  src/Components/Artwork/__tests__/Details.test.tsx
  src/Components/__tests__/__snapshots__/Artwork.test.tsx.snap
  src/__generated__/ArtistRecommendationsQuery.graphql.ts
  src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
  src/__generated__/ArtistsQuery.graphql.ts
  src/__generated__/ArtworkContextArtistQuery.graphql.ts
  src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkContextFairQuery.graphql.ts
  src/__generated__/ArtworkContextFair_Test_Query.graphql.ts
  src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
  src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
  src/__generated__/ArtworkFilterArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkGridExampleQuery.graphql.ts
  src/__generated__/ArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkGrid_Test_Query.graphql.ts
  src/__generated__/ArtworkMetadataQuery.graphql.ts
  src/__generated__/ArtworkQuery.graphql.ts
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectArtworkGridQuery.graphql.ts
  src/__generated__/CollectArtworkGridTestQuery.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/Details_Test_Query.graphql.ts
  src/__generated__/Details_artwork.graphql.ts
  src/__generated__/FillwidthQuery.graphql.ts
  src/__generated__/GeneArtworksContentQuery.graphql.ts
  src/__generated__/GeneContentsArtistsQuery.graphql.ts
  src/__generated__/GeneContentsArtworksQuery.graphql.ts
  src/__generated__/GridItem_artwork.graphql.ts
  src/__generated__/InquiryArtworkQuery.graphql.ts
  src/__generated__/RecentlyViewedQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_Test_Query.graphql.ts
  src/__generated__/SaveArtworkQuery.graphql.ts
  src/__generated__/SearchResultsArtworkGridQuery.graphql.ts
  src/__generated__/SearchResultsArtworkGridTestQuery.graphql.ts
  src/__generated__/SearchResultsRefetchQuery.graphql.ts
  src/__generated__/TagArtworksContentQuery.graphql.ts
  src/__generated__/TagContentsArtworksQuery.graphql.ts
  src/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
  src/__generated__/routes_SearchResultsArtworksQuery.graphql.ts
Labels: Version: Minor

#2286 Update reaction to route users to the correct place
  package.json
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Artwork/Utils/__tests__/createCollectUrl.test.tsx
  src/Apps/Artwork/Utils/createCollectUrl.tsx
  src/__generated__/MarketInsightsArtistPage_artist.graphql.ts
  src/__generated__/PricingContextTestQuery.graphql.ts
  src/__generated__/PricingContext_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  yarn.lock
Labels: Version: Patch

#2307 Price Context tracking
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/PricingContextModal.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Artwork/Components/__tests__/PricingContextModal.test.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/MarketInsightsArtistPage_artist.graphql.ts
Labels: Version: Patch

#2305 Search results loading skeleton
  src/Apps/Search/Components/SearchResultsSkeleton/FilterSidebar.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/GridItem.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/Header.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/index.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/Components/__stories__/Search.story.tsx
Labels: Version: Minor

#2299 @pepopowitz => [Badge] Extract component from GridItem and add to FillwidthItem
  src/Components/Artwork/Badge.tsx
  src/Components/Artwork/FillwidthItem.tsx
  src/Components/Artwork/GridItem.tsx
  src/__generated__/ArtistRecommendationsQuery.graphql.ts
  src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
  src/__generated__/ArtistsQuery.graphql.ts
  src/__generated__/ArtworkContextArtistQuery.graphql.ts
  src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkContextFairQuery.graphql.ts
  src/__generated__/ArtworkContextFair_Test_Query.graphql.ts
  src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
  src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
  src/__generated__/ArtworkFilterArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkGridExampleQuery.graphql.ts
  src/__generated__/ArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkGrid_Test_Query.graphql.ts
  src/__generated__/Badge_artwork.graphql.ts
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectArtworkGridQuery.graphql.ts
  src/__generated__/CollectArtworkGridTestQuery.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/FillwidthItem_artwork.graphql.ts
  src/__generated__/FillwidthQuery.graphql.ts
  src/__generated__/GeneArtworksContentQuery.graphql.ts
  src/__generated__/GeneContentsArtistsQuery.graphql.ts
  src/__generated__/GeneContentsArtworksQuery.graphql.ts
  src/__generated__/GridItem_artwork.graphql.ts
  src/__generated__/RecentlyViewedQuery.graphql.ts
  src/__generated__/RecentlyViewed_me.graphql.ts
  src/__generated__/RelatedWorksArtworkGridQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_Test_Query.graphql.ts
  src/__generated__/SaveArtworkQuery.graphql.ts
  src/__generated__/SearchResultsArtworkGridQuery.graphql.ts
  src/__generated__/SearchResultsArtworkGridTestQuery.graphql.ts
  src/__generated__/SearchResultsRefetchQuery.graphql.ts
  src/__generated__/TagArtworksContentQuery.graphql.ts
  src/__generated__/TagContentsArtworksQuery.graphql.ts
  src/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
  src/__generated__/routes_SearchResultsArtworksQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2311 Updates type to be more specific
  src/Components/Search/SearchInputContainer.tsx
Labels: Version: Patch

#2313 Fixes mapping between category and medium filter on /collect page to match gene names
  src/Apps/Artwork/Utils/__tests__/createCollectUrl.test.tsx
  src/Apps/Artwork/Utils/createCollectUrl.tsx
Labels: Jira Synced, Version: Patch

#2315 Switch to appliedFiltersDisplay
  data/schema.graphql
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/__generated__/PricingContextTestQuery.graphql.ts
  src/__generated__/PricingContext_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Patch

#2308 Use upper bound of range for displaying the highlighted bucket
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
Labels: Jira Synced, Version: Patch

#2316 Update search results loading skeleton
  src/Apps/Search/Components/SearchResultsSkeleton/FilterSidebar.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/GridItem.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/Header.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/index.tsx
Labels: Merge On Green, Version: Minor

#2318 @kierangillen => [Auction Results] Be defensive about missing images
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionDetailsModal.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/__stories__/ArtistApp.story.tsx
Labels: Version: Patch

#2319 @pepopowitz => [Artist Recommendations] Hide Related Artists tab
  src/Apps/Artist/Components/NavigationTabs.tsx
  src/Apps/Artist/Components/__tests__/NavigationTabs.test.tsx
Labels: Jira Synced, Version: Patch

#2320 [TRIVIAL] Remove null states from Icons
  src/Components/Publishing/Icon/IconEditEmbed.tsx
  src/Components/Publishing/Icon/IconEditImages.tsx
  src/Components/Publishing/Icon/IconEditSection.tsx
  src/Components/Publishing/Icon/IconEditText.tsx
  src/Components/Publishing/Icon/IconEditVideo.tsx
  src/Components/Publishing/Icon/IconHeroImage.tsx
  src/Components/Publishing/Icon/IconHeroVideo.tsx
Labels: Merge On Green, Version: Patch

#2321 Update moment-timezone to reduce payload size
  package.json
  yarn.lock
Labels: Version: Minor

#2323 DISCO-947 - RecommendedArtist carousel arrows only render if more content
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Components/v2/Carousel.tsx
Labels: Jira Synced

#2303 Unify logic to require authentication for following an artist, following a partner, and saving an artwork
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/Components/Artwork/Save.tsx
  src/Components/v2/ArtistCard.tsx
  src/Utils/openAuthModal.ts
  src/__generated__/ArtistRecommendationsQuery.graphql.ts
  src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
  src/__generated__/ArtistsQuery.graphql.ts
  src/__generated__/ArtworkContextArtistQuery.graphql.ts
  src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkContextFairQuery.graphql.ts
  src/__generated__/ArtworkContextFair_Test_Query.graphql.ts
  src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
  src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
  src/__generated__/ArtworkFilterArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkGridExampleQuery.graphql.ts
  src/__generated__/ArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkGrid_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectArtworkGridQuery.graphql.ts
  src/__generated__/CollectArtworkGridTestQuery.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/FillwidthQuery.graphql.ts
  src/__generated__/GeneArtworksContentQuery.graphql.ts
  src/__generated__/GeneContentsArtistsQuery.graphql.ts
  src/__generated__/GeneContentsArtworksQuery.graphql.ts
  src/__generated__/RecentlyViewedQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_Test_Query.graphql.ts
  src/__generated__/SaveArtworkQuery.graphql.ts
  src/__generated__/Save_artwork.graphql.ts
  src/__generated__/SearchResultsArtworkGridQuery.graphql.ts
  src/__generated__/SearchResultsArtworkGridTestQuery.graphql.ts
  src/__generated__/SearchResultsRefetchQuery.graphql.ts
  src/__generated__/TagArtworksContentQuery.graphql.ts
  src/__generated__/TagContentsArtworksQuery.graphql.ts
  src/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
  src/__generated__/routes_SearchResultsArtworksQuery.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#2327 @pepopowitz => Emit google ad snippet, and make sure it is rendered + evaluated once
  src/Apps/Artwork/Components/ArtworkMeta.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/__generated__/ArtworkMeta_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  typings/sharify.d.ts
Labels: Jira Synced

#2326 ensure experiment viewed event is fired
  src/Apps/Artist/Routes/Overview/index.tsx
Labels: Version: Patch

#2324 User can hover over ? icon and see the font color, cursor, and label change
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/PricingContextModal.tsx
Labels: Version: Patch

#2331 Use stitched 'create buy order' mutation
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/__tests__/Fixtures/Artwork/MutationResults.ts
  src/__generated__/ArtworkSidebarCommercialOrderMutation.graphql.ts
Labels: Version: Patch

#2333 DISCO-948: Exclude artworks that aren’t for sale from artist recommendations.
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/__generated__/ArtistRecommendationsPaginationQuery.graphql.ts
  src/__generated__/ArtistRecommendationsRendererQuery.graphql.ts
  src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
  src/__generated__/RecommendedArtist_artist.graphql.ts
Labels: Jira Synced, Version: Patch

#2325 User can not click into histogram bars
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Artwork/Utils/__tests__/createCollectUrl.test.tsx
  src/Apps/Artwork/Utils/createCollectUrl.tsx
Labels: Version: Patch

#2337 Add mobile styling for search results page loading skeleton
  src/Apps/Search/Components/SearchResultsSkeleton/FilterSidebar.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/Header.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/index.tsx
Labels: Version: Minor

#2330 When price is outside range include it in the bottom or top bucket
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/__stories__/PricingContext.story.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/__generated__/PricingContextStoryQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2338 Update responsive grid styling for search results skeleton
  src/Apps/Search/Components/SearchResultsSkeleton/index.tsx
Labels: Version: Patch

#2332 @pepopowitz => Adjust filter tracking on artist page, make sure to cover all filters
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterRefetch.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Collect/Components/Base/CollectRefetch.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsRefetch.tsx
  src/Artsy/Analytics/Schema/Values.ts
Labels: Jira Synced, Version: Patch

#2340 Adjust header margin on mobile search results skeleton
  src/Apps/Search/Components/SearchResultsSkeleton/Header.tsx
Labels: Merge On Green, Version: Patch

#2339 Update title of histogram
  src/Apps/Artwork/Components/PricingContext.tsx
Labels: Version: Patch

#2344 Update style for search results page skeleton
  src/Apps/Search/Components/SearchResultsSkeleton/FilterSidebar.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/Header.tsx
  src/Apps/Search/Components/SearchResultsSkeleton/index.tsx
Labels: Version: Patch

#2246 Remove the SystemContext around an Artwork metadata because it wasn't being used
  src/Components/Artwork/Metadata.tsx
Labels: Version: Patch

#2309 Updated copy for pricing context
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/PricingContextModal.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Artwork/Components/__tests__/PricingContextModal.test.tsx
Labels: Version: Patch

#2347 [Toolchain] Fix deprecated Storybooks options
  package.json
  src/__stories__/config.js
  yarn.lock
Labels: Skip Release, Version: Patch

#2348 [Toolchain] Add @storybook/viewport plugin
  .storybook/addons.js
  data/schema.graphql
  package.json
  yarn.lock
Labels: Skip Release

#2346 [Artist] don't trigger tracking event in control group
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Components/Artist/ArtistCollectionsRail/ArtistCollectionsRail.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2342 changed logic for displaying 'Show artist insights' button to account for minimum exhibitions
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/__tests__/ArtistInfo.test.tsx
  src/Components/v2/SelectedExhibitions.tsx
Labels: Version: Patch

#2133 [NavBar] Add notifications badge and auth
  .storybook/webpack.config.js
  package.json
  src/Artsy/Relay/renderWithLoadProgress.tsx
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/Menus/NotificationsMenu.tsx
  src/Components/NavBar/Menus/UserMenu.tsx
  src/Components/NavBar/Menus/index.tsx
  src/Components/NavBar/MobileNavMenu/MobileToggleIcon.tsx
  src/Components/NavBar/MobileNavMenu/index.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
  src/Components/NavBar/NotificationsBadge.tsx
  src/Components/NavBar/Utils/auth.ts
  src/Components/__stories__/Nav.story.tsx
  src/Components/__stories__/NavBar.story.tsx
  src/__generated__/NotificationsMenuQuery.graphql.ts
  typings/sharify.d.ts
  yarn.lock
Labels: Skip Release

#2352 @ashfurrow => [Artist Recommendations] Exclude artists with less than 7 for sale works
  data/schema.graphql
  src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
  src/__generated__/ArtistRecommendationsPaginationQuery.graphql.ts
  src/__generated__/ArtistRecommendationsRendererQuery.graphql.ts
  src/__generated__/ArtistRecommendations_Test_Query.graphql.ts
  src/__generated__/ArtistRecommendations_artist.graphql.ts
Labels: Version: Patch
