Repository artsy/reaction, pull requests merged in 2019-02, with the labels that each got.

#1965 Fixes height, width, and color filters on collections
  src/Apps/Collect/CollectionApp.tsx
  src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
  src/Apps/Collect/Components/Collection/CollectionRefetch.tsx
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionApp_collection.graphql.ts
  src/__generated__/CollectionFilterContainer_collection.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/CollectionRefetch_collection.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Version: Patch

#1987 [Renovate] Auto-merge minor and patch updates
  renovate.json
Labels: Version: Trivial

#1988 Update palette
  package.json
  src/Components/Artist/MarketInsights/__tests__/__snapshots__/MarketInsights.test.tsx.snap
  yarn.lock
Labels: Merge On Green, Version: Patch

#1979 Refactor tests (again)
  .circleci/config.yml
  package.json
  src/Apps/Order/Routes/__fixtures__/MutationResults/acceptOffer.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/buyerCounterOffer.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/initialOffer.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/rejectOffer.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderPayment.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderShipping.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitOfferOrder.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitOrder.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitPendingOffer.ts
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx
  src/DevTools/MockRelayRenderer.tsx
  src/DevTools/MockRouter.tsx
  src/DevTools/RootTestPage.tsx
  src/DevTools/__tests__/createMockNetworkLayer.test.ts
  src/DevTools/__tests__/createTestEnv.test.tsx
  src/DevTools/createMockNetworkLayer/index.ts
  src/DevTools/createTestEnv.tsx
  src/DevTools/renderRelayTree.tsx
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/RejectTestQuery.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/createMockNetworkLayerTestAliasPrecendenceQuery.graphql.ts
  src/__generated__/createMockNetworkLayerTestMutationResultsMutation.graphql.ts
  src/__generated__/createTestEnvCreditCardMutation.graphql.ts
  src/__generated__/createTestEnvOrderMutation.graphql.ts
  src/__generated__/createTestEnvQuery.graphql.ts
  src/__generated__/createTestEnv_artwork.graphql.ts
  tsconfig.json
  yarn.lock
Labels: Version: Patch

#1990 Fixup IconDrag interfaces
  src/Components/Publishing/Icon/IconDrag.tsx
Labels: Merge On Green, Version: Patch

#1991 Add to be deprecated slideshow and image to SectionType type
  src/Components/Publishing/Typings.ts
Labels: Merge On Green, Version: Patch

#1969 Refactor Input component in preparation for moving to Palette
  src/Apps/Order/Components/OfferInput.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
  src/Components/Authentication/Desktop/LoginForm.tsx
  src/Components/Authentication/Desktop/SignUpForm.tsx
  src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
  src/Components/Authentication/Mobile/LoginForm.tsx
  src/Components/Authentication/Mobile/SignUpForm.tsx
  src/Components/Authentication/__tests__/Mobile/LoginForm.test.tsx
  src/Components/Authentication/__tests__/Mobile/ResetPasswordForm.test.tsx
  src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
  src/Components/Input.tsx
  src/Components/Onboarding/Steps/Artists/index.tsx
  src/Components/Onboarding/Steps/Genes/index.tsx
  src/Components/PasswordInput.tsx
  src/Components/QuickInput.tsx
  src/Components/__stories__/Input.story.tsx
  src/Components/__tests__/Input.test.tsx
  src/Components/__tests__/PasswordInput.test.tsx
  src/Components/__tests__/QuickInput.test.tsx
  src/Components/__tests__/__snapshots__/Input.test.tsx.snap
  src/Components/__tests__/__snapshots__/PasswordInput.test.tsx.snap
  src/Components/__tests__/__snapshots__/QuickInput.test.tsx.snap
Labels: Version: Patch

#1992 Fix broken snapshot tests from #1969
  src/Components/__tests__/__snapshots__/PasswordInput.test.tsx.snap
Labels: Version: Trivial

#1993 [Lib] Point at proper relay-network-modern-build
  src/Artsy/Relay/createRelaySSREnvironment.ts
Labels: Version: Patch

#1989 @pepopowitz => [AutoSuggest] Rough implementation of artist handling for previews
  data/schema.graphql
  src/Components/Search/Previews/Grids/Artist.tsx
  src/Components/Search/Previews/index.tsx
  src/Components/__stories__/Search.story.tsx
  src/__generated__/ArtistSearchPreviewQuery.graphql.ts
  src/__generated__/ArtistSearchPreview_artist.graphql.ts
  src/__generated__/OfferMutation.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
Labels: Version: Patch

#1995 Add back access to the innerRef for Input
  src/Components/Input.tsx
Labels: Version: Patch

#1994 @pepopowitz => [Search] Add suggestions component
  src/Components/Search/SearchBar.tsx
  src/Components/Search/Suggestions/index.tsx
  src/Components/__stories__/Search.story.tsx
  src/__generated__/SearchBarQuery.graphql.ts
  src/__generated__/SuggestionsSearchQuery.graphql.ts
  src/__generated__/SuggestionsSearch_viewer.graphql.ts
Labels: Version: Patch

#1996 Update state of reaction
  README.md
Labels: Version: Patch

#1997 @pepopowitz => [Search] Prototype for loading previews w/ suggestions
  src/Components/Search/Suggestions/index.tsx
  src/__generated__/SearchBarQuery.graphql.ts
  src/__generated__/SuggestionsSearchQuery.graphql.ts
  src/__generated__/SuggestionsSearch_viewer.graphql.ts
Labels: Version: Patch

#1998 Make offer note (review + respond steps)
  package.json
  src/Apps/Order/Components/OfferHistoryItem.tsx
  src/Apps/Order/Components/OfferSummaryItem.tsx
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Components/__stories__/TransactionDetailsSummaryItem.story.tsx
  src/Apps/Order/Routes/Counter/index.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/initialOffer.ts
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/OfferHistoryItemStoryQuery.graphql.ts
  src/__generated__/OfferHistoryItemTestQuery.graphql.ts
  src/__generated__/OfferHistoryItem_order.graphql.ts
  src/__generated__/OfferMutation.graphql.ts
  src/__generated__/OfferSummaryItem_order.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/Respond_order.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/TransactionDetailsSummaryItemOfferProperties.graphql.ts
  src/__generated__/TransactionDetailsSummaryItemStoryQuery.graphql.ts
  src/__generated__/TransactionDetailsSummaryItemTestQuery.graphql.ts
  src/__generated__/TransactionDetailsSummaryItem_order.graphql.ts
  src/__generated__/routes_AcceptQuery.graphql.ts
  src/__generated__/routes_CounterQuery.graphql.ts
  src/__generated__/routes_OfferQuery.graphql.ts
  src/__generated__/routes_PaymentQuery.graphql.ts
  src/__generated__/routes_RespondQuery.graphql.ts
  src/__generated__/routes_ReviewQuery.graphql.ts
  src/__generated__/routes_ShippingQuery.graphql.ts
  src/__generated__/routes_StatusQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2002 Adds some inline logs to highlight metaphysics extensions used in the query
  src/Artsy/Relay/createRelaySSREnvironment.ts
  src/Artsy/Relay/middleware/errorMiddleware.ts
  src/Artsy/Relay/middleware/metaphysicsExtensionsLoggerMiddleware.ts
Labels: Version: Patch

#2004 Update series/video null states
  src/Components/Publishing/Fixtures/Components.ts
  src/Components/Publishing/Layouts/VideoLayout.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Series/SeriesAbout.tsx
  src/Components/Publishing/Series/SeriesTitle.tsx
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesTitle.test.tsx.snap
  src/Components/Publishing/Typings.ts
  src/Components/Publishing/Video/Player/VideoPlayer.tsx
  src/Components/Publishing/Video/VideoAbout.tsx
  src/Components/Publishing/Video/VideoCover.tsx
  src/Components/Publishing/Video/VideoInfoBlock.tsx
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoCover.test.tsx.snap
Labels: Version: Patch

#2007 @mzikherman => [Autosuggest] Remove spike naming, and some more cleanup of UI
  src/Components/Search/SearchBar.tsx
  src/Components/Search/Spike/SearchBarSpike.tsx
  src/Components/Search/Suggestions/SuggestionItem.tsx
  src/Components/__stories__/Search.story.tsx
  src/__generated__/SearchBarQuery.graphql.ts
  src/__generated__/SearchBarRefetchQuery.graphql.ts
  src/__generated__/SearchBarSuggestQuery.graphql.ts
  src/__generated__/SearchBar_viewer.graphql.ts
Labels: Version: Patch

#2008 @orta => [Metaphysics Logger] Fix some edge cases
  src/Artsy/Relay/middleware/metaphysicsExtensionsLoggerMiddleware.ts
Labels: Version: Patch

#2006 Add query-less merchandisable search preview
  src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
  src/Components/Search/Previews/Grids/PreviewGridItem.tsx
  src/Components/Search/Previews/index.tsx
  src/Components/__stories__/Search.story.tsx
  src/__generated__/MerchandisableArtworksPreviewQuery.graphql.ts
  src/__generated__/MerchandisableArtworks_viewer.graphql.ts
  src/__generated__/PreviewGridItem_artwork.graphql.ts
Labels: Jira Synced, Version: Patch

#2009 [PATCH authentication] pass artist name in query params
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Components/Authentication/Types.ts
Labels: Jira Synced, Version: Patch

#2011 @mzikherman => [AuctionTimer] Make sure to display the minute portion in label
  src/Components/v2/AuctionTimer.tsx
Labels: Version: Patch

#1870 [Lib] Upgrade styled-components@4.0.3
  package.json
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
  src/Artsy/Router/Components/Boot.tsx
  src/Artsy/Router/Components/PreloadLink.tsx
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Components/Animation/ReplaceTransition.tsx
  src/Components/Authentication/__tests__/Desktop/Components/DesktopModal.test.tsx
  src/Components/Authentication/__tests__/FormSwitcher.test.tsx
  src/Components/Authentication/commonElements.tsx
  src/Components/Input.tsx
  src/Components/Modal/ModalWrapper.tsx
  src/Components/Modal/__tests__/Modal.test.tsx
  src/Components/Modal/__tests__/ModalHeader.test.tsx
  src/Components/Nav.tsx
  src/Components/Publishing/Byline/__tests__/__snapshots__/NewsByline.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayPanel.test.tsx.snap
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Email/__tests__/__snapshots__/EmailPanel.test.tsx.snap
  src/Components/Publishing/Email/__tests__/__snapshots__/InstantArticleEmailSignup.test.tsx.snap
  src/Components/Publishing/Icon/IconPlus.tsx
  src/Components/Publishing/Icon/IconVideoFullscreen.tsx
  src/Components/Publishing/Icon/IconVideoMute.tsx
  src/Components/Publishing/Icon/IconVideoPause.tsx
  src/Components/Publishing/Icon/IconVideoPlay.tsx
  src/Components/Publishing/Icon/IconVideoUnmute.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Nav/__tests__/SubNav.test.tsx
  src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  src/Components/Publishing/Nav/__tests__/__snapshots__/NewsNav.test.tsx.snap
  src/Components/Publishing/Nav/__tests__/__snapshots__/SubNav.test.tsx.snap
  src/Components/Publishing/Partner/__tests__/PartnerInline.test.tsx
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCard.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCards.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/Block.test.tsx.snap
  src/Components/Publishing/Sections/ImageSetPreview/__tests__/__snapshots__/ImageSetPreview.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/ArtworkCaption.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Authors.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/SectionContainer.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesTitle.test.tsx.snap
  src/Components/Publishing/Video/Player/VideoPlayer.tsx
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoCover.test.tsx.snap
  src/Components/Search/SearchBar.tsx
  src/Components/Search/__tests__/SearchBar.test.tsx
  src/Components/__stories__/PopoverExamples/WithAnimationExample.tsx
  src/Components/__tests__/__snapshots__/PasswordInput.test.tsx.snap
  src/Components/v2/Lightbox/Lightbox.tsx
  src/Components/v2/Lightbox/LightboxSlider.tsx
  src/__stories__/config.js
  src/setup_jest.ts
  yarn.lock
Labels: Version: Major

#2012 @jonallured => Highlight matching parts of query
  package.json
  src/Components/Search/SearchBar.tsx
  src/Components/Search/Suggestions/SuggestionItem.tsx
  src/Components/Search/__tests__/SearchBar.test.tsx
  src/Components/__stories__/Search.story.tsx
  yarn.lock
Labels: Version: Patch

#2026 @mzikherman => [AuctionTimer] Fix bug when :00 would render as :0
  src/Components/v2/AuctionTimer.tsx
Labels: Merge On Green

#2029 Always render in context of isolated stylesheet.
  package.json
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  yarn.lock
Labels: Version: Major

#2034 @mzikherman => [Autosuggest] Link on click/enter to suggestion items
  src/Components/Search/SearchBar.tsx
  src/Components/Search/Suggestions/SuggestionItem.tsx
Labels: Version: Patch

#2035 Fail tests on console warn and error logs
  package.json
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Components/ArtworkGrid/__stories__/ArtworkGridFixture.ts
  src/Components/ArtworkGrid/__tests__/ArtworkGrid.test.tsx
  src/Components/Input.tsx
  src/Components/v2/FollowArtistPopover/__tests__/FollowArtistPopover.test.tsx
  src/DevTools/MockRelayRenderer.tsx
  src/setup_jest.ts
  yarn.lock
Labels: Version: Patch

#2036 [SearchBar] Fix disabled test.
  src/Components/Search/__tests__/SearchBar.test.tsx
Labels: Version: Trivial

#2038 [Publishing] remove GridThemeProvider
  src/Components/Publishing/Article.tsx
Labels: Version: Patch

#2041 Updates relay schema
  data/schema.graphql
Labels: Version: Patch

#2039 @alloy => [Autosuggest] Allow QueryRenderer to return w/o fetching
  src/Artsy/Relay/createRelaySSREnvironment.ts
Labels: Version: Patch

#2045 Adds jest-styled-components to EditorialFeature
  src/Components/Publishing/EditorialFeature/__tests__/EditorialFeature.test.tsx
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
Labels: Version: Patch

#2047 Bump Palette to latest
  package.json
  src/Components/Artist/MarketInsights/__tests__/__snapshots__/MarketInsights.test.tsx.snap
  src/Components/__tests__/__snapshots__/PasswordInput.test.tsx.snap
  yarn.lock
Labels: Version: Patch

#2049 Pull in latest schema
  data/schema.graphql
Labels: Version: Patch

#2044 Add showCollectionsRail prop to Articles
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
  src/Components/Publishing/Layouts/FeatureLayout.tsx
  src/Components/Publishing/Layouts/NewsLayout.tsx
  src/Components/Publishing/Layouts/StandardLayout.tsx
Labels: Version: Patch

#2052 Collections Rail
  src/Components/CollectionsRail/Collection.tsx
  src/Components/CollectionsRail/CollectionsRail.tsx
  src/Components/CollectionsRail/index.tsx
  src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
  src/Components/__stories__/CollectionsRail.story.tsx
  src/__generated__/CollectionEntity_collection.graphql.ts
  src/__generated__/CollectionsRailQuery.graphql.ts
  src/__generated__/CollectionsRail_collections.graphql.ts
Labels: Jira Synced, Version: Patch

#2058 Remove make offer feature flags
  .storybook/webpack.config.js
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Collect/Components/Filters/WaysToBuyFilter.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  typings/sharify.d.ts
Labels: Jira Synced, Version: Patch

#2056 DISCO-751: Support more breakpoints for new search bar
  src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/RelatedArtworks.tsx
  src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
  src/Components/Search/Previews/index.tsx
  src/Components/Search/SearchBar.tsx
Labels: Version: Minor

#2059 Remove stale code
  src/Components/Search/Suggestions/index.tsx
  src/Components/__stories__/Search.story.tsx
  src/__generated__/SuggestionsSearchQuery.graphql.ts
  src/__generated__/SuggestionsSearch_viewer.graphql.ts
Labels: Version: Patch

#2060 Don't dismiss the search results if the user clicked on a descendant component
  src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
  src/Components/Search/SearchBar.tsx
Labels: Jira Synced, Version: Patch

#2062 [Lib] Update react-line-ellipses
  package.json
  src/Components/Truncator.tsx
  yarn.lock
Labels: Version: Patch

#2061 DISCO-752: Add return icon to search suggestions
  src/Components/Search/Previews/index.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/Search/Suggestions/SuggestionItem.tsx
  src/Components/Search/Suggestions/SuggestionItemContainer.tsx
  src/Components/__stories__/Search.story.tsx
Labels: Version: Patch

#2065 @mzikherman => [Autosuggest] Hook up event dispatch for analytics tracking
  src/Components/Search/SearchBar.tsx
  src/Components/Search/Suggestions/SuggestionItem.tsx
Labels: Version: Patch

#2055 Hook up failed payment flow
  data/schema.graphql
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/acceptOffer.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/fixFailedPayment.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/index.ts
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/Accept_order.graphql.ts
  src/__generated__/NewPaymentRouteSetOrderPaymentMutation.graphql.ts
  src/__generated__/NewPaymentTestQuery.graphql.ts
  src/__generated__/NewPayment_order.graphql.ts
  src/__generated__/routes_AcceptQuery.graphql.ts
  src/__generated__/routes_NewPaymentQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2066 @jonallured => [Autosuggest] Couple minor QA items
  src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/__tests__/index.test.tsx
  src/Components/Search/SearchBar.tsx
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/Accept_order.graphql.ts
  src/__generated__/routes_AcceptQuery.graphql.ts
Labels: Version: Patch

#2067 DISCO-759: Add search bar icon
  src/Components/Search/SearchBar.tsx
  src/Components/Search/SearchInputContainer.tsx
Labels: Version: Patch

#2071 Fix link styles in Collections header
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Version: Patch

#2070 DISCO-760: Add an "empty" preview for artists without collections or artworks
  src/Components/Search/Previews/Grids/ArtistSearch/NoResults.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/RelatedArtworks.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/__tests__/index.test.tsx
  src/Components/__stories__/Search.story.tsx
Labels: Jira Synced, Version: Patch

#2072 Make @sentry/browser a peer dependency of reaction
  package.json
Labels: Version: Patch

#2069 @pepopowitz => [Autosuggest] Start letting keyboard navigate preview pane
  src/Components/Search/AutosuggestManager.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/RelatedArtworks.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/index.tsx
  src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
  src/Components/Search/Previews/Grids/PreviewGridItem.tsx
  src/Components/Search/Previews/index.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/Search/state.ts
  src/Components/__stories__/Search.story.tsx
  src/__generated__/ArtistSearchPreviewQuery.graphql.ts
  src/__generated__/MerchandisableArtworksPreviewQuery.graphql.ts
  src/__generated__/MerchandisableArtworks_viewer.graphql.ts
  src/__generated__/RelatedArtworksPreview_viewer.graphql.ts
  src/__generated__/TestsQuery.graphql.ts
Labels: Version: Patch

#2075 Randomize collections rail
  data/schema.graphql
  src/Components/CollectionsRail/index.tsx
  src/__generated__/CollectionsRailQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2076 Add separator between RelatedArticlesCanvas and CollectionsRail
  src/Components/CollectionsRail/CollectionsRail.tsx
  src/Components/CollectionsRail/__tests__/CollectionsRail.test.tsx
  src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
  src/Components/Publishing/RelatedArticles/Canvas/RelatedArticlesCanvas.tsx
  src/Components/Publishing/RelatedArticles/Canvas/__tests__/RelatedArticlesCanvas.test.tsx
  src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
  src/Components/Publishing/__stories__/ArticleStandard.story.tsx
Labels: Version: Patch

#2073 Update CollectionsRail analytics with revised fields
  src/Components/CollectionsRail/CollectionEntity.tsx
  src/Components/CollectionsRail/CollectionsRail.tsx
  src/Components/CollectionsRail/__tests__/CollectionEntity.test.tsx
  src/Components/CollectionsRail/__tests__/CollectionsRail.test.tsx
Labels: Version: Patch

#2078 Sync schema to avoid failures in force builds
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#2080 Avoid endlessly requesting further pages of followed artists' artworks
  src/Apps/WorksForYou/WorksForYouFeed.tsx
Labels: Jira Synced, Version: Patch

#2081 [DO NOT MERGE] New payment page will redirect to /status page unless the order's last transaction has failed
  data/schema.graphql
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/Order/redirects.tsx
  src/__generated__/redirects_order.graphql.ts
  src/__generated__/routes_OrderQuery.graphql.ts
Labels: Version: Patch

#2074 Prevent body from intercepting scroll events when modal is not open (GALL-1430, DISCO-683)
  src/Components/Authentication/__tests__/Desktop/ModalManager.test.tsx
  src/Components/Modal/ModalWrapper.tsx
Labels: Jira Synced, Version: Patch

#2082 Refactor search previews css
  src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/NoResults.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/RelatedArtworks.tsx
  src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
  src/Components/Search/Previews/Grids/PreviewGridItem.tsx
  src/Components/Search/SearchBar.tsx
Labels: Version: Patch

#2084 @pepopowitz => [Autosuggest] Maintain suggestion list even while navigating to a preview item
  src/Components/Search/Previews/Grids/ArtistSearch/MarketingCollections.tsx
  src/Components/Search/Previews/Grids/ArtistSearch/RelatedArtworks.tsx
  src/Components/Search/Previews/Grids/MerchandisableArtworks.tsx
  src/Components/Search/Previews/Grids/PreviewGridItem.tsx
  src/Components/Search/Previews/index.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/Search/state.ts
Labels: Version: Patch

#2088 Fix type errors
  package.json
  src/Components/Publishing/Nav/Nav.tsx
  src/Components/Publishing/Sections/ArtworkCaption.tsx
  src/Components/Publishing/Sections/Author.tsx
  src/Components/Publishing/Sections/ImageSetPreview/ImageSetPreview.tsx
  src/Components/Publishing/Sections/VerticalOrSeriesTitle.tsx
  src/Components/v2/Carousel.tsx
  yarn.lock
Labels: Version: Patch
