Repository artsy/reaction, pull requests merged in 2019-07, with the labels that each got.

#2561 updates price sort string to account for "sold" #DONTMERGE
  src/Apps/Collect/Components/Filters/SortFilterSortTypes.tsx
  src/Apps/Collect/Components/Filters/__tests__/SortFilterSortTypes.test.tsx
Labels: Version: Patch

#2589 PURCHASE-1197 - Adds TabCarousel
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/__tests__/SearchApp.test.tsx
  src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
  src/Components/v2/Carousel.tsx
  src/Components/v2/RouteTabs.tsx
  src/Components/v2/__stories__/Tabs.Router.story.tsx
Labels: Jira Synced, Version: Minor

#2593 @alloy => [Artist] Remove unused user context on overview route
  src/Apps/Artist/Routes/Overview/index.tsx
Labels: Version: Patch

#2594 Rename Feature Article Fixture
  src/Components/Publishing/Fixtures/Articles.ts
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
Labels: Merge On Green, Version: Trivial

#2548 PURCHASE-1198 - Adds fair and museums to Search results tabs
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/Components/__tests__/NavigationTabs.test.tsx
  src/Apps/Search/routes.tsx
Labels: Jira Synced, Merge On Green

#2595 Prevent Empty Div From Rendering If No Ad Served or Ad Blocker Enabled
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
Labels: Version: Patch

#2590 [GROW-1314] refactor to be able to use image with authentication modal
  src/Components/Authentication/Desktop/ModalManager.tsx
  src/Components/Authentication/Types.ts
  src/Components/Modal/Modal.tsx
  src/Components/Modal/__tests__/Modal.test.tsx
Labels: Jira Synced, Version: Patch

#2599 Handles empty divs when ad blocker is enabled
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
Labels: Version: Patch

#2598 grow_1367 Featured artist module on Small viewport should be 3 per row
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Jira Synced, Version: Patch

#2584 fix GROW-1341(Carousel tweaks for artist series and related collections)
  src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionsRail.tsx
  src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
  src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
Labels: Jira Synced, Version: Patch

#2602 Removes viewable threshold prop from ad component
  src/Components/Publishing/Display/DisplayAd.tsx
Labels: Merge On Green, Version: Patch

#2603 change sync correlator to true
  src/Components/Publishing/Display/DisplayAd.tsx
Labels: Version: Patch

#2597 Remove NewDisplayCanvas from news articles, in favor of DisplayAd
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/Layouts/NewsLayout.tsx
  src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/NewsLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
Labels: Jira Synced

#2606 @mbilokonsky => [CollectionRail] Switch artwork sorting to use -decayed_merch
  src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionEntity.tsx
  src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
  src/__generated__/ArtistCollectionEntity_collection.graphql.ts
  src/__generated__/ArtistCollectionsRailQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/RelatedCollectionEntity_collection.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Version: Patch

#2592 Deprecate old ads from featured articles
  src/Components/Publishing/Layouts/__tests__/FeatureLayout.test.tsx
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
Labels: Jira Synced, Version: Patch

#2607 Deprecate old ads for series landing pages
  src/Components/Publishing/Layouts/SeriesLayout.tsx
  src/Components/Publishing/Layouts/__tests__/SeriesLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/SeriesLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
Labels: Jira Synced, Version: Patch

#2608 [GROW-1314] handle modal width for medium screens
  src/Components/Modal/ModalWrapper.tsx
Labels: Jira Synced, Version: Patch

#2609 Deprecate old ads on video articles
  src/Components/Publishing/Layouts/VideoLayout.tsx
  src/Components/Publishing/Layouts/__tests__/VideoLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/VideoLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
Labels: Merge On Green, Version: Patch

#2610 Remove Old Display for Ad server cleanup
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/Display/Canvas/index.tsx
  src/Components/Publishing/Display/DisplayPanel.tsx
  src/Components/Publishing/Display/NewDisplayCanvas.tsx
  src/Components/Publishing/Display/NewDisplayPanel.tsx
  src/Components/Publishing/Display/__tests__/DisplayCanvas.test.tsx
  src/Components/Publishing/Display/__tests__/DisplayPanel.test.tsx
  src/Components/Publishing/Display/__tests__/NewDisplayCanvas.test.tsx
  src/Components/Publishing/Display/__tests__/NewDisplayPanel.test.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayPanel.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/Fixtures/Components.ts
  src/Components/Publishing/Layouts/Components/__tests__/Sidebar.test.tsx
  src/Components/Publishing/Layouts/__tests__/ArticleWithFullScreen.test.tsx
  src/Components/Publishing/Layouts/__tests__/FeatureLayout.test.tsx
  src/Components/Publishing/Typings.ts
  src/Components/Publishing/__stories__/ArticleFeature.story.tsx
  src/Components/Publishing/__stories__/ArticleNews.story.tsx
  src/Components/Publishing/__stories__/ArticleStandard.story.tsx
  src/Components/Publishing/__stories__/Display.story.tsx
Labels: Jira Synced, Version: Patch

#2612 Sync metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#2613 [Trivial] Rename and export article card image container
  src/Components/Publishing/RelatedArticles/ArticleCards/ArticleCard.tsx
Labels: Merge On Green, Version: Patch

#2611 Remove feature flag from display ads
  .storybook/webpack.config.js
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/Display/DisplayTargeting.tsx
  src/Components/Publishing/Layouts/ClassicLayout.tsx
  src/Components/Publishing/Layouts/Components/__tests__/CanvasFooter.test.tsx
  src/Components/Publishing/Layouts/FeatureLayout.tsx
  src/Components/Publishing/Layouts/NewsLayout.tsx
  src/Components/Publishing/Layouts/SeriesLayout.tsx
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/Layouts/VideoLayout.tsx
  src/Components/Publishing/Layouts/__tests__/ArticleWithFullScreen.test.tsx
  src/Components/Publishing/Layouts/__tests__/FeatureLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/SeriesLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/VideoLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
  typings/sharify.d.ts
Labels: Jira Synced, Version: Patch

#2616 Ad bug fixes
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
  src/Components/Publishing/Fixtures/Components.ts
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/Layouts/__tests__/SeriesLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/VideoLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Typings.ts
Labels: Version: Patch

#2618 Update featured articles to only render a max of 2 ads
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
Labels: Jira Synced, Version: Patch

#2620 grow-1391 Collections carousel tweaks QA for artist series and related collections
  src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionsRail.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Apps/Collect/CollectionApp.tsx
  src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
Labels: Jira Synced, Version: Patch

#2624 Update collections header image GROW-1257
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Jira Synced

#2626 @damassi => [ArtworkFilter] Remove unneeded call for medium aggregations
  src/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/index.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/__generated__/ArtworkFilterQuery.graphql.ts
  src/__generated__/ArtworkFilter_viewer.graphql.ts
Labels: Merge On Green

#2627 Fix Modal with image on smaller(xs) screens
  src/Components/Modal/Modal.tsx
Labels: Merge On Green, Version: Patch

#2614 Test & refactor collection header
  src/Apps/Collect/Components/Collection/Header/__tests__/Header.test.tsx
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2630 Fixed spacing above Related Works artwork grid on artwork page
  src/Apps/Artwork/Components/OtherWorks/index.tsx
  src/__generated__/CollectionsRailsQuery.graphql.ts
  src/__generated__/FeaturedCollectionsRails_marketingCollection.graphql.ts
Labels: Version: Patch

#2631 @sweir27 => [RelatedArtworks] Pass thru artwork slug to refetch query
  src/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx
  src/__generated__/OtherWorksQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Merge On Green

#2605 Add initial auction registration flow
  src/Apps/Auction/AuctionApp.tsx
  src/Apps/Auction/Components/ConditionsOfSaleCheckbox.tsx
  src/Apps/Auction/Components/RegistrationForm.tsx
  src/Apps/Auction/routes.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/__generated__/AuctionApp_sale.graphql.ts
  src/__generated__/RegistrationFormCreateBidderMutation.graphql.ts
  src/__generated__/RegistrationFormCreateCreditCardMutation.graphql.ts
  src/__generated__/routes_AuctionQuery.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Minor

#2633 Other collections module
  src/Apps/__tests__/Fixtures/Collections.ts
  src/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
  src/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionEntity.test.tsx
  src/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionsRail.test.tsx
  src/Components/CollectionsHubRails/OtherCollectionsRail/index.tsx
  src/Components/CollectionsHubRails/index.tsx
  src/__generated__/CollectionsHubRails_marketingCollection.graphql.ts
  src/__generated__/CollectionsRailsQuery.graphql.ts
  src/__generated__/OtherCollectionEntity_member.graphql.ts
  src/__generated__/OtherCollectionsRail_collectionGroup.graphql.ts
Labels: Jira Synced, Version: Patch

#2632 PURCHASE-1347 - Uses modal for price in context
  src/Apps/Artwork/Components/PricingContextModal.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Artwork/Components/__tests__/PricingContextModal.test.tsx
Labels: Jira Synced, Version: Patch

#2637 Sync MP schema #trivial
  data/schema.graphql
Labels: Version: Patch

#2636 Scaffold Vanguard series page
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/ArtistWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/Introduction.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/SeriesWrapper.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/Components/TableOfContents.tsx
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/index.tsx
  src/Components/Publishing/EditorialFeature/EditorialFeature.tsx
Labels: Merge On Green, Version: Patch

#2638 @damassi => [SearchResults] Remove unneeded call for medium aggregations
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/FilterContainer.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/MediumFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsFilterContainer.tsx
  src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
  src/__generated__/SearchResultsArtworks_viewer.graphql.ts
  src/__generated__/SearchResultsFilterContainer_viewer.graphql.ts
  src/__generated__/routes_SearchResultsArtworksQuery.graphql.ts
Labels: Merge On Green, Version: Patch

#2634 [Collections] Default Header
  src/Apps/Collect/CollectionApp.tsx
  src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
  src/Apps/Collect/Components/Collection/Header/DefaultHeader.tsx
  src/Apps/Collect/Components/Collection/Header/__tests__/DefaultHeader.test.tsx
  src/Apps/Collect/Components/Collection/Header/__tests__/Header.test.tsx
  src/Apps/Collect/Components/Collection/Header/__tests__/__snapshots__/DefaultHeader.test.tsx.snap
  src/Apps/Collect/Components/Collection/Header/__tests__/fixtures/artworks.ts
  src/Apps/Collect/Components/Collection/Header/index.tsx
  src/Components/Modal/ModalWrapper.tsx
  src/Utils/Hooks/useWindowSize.ts
  src/Utils/viewport.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionApp_collection.graphql.ts
  src/__generated__/CollectionFilterContainer_collection.graphql.ts
  src/__generated__/DefaultHeader_headerArtworks.graphql.ts
  src/__generated__/Header_artworks.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2642 Video Headers Won't Crash
  src/Components/Publishing/Series/FixedBackground.tsx
  src/Components/Publishing/Series/__tests__/FixedBackground.test.tsx
  src/Components/Publishing/Series/__tests__/__snapshots__/FixedBackground.test.tsx.snap
Labels: Jira Synced

#2640 Address more MP v2 deprecations
  data/schema.graphql
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarClassification.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarClassification.test.tsx
  src/Apps/Artwork/Components/PricingContext.tsx
  src/Apps/Artwork/Components/Seo/SeoDataForArtwork.tsx
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.fixture.ts
  src/Apps/Artwork/Components/Seo/__tests__/SeoDataForArtwork.test.tsx
  src/Apps/Artwork/Components/__stories__/PricingContext.story.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Collect/Components/Seo/SeoProductsForArtworks.tsx
  src/Apps/Order/Components/ItemReview.tsx
  src/Apps/Order/Components/__stories__/ItemReview.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarMetadata.ts
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/ArtworkImageBrowser_artwork.graphql.ts
  src/__generated__/ArtworkSidebarClassification_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarClassification_artwork.graphql.ts
  src/__generated__/ArtworkSidebarCommercial_artwork.graphql.ts
  src/__generated__/ArtworkSidebarMetadata_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/ItemReview_artwork.graphql.ts
  src/__generated__/PricingContextStoryQuery.graphql.ts
  src/__generated__/PricingContextTestQuery.graphql.ts
  src/__generated__/PricingContext_artwork.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/SeoDataForArtwork_artwork.graphql.ts
  src/__generated__/SeoProductsForArtworks_artworks.graphql.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_ReviewQuery.graphql.ts
  src/__generated__/routes_StatusQuery.graphql.ts
Labels: Jira Synced, Version: Minor

#2650 [RecentlyViewed Carousel] Make consistent with recent patterns
  src/Components/v2/RecentlyViewed.tsx
  src/Components/v2/__stories__/RecentlyViewed.story.tsx
Labels: Version: Patch
