Repository artsy/reaction, pull requests merged in 2019-01, with the labels that each got.

#1772 Make offer speed bumps
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
  src/Apps/Order/Dialogs.tsx
  src/Apps/Order/OrderApp.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/Components/Modal/ErrorModal.tsx
  src/Components/Modal/ModalDialog.tsx
  src/Components/Modal/__tests__/ErrorModal.test.tsx
  src/Components/Modal/__tests__/ModalDialog.test.tsx
  src/Components/Payment/__tests__/PaymentForm.test.tsx
  src/Components/__stories__/ModalDialog.story.tsx
  src/__generated__/OfferMutation.graphql.ts
  src/__generated__/Offer_order.graphql.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/Respond_order.graphql.ts
  src/__generated__/routes_OfferQuery.graphql.ts
  src/__generated__/routes_RespondQuery.graphql.ts
Labels: Jira Synced

#1780 PURCHASE-768: Copy updates
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Components/Publishing/Video/Player/Scrubber.tsx
  src/Components/__stories__/PopoverExamples/DisplayPopoverOnBlurExample.tsx
Labels: Jira Synced

#1781 Add a skip release label
  .autorc
Labels: Version: Trivial

#1782 Update readme
  README.md
Labels: Version: Patch

#1785 Visual pass at non auction sidebar
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarClassification.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarExtraLinks.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarArtists.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarAuctionPartnerInfo.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarBidActionStory.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarClassification.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarCommercial.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarCurrentBidInfo.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarExtraLinks.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarMetadata.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarPageviews.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarPartnerInfo.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarSizeInfo.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarTitleInfo.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
Labels: Jira Synced, Version: Patch

#1778 Surface only time periods that match a defined list in filters
  src/Apps/Collect/Components/Filters/TimePeriodFilter.tsx
  src/Apps/Collect/Components/Filters/__tests__/TimePeriodFilter.test.tsx
Labels: Jira Synced

#1787 Update auto, should fix our custom tags
  package.json
  yarn.lock
Labels: Skip Release

#1786 fix offer speed bump thresholds
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
Labels: Version: Patch

#1788 Add specific error for insufficient inventory
  src/Apps/Order/Routes/Counter/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitPendingOffer.ts
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
Labels: Version: Patch

#1789 Remove release label requirement
  .autorc
Labels: Version: Patch

#1773 [yeoman] Add empty stub so the omakase generator knows what the root is.
  .yo-rc.json
Labels: Merge On Green, Version: Trivial

#1791 Remove BNMO marketing banner on Works for You page
  src/Apps/WorksForYou/MarketingHeader.tsx
Labels: Jira Synced, Version: Patch

#1792 @damassi => Fix couple small blockers on BNMO flow in new artwork page
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
  src/__generated__/ArtworkSidebarCommercial_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Patch

#1793 Remove extra space at bottom of order/offer pages
  src/Apps/Order/OrderApp.tsx
Labels: Jira Synced, Version: Patch

#1795 [Artwork] Fix share zoom on iOS
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#1794 Add spacing below buttons of some order/offer forms
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
Labels: Version: Patch

#1798 [Artwork] Make center content properly flow regardless of sidebar size
  src/Apps/Artwork/ArtworkApp.tsx
Labels: Version: Patch

#1799 [Artwork] Tighten up main Artwork image sizings
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
Labels: Version: Patch

#1800 [Artwork] Tighten up image size (more)
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
Labels: Merge On Green, Version: Patch

#1801 [Artwork] Padding to actions
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
Labels: Merge On Green, Version: Patch

#1797 updates to layout on the sidebar for auctions
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#1803 Remove unused dependency and update auto-release-cli
  package.json
  yarn.lock
Labels: Version: Trivial

#1744 PURCHASE-613 - Adds make offer filter inputs
  data/schema.graphql
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterRefetch.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Artist/Routes/Overview/state.ts
  src/Apps/Collect/Components/Base/CollectRefetch.tsx
  src/Apps/Collect/Components/Collection/CollectionFilterContainer.tsx
  src/Apps/Collect/Components/Collection/CollectionRefetch.tsx
  src/Apps/Collect/Components/Filters/WaysToBuyFilter.tsx
  src/Apps/Collect/FilterState.tsx
  src/Apps/Collect/__tests__/FilterState.test.tsx
  src/Apps/Collect/routes.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkFilter_artist.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectRefetch_viewer.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionFilterContainer_collection.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/CollectionRefetch_collection.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
  typings/sharify.d.ts
Labels: Jira Synced, Version: Minor

#1796 Use current offer on counter when checking offer amount
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/Respond_order.graphql.ts
  src/__generated__/routes_RespondQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#1804 Fix spacing and state management for BNMO buttons on artwork page.
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Labels: Jira Synced, Version: Patch

#1805 fix display for single editioned works with hidden availability
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCommercial.ts
Labels: Jira Synced, Version: Patch

#1806 @damassi => Add some missing analytics
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/ArtworkSidebarArtists_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarArtists_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Merge On Green, Version: Patch

#1808 Not show contact gallery for works enabled for BNMO
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarCommercial.ts
Labels: Version: Patch

#1810 @damassi => Some more analytics updates for artwork page
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarClassification.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Artsy/Analytics/Schema/Values.ts
Labels: Version: Patch

#1811 @damassi => Analytics for clicking to enter a live auction
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Artsy/Analytics/Schema/Values.ts
Labels: Merge On Green, Version: Patch

#1813 @damassi => Add analytics for clicking lightbox zoom
  src/Artsy/Analytics/Schema/Values.ts
  src/Styleguide/Components/Lightbox/Lightbox.tsx
Labels: Version: Patch

#1812 [package] Add @omakase/cli which has the component/container generator.
  package.json
  yarn.lock
Labels: Skip Release

#1814 @damassi => Custom artwork analytics for BNMO + pageview
  src/Apps/Artwork/ArtworkApp.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Merge On Green, Version: Patch

#1815 Grab circle jobs from yarn orbs
  .circleci/config.yml
Labels: Version: Trivial

#1816 [Artwork] Add tracking to OtherWorks ArtworkGrid bricks
  src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/AuctionArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/FairArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerShowArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/Components/Artwork/FillwidthItem.tsx
  src/Components/Artwork/GridItem.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Styleguide/Components/ArtistCard.tsx
  src/Styleguide/Components/RecentlyViewed.tsx
Labels: Merge On Green, Version: Patch

#1820 Update auto-update to v2
  .autorc
  package.json
  yarn.lock
Labels: Version: Trivial

#1821 [Artwork] Add action_types to click
  src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/ArtistArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/AuctionArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/FairArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/PartnerShowArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
  src/Styleguide/Components/RecentlyViewed.tsx
Labels: Merge On Green, Version: Patch

#1822 [version] Bump to 9.3.10
  package.json
Labels: Skip Release, Version: Patch

#1826 fix typo
  src/Artsy/Analytics/Schema/Values.ts
Labels: Version: Patch

#1818 Fix artsy.com typo
  src/Apps/Order/Routes/Counter/index.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
Labels: Jira Synced, Version: Patch

#1807 Fix offer cancelled messages
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/__stories__/OrderApp.story.tsx
Labels: Jira Synced, Version: Patch

#1809 [WIP] Visual QA fixes
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Status/index.tsx
  src/Components/Modal/ModalWrapper.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#1827 Rename events for buy and make offer click tracking
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Artsy/Analytics/Schema/Values.ts
Labels: Jira Synced, Version: Patch

#1828 @oxaudo => Tweak some more analytics for the artwork page
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/Components/Artwork/Save.tsx
  src/__generated__/ArtistsQuery.graphql.ts
  src/__generated__/ArtworkContextArtistQuery.graphql.ts
  src/__generated__/ArtworkContextArtist_Test_Query.graphql.ts
  src/__generated__/ArtworkContextAuctionQuery.graphql.ts
  src/__generated__/ArtworkContextFairQuery.graphql.ts
  src/__generated__/ArtworkContextFair_Test_Query.graphql.ts
  src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
  src/__generated__/ArtworkContextPartnerShow_Test_Query.graphql.ts
  src/__generated__/ArtworkFilterArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilter_Test_Query.graphql.ts
  src/__generated__/ArtworkGridExampleQuery.graphql.ts
  src/__generated__/ArtworkGridQuery.graphql.ts
  src/__generated__/ArtworkGrid_Test_Query.graphql.ts
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectArtworkGridQuery.graphql.ts
  src/__generated__/CollectArtworkGridTestQuery.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionRefetchQuery.graphql.ts
  src/__generated__/ComparablesQuery.graphql.ts
  src/__generated__/ComparablesViewQuery.graphql.ts
  src/__generated__/FillwidthQuery.graphql.ts
  src/__generated__/GeneArtworksContentQuery.graphql.ts
  src/__generated__/GeneContentsArtistsQuery.graphql.ts
  src/__generated__/GeneContentsArtworksQuery.graphql.ts
  src/__generated__/RecentlyViewedQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGridRefetchQuery.graphql.ts
  src/__generated__/RelatedWorksArtworkGrid_Test_Query.graphql.ts
  src/__generated__/SaveArtworkQuery.graphql.ts
  src/__generated__/Save_artwork.graphql.ts
  src/__generated__/TagArtworksContentQuery.graphql.ts
  src/__generated__/TagContentsArtworksQuery.graphql.ts
  src/__generated__/WorksForYouArtistFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouFeedPaginationQuery.graphql.ts
  src/__generated__/WorksForYouQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
Labels: Version: Patch

#1830 @oxaudo => Correct reference to props in BNMO analytics
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Labels: Merge On Green, Version: Patch

#1829 @jonallured => Send `offerable` params everywhere!
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/ArtworkFilterRefetch.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artist/routes.tsx
  src/Apps/Collect/CollectApp.tsx
  src/Apps/Collect/Components/Base/CollectFilterContainer.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/__generated__/ArtworkFilterRefetchQuery.graphql.ts
  src/__generated__/ArtworkFilterRefetch_artist.graphql.ts
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectApp_viewer.graphql.ts
  src/__generated__/CollectFilterContainer_viewer.graphql.ts
  src/__generated__/Overview_artist.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#1784 Add Selected Career Achievements component (Artist Insights 2.0)
  .storybook/webpack.config.js
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/Apps/__tests__/Fixtures/SelectedCareerAchievements.ts
  src/Assets/Icons/Auction.tsx
  src/Assets/Icons/BlueChip.tsx
  src/Assets/Icons/Book.tsx
  src/Assets/Icons/Fair.tsx
  src/Assets/Icons/Group.tsx
  src/Assets/Icons/Museum.tsx
  src/Assets/Icons/Solo.tsx
  src/Assets/Icons/TopEmerging.tsx
  src/Assets/Icons/TopEstablished.tsx
  src/Assets/SVGIcons.tsx
  src/Components/__stories__/Icons.story.tsx
  src/Styleguide/Components/ArtistInsight.tsx
  src/Styleguide/Components/ArtistInsightsModal.tsx
  src/Styleguide/Components/SelectedCareerAchievements.tsx
  src/Styleguide/Components/__stories__/SelectedCareerAchivements.story.tsx
  src/Styleguide/Components/index.tsx
  src/Utils/getUser.ts
  src/__generated__/Overview_artist.graphql.ts
  src/__generated__/SelectedCareerAchievementsArtistPage_artist.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
  typings/gravity.d.ts
Labels: Jira Synced, Version: Minor

#1833 [Artwork] Refactor ActionPanel links
  .env.oss
  .storybook/webpack.config.js
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__stories__/ArtworkActions.story.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkActions.fixture.ts
  src/Apps/__tests__/Fixtures/Artwork/ArtworkImageBrowser.fixture.ts
  src/Assets/Icons.tsx
  src/Assets/Icons/Bell.tsx
  src/Assets/Icons/Download.tsx
  src/Assets/Icons/Edit.tsx
  src/Assets/Icons/Genome.tsx
  src/Assets/Icons/Heart.tsx
  src/Assets/Icons/Share.tsx
  src/Assets/SVGIcons.tsx
  src/__generated__/ArtworkActions_artwork.graphql.ts
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  typings/gravity.d.ts
  typings/sharify.d.ts
Labels: Version: Patch

#1837 Fix offer speedbump UX
  src/Apps/Order/Dialogs.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
Labels: Jira Synced, Version: Patch

#1790 Custom colors
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/EditorialFeature/__tests__/EditorialFeature.test.tsx
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Icon/IconImageSet.tsx
  src/Components/Publishing/Layouts/FeatureLayout.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Sections/Artwork.tsx
  src/Components/Publishing/Sections/ArtworkCaption.tsx
  src/Components/Publishing/Sections/Author.tsx
  src/Components/Publishing/Sections/Authors.tsx
  src/Components/Publishing/Sections/Caption.tsx
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Caption.test.tsx.snap
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/FullscreenViewer.test.tsx.snap
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Slide.test.tsx.snap
  src/Components/Publishing/Sections/Image.tsx
  src/Components/Publishing/Sections/ImageCollection.tsx
  src/Components/Publishing/Sections/ImageSetPreview/ImageSetLabel.tsx
  src/Components/Publishing/Sections/ImageSetPreview/ImageSetPreview.tsx
  src/Components/Publishing/Sections/ImageSetPreview/__tests__/__snapshots__/ImageSetPreview.test.tsx.snap
  src/Components/Publishing/Sections/ImageSetPreview/__tests__/__snapshots__/ImageSetPreviewClassic.test.tsx.snap
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/StyledText.tsx
  src/Components/Publishing/Sections/Text.tsx
  src/Components/Publishing/Sections/Video.tsx
  src/Components/Publishing/Sections/__tests__/__snapshots__/Artwork.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/ArtworkCaption.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Authors.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/SectionContainer.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
  src/Components/Publishing/ToolTip/LinkWithTooltip.tsx
  src/Components/Publishing/ToolTip/ToolTip.tsx
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
  src/Components/Publishing/__stories__/ArticleFeature.story.tsx
  src/Components/Publishing/__tests__/Icon/__snapshots__/IconImageset.test.tsx.snap
Labels: Version: Minor

#1838 Address React warnings found via React Dev Tools
  src/Assets/Icons/Auction.tsx
  src/Assets/Icons/BlueChip.tsx
  src/Assets/Icons/Book.tsx
  src/Assets/Icons/Fair.tsx
  src/Assets/Icons/Group.tsx
  src/Assets/Icons/Museum.tsx
  src/Assets/Icons/Solo.tsx
  src/Assets/Icons/TopEmerging.tsx
  src/Assets/Icons/TopEstablished.tsx
  src/Styleguide/Components/SelectedCareerAchievements.tsx
Labels: Version: Trivial

#1834 [Refactor] Remove useRelay fork code for ArtworkGrid
  src/Components/Artwork/Fillwidth.tsx
  src/Components/Artwork/FillwidthItem.tsx
  src/Components/Artwork/GridItem.tsx
  src/Components/Artwork/Metadata.tsx
  src/Components/Artwork/Save.tsx
  src/Components/Artwork/index.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/Components/ArtworkGrid/ArtworkGridEmptyState.tsx
  src/Components/ArtworkGrid/__stories__/ArtworkGrid.story.tsx
  src/Components/ArtworkGrid/__tests__/ArtworkGrid.test.tsx
  src/Components/__stories__/Artwork.story.tsx
  src/Components/__stories__/ArtworkMetadata.story.tsx
  src/Components/__stories__/Fillwidth.story.tsx
  src/Styleguide/Components/RecentlyViewed.tsx
  src/Styleguide/Components/__stories__/Carousel.story.tsx
  src/Styleguide/Components/__stories__/RecentlyViewed.story.tsx
Labels: Version: Patch

#1839 DISCO-656: Add event tracking for Read more / Learn more artist insight actions
  src/Artsy/Analytics/Schema/Values.ts
  src/Styleguide/Components/ArtistInsight.tsx
  src/Styleguide/Components/ArtistInsightsModal.tsx
  src/Styleguide/Components/SelectedCareerAchievements.tsx
Labels: Jira Synced, Version: Patch

#1841 [Minor] Fix IconRemove component definition
  src/Components/Publishing/Icon/IconRemove.tsx
Labels: Version: Patch

#1843 Tidy up design implementation and component ordering for Artist Insights v2
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Assets/Icons/Auction.tsx
  src/Assets/Icons/Group.tsx
  src/Assets/Icons/Solo.tsx
  src/Styleguide/Components/ArtistInsight.tsx
  src/Styleguide/Components/ArtistInsightsModal.tsx
  src/Styleguide/Components/SelectedCareerAchievements.tsx
Labels: Jira Synced, Version: Patch

#1849 Tidy up Artist Insights design implementation
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Styleguide/Components/ArtistInsight.tsx
  src/Styleguide/Components/ArtistInsightsModal.tsx
Labels: Jira Synced, Version: Patch

#1845 Add MO speedbump analytics
  src/Apps/Order/Components/OfferInput.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Artsy/Analytics/Schema/Values.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#1852 Switch between Artist Insights variations based on A/B enrollment
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Artsy/Analytics/Schema/Values.ts
  typings/sharify.d.ts
Labels: Version: Patch

#1856 Move Artist Insights component after bio
  src/Apps/Artist/Routes/Overview/index.tsx
Labels: Version: Patch

#1850 @oxaudo => Keep track of suggested artists that have been displayed (use `unstated`)
  src/Styleguide/Components/FollowArtistPopover/FollowArtistPopoverRow.tsx
  src/Styleguide/Components/FollowArtistPopover/index.tsx
  src/Styleguide/Components/FollowArtistPopover/state.ts
  src/__generated__/ArtworkSidebarArtists_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/FollowArtistPopoverQuery.graphql.ts
  src/__generated__/FollowArtistPopoverRowMutation.graphql.ts
  src/__generated__/FollowArtistPopover_suggested.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Patch

#1858 Modal: Support background scroll locking and close via escape key
  src/Components/Modal/ModalWrapper.tsx
Labels: Jira Synced, Version: Patch

#1860 Update condition for when to show Artist Insights V2
  src/Apps/Artist/Routes/Overview/index.tsx
  src/__generated__/Overview_artist.graphql.ts
  src/__generated__/routes_OverviewQueryRendererQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#1853 [Styleguide] Remove <GlobalStyles> component in favor of palette version
  src/Artsy/Router/Components/Boot.tsx
  src/Styleguide/Elements/GlobalStyles.tsx
Labels: Merge On Green, Version: Patch

#1866 [Styleguide] Remove <Grid> and move to palette
  package.json
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Routes/Articles/ArtistArticle.tsx
  src/Apps/Artist/Routes/Articles/ArtistArticles.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/TableColumns.tsx
  src/Apps/Artist/Routes/AuctionResults/TableSidebar.tsx
  src/Apps/Artist/Routes/CV/CVItem.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artist/Routes/RelatedArtists/RelatedArtistsList.tsx
  src/Apps/Artist/Routes/Shows/ArtistShowListItem.tsx
  src/Apps/Artist/Routes/Shows/ArtistShows.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsArticles.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__stories__/ArtworkImageBrowser.story.tsx
  src/Apps/Collect/Components/Collection/Header/index.tsx
  src/Apps/Order/Components/TwoColumnLayout.tsx
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/Counter/index.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Artsy/Router/Components/Boot.tsx
  src/Components/__stories__/Icons.story.tsx
  src/Styleguide/Components/Carousel.tsx
  src/Styleguide/Components/Tabs.tsx
  src/Styleguide/Elements/Grid.tsx
  src/Styleguide/Elements/index.tsx
  src/Styleguide/Utils/HorizontalPadding.tsx
  src/Styleguide/Utils/ScrollIntoView.tsx
  yarn.lock
Labels: Version: Patch

#1869 [Release] Attempt 2 to send out major release
  src/Utils/index.ts
  src/Utils/index.tsx
Labels: Version: Major

#1846 EOY artists unit tests
  src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/ArticleHeader.tsx
  src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/__tests__/index.test.tsx
  src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/index.tsx
  src/Components/Publishing/EditorialFeature/Fixtures/Eoy2018Artists.ts
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
Labels: Version: Patch

#1871 Fix Carousel arrows
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/v2/Carousel.tsx
Labels: Version: Patch

#1872 Remove GridThemeProvider and move to palette
  .circleci/config.yml
  package.json
  src/Artsy/Router/Components/Boot.tsx
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  yarn.lock
Labels: Merge On Green

#1854 Incremental relay mocking fixes
  patches/@types/relay-runtime+1.3.5.patch
  patches/relay-mock-network-layer+2.0.0.patch
  src/Apps/Order/Components/__tests__/TransactionDetailsSummary.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/__stories__/OrderApp.story.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/DevTools/MockRelayRenderer.tsx
  src/DevTools/MockRouter.tsx
  src/DevTools/__tests__/createMockNetworkLayer.test.ts
  src/DevTools/createMockNetworkLayer/index.ts
  src/DevTools/renderRelayTree.tsx
  src/__generated__/createMockNetworkLayerTestAliasQuery.graphql.ts
  src/__generated__/createMockNetworkLayerTestQuery.graphql.ts
Labels: Version: Patch

#1876 Remove react-styled-flexboxgrid from feature split header
  src/Components/Publishing/Header/Layouts/Components/FeatureSplitHeader.tsx
Labels: Version: Patch

#1877 Ensure artist insights flex container uses 100% of available space
  src/Components/v2/SelectedCareerAchievements.tsx
Labels: Jira Synced, Version: Patch

#1875 Refactor error modals
  src/Apps/Order/Dialogs.tsx
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/Counter/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
Labels: Jira Synced, Version: Patch

#1878 Add information about closed registration for live auctions if the user is not registered
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarBidAction.test.tsx
Labels: Jira Synced, Version: Patch

#1880 Add gutter space between artist insight components
  src/Components/v2/ArtistInsight.tsx
  src/Components/v2/SelectedCareerAchievements.tsx
Labels: Version: Patch

#1879 Add spacing below button on offer/respond page
  src/Apps/Order/Routes/Respond/index.tsx
Labels: Jira Synced, Version: Patch

#1881 Add specs to exercise components for Artist Insights V2
  src/Apps/__tests__/Fixtures/SelectedCareerAchievements.ts
  src/Components/v2/__tests__/ArtistInsight.test.tsx
  src/Components/v2/__tests__/SelectedCareerAchievements.test.tsx
  src/__generated__/SelectedCareerAchievementsTestQuery.graphql.ts
Labels: Version: Patch

#1883 Intercom
  src/Apps/Artwork/ArtworkApp.tsx
Labels: Version: Patch

#1882 [Util] Add collectSSRStyles util and update buildServerApp
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Collect/CollectApp.tsx
  src/Apps/Collect/CollectionApp.tsx
  src/Apps/Collections/CollectionsApp.tsx
  src/Apps/Components/AppContainer.tsx
  src/Apps/Components/HorizontalPadding.tsx
  src/Apps/Order/OrderApp.tsx
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/Counter/index.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/Status/index.tsx
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Components/ErrorPage.tsx
  src/Components/FrameWithRecentlyViewed.tsx
  src/Utils/ResponsiveDeprecated.tsx
  src/Utils/collectSSRStyles.tsx
Labels: Merge On Green, Version: Minor

#1889 clean up the mediator call for launching intercom and pass artwork to it
  src/Apps/Artwork/ArtworkApp.tsx
Labels: Version: Patch

#1891 Remove auto-release-cli as a direct dependency
  package.json
  yarn.lock
Labels: Version: Trivial

#1892 Make trivial considered an internal change
  .autorc
Labels: Version: Trivial

#1895 Don't deploy trivial changes
  .autorc
Labels: Version: Trivial

#1887 added error message modal for invalid amount
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/initialOffer.ts
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
Labels: Version: Patch

#1900 Deprecate Grid
  package.json
  src/Components/Grid.tsx
  src/Components/__stories__/Grid.story.tsx
  src/Components/__stories__/PopoverExamples/DisplayPopoverOnClickExample.tsx
  yarn.lock
Labels: Version: Major

#1898 Add docs for relay data mocking
  src/DevTools/README.md
Labels: Version: Patch

#1902 ArtworkBanner for auctions should show sale cover image instead of partner profile image
  src/Apps/Artwork/Components/ArtworkBanner/__tests__/ArtworkBanner.test.tsx
  src/Apps/Artwork/Components/ArtworkBanner/index.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkBanner.ts
  src/__generated__/ArtworkBannerQuery.graphql.ts
  src/__generated__/ArtworkBanner_Test_Query.graphql.ts
  src/__generated__/ArtworkBanner_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#1897 [Refactor] Remove <Tabs> and <Toggle> and move to Palette
  package.json
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Artwork/Components/ArtworkDetails/index.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
  src/Apps/Collect/Components/Filters/FilterContainer.tsx
  src/Apps/Comparables/Filter.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Components/v2/RouteTabs.tsx
  src/Components/v2/Stepper.tsx
  src/Components/v2/Tabs.tsx
  src/Components/v2/Toggle.tsx
  src/Components/v2/__stories__/Tabs.story.tsx
  src/Components/v2/__stories__/Toggle.story.tsx
  src/Components/v2/__tests__/Tabs.test.tsx
  src/Components/v2/__tests__/Toggle.test.tsx
  src/Components/v2/index.tsx
  yarn.lock
Labels: Version: Patch

#1861 User should see the mobile sign up modal in the artist page
  src/Apps/Artist/Components/ArtistHeader.tsx
Labels: Jira Synced, Version: Minor

#1848 Sort Collections alphabetically by title in Index page
  src/Apps/Collections/CollectionsApp.tsx
  src/Apps/Collections/Components/CollectionsGrid.tsx
  src/Apps/Collections/Components/__tests__/CollectionsGrid.test.tsx
  src/Apps/Collections/__tests__/CollectionsApp.test.tsx
Labels: Jira Synced, Version: Minor

#1906 Styling changes to Collections blurb font sizes
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Jira Synced, Version: Patch

#1909 Manually update version
  CHANGELOG.md
  package.json
Labels: Version: Trivial

#1905 Use fluid fontsize for EOY artists feature
  src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/ArticleHeader.tsx
  src/Components/Publishing/EditorialFeature/Components/Eoy2018Artists/index.tsx
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
Labels: Merge On Green, Version: Patch

#1915 Move Pagination display components to Palette
  package.json
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/v2/Pagination.tsx
  src/Components/v2/__stories__/Pagination.story.tsx
  src/Components/v2/__tests__/Pagination.test.tsx
  src/setup_jest.ts
  yarn.lock
Labels: Version: Patch

#1907 Migrate Pagination Components to Palette (SELL-862)
  src/Components/v2/Pagination.tsx
  src/Components/v2/__stories__/Pagination.story.tsx
  src/Components/v2/__tests__/Pagination.test.tsx
Labels: Jira Synced, Version: Patch

#1922 Disallow whitespace for address form
  src/Apps/Order/Utils/__tests__/formValidators.test.tsx
  src/Apps/Order/Utils/formValidators.tsx
Labels: Jira Synced, Version: Patch

#1923 Fixes "related auction" image overlapping with text on RAP
  src/Apps/__stories__/ArtworkApp.story.tsx
  src/Components/v2/AuctionCard.tsx
Labels: Jira Synced, Version: Patch

#1924 remove partner icon for artwork details if artwork is from benefit auction
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
  src/Apps/Artwork/Components/__stories__/ArtworkDetails.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkDetails.ts
  src/__generated__/ArtworkDetailsAboutTheWorkFromPartner_artwork.graphql.ts
  src/__generated__/ArtworkDetailsQuery.graphql.ts
  src/__generated__/ArtworkDetails_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarCommercialOfferOrderMutation.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#1925 Do not display partner name in banner for benefit auction artworks
  src/Apps/Artwork/Components/ArtworkBanner/__tests__/ArtworkBanner.test.tsx
  src/Apps/Artwork/Components/ArtworkBanner/index.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/__stories__/ArtworkBanner.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkBanner.ts
  src/__generated__/ArtworkBannerQuery.graphql.ts
  src/__generated__/ArtworkBanner_Test_Query.graphql.ts
  src/__generated__/ArtworkBanner_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#1888 Missing info error message
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitOrder.ts
  src/Apps/Order/Routes/__tests__/Review.test.tsx
Labels: Version: Patch

#1928 [WIP] Start on adding view in room to artwork page v2
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/__generated__/ArtworkActions_artwork.graphql.ts
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#1929 Pull `lastOffer` from `OrderOffer` instead of `Order`, due to deprecation
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/Reject/index.tsx
  src/__generated__/Accept_order.graphql.ts
  src/__generated__/Reject_order.graphql.ts
  src/__generated__/routes_AcceptQuery.graphql.ts
  src/__generated__/routes_RejectQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#1932 @damassi => [Collect] Re-add the color wheel filter
  package.json
  src/Apps/Collect/CollectApp.tsx
  src/Apps/Collect/Components/Base/CollectFilterContainer.tsx
  src/Apps/Collect/Components/Base/CollectRefetch.tsx
  src/Apps/Collect/Components/Filters/ColorFilter.tsx
  src/Apps/Collect/Components/Filters/FilterContainer.tsx
  src/Apps/Collect/FilterState.tsx
  src/Apps/Collect/__tests__/FilterState.test.tsx
  src/Apps/Collect/routes.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectApp_viewer.graphql.ts
  src/__generated__/CollectFilterContainer_viewer.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectRefetch_viewer.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  yarn.lock
Labels: Version: Patch

#1934 Migrate to palette price filter
  src/Apps/Collect/Components/Filters/PriceRangeFilter.tsx
  src/Components/Input.tsx
  src/Components/v2/PriceRange.tsx
Labels: Jira Synced, Version: Patch

#1936 Imageset props
  src/Components/Publishing/Sections/ImageSetPreview/ImageSetPreview.tsx
  src/Components/Publishing/Sections/ImageSetPreview/ImageSetPreviewClassic.tsx
  src/Components/Publishing/Typings.ts
Labels: Version: Patch

#1937 [Collect] Hide footer in Eigen #bug-bash
  src/Components/FrameWithRecentlyViewed.tsx
Labels: Jira Synced, Version: Patch

#1938 Add hook to artwork image for view in room
  src/Components/v2/Lightbox/Lightbox.tsx
Labels: Version: Patch

#1930 pass image url when calling viewInRoom mediator
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkActions.fixture.ts
  src/__generated__/ArtworkActions_artwork.graphql.ts
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Patch

#1940 Expose image width and height for view in room
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
Labels: Merge On Green, Version: Patch

#1941 [Bugfix] Guard against missing elements
  package.json
  src/Components/v2/Lightbox/Lightbox.tsx
  yarn.lock
Labels: Version: Patch

#1943 add tracking to view in room click
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/ArtworkActions_artwork.graphql.ts
  src/__generated__/ArtworkImageBrowserQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#1947 Fixes moment warning
  src/Components/v2/AuctionCard.tsx
Labels: Version: Patch

#1950 [Bugfix] Guard against missing images on /artwork/id
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkImageBrowser.test.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
Labels: Jira Synced, Version: Patch

#1953 Remove obsolete offer fields from "schema.graphql"
  data/schema.graphql
Labels: Version: Patch

#1901 Add ability to customize sign up form title
  src/Components/Authentication/FormSwitcher.tsx
  src/Components/Authentication/Mobile/SignUpForm.tsx
  src/Components/Authentication/Types.ts
  src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
Labels: Jira Synced, Version: Minor

#1954 Add separator to pagination component
  src/Components/v2/Pagination.tsx
Labels: Merge On Green, Version: Patch

#1939 Autofocus on first field in authentication forms
  src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
  src/Components/Authentication/Desktop/LoginForm.tsx
  src/Components/Authentication/Desktop/SignUpForm.tsx
  src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
  src/Components/Authentication/Mobile/LoginForm.tsx
  src/Components/Authentication/Mobile/SignUpForm.tsx
Labels: Jira Synced

#1956 Remove palette components
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromArtsy.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Collect/Components/Collection/Header/index.tsx
  src/Apps/Collections/Components/CollectionsGrid.tsx
  src/Apps/Collections/Components/__tests__/CollectionsGrid.test.tsx
  src/Apps/Collections/__tests__/CollectionsApp.test.tsx
  src/Apps/Order/Components/OrderStepper.tsx
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Apps/WorksForYou/WorksForYouArtistFeed.tsx
  src/Apps/WorksForYou/WorksForYouFeed.tsx
  src/Components/v2/ArtistBio.tsx
  src/Components/v2/CountdownTimer.tsx
  src/Components/v2/EntityHeader.tsx
  src/Components/v2/ReadMore.tsx
  src/Components/v2/Stepper.tsx
  src/Components/v2/__stories__/EntityHeader.story.tsx
  src/Components/v2/__stories__/ReadMore.story.tsx
  src/Components/v2/__stories__/Tabs.Stepper.story.tsx
  src/Components/v2/__tests__/ReadMore.test.tsx
  src/Components/v2/__tests__/Stepper.test.tsx
  src/Components/v2/index.tsx
Labels: Version: Major

#1951 Article titles have h1 headers
  src/Components/Publishing/Header/Layouts/ClassicHeader.tsx
  src/Components/Publishing/Header/Layouts/Components/FeatureInnerContent.tsx
  src/Components/Publishing/Header/Layouts/StandardHeader.tsx
  src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/ClassicHeader.test.tsx.snap
  src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/StandardHeader.test.tsx.snap
Labels: Version: Patch

#1948 Add size filters
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Collect/CollectApp.tsx
  src/Apps/Collect/Components/Base/CollectFilterContainer.tsx
  src/Apps/Collect/Components/Base/CollectRefetch.tsx
  src/Apps/Collect/Components/Filters/FilterContainer.tsx
  src/Apps/Collect/Components/Filters/PriceRangeFilter.tsx
  src/Apps/Collect/Components/Filters/SizeRangeFilters.tsx
  src/Apps/Collect/Components/Filters/WaysToBuyFilter.tsx
  src/Apps/Collect/Components/Filters/index.tsx
  src/Apps/Collect/FilterState.tsx
  src/Apps/Collect/__tests__/FilterState.test.tsx
  src/Apps/Collect/routes.tsx
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectApp_viewer.graphql.ts
  src/__generated__/CollectFilterContainer_viewer.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectRefetch_viewer.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#1959 [minor] Replace height_range/width_range with height/width for clarity
  src/Apps/Collect/CollectApp.tsx
  src/Apps/Collect/Components/Base/CollectFilterContainer.tsx
  src/Apps/Collect/Components/Base/CollectRefetch.tsx
  src/Apps/Collect/Components/Filters/SizeRangeFilters.tsx
  src/Apps/Collect/FilterState.tsx
  src/Apps/Collect/__tests__/FilterState.test.tsx
  src/Apps/Collect/routes.tsx
  src/__generated__/CollectAppTestQuery.graphql.ts
  src/__generated__/CollectAppTestWithMediumQuery.graphql.ts
  src/__generated__/CollectApp_viewer.graphql.ts
  src/__generated__/CollectFilterContainer_viewer.graphql.ts
  src/__generated__/CollectRefetchQuery.graphql.ts
  src/__generated__/CollectRefetch_viewer.graphql.ts
  src/__generated__/routes_CollectAppQuery.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Version: Patch

#1960 @mzikherman => [ColorFilter] Update positions for checkmark overlay
  src/Apps/Collect/Components/Filters/ColorFilter.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#1949 [Bugfix] Prevent apostrophes from line breaking tooltip links
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Fixtures/Articles.ts
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Sections/StyledText.tsx
  src/Components/Publishing/Sections/Text.tsx
  src/Components/Publishing/Sections/__tests__/Text.test.tsx
  src/Components/Publishing/Sections/__tests__/__snapshots__/SectionContainer.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
Labels: Jira Synced, Version: Patch

#1958 Adds text labels to ArtworkActions and conditionally renders them for mobile web
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkPopoutPanel.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkSharePanel.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__stories__/ArtworkActions.story.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/__tests__/ArtworkActions.test.tsx
Labels: Jira Synced, Version: Patch

#1961 Keep actions and image dots centered for mobile web as well
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
Labels: Version: Patch

#1899 Refactor tests
  package.json
  src/Apps/Order/Routes/__fixtures__/MutationResults/acceptOffer.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/buyerCounterOffer.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/initialOffer.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/rejectOffer.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderPayment.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/setOrderShipping.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitOfferOrder.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitOrder.ts
  src/Apps/Order/Routes/__fixtures__/MutationResults/submitPendingOffer.ts
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/Order/Routes/__tests__/Utils/OrderAppTestPage.tsx
  src/DevTools/MockRelayRenderer.tsx
  src/DevTools/MockRouter.tsx
  src/DevTools/RootTestPage.tsx
  src/DevTools/__tests__/createMockNetworkLayer.test.ts
  src/DevTools/__tests__/createTestEnv.test.tsx
  src/DevTools/createMockNetworkLayer/index.ts
  src/DevTools/createTestEnv.tsx
  src/DevTools/renderRelayTree.tsx
  src/__generated__/AcceptTestQuery.graphql.ts
  src/__generated__/CounterTestQuery.graphql.ts
  src/__generated__/OfferTestQuery.graphql.ts
  src/__generated__/PaymentTestQuery.graphql.ts
  src/__generated__/RejectTestQuery.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/ReviewTestQuery.graphql.ts
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/createMockNetworkLayerTestAliasPrecendenceQuery.graphql.ts
  src/__generated__/createMockNetworkLayerTestMutationResultsMutation.graphql.ts
  src/__generated__/createTestEnvCreditCardMutation.graphql.ts
  src/__generated__/createTestEnvOrderMutation.graphql.ts
  src/__generated__/createTestEnvQuery.graphql.ts
  src/__generated__/createTestEnv_artwork.graphql.ts
  tsconfig.json
  yarn.lock
Labels: Version: Patch

#1966 Make entire link clickable on artwork actions
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
Labels: Version: Patch

#1968 Fixture for ImageCollection data
  src/Components/Publishing/Fixtures/Components.ts
Labels: Merge On Green, Version: Patch

#1945 Add social sharing buttons on series pages
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Series/SeriesAbout.tsx
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
Labels: Jira Synced, Version: Patch

#1970 Fix SSR issues on /collect, grid images, tracking and h1 global tags
  src/Apps/Collect/Components/Filters/FilterContainer.tsx
  src/Apps/Collect/Components/Filters/__tests__/FilterContainer.test.tsx
  src/Artsy/Router/Components/Boot.tsx
  src/Components/Artwork/GridItem.tsx
  src/Components/Publishing/Header/Layouts/ClassicHeader.tsx
  src/Components/Publishing/Header/Layouts/Components/FeatureInnerContent.tsx
  src/Components/Publishing/Header/Layouts/StandardHeader.tsx
  src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/ClassicHeader.test.tsx.snap
  src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/StandardHeader.test.tsx.snap
  src/setup_jest.ts
Labels: Jira Synced, Version: Patch

#1974 Use shared auto config
  .autorc
  package.json
  yarn.lock
Labels: Version: Trivial
