Repository artsy/reaction, pull requests merged in 2019-06, with the labels that each got.

#2464 DISCO-1051/DISCO-946 - Adjustments to search input styling and behavior
  src/Components/Search/SearchBar.tsx
  src/Components/Search/SearchInputContainer.tsx
  src/Components/Search/Suggestions/SuggestionItem.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2466 DISCO-1021 - Bring user to top of page when advancing pagination
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
Labels: Jira Synced, Version: Patch

#2492 PLATFORM-1440 - Removes React-Flickity-Component from Carousel3
  package.json
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Components/v2/CarouselV3.tsx
Labels: Jira Synced, Version: Patch

#2497 Removes react-flickity-component
  package.json
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Components/Artist/ArtistCollectionsRail/ArtistCollectionEntity.tsx
  src/Components/Artist/ArtistCollectionsRail/ArtistCollectionsRail.tsx
  src/Components/Artist/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
  src/Components/v2/CarouselV2.tsx
  src/Components/v2/RecentlyViewed.tsx
  src/Components/v2/__stories__/CarouselV2.story.tsx
  yarn.lock
Labels: Merge On Green, Version: Patch

#2495 [NavBar] Fix search-on-enter, SSR query persistence, missing admin / CMS dropdown links
  .storybook/webpack.config.js
  src/Apps/Artwork/Components/ArtworkBanner/index.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkBanner.ts
  src/Artsy/SystemContext.tsx
  src/Components/NavBar/Menus/UserMenu.tsx
  src/Components/NavBar/Menus/__tests__/UserMenu.test.tsx
  src/Components/Search/SearchBar.tsx
  src/__generated__/ArtworkBannerQuery.graphql.ts
  src/__generated__/ArtworkBanner_Test_Query.graphql.ts
  src/__generated__/ArtworkBanner_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  typings/gravity.d.ts
  typings/sharify.d.ts
Labels: Jira Synced, Version: Patch

#2478 [Article] add GPT ads to featured article
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/Typings.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#2499 [QA] Miscellaneous app QA
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/MobileActionSheet.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Collect/Components/Filters/FilterContainer.tsx
  src/Apps/Collect/Components/Filters/SortFilter.tsx
  src/Apps/Collect/Components/Filters/WaysToBuyFilter.tsx
  src/Apps/Collect/Components/MobileActionSheet.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/FilterContainer.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/WaysToBuyFilter.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsMobileActionSheet.tsx
  src/Components/NavBar/NavItem.tsx
  src/Components/Search/SearchBar.tsx
Labels: Version: Patch

#2500 [NavBar] Fix instant page issue
  src/Components/NavBar/Menus/UserMenu.tsx
Labels: Version: Patch

#2504 Revert "[Article] add GPT ads to featured article"
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/Typings.ts
Labels: Version: Patch

#2502 Render artwork page OtherWorks section server-side
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextArtist.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextFair.tsx
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkContextPartnerShow.tsx
  src/Apps/Artwork/Components/OtherWorks/index.tsx
  src/__generated__/ArtworkContextArtistQuery.graphql.ts
  src/__generated__/ArtworkContextFairQuery.graphql.ts
  src/__generated__/ArtworkContextPartnerShowQuery.graphql.ts
  src/__generated__/OtherWorksQuery.graphql.ts
  src/__generated__/OtherWorks_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Minor

#2498 DISCO-1022 - Updates zero state copy
  src/Apps/Search/Components/ZeroState.tsx
  src/Apps/Search/FilterState.tsx
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/Routes/Artworks/Components/Filter/SearchResultsArtworkGrid.tsx
  src/Apps/Search/Routes/Artworks/SearchResultsArtworks.tsx
  src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/__tests__/FilterState.test.ts
Labels: Jira Synced

#2503 [Collections] do not render featured artist module when there are not featured artists
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Version: Patch

#2505 [NavBar] Address QA items
  src/Components/Input.tsx
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
  src/Components/NavBar/NotificationsBadge.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/__tests__/__snapshots__/Input.test.tsx.snap
Labels: Version: Patch

#2508 add a custom hook for accessing the SystemContext
  src/Artsy/SystemContext.tsx
  src/Components/Artist/ArtistCollectionsRail/index.tsx
Labels: Version: Patch

#2510 [NavBar] Add toggle test for menu position
  package.json
  src/Components/NavBar/Menus/MoreNavMenu.tsx
  src/Components/NavBar/NavBar.tsx
  yarn.lock
Labels: Version: Patch

#2514 Removes width from slide box element
  src/Components/Artist/ArtistCollectionsRail/ArtistCollectionEntity.tsx
Labels: Version: Patch

#2517 [Lib] Ensure tests run against linked packages and upgrade jest@24.8.0
  .circleci/config.yml
  package.json
  src/Components/Artist/MarketInsights/__tests__/__snapshots__/MarketInsights.test.tsx.snap
  src/Components/Publishing/Byline/__tests__/__snapshots__/Byline.test.tsx.snap
  src/Components/Publishing/Byline/__tests__/__snapshots__/Date.test.tsx.snap
  src/Components/Publishing/Byline/__tests__/__snapshots__/NewsByline.test.tsx.snap
  src/Components/Publishing/Byline/__tests__/__snapshots__/ShareDate.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/StandardHeader.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCard.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCards.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/Block.test.tsx.snap
  src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
  src/Components/Publishing/RelatedArticles/Panel/__tests__/__snapshots__/RelatedArticlesPanel.test.tsx.snap
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Caption.test.tsx.snap
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/FullscreenViewer.test.tsx.snap
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Slide.test.tsx.snap
  src/Components/Publishing/Sections/ImageSetPreview/__tests__/__snapshots__/ImageSetPreview.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Artwork.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/ArtworkCaption.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Authors.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/VerticalOrSeriesTitle.test.tsx.snap
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesTitle.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoCover.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoInfoBlock.test.tsx.snap
  src/Components/__tests__/__snapshots__/Artwork.test.tsx.snap
  src/Components/__tests__/__snapshots__/Input.test.tsx.snap
  src/Components/__tests__/__snapshots__/PasswordInput.test.tsx.snap
  src/Components/v2/__tests__/CountdownTimer.test.tsx
  yarn.lock
Labels: Version: Trivial

#2506 [Article] Add GAM Hosted Ads to Featured Articles
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/Fixtures/Articles.ts
  src/Components/Publishing/Layouts/FeatureLayout.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
  src/Components/Publishing/Typings.ts
Labels: Version: Patch

#2524 Configure jest caching location
  .circleci/config.yml
  package.json
  src/Apps/Artist/Components/__tests__/NavigationTabs.test.tsx
  src/Components/Artist/MarketInsights/__tests__/__snapshots__/MarketInsights.test.tsx.snap
  src/Components/Publishing/Byline/__tests__/__snapshots__/Byline.test.tsx.snap
  src/Components/Publishing/Byline/__tests__/__snapshots__/Date.test.tsx.snap
  src/Components/Publishing/Byline/__tests__/__snapshots__/NewsByline.test.tsx.snap
  src/Components/Publishing/Byline/__tests__/__snapshots__/ShareDate.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/StandardHeader.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCard.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCards.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/Block.test.tsx.snap
  src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
  src/Components/Publishing/RelatedArticles/Panel/__tests__/__snapshots__/RelatedArticlesPanel.test.tsx.snap
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Caption.test.tsx.snap
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/FullscreenViewer.test.tsx.snap
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Slide.test.tsx.snap
  src/Components/Publishing/Sections/ImageSetPreview/__tests__/__snapshots__/ImageSetPreview.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Artwork.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/ArtworkCaption.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Authors.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/VerticalOrSeriesTitle.test.tsx.snap
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesTitle.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoCover.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoInfoBlock.test.tsx.snap
  src/Components/__tests__/__snapshots__/Artwork.test.tsx.snap
  src/Components/__tests__/__snapshots__/Input.test.tsx.snap
  src/Components/__tests__/__snapshots__/PasswordInput.test.tsx.snap
  src/Components/v2/__tests__/CountdownTimer.test.tsx
Labels: Merge On Green

#2525 Prepare Reaction for Palette luxon updates
  package.json
  src/Components/WithCurrentTime.tsx
  src/Components/v2/__tests__/CountdownTimer.test.tsx
  yarn.lock
Labels: Merge On Green, Version: Patch

#2526 DISCO-1070 - Better handling of long artist names/origins
  src/Components/v2/ArtistCard.tsx
Labels: Jira Synced, Version: Patch

#2515 DISCO-1067 Add a "show more" button to Artwork/related artists
  src/Apps/Artist/Routes/Overview/Components/ArtistRecommendations.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
  src/Apps/Artwork/Components/__tests__/ArtworkRelatedArtists.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkRelatedArtists.fixture.ts
  src/__generated__/ArtworkRelatedArtistsPaginationQuery.graphql.ts
  src/__generated__/ArtworkRelatedArtists_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Jira Synced, Version: Minor

#2528 [ArtistCard] Update comments to give hints about proper truncation methods
  src/Components/Truncator.tsx
  src/Components/v2/ArtistCard.tsx
Labels: Merge On Green, Version: Trivial

#2529 Moves CarouselV3 to Carousel
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Components/Artist/ArtistCollectionsRail/ArtistCollectionsRail.tsx
  src/Components/Artist/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
  src/Components/v2/Carousel.tsx
  src/Components/v2/CarouselV3.tsx
  src/Components/v2/RecentlyViewed.tsx
  src/Components/v2/__stories__/Carousel.story.tsx
  src/Components/v2/__stories__/CarouselV3.story.tsx
  src/Components/v2/__tests__/Carousel.test.tsx
Labels: Merge On Green

#2476 Removes Moment-Timezone and introduces Luxon
  package.json
  src/Apps/Artwork/Components/__stories__/OtherAuctions.story.tsx
  src/Components/Publishing/Byline/__tests__/ClassicByline.test.tsx
  src/Components/Publishing/Byline/__tests__/Date.test.tsx
  src/Components/Publishing/Byline/__tests__/__snapshots__/Byline.test.tsx.snap
  src/Components/Publishing/Byline/__tests__/__snapshots__/ClassicByline.test.tsx.snap
  src/Components/Publishing/Byline/__tests__/__snapshots__/Date.test.tsx.snap
  src/Components/Publishing/Byline/__tests__/__snapshots__/NewsByline.test.tsx.snap
  src/Components/Publishing/Byline/__tests__/__snapshots__/ShareDate.test.tsx.snap
  src/Components/Publishing/Constants.ts
  src/Components/Publishing/Display/Canvas/index.tsx
  src/Components/Publishing/Display/__tests__/DisplayCanvas.test.tsx
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Header/Layouts/Components/__tests__/FeatureInnerContent.test.tsx
  src/Components/Publishing/Header/Layouts/__tests__/ClassicHeader.test.tsx
  src/Components/Publishing/Header/Layouts/__tests__/StandardHeader.test.tsx
  src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/ClassicHeader.test.tsx.snap
  src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/StandardHeader.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/ArticleCard.test.tsx
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
  src/Components/v2/AuctionCard.tsx
  src/Components/v2/AuctionTimer.tsx
  src/Components/v2/CountdownTimer.tsx
  src/Components/v2/Timer.tsx
  src/Components/v2/__stories__/AuctionTimer.story.tsx
  src/Components/v2/__stories__/Timer.story.tsx
  src/Components/v2/__tests__/AuctionCard.test.tsx
  src/Utils/getCurrentTimeAsIsoString.ts
  yarn.lock
Labels: Version: Minor

#2530 [NavBar] Add animation to dropdown
  package.json
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
  yarn.lock
Labels: Merge On Green, Version: Patch

#2532 Revert "[NavBar] Add animation to dropdown"
  package.json
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
  yarn.lock
Labels: Merge On Green, Version: Patch

#2536 Restore NavBar dropdown animations
  package.json
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
  yarn.lock
Labels: Version: Patch

#2538 Test CI date fix
  src/Components/Publishing/News/__tests__/NewsDateHeader.test.tsx
Labels: Version: Patch

#2539 Bump palette
  package.json
  yarn.lock
Labels: Version: Patch

#2540 [Lib] Remove babel-plugin-rename-import
  .babelrc
  package.json
  yarn.lock
Labels: Version: Patch

#2535 Removes jsx and js from test regex
  package.json
Labels: Version: Trivial

#2542 DISCO-1031 - Don't render related artworks without artworks to display
  src/Apps/Artwork/Components/OtherWorks/ArtworkContexts/ArtworkGrids/RelatedWorksArtworkGrid.tsx
Labels: Jira Synced, Version: Patch

#2543 [NavBar] Adjust animation settings
  src/Components/NavBar/NavItem.tsx
Labels: Version: Patch

#2546 featured artist module follow up
  src/Apps/Collect/Components/Collection/Header/__tests__/Header.test.tsx
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Version: Patch

#2518 [CollectionFeatureArtists] only use aggregate artists when there is not explicit artist_ids
  src/Apps/Collect/Components/Collection/Header/__tests__/Header.test.ts
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Jira Synced, Version: Patch

#2527 Update logic to handle hiding/displaying ads
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Typings.ts
Labels: Jira Synced, Version: Patch

#2549 Extract action sheet management from Artist/state into Artist/ArtworkFilter
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtworkFilter/index.tsx
  src/Apps/Artist/Routes/Overview/state.ts
  src/Apps/__tests__/Fixtures/Artist/Components/ArtworkFilter.tsx
Labels: Version: Patch

#2550 Add more context to mock relay errors (the operation name)
  src/DevTools/__tests__/createMockNetworkLayer.test.ts
  src/DevTools/createMockNetworkLayer/index.ts
Labels: Version: Patch

#2554 Fixes date regression bug in News Header
  src/Components/Publishing/News/NewsPanel.tsx
  src/Components/Publishing/News/__tests__/NewsPanel.test.tsx
Labels: Jira Synced, Version: Patch

#2555 GROW-1310 - Updates date to isostring for luxon consumption
  src/Components/Publishing/Byline/DateSource.tsx
Labels: Jira Synced, Version: Patch

#2559 [Bugfix] Fix navBar zIndex #trivial
  src/Components/NavBar/NavBar.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2489 [Collections] Related collections rail
  src/Apps/Collect/CollectionApp.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
  src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionEntity.test.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
  src/__generated__/CollectionAppTestQuery.graphql.ts
  src/__generated__/CollectionApp_collection.graphql.ts
  src/__generated__/RelatedCollectionEntity_collection.graphql.ts
  src/__generated__/RelatedCollectionsRail_collections.graphql.ts
  src/__generated__/routes_MarketingCollectionAppQuery.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#2551 Require targeting data prop on all display ad components
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
  src/Components/Publishing/Display/__tests__/NewDisplayCanvas.test.tsx
  src/Components/Publishing/Display/__tests__/NewDisplayPanel.test.tsx
  src/Components/Publishing/Fixtures/Components.ts
  src/Components/Publishing/Layouts/FeatureLayout.tsx
  src/Components/Publishing/Layouts/SeriesLayout.tsx
  src/Components/Publishing/Layouts/VideoLayout.tsx
  src/Components/Publishing/Layouts/__tests__/NewsLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Layouts/__tests__/SeriesLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Layouts/__tests__/VideoLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
  src/Components/Publishing/Typings.ts
  src/Components/Publishing/utils/Sponsored.ts
Labels: Jira Synced, Version: Patch

#2563 remove a/b test tracking logic
  src/Apps/Artist/Routes/Overview/index.tsx
Labels: Jira Synced, Version: Patch

#2567 fix price format in buynow click events
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Labels: Version: Patch

#2569 fix event tracking for price. #minor
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Labels: Version: Patch

#2571 PURCHASE-1155: update status expiration message
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/__generated__/StatusQuery.graphql.ts
  src/__generated__/Status_order.graphql.ts
  src/__generated__/routes_StatusQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#2564 featured artists now always positioned below summary
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Jira Synced, Version: Patch

#2572 [ArtworkFilter Refactor] Extract and consolidate
  src/Apps/Search/Routes/Artworks/Components/Filter/Filters/index.tsx
  src/Artsy/Analytics/Schema/index.ts
  src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid2.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterZeroState.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/ColorFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/MediumFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/SizeRangeFilters.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/TimePeriodFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/WaysToBuyFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/index.tsx
  src/Components/v2/ArtworkFilter/README.md
  src/Components/v2/ArtworkFilter/Utils/hasFilters.tsx
  src/Components/v2/ArtworkFilter/Utils/isDefaultFilter.tsx
  src/Components/v2/ArtworkFilter/Utils/rangeToTuple.tsx
  src/Components/v2/ArtworkFilter/Utils/urlFragmentFromState.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/Components/v2/Pagination.tsx
  src/Components/v2/__stories__/ArtworkFilter.story.tsx
  src/Utils/Hooks/usePrevious.ts
  src/__generated__/ArtworkFilterArtworkGrid2Query.graphql.ts
  src/__generated__/ArtworkFilterArtworkGrid2_filtered_artworks.graphql.ts
  src/__generated__/ArtworkFilterQuery.graphql.ts
  src/__generated__/ArtworkFilter_viewer.graphql.ts
  tslint.json
Labels: Merge On Green, Version: Patch

#2574 [RelatedCollectionsRail] fix related collections carousel
  src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
  src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionEntity.test.tsx
Labels: Jira Synced, Version: Patch

#2576 [ArtistRecommendations] Fix carousel alignment
  src/Components/Artist/ArtistCollectionsRail/ArtistCollectionsRail.tsx
  src/Components/Artist/ArtistCollectionsRail/index.tsx
Labels: Version: Patch

#2579 [FeaturedArtistModule] refactor featured artist module to truncate on both desktop and mobile
  src/Apps/Collect/Components/Collection/Header/index.tsx
Labels: Jira Synced, Version: Patch

#2575 Deprecate Ads on Standard Articles
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Layouts/Components/CanvasFooter.tsx
  src/Components/Publishing/Layouts/Components/__tests__/CanvasFooter.test.tsx
  src/Components/Publishing/Layouts/FeatureLayout.tsx
  src/Components/Publishing/Layouts/NewsLayout.tsx
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/Layouts/__tests__/FeatureLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/NewsLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayoutAdsEnabled.test.tsx
Labels: Jira Synced, Version: Patch

#2581 Bring padding on mobile leaderboard ads up to spec
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/DisplayTargeting.tsx
  src/Components/Publishing/Display/NewDisplayCanvas.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayCanvas.test.tsx.snap
  src/Components/Publishing/Display/__tests__/__snapshots__/NewDisplayPanel.test.tsx.snap
  src/Components/Publishing/Layouts/NewsLayout.tsx
  src/Components/Publishing/Layouts/SeriesLayout.tsx
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/Layouts/VideoLayout.tsx
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayoutAdsEnabled.test.tsx.snap
  src/Components/Publishing/Sections/Sections.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#2585 Return myLastOffer so we can correctly redirect
  src/Apps/Order/Routes/Respond/index.tsx
  src/__generated__/RespondCounterOfferMutation.graphql.ts
  src/__generated__/RespondTestQuery.graphql.ts
  src/__generated__/Respond_order.graphql.ts
  src/__generated__/routes_RespondQuery.graphql.ts
Labels: Merge On Green, Version: Patch

#2582 Corrects standard article mobile ad dimensions
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
  src/Components/Publishing/Typings.ts
Labels: Jira Synced, Version: Patch

#2583 Corrects ad dimensions in mobile ads on feature articles
  src/Components/Publishing/Fixtures/Articles.ts
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
  src/Components/Publishing/Typings.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#2586 Updates mobile ad dimensions on news articles
  src/Components/Publishing/Layouts/__tests__/NewsLayoutAdsEnabled.test.tsx
  src/Components/Publishing/Typings.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#2588 Handle Flicker Affect When Ad Server Content is Empty
  src/Components/Publishing/Display/DisplayAd.tsx
Labels: Version: Patch
