Repository artsy/reaction, pull requests merged in 2019-12, with the labels that each got.

#3037 PURCHASE-1649: Adds data-test attribute to the sale message on artwork view
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Labels: Merge On Green, Version: Patch

#3039 Handle missing partner on artwork page
  src/Apps/Artwork/Components/ArtworkBanner/index.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
Labels: Version: Patch

#3036 Remove dots from the artist images
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/ArtistHeader.tsx
Labels: Jira Synced, Version: Patch

#3038 Modifies waypoint method call
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
Labels: Jira Synced, Version: Patch

#3042 Maintain proper aspect ratio for image on confirm bid
  src/Apps/Auction/Components/LotInfo.tsx
  src/Apps/Auction/Routes/__stories__/ConfirmBid.story.tsx
Labels: Jira Synced, Version: Patch

#3044 Bring back arrows removed by #3036
  src/Apps/Artist/Components/ArtistHeader.tsx
Labels: Version: Patch

#3048 [GROW-1681] adds analytics events to the navbar notification menu
  src/Artsy/Analytics/Schema/Values.ts
  src/Components/NavBar/Menus/NotificationsMenu.tsx
  src/Components/NavBar/Menus/__tests__/NotificationsMenu.test.tsx
Labels: Jira Synced, Version: Patch

#3049 Bump version of lazy-load lib to fix SSR issue
  package.json
  yarn.lock
Labels: Merge On Green, Version: Patch

#3047 Add lazy loading to collections rail
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Components/RelatedCollectionsRail/RelatedCollectionEntity.tsx
  src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
Labels: Version: Patch

#3046 Restore Artworks link to mobile nav
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
Labels: Jira Synced, Version: Patch

#3053 Bump down threshold for lazy-loading on artist artwork grid
  src/Components/v2/ArtworkFilter/ArtworkFilterArtworkGrid2.tsx
Labels: Merge On Green, Version: Patch

#3050 [GROW-1633] remove duplicate hover analytics event
  src/Components/NavBar/NotificationsBadge.tsx
Labels: Jira Synced, Version: Patch

#3055 [GROW-1683] clone the NavBar component for navigation a/b test
  src/Components/NavBarTest/Menus/MobileNavMenu.tsx
  src/Components/NavBarTest/Menus/MoreNavMenu.tsx
  src/Components/NavBarTest/Menus/NotificationsMenu.tsx
  src/Components/NavBarTest/Menus/UserMenu.tsx
  src/Components/NavBarTest/Menus/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBarTest/Menus/__tests__/MoreNavMenu.test.tsx
  src/Components/NavBarTest/Menus/__tests__/NotificationsMenu.test.tsx
  src/Components/NavBarTest/Menus/__tests__/UserMenu.test.tsx
  src/Components/NavBarTest/Menus/index.tsx
  src/Components/NavBarTest/NavBar.tsx
  src/Components/NavBarTest/NavItem.tsx
  src/Components/NavBarTest/NotificationsBadge.tsx
  src/Components/NavBarTest/Utils/__tests__/authentication.test.ts
  src/Components/NavBarTest/Utils/authentication.ts
  src/Components/NavBarTest/__tests__/NavBar.test.tsx
  src/Components/NavBarTest/__tests__/NavBarTracking.test.tsx
  src/Components/NavBarTest/__tests__/NavItem.test.tsx
  src/Components/NavBarTest/__tests__/NotificationsBadge.test.tsx
  src/Components/NavBarTest/index.tsx
  src/__generated__/NotificationsMenuTestQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#3052 Updates to display ad tracking
  src/Components/Publishing/Display/DisplayAd.tsx
  src/Components/Publishing/Display/__tests__/DisplayAd.test.tsx
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
Labels: Version: Patch

#3057 [GROW-1633] fix double hover event in new navbar
  src/Components/NavBarTest/NotificationsBadge.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#3051 Coverage reporting
  .circleci/config.yml
  package.json
Labels: Jira Synced, Version: Patch

#3043 Adds full page AppShell component w/ routing for supported Reaction apps
  .storybook/preview-head.html
  .storybook/webpack.config.js
  package.json
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionEntity.tsx
  src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionEntity.test.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/routes.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/Register/index.tsx
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/Collect2/Routes/Collections/index.tsx
  src/Apps/Components/AppShell.tsx
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/Counter/index.tsx
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/__stories__/AppShell.story.tsx
  src/Apps/__stories__/Apps.story.tsx
  src/Apps/getAppRoutes.tsx
  src/Artsy/Analytics/index.ts
  src/Artsy/Analytics/trackPageView.ts
  src/Artsy/Analytics/trackPageViewWrapper.tsx
  src/Artsy/Router/Utils/RenderStatus.tsx
  src/Artsy/Router/__stories__/Router.story.tsx
  src/Artsy/Router/__tests__/buildClientApp.test.tsx
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Artsy/Router/makeAppRoutes.tsx
  src/Artsy/SystemContext.tsx
  src/Artsy/__tests__/SystemContext.test.tsx
  src/Components/ArtworkGrid/ArtworkGridEmptyState.tsx
  src/Components/ArtworkGrid/__tests__/ArtworkGrid.test.tsx
  src/Components/ErrorBoundary.tsx
  src/Components/FrameWithRecentlyViewed.tsx
  src/Components/Search/SearchBar.tsx
  src/Components/v2/ArtworkFilter/Utils/urlBuilder.tsx
  src/Components/v2/Carousel.tsx
  src/Utils/catchLinks.tsx
  src/Utils/getENV.tsx
  typings/sharify.d.ts
Labels: Version: Major

#3059 Add coverage badge
  README.md
Labels: Merge On Green, Version: Trivial

#3056 Update "artist summary" on artist page
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Components/ArtistIndicator.tsx
  src/Apps/Artist/Components/__tests__/ArtistHeader.test.tsx
  src/Apps/__stories__/ArtistApp.story.tsx
  src/Apps/__tests__/Fixtures/Artist/Components/ArtistHeader.tsx
  src/Components/v2/ArtistMarketInsights.tsx
  src/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/__generated__/ArtistHeader_artist.graphql.ts
  src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Labels: Version: Patch

#3060 Remove @alloy from point people
  README.md
Labels: Merge On Green, Version: Trivial

#3061 Margin fix for Artist Header
  src/Apps/Artist/Components/ArtistHeader.tsx
Labels: Merge On Green, Version: Patch

#3063 Fix scrolling issue after modal is closed
  src/Components/Modal/ModalWrapper.tsx
Labels: Version: Patch

#3062 [GROW-1698] Fix whitespace in global nav
  src/Components/NavBar/NavBar.tsx
Labels: Version: Patch

#3064 Remove linking artifact
  2
Labels: Version: Patch

#3066 @mzikherman => [CatchLinks] Dont attempt to handle empty anchor tags
  src/Utils/catchLinks.tsx
Labels: Merge On Green, Version: Patch

#3065 PURCHASE-1700: Artist Page Tweaks
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Components/ArtistIndicator.tsx
  src/Apps/Artist/Components/__tests__/ArtistHeader.test.tsx
  src/Components/v2/SelectedCareerAchievements.tsx
Labels: Jira Synced, Version: Patch

#3067 @joeyAghion => [Analytics] Fire AB test events for client side routing
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/Collect2/Routes/Collections/__tests__/CollectionsApp.test.tsx
  src/Apps/Collect2/Routes/Collections/index.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/__tests__/SearchApp.test.tsx
  src/Components/Search/SearchBar.tsx
  typings/sharify.d.ts
Labels: Version: Patch

#3069 @joeyAghion => [CCPA] Initial start for CCPA modals
  data/schema.graphql
  package.json
  src/Components/v2/CCPARequest.tsx
  src/Components/v2/__stories__/CCPARequest.story.tsx
  src/__generated__/ArtworkBannerQuery.graphql.ts
  src/__generated__/ArtworkBanner_Test_Query.graphql.ts
  src/__generated__/CCPARequestMutation.graphql.ts
  src/__generated__/OtherWorksQuery.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
  typings/gravity.d.ts
  yarn.lock
Labels: Version: Patch

#3072 @mzikherman => [CCPARequest] Proper cta styling for Force integration
  src/Components/v2/CCPARequest.tsx
Labels: Version: Patch

#3070 [AUCT-812] Fix link in buy now benefit auctions to link to sale, not partner
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarPartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarPartnerInfo.test.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarPartnerInfo.ts
  src/__generated__/ArtworkSidebarPartnerInfo_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarPartnerInfo_artwork.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebarStoryQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Merge On Green, Version: Patch

#3074 Remove showing follower numbers twice on mobile
  src/Apps/Artist/Components/ArtistHeader.tsx
Labels: Merge On Green, Version: Patch
