Repository artsy/reaction, pull requests merged in 2020-08, with the labels that each got.

#3617 deprecate Clicked article impression event
  src/Components/Publishing/Sections/ViewFullscreen.tsx
Labels: Version: Minor

#3618 Bump yarn orb
  .circleci/config.yml
Labels: Merge On Green, Version: Minor

#3621 [HOLD] Upgrade relay
  package.json
  patches/found+0.5.5.patch
  patches/relay-compiler+9.1.0.patch
  patches/relay-runtime+9.1.0.patch
  src/Artsy/Router/RenderStatus.tsx
  src/Artsy/Router/Route.tsx
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Components/FollowArtistPopover/index.tsx
  src/Components/Publishing/ToolTip/TooltipsDataLoader.tsx
  src/DevTools/MockRelayRenderer.tsx
  src/DevTools/__tests__/MockRelayRendererFixtures.tsx
  src/DevTools/__tests__/createMockNetworkLayer.test.ts
  src/__generated__/ArtistToolTip_artist.graphql.ts
  src/__generated__/FollowArtistButtonMutation.graphql.ts
  src/__generated__/FollowArtistButton_artist.graphql.ts
  src/__generated__/FollowArtistPopoverQuery.graphql.ts
  src/__generated__/FollowArtistPopoverRowMutation.graphql.ts
  src/__generated__/FollowArtistPopoverRow_artist.graphql.ts
  src/__generated__/FollowArtistPopover_Test_Query.graphql.ts
  src/__generated__/FollowArtistPopover_artist.graphql.ts
  src/__generated__/FollowGeneButtonMutation.graphql.ts
  src/__generated__/FollowGeneButton_gene.graphql.ts
  src/__generated__/GeneToolTip_gene.graphql.ts
  src/__generated__/MarketDataSummary_artist.graphql.ts
  src/__generated__/MockRelayRendererFixturesArtistQuery.graphql.ts
  src/__generated__/MockRelayRendererFixturesBadQuery.graphql.ts
  src/__generated__/MockRelayRendererFixturesQuery.graphql.ts
  src/__generated__/MockRelayRendererFixtures_artist.graphql.ts
  src/__generated__/MockRelayRendererFixtures_artwork.graphql.ts
  src/__generated__/MockRelayRendererFixtures_artworkMetadata.graphql.ts
  src/__generated__/RouterQuery.graphql.ts
  src/__generated__/TooltipsDataLoaderQuery.graphql.ts
  src/__generated__/buildClientAppTestQuery.graphql.ts
  src/__generated__/buildServerAppTestQuery.graphql.ts
  src/__generated__/createMockNetworkLayerTestAliasPrecendenceQuery.graphql.ts
  src/__generated__/createMockNetworkLayerTestAliasQuery.graphql.ts
  src/__generated__/createMockNetworkLayerTestMutationResultsMutation.graphql.ts
  src/__generated__/createMockNetworkLayerTestQuery.graphql.ts
  src/__generated__/createTestEnvCreditCardMutation.graphql.ts
  src/__generated__/createTestEnvOrderMutation.graphql.ts
  src/__generated__/createTestEnvQuery.graphql.ts
  src/__generated__/createTestEnv_artwork.graphql.ts
  src/__generated__/timeQuery.graphql.ts
  yarn.lock
Labels: Version: Major, canary

#3622 Upgrades various dependencies
  package.json
  src/Assets/Theme.ts
  src/Components/Publishing/Display/__tests__/__snapshots__/DisplayAd.test.tsx.snap
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/ClassicHeader.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  src/Components/Publishing/News/__tests__/__snapshots__/NewsHeadline.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCard.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCards.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/Block.test.tsx.snap
  src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
  src/Components/Publishing/Sections/ImageSetPreview/__tests__/__snapshots__/ImageSetPreview.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Authors.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoCover.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoInfoBlock.test.tsx.snap
  src/__stories__/config.js
  yarn.lock
Labels: Version: Minor

#3624 Bugfixes for classic layouts
  src/Components/Publishing/Layouts/ClassicLayout.tsx
  src/Components/Publishing/Sections/ArtworkCaption.tsx
  src/Components/Publishing/Sections/__tests__/ArtworkCaption.test.tsx
Labels: Version: Minor, canary

#3625 [FX-2184] Updates captions
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/NewsLayout.test.tsx.snap
  src/Components/Publishing/Sections/ArtworkCaption.tsx
  src/Components/Publishing/Sections/Caption.tsx
  src/Components/Publishing/Sections/FullscreenViewer/ArtworkCaption.tsx
  src/Components/Publishing/Sections/FullscreenViewer/Caption.tsx
  src/Components/Publishing/Sections/FullscreenViewer/FullscreenViewer.tsx
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/Caption.test.tsx
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/FullscreenViewer.test.tsx
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Caption.test.tsx.snap
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/FullscreenViewer.test.tsx.snap
  src/Components/Publishing/Sections/FullscreenViewer/__tests__/__snapshots__/Slide.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Artwork.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/ArtworkCaption.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Caption.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Image.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Video.test.tsx.snap
Labels: Version: Minor

#3628 Deprecate editorial email signup
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/Email/EmailPanel.tsx
  src/Components/Publishing/Email/InstantArticleEmailSignup.tsx
  src/Components/Publishing/Email/__tests__/EmailPanel.test.tsx
  src/Components/Publishing/Email/__tests__/InstantArticleEmailSignup.test.tsx
  src/Components/Publishing/Email/__tests__/__snapshots__/EmailPanel.test.tsx.snap
  src/Components/Publishing/Email/__tests__/__snapshots__/InstantArticleEmailSignup.test.tsx.snap
  src/Components/Publishing/Layouts/Components/Sidebar.tsx
  src/Components/Publishing/Layouts/Components/__tests__/Sidebar.test.tsx
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/__stories__/Email.story.tsx
  src/Components/Publishing/index.tsx
Labels: Version: Minor

#3631 Avoids passing width/height to captions
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
  src/Components/Publishing/Sections/Artwork.tsx
  src/Components/Publishing/Sections/__tests__/__snapshots__/Artwork.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/ImageCollection.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
Labels: Version: Patch
