Repository artsy/reaction, pull requests merged in 2020-01, with the labels that each got.

#3076 @joeyAghion => [Analytics] Correctly trigger pageviews using componentDidUpdate
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/Collect2/Routes/Collections/index.tsx
  src/Apps/Search/SearchApp.tsx
  src/Artsy/Analytics/trackPageViewWrapper.tsx
  src/Components/Search/SearchBar.tsx
  typings/sharify.d.ts
Labels: Version: Patch

#3077 Add "no-switch-case-fall-through" tslint rule
  src/Apps/Collect2/Routes/Collect/Components/CollectMediumMetadata.ts
  tslint.json
Labels: Version: Patch

#3078 Update `react-lazy-load-image-component` version
  package.json
  yarn.lock
Labels: Merge On Green, Version: Patch

#3081 @pepopowitz => [RouterLink] Tweak check to decide whether to route
  src/Artsy/Router/RouterLink.tsx
  src/Artsy/Router/__tests__/RouterLink.test.tsx
Labels: Version: Patch

#3083 Prevent right click on auction results images
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionDetailsModal.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
Labels: Merge On Green, Version: Patch

#3080 Fix artwork grid preloading too many images
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/Components/ArtworkGrid/__tests__/ArtworkGrid.test.tsx
Labels: Version: Patch

#3082 [GROW-1725] Fix global nav bar spacing
  src/Components/NavBar/NavBar.tsx
  src/Components/__stories__/NavBar.story.tsx
Labels: Version: Patch

#3084 Remove react-responsive-media and add fresnel
  package.json
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/Nav/__tests__/__snapshots__/Nav.test.tsx.snap
  src/Components/Publishing/Sections/ImageSetPreview/__tests__/__snapshots__/ImageSetPreview.test.tsx.snap
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/Series/__tests__/__snapshots__/SeriesAbout.test.tsx.snap
  src/Components/Publishing/Video/__tests__/__snapshots__/VideoAbout.test.tsx.snap
  src/Utils/Responsive/DeprecatedResponsive.tsx
  src/Utils/Responsive/index.tsx
  yarn.lock
Labels: Version: Patch

#3085 Only render one breakpoint for mobile googlebot
  src/Artsy/Router/Utils/matchingMediaQueriesForUserAgent.ts
Labels: Version: Patch

#3086 @damassi => [PageView Tracking] Correct for over-tracking on tabbed routes
  src/Apps/Artist/Components/NavigationTabs.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Artsy/Analytics/trackPageView.ts
  src/Artsy/Analytics/trackPageViewWrapper.tsx
  src/Artsy/Router/RouterLink.tsx
  src/Artsy/Router/__tests__/RouterLink.test.tsx
Labels: Version: Patch

#3007 Grow 1378 Add AggregateOffer schema for Collections pages
  src/Apps/Collect2/Components/SeoProductsForCollections.tsx
  src/Apps/Collect2/Components/__tests__/SeoProductsForCollections.test.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/__generated__/CollectionRefetch2Query.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
  src/__generated__/SeoProductsForCollections_ascending_artworks.graphql.ts
  src/__generated__/SeoProductsForCollections_descending_artworks.graphql.ts
Labels: Jira Synced, Version: Patch

#3089 Add `data-test` attribute to Order code so we can use it in integrity
  src/Apps/Order/Routes/Status/index.tsx
Labels: Version: Patch

#3090 Reset pagination on artwork filter updates
  src/Components/v2/ArtworkFilter/ArtworkFilterContext.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterContext.test.tsx
Labels: Version: Patch

#3091 @damassi => [PageView Tracking] Ensure pageviews are counted for navigation in the same page type
  src/Artsy/Router/makeAppRoutes.tsx
Labels: Version: Patch

#3094 Fix spacing issue in follow button on related artists component
  src/Components/FollowButton/Button.tsx
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/v2/ArtistCard.tsx
Labels: Version: Patch

#3097 Wrap main page header in header tags
  src/Components/NavBar/NavBar.tsx
Labels: Version: Patch

#3095 MX-104 - Fix double capitalized letters in iOS inputs
  src/Apps/Order/Components/AddressForm.tsx
Labels: Jira Synced, Version: Patch

#3096 My purchases #hackaton2020
  data/schema.graphql
  src/Apps/Purchase/Components/PurchaseHistory.tsx
  src/Apps/Purchase/PurchaseApp.tsx
  src/Apps/Purchase/__tests__/PurchaseApp.test.tsx
  src/Apps/Purchase/routes.tsx
  src/Apps/__stories__/PurchaseApp.story.tsx
  src/Components/NavBar/Menus/UserMenu.tsx
  src/Components/NavBar/Menus/__tests__/UserMenu.test.tsx
  src/__generated__/PurchaseAppTestQuery.graphql.ts
  src/__generated__/PurchaseApp_orders.graphql.ts
  src/__generated__/PurchaseHistory_orders.graphql.ts
  src/__generated__/RejectOfferMutation.graphql.ts
  src/__generated__/ShippingOrderAddressUpdateMutation.graphql.ts
  src/__generated__/routes_PurchaseQuery.graphql.ts
Labels: Version: Minor

#3100 Removes FOSSA badge. #trivial
  README.md
Labels: Merge On Green

#3101 Add `data-test` tags to offer response radio btns
  src/Apps/Order/Routes/Respond/index.tsx
Labels: Merge On Green, Version: Patch

#3102 Fix double image load issue by updating lazy load library
  package.json
  yarn.lock
Labels: Merge On Green, Version: Patch

#3092 @joeyAghion => [Client Side Routing] Reenable AB test
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/Collect2/Routes/Collections/index.tsx
  src/Apps/Search/SearchApp.tsx
  src/Components/Search/SearchBar.tsx
  typings/sharify.d.ts
Labels: Version: Patch

#3103 Add cypress test attrs for artwork grid
  src/Components/Artwork/GridItem.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
Labels: Version: Patch

#3105 @joeyAghion => [Analytics] More explicitly track AB test events
  src/Artsy/Analytics/trackExperimentViewed.tsx
  src/Artsy/Router/RouterLink.tsx
  src/Artsy/Router/makeAppRoutes.tsx
Labels: Version: Patch

#3106 @mzikherman => [Analytics] Proper structure for experiment viewed event
  src/Artsy/Analytics/trackExperimentViewed.tsx
Labels: Merge On Green, Version: Patch

#3107 [Schema] Update schema to latest
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3109 [FX-1692] Reorder mobile nav items to match desktop
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBarTest/Menus/MobileNavMenu.tsx
  src/Components/NavBarTest/Menus/__tests__/MobileNavMenu.test.tsx
  src/Components/__stories__/NavBar.story.tsx
Labels: Version: Patch

#3110 Use open:auth with redirectTo option to skip signup onboarding
  src/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/RequestConditionReport.test.tsx
Labels: Version: Minor

#3108 @zephraph => [TSLint] Rule to warn about using QueryRenderer
  src/Artsy/Relay/SystemQueryRenderer.tsx
  src/Components/Publishing/ToolTip/TooltipsDataLoader.tsx
  src/DevTools/MockRelayRenderer.tsx
  tslint.json
  tslint/README.md
  tslint/noQueryRendererImportRule.js
Labels: Version: Trivial

#3112 User should not be able to advance to the payment page without entering a phone number with their shipping address
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#3113 Rename 'repcaptcha' to 'recaptcha', add new types
  src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
  src/Components/Authentication/Desktop/LoginForm.tsx
  src/Components/Authentication/Desktop/SignUpForm.tsx
  src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
  src/Components/Authentication/Mobile/LoginForm.tsx
  src/Components/Authentication/Mobile/SignUpForm.tsx
  src/Utils/__tests__/recaptcha.test.ts
  src/Utils/recaptcha.ts
Labels: Version: Major

#3116 [PUR-1727] Add medium field to artwork details
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkDetails.ts
  src/__generated__/ArtworkDetailsAdditionalInfo_artwork.graphql.ts
  src/__generated__/ArtworkDetailsQuery.graphql.ts
  src/__generated__/ArtworkDetailsStoryQuery.graphql.ts
  src/__generated__/ArtworkDetails_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Minor

#3115 [FX-1675] Resize collection header artist images
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/fixtures/artworks.ts
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
  src/__generated__/CollectionRefetch2Query.graphql.ts
  src/__generated__/Header_artworks.graphql.ts
Labels: Version: Patch

#3114 [FX-1684] use resizer for featured collection image
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
Labels: Version: Patch
