Repository artsy/reaction, pull requests merged in 2020-02, with the labels that each got.

#3119 Avoid performance hit by not importing all components from v2
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/NavigationTabs.tsx
  src/Apps/Artist/Routes/Articles/ArtistArticles.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artist/Routes/Shows/ArtistShows.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
  src/Apps/Order/Components/AddressForm.tsx
  src/Apps/Order/Components/ShippingAddress.tsx
  src/Apps/Order/Components/TransactionDetailsSummaryItem.tsx
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Apps/Order/Routes/__tests__/Utils/addressForm.ts
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
  src/Apps/Search/SearchApp.tsx
  src/Components/FrameWithRecentlyViewed.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx
  src/Components/v2/ArtworkGrid.tsx
  src/Components/v2/RouteTabs.tsx
  src/Components/v2/__stories__/CountrySelect.story.tsx
  src/Components/v2/__stories__/Lightbox.story.tsx
  src/Components/v2/__stories__/MobileActionSheet.story.tsx
  src/Components/v2/__stories__/MobileTopBar.story.tsx
  src/Components/v2/__stories__/RecentlyViewed.story.tsx
  src/Components/v2/__stories__/StepSummaryItem.story.tsx
  src/Components/v2/__stories__/Tabs.Router.story.tsx
  src/Components/v2/index.tsx
Labels: Version: Patch

#3121 [PUR-1727] Return category data for medium field
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkDetails.ts
  src/__generated__/ArtworkDetailsAdditionalInfo_artwork.graphql.ts
  src/__generated__/ArtworkDetailsQuery.graphql.ts
  src/__generated__/ArtworkDetailsStoryQuery.graphql.ts
  src/__generated__/ArtworkDetails_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Merge On Green, Version: Minor

#3118 Update the auction result layout
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionResultsCount.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/SortSelect.tsx
  src/Apps/Artist/Routes/AuctionResults/TableSidebar.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/__generated__/AuctionResultsCount_results.graphql.ts
  src/__generated__/AuctionResults_Test_Query.graphql.ts
  src/__generated__/routes_AuctionResultsQuery.graphql.ts
Labels: Version: Minor

#3125 @eessex => Fix SSR on article pages
  src/Components/Publishing/ToolTip/TooltipsDataLoader.tsx
Labels: Merge On Green, Version: Patch

#3127 Resize category rail
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/__tests__/OtherCollectionEntity.test.tsx
Labels: Version: Patch

#3128 Remove Node verson requirement
  package.json
Labels: Version: Patch

#3130 Update URL for storybooks documentation
  README.md
Labels: Merge On Green, Version: Trivial

#3126 [Tracking] Consolidate page-view tracking within new trackingMiddleware
  data/schema.graphql
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/NavigationTabs.tsx
  src/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/Register/index.tsx
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/Collect2/Routes/Collections/index.tsx
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/Counter/index.tsx
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/Routes/__tests__/Accept.test.tsx
  src/Apps/Order/Routes/__tests__/Counter.test.tsx
  src/Apps/Order/Routes/__tests__/NewPayment.test.tsx
  src/Apps/Order/Routes/__tests__/Offer.test.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Reject.test.tsx
  src/Apps/Order/Routes/__tests__/Respond.test.tsx
  src/Apps/Order/Routes/__tests__/Review.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Apps/Order/Routes/__tests__/Status.test.tsx
  src/Apps/Order/Utils/__mocks__/trackPageView.ts
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/SearchApp.tsx
  src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
  src/Artsy/Analytics/index.ts
  src/Artsy/Analytics/trackExperimentViewed.tsx
  src/Artsy/Analytics/trackPageView.ts
  src/Artsy/Analytics/trackPageViewWrapper.tsx
  src/Artsy/Analytics/trackingMiddleware.ts
  src/Artsy/Router/RouterLink.tsx
  src/Artsy/Router/__tests__/RouterLink.test.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/makeAppRoutes.tsx
  src/Typings/global.d.ts
  src/Utils/Events.ts
  src/__generated__/ArtistArtworkFilterQuery.graphql.ts
  src/__generated__/ArtistArtworkFilter_artist.graphql.ts
  src/__generated__/OverviewQuery.graphql.ts
  src/__generated__/Overview_artist.graphql.ts
  typings/sharify.d.ts
Labels: Version: Minor

#3117 [FX-1773] Adjust default jpeg quality for cropped images
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/SeriesLayout.test.tsx.snap
  src/Components/Publishing/Layouts/__tests__/__snapshots__/VideoLayout.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCard.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/ArticleCards.test.tsx.snap
  src/Components/Publishing/RelatedArticles/ArticleCards/__tests__/__snapshots__/Block.test.tsx.snap
  src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
  src/Components/Publishing/RelatedArticles/Panel/__tests__/__snapshots__/RelatedArticlesPanel.test.tsx.snap
  src/Components/Publishing/__tests__/ArticleMeta.test.tsx
  src/Utils/resizer.ts
Labels: Version: Patch

#3133 Ensure PNG → JPG in Collection Hubs's related rail
  src/Apps/Collect2/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/index.tsx
Labels: Version: Patch

#3135 [Tracking Bugfix] Fix url and referrer tracking
  src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
  src/Artsy/Analytics/trackingMiddleware.ts
Labels: Version: Patch

#3136 [Tracking Bugfix] Make path absolute
  src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
  src/Artsy/Analytics/trackingMiddleware.ts
Labels: Version: Patch

#3138 [Tracking Bugfix] Fix artwork page 1-off
  src/Apps/Artwork/ArtworkApp.tsx
  src/Artsy/Analytics/trackingMiddleware.ts
Labels: Version: Patch

#3134 [AUCT-870] - Add lot viewed analytics
  src/Apps/Artwork/ArtworkApp.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/ArtworkApp_artwork.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Patch

#3142 [Analytics] Path is relative
  src/Apps/Artwork/ArtworkApp.tsx
  src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
  src/Artsy/Analytics/trackingMiddleware.ts
Labels: Merge On Green, Version: Patch

#3140 [Bugfix] Ensure nav closed on clienside routes
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBarTest/Menus/MobileNavMenu.tsx
  src/Components/NavBarTest/NavBar.tsx
Labels: Version: Patch

#3141 [Clientside Routing] Update mobile page loader to be more obvious
  src/Artsy/Router/Utils/RenderStatus.tsx
Labels: Version: Patch

#3145 Updates MP schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3139 As a user I see the updated list view of auction results and i can expand the result
  CHANGELOG.md
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionDetailsModal.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/Apps/Artist/Routes/AuctionResults/state.ts
  src/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
  src/__generated__/ArtistAuctionResultItem_auctionResult.graphql.ts
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/AuctionResults_Test_Query.graphql.ts
  src/__generated__/routes_AuctionResultsQuery.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Minor

#3137 [Refactor] Implement route-level bundle splitting
  .babelrc
  .gitignore
  package.json
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Components/StyledLink.tsx
  src/Apps/Artist/Routes/Articles/index.tsx
  src/Apps/Artist/Routes/AuctionResults/index.tsx
  src/Apps/Artist/Routes/CV/index.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artist/Routes/Shows/index.tsx
  src/Apps/Artist/Routes/Works/index.tsx
  src/Apps/Artist/routes.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/routes.tsx
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Routes/Collection/CollectionAppQuery.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/Collect2/Routes/Collections/index.tsx
  src/Apps/Collect2/collectRoutes.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/routes.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Components/v2/ArtworkFilter/ArtworkQueryFilter.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/fixtures/ArtworkFilter.fixture.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/CollectionAppQuery.graphql.ts
  tsconfig.json
  yarn.lock
Labels: Version: Minor

#3143 Remove deprecated fonts from classic articles, fix bylines
  2
  src/Components/Publishing/Byline/ClassicByline.tsx
  src/Components/Publishing/Byline/__tests__/ClassicByline.test.tsx
  src/Components/Publishing/Byline/__tests__/__snapshots__/ClassicByline.test.tsx.snap
  src/Components/Publishing/Constants.ts
  src/Components/Publishing/EditorialFeature/__tests__/__snapshots__/EditorialFeature.test.tsx.snap
  src/Components/Publishing/Fixtures/Articles.ts
  src/Components/Publishing/Header/Layouts/ClassicHeader.tsx
  src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/ClassicHeader.test.tsx.snap
  src/Components/Publishing/Layouts/ClassicLayout.tsx
  src/Components/Publishing/Typings.ts
Labels: Merge On Green, Version: Patch

#3131 Auction results auction-house filter
  data/schema.graphql
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilterMobileActionSheet.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionResultHeader.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionResultsControls.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/SortSelect.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/TableSidebar.tsx
  src/Apps/Artist/Routes/AuctionResults/TableSidebar.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.test.tsx
  src/Apps/Artist/Routes/AuctionResults/index.tsx
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/__generated__/AuctionResults_Test_Query.graphql.ts
  src/__generated__/routes_AuctionResultsQuery.graphql.ts
Labels: Version: Minor

#3150 Revert "[Refactor] Implement route-level bundle splitting"
  .babelrc
  .gitignore
  package.json
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Components/StyledLink.tsx
  src/Apps/Artist/Routes/Articles/index.tsx
  src/Apps/Artist/Routes/AuctionResults/index.tsx
  src/Apps/Artist/Routes/CV/index.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artist/Routes/Shows/index.tsx
  src/Apps/Artist/Routes/Works/index.tsx
  src/Apps/Artist/routes.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/routes.tsx
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Routes/Collection/CollectionAppQuery.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/Collect2/Routes/Collections/index.tsx
  src/Apps/Collect2/collectRoutes.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/routes.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Components/v2/ArtworkFilter/ArtworkQueryFilter.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/fixtures/ArtworkFilter.fixture.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/__generated__/ArtworkFilterQuery.graphql.ts
  src/__generated__/CollectionRefetch2Query.graphql.ts
  tsconfig.json
  yarn.lock
Labels: Version: Patch

#3152 Add Auction result header description
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionResultHeader.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/__generated__/AuctionResultHeader_artist.graphql.ts
  src/__generated__/AuctionResults_Test_Query.graphql.ts
  src/__generated__/routes_AuctionResultsQuery.graphql.ts
Labels: Merge On Green, Version: Patch

#3154 [FX-1807] update MP schema and use new size arg to limit relatedCollections
  data/schema.graphql
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
  src/__generated__/CollectionRefetch2Query.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
Labels: Version: Patch

#3156 Update README with info on publishing canary
  README.md
Labels: Version: Trivial

#3155 Collapse auction results filter for reasons
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
Labels: Merge On Green, Version: Patch

#3151 Take 2: [Refactor] Implement route-level bundle splitting
  .babelrc
  .gitignore
  package.json
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Components/StyledLink.tsx
  src/Apps/Artist/Routes/Articles/index.tsx
  src/Apps/Artist/Routes/AuctionResults/index.tsx
  src/Apps/Artist/Routes/CV/index.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artist/Routes/Shows/index.tsx
  src/Apps/Artist/Routes/Works/index.tsx
  src/Apps/Artist/routes.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/routes.tsx
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Routes/Collection/CollectionAppQuery.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/Collect2/Routes/Collections/index.tsx
  src/Apps/Collect2/collectRoutes.tsx
  src/Apps/Search/SearchApp.tsx
  src/Apps/Search/routes.tsx
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Components/v2/ArtworkFilter/ArtworkQueryFilter.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/fixtures/ArtworkFilter.fixture.tsx
  src/Components/v2/ArtworkFilter/index.tsx
  src/__generated__/ArtworkQueryFilterQuery.graphql.ts
  src/__generated__/CollectionAppQuery.graphql.ts
  tsconfig.json
  yarn.lock
Labels: Version: Minor

#3153 [PURCHASE-1749] Add auction result size filter
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/SizeFilter.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
Labels: Version: Patch

#3159 [Bugfix] Prefix injected split tag scripts with CDN_URL
  .storybook/webpack.config.js
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Artsy/Router/buildServerApp.tsx
Labels: Version: Patch

#3160 Bundle split search; fix SSR search input
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/Search/Routes/Artworks/index.tsx
  src/Apps/Search/Routes/Entity/SearchResultsEntity.tsx
  src/Apps/Search/routes.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Artsy/Router/server.ts
  src/Components/Search/SearchBar.tsx
  src/Utils/Hooks/useDidMount.ts
Labels: Version: Patch

#3161 [Bugfix] Ensure all search-bar nav items navigate properly
  src/Artsy/Router/makeAppRoutes.tsx
  src/Components/Search/SearchBar.tsx
Labels: Version: Patch

#3162 [Clientside Routing] Wire in Order app
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Components/AppShell.tsx
  src/Apps/Order/OrderApp.tsx
  src/Apps/Order/Routes/Accept/index.tsx
  src/Apps/Order/Routes/Counter/index.tsx
  src/Apps/Order/Routes/NewPayment/index.tsx
  src/Apps/Order/Routes/Offer/index.tsx
  src/Apps/Order/Routes/Payment/index.tsx
  src/Apps/Order/Routes/Reject/index.tsx
  src/Apps/Order/Routes/Respond/index.tsx
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/Status/index.tsx
  src/Apps/Order/__tests__/OrderApp.test.tsx
  src/Apps/Order/routes.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/Apps/getAppRoutes.tsx
  src/Artsy/Analytics/trackingMiddleware.ts
  src/Artsy/Router/Utils/RenderStatus.tsx
  src/Artsy/Router/Utils/findCurrentRoute.tsx
  src/Artsy/SystemContext.tsx
  src/Components/NavBar/MinimalNavBar.tsx
  src/__generated__/OrderApp_order.graphql.ts
  src/__generated__/routes_OrderQuery.graphql.ts
Labels: Version: Minor

#3163 [Clientside Routing] Wire in Auctions app
  src/Apps/Artwork/Components/ArtworkBanner/Banner.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Auction/Components/AuctionFAQ.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/Register/index.tsx
  src/Apps/Auction/Routes/__tests__/ConfirmBid.test.tsx
  src/Apps/Auction/routes.tsx
  src/Apps/Order/routes.tsx
  src/Apps/getAppRoutes.tsx
  src/__generated__/routes_AuctionFAQQuery.graphql.ts
Labels: Version: Minor

#3168 Add canary deployment to reaction PRs
  .circleci/config.yml
Labels: Version: Trivial

#3171 Add integrity classname
  src/Components/NavBar/MinimalNavBar.tsx
Labels: Version: Patch

#3172 Note that canaries are auto published
  README.md
Labels: Version: Trivial

#3169 Migrate "Promoted Content" banner from Force
  src/Components/Publishing/Byline/__tests__/ClassicByline.test.tsx
  src/Components/Publishing/Byline/__tests__/__snapshots__/ClassicByline.test.tsx.snap
  src/Components/Publishing/Fixtures/Articles.ts
  src/Components/Publishing/Header/Layouts/ClassicHeader.tsx
  src/Components/Publishing/Header/Layouts/Components/ClassicPromotedContent.tsx
  src/Components/Publishing/Header/Layouts/Components/__tests__/ClassicPromotedContent.test.tsx
  src/Components/Publishing/Header/Layouts/__tests__/ClassicHeader.test.tsx
  src/Components/Publishing/Header/Layouts/__tests__/__snapshots__/ClassicHeader.test.tsx.snap
  src/Components/Publishing/Typings.ts
  src/Components/Publishing/__stories__/ArticleClassic.story.tsx
Labels: Version: Patch

#3174 Use data-link instead of classname for integration test
  src/Components/NavBar/MinimalNavBar.tsx
Labels: Version: Patch

#3175 [PURCHASE-1793] Fix artwork filter events being tracked twice.
  src/Apps/Artist/Routes/Overview/Components/ArtistArtworkFilter.tsx
  src/Apps/Collect2/Routes/Collect/index.tsx
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/Apps/Search/Routes/Artworks/index.tsx
Labels: Version: Patch

#3176 Remove dd-trace
  package.json
  src/Artsy/Router/buildServerApp.tsx
  src/Utils/__tests__/trace.test.ts
  src/Utils/trace.ts
  yarn.lock
Labels: Version: Patch

#3180 Remove weird 2 file generated by yarn integrate
  .gitignore
  2
Labels: Merge On Green, Version: Trivial

#3178 [PURCHASE-1790] Add auction result filter instrumentation
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/Artsy/Analytics/Schema/Values.ts
Labels: Version: Minor

#3158 [FX-1752] Add "Consign" to desktop global nav More menu; nav code cleanup
  src/Components/Nav/MobileMenu.tsx
  src/Components/Nav/__tests__/MobileMenu.test.tsx
  src/Components/Nav/__tests__/__snapshots__/MobileMenu.test.tsx.snap
  src/Components/NavBar/Menus/MoreNavMenu.tsx
  src/Components/NavBar/Menus/__tests__/MoreNavMenu.test.tsx
  src/Components/NavBarTest/Menus/MobileNavMenu.tsx
  src/Components/NavBarTest/Menus/MoreNavMenu.tsx
  src/Components/NavBarTest/Menus/NotificationsMenu.tsx
  src/Components/NavBarTest/Menus/UserMenu.tsx
  src/Components/NavBarTest/Menus/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBarTest/Menus/__tests__/MoreNavMenu.test.tsx
  src/Components/NavBarTest/Menus/__tests__/NotificationsMenu.test.tsx
  src/Components/NavBarTest/Menus/__tests__/UserMenu.test.tsx
  src/Components/NavBarTest/Menus/index.tsx
  src/Components/NavBarTest/NavBar.tsx
  src/Components/NavBarTest/NavItem.tsx
  src/Components/NavBarTest/NotificationsBadge.tsx
  src/Components/NavBarTest/Utils/__tests__/authentication.test.ts
  src/Components/NavBarTest/Utils/authentication.ts
  src/Components/NavBarTest/__tests__/NavBar.test.tsx
  src/Components/NavBarTest/__tests__/NavBarTracking.test.tsx
  src/Components/NavBarTest/__tests__/NavItem.test.tsx
  src/Components/NavBarTest/__tests__/NotificationsBadge.test.tsx
  src/Components/NavBarTest/index.tsx
  src/Components/Publishing/Nav/SubNav.tsx
  src/Components/Publishing/Nav/__tests__/SubNav.test.tsx
  src/Components/Publishing/Nav/__tests__/__snapshots__/SubNav.test.tsx.snap
  src/Components/__stories__/NavBar.story.tsx
  src/__generated__/NotificationsMenuTestQuery.graphql.ts
Labels: Version: Minor

#3181 [Clientside Nav] Fix double track on artwork page
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Order/OrderApp.tsx
  src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
Labels: Version: Patch

#3173 Show My Conversations
  src/Apps/Conversation/Components/Conversation.tsx
  src/Apps/Conversation/Components/ConversationSnippet.tsx
  src/Apps/Conversation/Components/Conversations.tsx
  src/Apps/Conversation/Components/Message.tsx
  src/Apps/Conversation/Components/Reply.tsx
  src/Apps/Conversation/ConversationApp.tsx
  src/Apps/Conversation/Mutation/SendConversationMessage.ts
  src/Apps/Conversation/Routes/Conversation/index.tsx
  src/Apps/Conversation/__tests__/ConversationApp.test.tsx
  src/Apps/Conversation/routes.tsx
  src/Apps/__stories__/ConversationApp.story.tsx
  src/Apps/__tests__/Fixtures/Conversation.ts
  src/Apps/getAppRoutes.tsx
  src/Components/NavBar/Menus/UserMenu.tsx
  src/Components/NavBar/Menus/__tests__/UserMenu.test.tsx
  src/__generated__/ConversationAppTestQuery.graphql.ts
  src/__generated__/ConversationApp_me.graphql.ts
  src/__generated__/ConversationSnippet_conversation.graphql.ts
  src/__generated__/Conversation_conversation.graphql.ts
  src/__generated__/Conversation_me.graphql.ts
  src/__generated__/ConversationsQuery.graphql.ts
  src/__generated__/Conversations_me.graphql.ts
  src/__generated__/Message_message.graphql.ts
  src/__generated__/SendConversationMessageMutation.graphql.ts
  src/__generated__/routes_ConversationQuery.graphql.ts
  src/__generated__/routes_DetailQuery.graphql.ts
Labels: Merge On Green, Version: Minor

#3184 @damassi => [ClientSide Routing] Launch v3 of the AB test
  src/Artsy/Analytics/trackingMiddleware.ts
  src/Components/Search/SearchBar.tsx
  typings/sharify.d.ts
Labels: Version: Patch

#3188 [BundleSplitting] Comment out for now
  src/Apps/Artist/routes.tsx
  src/Apps/Artwork/routes.tsx
  src/Apps/Auction/routes.tsx
  src/Apps/Collect2/collectRoutes.tsx
  src/Apps/Conversation/routes.tsx
  src/Apps/Order/routes.tsx
  src/Apps/Search/routes.tsx
Labels: Version: Minor

#3187 Fix conversation detail link
  src/Apps/Conversation/Components/ConversationSnippet.tsx
  src/Apps/Conversation/Routes/Conversation/index.tsx
Labels: Merge On Green, Version: Patch

#3189 [BundleSplitting] Reenable
  src/Apps/Artist/routes.tsx
  src/Apps/Artwork/routes.tsx
  src/Apps/Auction/routes.tsx
  src/Apps/Collect2/collectRoutes.tsx
  src/Apps/Conversation/routes.tsx
  src/Apps/Order/routes.tsx
  src/Apps/Search/routes.tsx
Labels: Version: Minor

#3185 [QueryRenderers] Delay showing spinner
  src/Artsy/Relay/renderWithLoadProgress.tsx
Labels: Merge On Green, Version: Patch

#3192 Add attachments to each message
  src/Apps/Conversation/Components/ConversationSnippet.tsx
  src/Apps/Conversation/Components/Message.tsx
  src/Apps/Conversation/Mutation/SendConversationMessage.ts
  src/Apps/Conversation/__tests__/ConversationApp.test.tsx
  src/Apps/__tests__/Fixtures/Conversation.ts
  src/__generated__/Message_message.graphql.ts
  src/__generated__/SendConversationMessageMutation.graphql.ts
  src/__generated__/routes_DetailQuery.graphql.ts
Labels: Merge On Green, Version: Minor

#3191 Simplify A/B test lookup via `express-http-context`
  .babelrc
  package.json
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/OtherWorks/Header.tsx
  src/Artsy/Analytics/trackingMiddleware.ts
  src/Artsy/Relay/renderWithLoadProgress.tsx
  src/Artsy/Router/makeAppRoutes.tsx
  src/Utils/getENV.tsx
  typings/sharify.d.ts
  yarn.lock
Labels: Version: Patch

#3198 Fix issue where expanding auction result changed page
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.test.tsx
  src/Apps/Artist/Routes/AuctionResults/state.ts
  src/Artsy/Analytics/Schema/Values.ts
Labels: Merge On Green, Version: Patch

#3190 Update field used for notifications badge count
  data/schema.graphql
  src/Components/NavBar/Menus/NotificationsMenu.tsx
  src/Components/NavBar/Menus/__tests__/NotificationsMenu.test.tsx
  src/Components/NavBar/NotificationsBadge.tsx
  src/Components/NavBar/__tests__/NotificationsBadge.test.tsx
  src/__generated__/NotificationsMenuQuery.graphql.ts
Labels: Version: Patch

#3200 Link header badges to Auction Result / Career Highlights
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Components/ArtistIndicator.tsx
  src/Apps/Artist/Components/__tests__/ArtistHeader.test.tsx
Labels: Jira Synced, Version: Minor

#3197 Handle "works for sale" copy and tabs on artwork page if no works for sale
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Components/NavigationTabs.tsx
  src/Apps/Artist/Components/__tests__/ArtistHeader.test.tsx
  src/Apps/Artist/Components/__tests__/NavigationTabs.test.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
Labels: Jira Synced, Merge On Green, Version: Minor

#3201 use `formattedNationalityAndBirthday` in artist header
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/__tests__/routes.test.tsx
  src/Apps/__tests__/Fixtures/Artist/Components/ArtistHeader.tsx
  src/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/__generated__/ArtistHeader_artist.graphql.ts
  src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#3202 Log recaptcha misses on signup
  src/Utils/recaptcha.ts
Labels: Version: Patch

#3199 Add data file to describe new menu structure (for mobile and desktop)
  src/Components/NavBar/menuData.ts
Labels: Version: Patch

#3203 [Clientside Nav] Move to more conventional A/B test structure
  package.json
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/Register/index.tsx
  src/Apps/Auction/__tests__/routes.test.ts
  src/Apps/Auction/routes.tsx
  src/Apps/Order/OrderApp.tsx
  src/Artsy/Analytics/trackingMiddleware.ts
  src/Artsy/Router/Utils/RenderStatus.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Artsy/SystemContext.tsx
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/Search/SearchBar.tsx
  src/Utils/getENV.tsx
  yarn.lock
Labels: Merge On Green, Version: Minor

#3204 Bump Node to v12 to have parity with Force
  .nvmrc
Labels: Merge On Green, Version: Patch

#3205 [step 2] Update schema to use MP's schema at mp@rename-wizard-to-flow
  data/schema.graphql
  package.json
Labels: Version: Patch

#3208 Only render "RelatedCollections" that have artworks
  src/Components/RelatedCollectionsRail/RelatedCollectionsRail.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
  src/__generated__/CollectionAppQuery.graphql.ts
  src/__generated__/RelatedCollectionsRail_collections.graphql.ts
Labels: Version: Patch

#3209 [FX-1828] Update typography and spacing in mobile menu
  src/Components/NavBar/Menus/MobileNavMenu.tsx
Labels: Version: Patch

#3207 [Clientside Nav] Add async bundle preloading pattern to router
  package.json
  src/Apps/Artist/routes.tsx
  src/Apps/Artwork/routes.tsx
  src/Apps/Auction/routes.tsx
  src/Apps/Collect2/collectRoutes.tsx
  src/Apps/Components/AppShell.tsx
  src/Apps/Order/routes.tsx
  src/Apps/Search/routes.tsx
  src/Artsy/Router/buildServerApp.tsx
  yarn.lock
Labels: Version: Minor

#3214 [Search] Dont split bundles
  src/Apps/Search/routes.tsx
Labels: Version: Patch

#3215 Update yarn orb to track tests via circle again
  .circleci/config.yml
  .gitignore
Labels: Version: Trivial
