Repository artsy/reaction, pull requests merged in 2020-03, with the labels that each got.

#3186 Collector Verification App
  .nvmrc
  .tool-versions
  src/Apps/IdentityVerification/IdentityVerificationApp.tsx
  src/Apps/IdentityVerification/__fixtures__/routes_IdentityVerificationAppQuery.ts
  src/Apps/IdentityVerification/__tests__/IdentityVerificationApp.test.tsx
  src/Apps/IdentityVerification/__tests__/Utils/IdentityVerificationAppTestPage.tsx
  src/Apps/IdentityVerification/__tests__/routes.test.tsx
  src/Apps/IdentityVerification/routes.tsx
  src/Apps/getAppRoutes.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/IdentityVerificationAppTestQuery.graphql.ts
  src/__generated__/IdentityVerificationApp_me.graphql.ts
  src/__generated__/routes_IdentityVerificationAppQuery.graphql.ts
Labels: Version: Minor

#3218 [Artist] Visual QA
  src/Apps/Artist/Components/ArtistCollectionsRail/index.tsx
  src/Apps/Collect2/collectRoutes.tsx
Labels: Version: Patch

#3221 [Clientside Nav] Add more tests
  src/Apps/Components/__tests__/AppShell.test.tsx
  src/Apps/getAppRoutes.tsx
  src/Artsy/Router/RenderStatus.tsx
  src/Artsy/Router/Route.tsx
  src/Artsy/Router/Utils/catchLinks.tsx
  src/Artsy/Router/Utils/createRouteConfig.ts
  src/Artsy/Router/__tests__/buildAppRoutes.test.tsx
  src/Artsy/Router/buildAppRoutes.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Components/NavBar/NavBar.tsx
Labels: Version: Patch

#3211 [PURCHASE-1765] Add medium (categories) filter to auction results
  data/schema.graphql
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/MediumFilter.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
Labels: Version: Minor

#3217 [Search] Visual QA
  src/Apps/Search/SearchApp.tsx
  src/Components/Search/SearchBar.tsx
Labels: Merge On Green, Version: Patch

#3224 Update AB test name to CLIENT_NAVIGATION_V4
  src/Apps/Auction/__tests__/routes.test.ts
  src/Apps/Auction/routes.tsx
  src/Artsy/Analytics/trackingMiddleware.ts
  typings/sharify.d.ts
Labels: Merge On Green, Version: Patch

#3228 Revert "Only lint changed files"
  .circleci/config.yml
  package.json
  yarn.lock
Labels: Merge On Green, Version: Patch

#3230 Only lint changed files
  .circleci/config.yml
  package.json
  yarn.lock
Labels: Version: Trivial

#3223 User does not see lot condition report request if it's disabled for a sale
  data/schema.graphql
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkDetails.ts
  src/__generated__/ArtworkDetailsAdditionalInfo_artwork.graphql.ts
  src/__generated__/ArtworkDetailsQuery.graphql.ts
  src/__generated__/ArtworkDetailsStoryQuery.graphql.ts
  src/__generated__/ArtworkDetails_Test_Query.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Patch

#3234 Adds hooks to login modals for integration tests
  src/Components/Authentication/Desktop/LoginForm.tsx
  src/Components/Authentication/Mobile/LoginForm.tsx
Labels: Version: Minor

#3233 Add attribute to body when app is ready to be tested
  src/Apps/Components/AppShell.tsx
Labels: Version: Minor

#3236 Update attribute to follow pre-established testing patterns
  src/Apps/Components/AppShell.tsx
Labels: Merge On Green, Version: Patch

#3232 Begin ID Verification flow from collector verification app
  src/Apps/IdentityVerification/IdentityVerificationApp.tsx
  src/Apps/IdentityVerification/__tests__/IdentityVerificationApp.test.tsx
  src/__generated__/IdentityVerificationAppStartFlowMutation.graphql.ts
Labels: Version: Patch

#3242 Sync schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3241 Move conversations behind lab feature flag
  src/Components/NavBar/Menus/UserMenu.tsx
  src/Components/NavBar/Menus/__tests__/UserMenu.test.tsx
Labels: Merge On Green, Version: Minor

#3243 [Carousel] Remove error boundary
  src/Components/v2/Carousel.tsx
Labels: Version: Patch

#3244 Replace getENV with sd for now
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
Labels: Merge On Green, Version: Patch

#3245 Update lint-staged
  package.json
  yarn.lock
Labels: Merge On Green, Version: Trivial

#3249 Update schema
  data/schema.graphql
Labels: Version: Patch

#3239 Helpers for opening auth modals are strictly typed
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Apps/Artist/Routes/Overview/Components/ZeroState.tsx
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
  src/Components/Artwork/Save.tsx
  src/Components/Authentication/FormSwitcher.tsx
  src/Components/Authentication/Types.ts
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/FollowButton/FollowGeneButton.tsx
  src/Components/FollowButton/__tests__/FollowArtistButton.test.tsx
  src/Components/FollowButton/__tests__/FollowGeneButton.test.tsx
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/ToolTip/__tests__/ArtistToolTip.test.tsx
  src/Components/Publishing/ToolTip/__tests__/GeneToolTip.test.tsx
  src/Components/v2/ArtistCard.tsx
  src/Utils/__tests__/openAuthModal.test.ts
  src/Utils/openAuthModal.ts
Labels: Version: Patch

#3250 Revert "Helpers for opening auth modals are strictly typed"
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Apps/Artist/Routes/Overview/Components/ZeroState.tsx
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
  src/Components/Artwork/Save.tsx
  src/Components/Authentication/FormSwitcher.tsx
  src/Components/Authentication/Types.ts
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/FollowButton/FollowGeneButton.tsx
  src/Components/FollowButton/__tests__/FollowArtistButton.test.tsx
  src/Components/FollowButton/__tests__/FollowGeneButton.test.tsx
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/ToolTip/__tests__/ArtistToolTip.test.tsx
  src/Components/Publishing/ToolTip/__tests__/GeneToolTip.test.tsx
  src/Components/v2/ArtistCard.tsx
  src/Utils/__tests__/openAuthModal.test.ts
  src/Utils/openAuthModal.ts
Labels: Version: Patch

#3251 [Bugfix] => Make `SEOProductsForCollections` safer
  src/Apps/Collect2/Components/SeoProductsForCollections.tsx
Labels: Merge On Green, Version: Patch

#3248 Make hide grids function a bit safer
  src/Apps/Artwork/Components/OtherWorks/index.tsx
Labels: Version: Patch

#3253 [Artist] Fix redirect
  src/Apps/Artist/__tests__/routes.test.tsx
  src/Apps/Artist/routes.tsx
  src/Apps/Artwork/Components/ArtworkBanner/index.tsx
Labels: Version: Patch

#3255 Remove auction routes
  src/Apps/getAppRoutes.tsx
Labels: Merge On Green, Version: Patch

#3256 Remove BidFlow from router
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Auction/Routes/ConfirmBid/index.tsx
  src/Apps/Auction/Routes/Register/index.tsx
  src/Apps/Auction/routes.tsx
Labels: Version: Patch

#3252 Type openAuthModal helpers
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Components/Artwork/Save.tsx
  src/Components/Authentication/FormSwitcher.tsx
  src/Components/Authentication/Types.ts
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/FollowButton/FollowGeneButton.tsx
  src/Components/FollowButton/__tests__/FollowArtistButton.test.tsx
  src/Components/FollowButton/__tests__/FollowGeneButton.test.tsx
  src/Components/Publishing/Article.tsx
  src/Components/Publishing/ToolTip/__tests__/ArtistToolTip.test.tsx
  src/Components/Publishing/ToolTip/__tests__/GeneToolTip.test.tsx
  src/Utils/__tests__/openAuthModal.test.ts
  src/Utils/openAuthModal.ts
Labels: Version: Patch

#3257 Add Integrity-ready flag to boot
  src/Artsy/Router/Boot.tsx
Labels: Version: Patch

#3258 Move conversations app to be behind lab feature instead of admin flag
  src/Apps/Conversation/ConversationApp.tsx
  src/Apps/Conversation/Routes/Conversation/index.tsx
  src/Apps/Conversation/__tests__/ConversationApp.test.tsx
Labels: Version: Patch

#3259 Debug ErrorBoundry error on mobile
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
Labels: Merge On Green, Version: Patch

#3260 Update openseadragon to try to fix some mobile bugs
  package.json
  yarn.lock
Labels: Merge On Green, Version: Patch

#3222 Make countries list on the Address form render only EU countries if it's marked as euOrigin and domesticOnly
  src/Apps/Order/Components/AddressForm.tsx
  src/Apps/Order/Components/__stories__/AddressForm.story.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Apps/__tests__/Fixtures/Order.ts
  src/Components/v2/CountrySelect.tsx
  src/__generated__/ShippingTestQuery.graphql.ts
  src/__generated__/Shipping_order.graphql.ts
  src/__generated__/routes_ShippingQuery.graphql.ts
Labels: Version: Patch

#3263 the default should be country of origin if the country select is locked to EU only
  src/Apps/Order/Components/AddressForm.tsx
  src/Apps/Order/Components/__stories__/AddressForm.story.tsx
Labels: Merge On Green, Version: Patch

#3265 Attempt to fix Flickity error
  src/Components/v2/Carousel.tsx
Labels: Version: Patch

#3240 [Clientside Nav] Add <NetworkTimeout /> & <NetworkOfflineMonitor /> components
  src/Apps/Components/AppShell.tsx
  src/Artsy/Router/NetworkOfflineMonitor.tsx
  src/Artsy/Router/NetworkTimeout.tsx
  src/Artsy/Router/RenderStatus.tsx
  src/Artsy/Router/buildAppRoutes.tsx
Labels: Merge On Green, Version: Minor

#3262 [PUR-1818] Update header text for auction results page
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionResultHeader.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/AuctionResultHeader_artist.graphql.ts
  src/__generated__/AuctionResults_Test_Query.graphql.ts
  src/__generated__/routes_AuctionResultsQuery.graphql.ts
Labels: Version: Minor

#3266 [Clientside Nav] Remove mobile loader test
  src/Apps/Artwork/ArtworkApp.tsx
  src/Artsy/Router/RenderStatus.tsx
Labels: Version: Patch

#3267 [Clientside Nav] Fix throttle invocation
  src/Artsy/Router/NetworkOfflineMonitor.tsx
Labels: Version: Patch

#3268 Sync schema
  data/schema.graphql
Labels: Version: Patch

#3269 [Carousel] Fix alignment in image
  src/Components/v2/Carousel.tsx
Labels: Version: Patch

#3271 [Clientside Nav] Add more safety around network failures with fallback UI
  src/Artsy/Router/Boot.tsx
  src/Artsy/Router/__tests__/Boot.test.tsx
  src/Artsy/Router/__tests__/buildClientApp.test.tsx
  src/Components/ErrorBoundary.tsx
  src/Components/Payment/__tests__/PaymentForm.test.tsx
  src/Components/__tests__/ErrorBoundary.test.tsx
Labels: Version: Minor

#3226 [FX-1758] add a fallback image when there is no headerImage
  src/Apps/Collect2/Routes/Collection/index.tsx
  src/__generated__/CollectionAppQuery.graphql.ts
  src/__generated__/Collection_collection.graphql.ts
Labels: Version: Patch

#3272 [ErrorBoundary] Add generic error handler
  src/Components/ErrorBoundary.tsx
  src/Components/__tests__/ErrorBoundary.test.tsx
Labels: Version: Minor

#3264 Expand openAuthModal helpers, update NavBar triggers
  docs/authentication.md
  package.json
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Components/__tests__/ArtistHeader.test.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Apps/Artist/Routes/Overview/Components/ZeroState.tsx
  src/Apps/Artist/Routes/Overview/Components/__tests__/RecommendedArtist.test.tsx
  src/Apps/Artist/Routes/Overview/Components/__tests__/ZeroState.test.tsx
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetailsAboutTheWorkFromPartner.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarArtists.test.tsx
  src/Apps/Artwork/Components/__tests__/ArtistInfo.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/__tests__/Header.test.tsx
  src/Apps/Collect2/Routes/Collection/Components/Header/index.tsx
  src/Components/Artwork/Save.tsx
  src/Components/Artwork/__tests__/Save.test.tsx
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/Menus/UserMenu.tsx
  src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBar/Menus/__tests__/UserMenu.test.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/Utils/__tests__/authentication.test.ts
  src/Components/NavBar/Utils/authentication.ts
  src/Components/NavBar/__tests__/NavBar.test.tsx
  src/Components/NavBar/__tests__/NavBarTracking.test.tsx
  src/Components/v2/ArtistCard.tsx
  src/Components/v2/__tests__/ArtistCard.test.tsx
  src/Utils/__tests__/openAuthModal.test.ts
  src/Utils/openAuthModal.ts
Labels: Version: Patch

#3261 [Consignments] Build out new Artist/Consign landing page
  .vscode/settings.json
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignMarketTrends.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignPageViews.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
  src/Apps/Artist/Routes/Consign/Components/SectionContainer.tsx
  src/Apps/Artist/Routes/Consign/Utils/getConsignmentData.ts
  src/Apps/Artist/Routes/Consign/Utils/staticCSVToJSONData.ts
  src/Apps/Artist/Routes/Consign/index.tsx
  src/Apps/Artist/Routes/Overview/Components/__tests__/WorksForSaleRail.test.tsx
  src/Apps/Artist/routes.tsx
  src/Apps/__stories__/ArtistApp.story.tsx
  src/Artsy/Router/NetworkOfflineMonitor.tsx
  src/Components/Artwork/Badge.tsx
  src/Components/Artwork/Details.tsx
  src/Components/Artwork/FillwidthItem.tsx
  src/__generated__/Consign_artist.graphql.ts
  src/__generated__/routes_ArtistConsignQuery.graphql.ts
Labels: Merge On Green, Version: Minor

#3273 Forgot form titles
  src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
  src/Components/Authentication/Desktop/ModalManager.tsx
  src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
  src/Components/Authentication/__tests__/Desktop/ModalManager.test.tsx
Labels: Version: Patch

#3275 Fix admin check on staging
  src/Apps/Artist/Routes/Consign/index.tsx
  src/Utils/user.ts
Labels: Version: Patch

#3276 [Consignments] Ensure dynamic data is passed
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignMarketTrends.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
Labels: Version: Patch

#3277 [Consignments] Update artist name
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignPageViews.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/Apps/Artist/Routes/Consign/index.tsx
Labels: Version: Patch

#3280 [Search] Fix tab UI spacing
  src/Apps/Search/Components/NavigationTabs.tsx
Labels: Version: Patch

#3274 [AUCT-930] static id verification processing page
  src/Apps/IdentityVerification/Processing.tsx
  src/Apps/IdentityVerification/__tests__/routes.test.tsx
  src/Apps/IdentityVerification/routes.tsx
Labels: Version: Patch

#3283 Update remaining mediator calls
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
Labels: Merge On Green, Version: Patch

#3238 [FX-1702] new mobile nav menu
  src/Components/NavBar/Menus/MobileLink.tsx
  src/Components/NavBar/Menus/NavigatorContextProvider.tsx
  src/Components/NavBar/Menus/NewMobileNavMenu.tsx
  src/Components/NavBar/Menus/__tests__/NewMobileNavMenu.test.tsx
  src/Components/NavBar/Menus/index.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/__tests__/NavBar.test.tsx
  src/Components/NavBar/menuData.ts
Labels: Version: Patch

#3282 User can navigate to IDV FAQ from the IDV landing page
  src/Apps/IdentityVerification/IdentityVerificationApp.tsx
Labels: Version: Patch

#3270 Add initial UI for years created filters on auction results
  package.json
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/index.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.test.tsx
  src/Apps/Conversation/ConversationApp.tsx
  src/Apps/Conversation/Routes/Conversation/index.tsx
  src/Apps/Conversation/__tests__/ConversationApp.test.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/__generated__/AuctionResults_Test_Query.graphql.ts
  src/__generated__/routes_AuctionResultsQuery.graphql.ts
Labels: Version: Minor

#3288 Update MP schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3286 Adds a 3rd Display Ad to Standard Articles
  src/Components/Publishing/Layouts/StandardLayout.tsx
  src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
  src/Components/Publishing/ReadMore/__tests__/ReadMore.test.tsx
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
  src/Components/Publishing/Typings.ts
Labels: Merge On Green, Version: Patch

#3290 Update MP schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3291 Prepopulate email input from URL query string on forgot password page
  src/Components/Authentication/FormSwitcher.tsx
  src/Components/Authentication/__tests__/FormSwitcher.test.tsx
Labels: Version: Minor

#3279 [Artist/Consign] Add tests
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignMarketTrends.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
  src/Apps/Artist/Routes/Consign/Utils/__tests__/getConsignmentData.test.tsx
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
  src/Apps/Artist/Routes/Consign/index.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/ConsignRouteFixture.ts
  src/__generated__/ConsignRoute_Test_Query.graphql.ts
Labels: Version: Patch

#3284 Auction Results Visual Tweaks
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/AuctionHouseFilter.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/SizeFilter.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionResultHeader.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/ImageWithFallback.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/TableSidebar.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
  src/__generated__/ArtistAuctionResultItem_auctionResult.graphql.ts
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/AuctionResults_Test_Query.graphql.ts
  src/__generated__/routes_AuctionResultsQuery.graphql.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#3293 Updates size on 3rd display ad on standard desktop
  src/Components/Publishing/Layouts/__tests__/StandardLayout.test.tsx
  src/Components/Publishing/Sections/Sections.tsx
  src/Components/Publishing/Sections/__tests__/Sections.test.tsx
  src/Components/Publishing/Sections/__tests__/__snapshots__/Sections.test.tsx.snap
Labels: Version: Patch

#3292 [Consignments] Add Artist/Consign SEO/meta tags
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignMarketTrends.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignMeta.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignPageViews.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
  src/Apps/Artist/Routes/Consign/Components/Subheader.tsx
  src/Apps/Artist/Routes/Consign/Components/__tests__/ArtistConsignMeta.test.tsx
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
  src/Apps/Artist/Routes/Consign/index.tsx
  src/Apps/Artist/routes.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/ConsignRouteFixture.ts
  src/DevTools/MockBoot.tsx
  src/Utils/getENV.tsx
  src/__generated__/ConsignRoute_Test_Query.graphql.ts
  src/__generated__/Consign_artist.graphql.ts
  src/__generated__/Consign_artworksByInternalID.graphql.ts
  src/__generated__/routes_ArtistConsignQuery.graphql.ts
  typings/sharify.d.ts
Labels: Version: Patch

#3295 Fix broken pagination on auction results page
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
Labels: Merge On Green

#3297 Update NetworkTimeout language
  src/Artsy/Router/NetworkTimeout.tsx
  src/Components/ErrorBoundary.tsx
  src/Components/__tests__/ErrorBoundary.test.tsx
Labels: Merge On Green

#3301 Adds social_embed section type to ad insertion logic
  src/Components/Publishing/Sections/Sections.tsx
Labels: Version: Patch

#3304 Missing Image Fix
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
Labels: Merge On Green, Version: Patch

#3294 Show a pass/fail message for a completed identity verification
  src/Apps/IdentityVerification/IdentityVerificationApp/CompleteFailed.tsx
  src/Apps/IdentityVerification/IdentityVerificationApp/CompletePassed.tsx
  src/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
  src/Apps/IdentityVerification/__fixtures__/routes_IdentityVerificationAppQuery.ts
  src/Apps/IdentityVerification/__tests__/IdentityVerificationApp.test.tsx
  src/Apps/IdentityVerification/__tests__/Utils/IdentityVerificationAppTestPage.tsx
  src/__generated__/IdentityVerificationAppStartMutation.graphql.ts
  src/__generated__/IdentityVerificationAppTestQuery.graphql.ts
  src/__generated__/IdentityVerificationApp_me.graphql.ts
  src/__generated__/StartIdentityVerificationMutation.graphql.ts
  src/__generated__/routes_IdentityVerificationAppQuery.graphql.ts
Labels: Version: Patch

#3306 cleanup stray text
  src/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
  src/Apps/IdentityVerification/__fixtures__/routes_IdentityVerificationAppQuery.ts
  src/__generated__/IdentityVerificationAppTestQuery.graphql.ts
  src/__generated__/IdentityVerificationApp_me.graphql.ts
  src/__generated__/StartIdentityVerificationMutation.graphql.ts
  src/__generated__/routes_IdentityVerificationAppQuery.graphql.ts
Labels: Merge On Green, Version: Patch

#3302 Add year created filter reset link
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/Components/FilterResetLink.tsx
Labels: Version: Minor

#3308 [Consignments] Artist/Consign QA
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignPageViews.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/Apps/Artist/Routes/Consign/Components/SectionContainer.tsx
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
  src/Apps/Artist/Routes/Consign/index.tsx
  src/Apps/Artist/routes.tsx
  src/Components/Artwork/FillwidthItem.tsx
Labels: Version: Patch

#3310 Copy: Remove stray whitespace in verification failed view
  src/Apps/IdentityVerification/IdentityVerificationApp/CompleteFailed.tsx
Labels: Merge On Green, Version: Patch

#3311 [Consignments] QA round 2
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignMarketTrends.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
  src/Apps/Artist/routes.tsx
  src/__generated__/routes_ArtistConsignQuery.graphql.ts
Labels: Version: Patch

#3305 Move AddressForm component out of the order app
  src/Apps/Auction/Components/BidForm.tsx
  src/Apps/Auction/Components/RegistrationForm.tsx
  src/Apps/Auction/Routes/__tests__/Utils/ConfirmBidTestPage.tsx
  src/Apps/Auction/Routes/__tests__/Utils/RegisterTestPage.tsx
  src/Apps/Order/Components/PaymentPicker.tsx
  src/Apps/Order/Components/__tests__/PaymentPicker.test.tsx
  src/Apps/Order/Routes/Shipping/index.tsx
  src/Apps/Order/Routes/__tests__/Payment.test.tsx
  src/Apps/Order/Routes/__tests__/Shipping.test.tsx
  src/Apps/Order/Utils/__tests__/formValidators.test.tsx
  src/Apps/Order/Utils/formValidators.tsx
  src/Components/AddressForm.tsx
  src/Components/Payment/PaymentForm.tsx
  src/Components/Payment/__tests__/PaymentForm.test.tsx
  src/Components/__stories__/AddressForm.story.tsx
  src/Components/__tests__/Utils/addressForm.ts
Labels: Jira Synced, Merge On Green, Version: Patch

#3289 Mobile nav menu analytics
  src/Artsy/Analytics/Schema/Values.ts
  src/Components/NavBar/Menus/MobileLink.tsx
  src/Components/NavBar/Menus/NewMobileNavMenu.tsx
  src/Components/NavBar/Menus/__tests__/MobileLink.test.tsx
  src/Components/NavBar/Menus/__tests__/NewMobileNavMenu.test.tsx
Labels: Version: Patch

#3312 Switch props.router.push back to window.locaion.assign for idv flow
  src/Apps/IdentityVerification/IdentityVerificationApp/index.tsx
  src/Apps/IdentityVerification/__tests__/IdentityVerificationApp.test.tsx
Labels: Version: Patch

#3313 the Address Form component should respect country selection for Euro only shipping
  src/Components/AddressForm.tsx
  src/Components/__stories__/AddressForm.story.tsx
Labels: Version: Patch

#3314 Video meta bug
  src/Components/Publishing/ArticleMeta.tsx
  src/Components/Publishing/__tests__/ArticleMeta.test.tsx
Labels: Version: Patch

#3315 Mobile nav menu ui qa
  src/Components/NavBar/Menus/NewMobileNavMenu.tsx
  src/Components/NavBar/menuData.ts
Labels: Version: Patch

#3316 Ensure year created check doesn't error on nulls
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
Labels: Version: Patch

#3319 [Mobile Nav Menu] adjust chevron position
  src/Components/NavBar/Menus/NewMobileNavMenu.tsx
Labels: Version: Patch

#3317 [Consignments] Add ArtistConsignButton
  src/Apps/Artist/Components/ArtistConsignButton.tsx
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Components/__stories__/ArtistConsignButton.story.tsx
  src/Apps/Artist/Components/__tests__/ArtistConsignButton.test.tsx
  src/Apps/Artist/Components/__tests__/ArtistHeader.test.tsx
  src/Apps/Artist/__tests__/routes.test.tsx
  src/Apps/__tests__/Fixtures/Artist/Components/ArtistHeader.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/ArtistConsignButtonQuery.graphql.ts
  src/__generated__/ArtistConsignButton_Test_Query.graphql.ts
  src/__generated__/ArtistConsignButton_artist.graphql.ts
  src/__generated__/ArtistHeader_Test_Query.graphql.ts
  src/__generated__/ArtistHeader_artist.graphql.ts
  src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Labels: Version: Patch

#3320 [FX-1877] launch new mobile nav menu
  src/Components/NavBar/Menus/MobileNavMenu.tsx
  src/Components/NavBar/Menus/NewMobileNavMenu.tsx
  src/Components/NavBar/Menus/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBar/Menus/__tests__/NewMobileNavMenu.test.tsx
  src/Components/NavBar/Menus/index.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/__tests__/NavBar.test.tsx
  src/Components/NavBar/__tests__/NavBarTracking.test.tsx
  src/Components/NavBar/menuData.ts
  src/Components/__stories__/NavBar.story.tsx
Labels: Version: Patch

#3321 [Consignments] Add "Sold for" price data
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/Apps/Artist/Routes/Consign/Utils/getConsignmentData.ts
  src/Apps/Artist/Routes/Consign/Utils/staticCSVToJSONData.ts
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/ConsignRouteFixture.ts
  src/Components/Artwork/FillwidthItem.tsx
Labels: Version: Patch

#3324 [Consignments] Launch Consign Page / Update FAQ
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
  src/Apps/Artist/routes.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/routes_ArtistConsignQuery.graphql.ts
Labels: Merge On Green, Version: Minor

#3323 gitignore node diagnostic reports
  .gitignore
Labels: Version: Trivial

#3322 [Consignments] Add images to Artist/Consign header
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/HeaderImages.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/__tests__/HeaderImages.test.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/index.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/Apps/Artist/Routes/Consign/Components/SectionContainer.tsx
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
  src/Apps/Artist/Routes/Consign/index.tsx
  src/Apps/__stories__/ArtistApp.story.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/ConsignRouteFixture.ts
  src/__generated__/ConsignRoute_Test_Query.graphql.ts
  src/__generated__/Consign_artworksByInternalID.graphql.ts
  src/__generated__/routes_ArtistConsignQuery.graphql.ts
Labels: Version: Patch

#3325 [ErrorBoundary] Add stack trace in development
  src/Components/ErrorBoundary.tsx
  src/Components/Modal/ErrorModal.tsx
  src/Components/Modal/__tests__/ErrorModal.test.tsx
  src/Components/__tests__/ErrorBoundary.test.tsx
Labels: Version: Minor

#3326 [Consignments] Remove shuffle on recently sold
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
Labels: Version: Patch

#3328 [HotFix] Comment out NewsNav date
  src/Components/Publishing/Nav/NewsNav.tsx
  src/Components/Publishing/Nav/__tests__/__snapshots__/NewsNav.test.tsx.snap
Labels: Version: Patch

#3330 Remove UI patch
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/AuctionResultsFixture.ts
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
  src/__generated__/AuctionResults_Test_Query.graphql.ts
  src/__generated__/routes_AuctionResultsQuery.graphql.ts
Labels: Version: Patch

#3329 [Artist] Add ConsignButton to Artist/Overview page
  src/Apps/Artist/Components/ArtistConsignButton.tsx
  src/Apps/Artist/Routes/Overview/__tests__/index.test.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/__generated__/Overview_artist.graphql.ts
  src/__generated__/routes_OverviewQuery.graphql.ts
Labels: Merge On Green, Version: Minor

#3332 Land on Work for Sale tab when coming from internal links
  src/Apps/Search/Routes/Artists/SearchResultsArtists.tsx
  src/Apps/WorksForYou/WorksForYouArtistFeed.tsx
  src/Apps/WorksForYou/WorksForYouFeed.tsx
  src/Components/NavBar/Menus/NotificationsMenu.tsx
Labels: Jira Synced, Version: Minor

#3331 [Refactor] Update Artist/Consign to support MP-based data
  data/schema.graphql
  src/Apps/Artist/Components/ArtistConsignButton.tsx
  src/Apps/Artist/Components/__tests__/ArtistConsignButton.test.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/ArtistConsignHeaderImages.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/__tests__/ArtistConsignHeaderImages.test.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/__tests__/HeaderImages.test.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/index.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignMarketTrends.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignMeta.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignPageViews.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/Apps/Artist/Routes/Consign/Components/__tests__/ArtistConsignMeta.test.tsx
  src/Apps/Artist/Routes/Consign/Utils/__tests__/getConsignmentData.test.tsx
  src/Apps/Artist/Routes/Consign/Utils/getConsignmentData.ts
  src/Apps/Artist/Routes/Consign/Utils/staticCSVToJSONData.ts
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
  src/Apps/Artist/Routes/Consign/index.tsx
  src/Apps/Artist/Routes/Overview/__tests__/index.test.tsx
  src/Apps/Artist/routes.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/ConsignRouteFixture.ts
  src/__generated__/ArtistConsignButtonQuery.graphql.ts
  src/__generated__/ArtistConsignButton_Test_Query.graphql.ts
  src/__generated__/ArtistConsignButton_artist.graphql.ts
  src/__generated__/ArtistConsignHeaderImages_artist.graphql.ts
  src/__generated__/ArtistConsignHeader_artist.graphql.ts
  src/__generated__/ArtistConsignMarketTrends_artist.graphql.ts
  src/__generated__/ArtistConsignMeta_artist.graphql.ts
  src/__generated__/ArtistConsignPageViews_artist.graphql.ts
  src/__generated__/ArtistConsignRecentlySold_artist.graphql.ts
  src/__generated__/ConsignRoute_Test_Query.graphql.ts
  src/__generated__/Consign_artist.graphql.ts
  src/__generated__/Consign_artworksByInternalID.graphql.ts
  src/__generated__/routes_ArtistConsignQuery.graphql.ts
  src/__generated__/routes_OverviewQuery.graphql.ts
Labels: Version: Minor

#3333 [Consignments] Guard against missing data
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignMeta.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/Apps/Artist/Routes/Consign/Components/__tests__/ArtistConsignMeta.test.tsx
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
  src/Apps/Artist/routes.tsx
  src/Apps/__stories__/ArtistApp.story.tsx
Labels: Merge On Green, Version: Patch
