Repository artsy/reaction, pull requests merged in 2020-04, with the labels that each got.

#3334 Display information about identity verification on credit card form
  src/Apps/Auction/Components/RegistrationForm.tsx
  src/Apps/Auction/Components/__stories__/RegistrationForm.story.tsx
  src/Apps/Auction/Routes/Register/index.tsx
  src/Apps/Auction/Routes/__tests__/Register.test.tsx
  src/Apps/Auction/__fixtures__/routes_RegisterQuery.ts
  src/Apps/__tests__/Fixtures/Auction/Routes/Register/index.ts
  src/__generated__/RegisterValidTestQuery.graphql.ts
  src/__generated__/Register_me.graphql.ts
  src/__generated__/Register_sale.graphql.ts
  src/__generated__/routes_RegisterQuery.graphql.ts
Labels: Version: Patch

#3307 Redirect logged in users to the works for sale tab
  src/Apps/Artist/Components/NavigationTabs.tsx
  src/Apps/Artist/__tests__/routes.test.tsx
  src/Apps/Artist/routes.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Labels: Merge On Green, Version: Minor

#3335 Organize MobileNav into folder
  src/Components/NavBar/Menus/MobileNavMenu/MobileLink.tsx
  src/Components/NavBar/Menus/MobileNavMenu/NavigatorContextProvider.tsx
  src/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileLink.test.tsx
  src/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBar/Menus/MobileNavMenu/index.tsx
  src/Components/NavBar/NavBar.tsx
Labels: Version: Patch

#3337 Revert "Redirect logged in users to the works for sale tab"
  src/Apps/Artist/Components/NavigationTabs.tsx
  src/Apps/Artist/__tests__/routes.test.tsx
  src/Apps/Artist/routes.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Labels: Version: Patch

#3336 [FX-1885] restructure the main nav menu
  src/Components/NavBar/Menus/MoreNavMenu.tsx
  src/Components/NavBar/Menus/__tests__/MoreNavMenu.test.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/__tests__/NavBar.test.tsx
Labels: Version: Patch

#3340 Ensure consign button shows for all artists
  src/Apps/Artist/Components/ArtistConsignButton.tsx
  src/Apps/Artist/Routes/Overview/__tests__/index.test.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Artsy/Analytics/trackingMiddleware.ts
  src/__generated__/Overview_artist.graphql.ts
  src/__generated__/routes_OverviewQuery.graphql.ts
Labels: Version: Patch

#3339 Use "Artsy for Galleries" instead of "Partner with Artsy" naming in mobile nav
  src/Components/NavBar/Menus/MobileNavMenu/index.tsx
  src/Components/NavBar/menuData.ts
Labels: Version: Patch

#3338 Fix redirect loop when user logged in on artist page
  src/Apps/Artist/Components/NavigationTabs.tsx
  src/Apps/Artist/__tests__/routes.test.tsx
  src/Apps/Artist/routes.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Labels: Version: Patch

#3341 [Bugfix] Add missing `action` call to ArtworkConsignButton
  src/Apps/Artist/Components/ArtistConsignButton.tsx
  src/Apps/Artist/Components/__tests__/ArtistConsignButton.test.tsx
Labels: Version: Patch

#3342 [Clientside Nav] Use app shell top-loader by default
  src/Apps/Artist/routes.tsx
  src/Artsy/Router/Route.tsx
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Components/Modal/ErrorModal.tsx
  src/Components/Modal/ModalDialog.tsx
Labels: Version: Patch

#3343 Remove contextModule from auction redirect
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
Labels: Merge On Green, Version: Patch

#3344 [Route] Log generic errors but throw on HttpError
  src/Artsy/Router/Route.tsx
Labels: Version: Patch

#3285 HOLD => [Clientside Nav] Bump A/B test to v5
  src/Apps/Artist/routes.tsx
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Auction/__tests__/routes.test.ts
  src/Apps/Components/AppShell.tsx
  src/Apps/Components/__tests__/AppShell.test.tsx
  src/Artsy/Analytics/trackingMiddleware.ts
  src/Artsy/Analytics/useRouteTracking.tsx
  src/Artsy/Router/Boot.tsx
  src/Artsy/Router/ErrorBoundary.tsx
  src/Artsy/Router/RenderStatus.tsx
  src/Artsy/Router/Utils/useMaybeReloadAfterInquirySignIn.tsx
  src/Artsy/Router/__tests__/ErrorBoundary.test.tsx
  src/Artsy/Router/__tests__/buildAppRoutes.test.tsx
  src/Artsy/SystemContext.tsx
  src/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
  src/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBar/Menus/index.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/Publishing/Sections/ArtworkCaption.tsx
  src/Components/Truncator.tsx
  typings/sharify.d.ts
Labels: Version: Minor

#3349 Sync schema
  data/schema.graphql
Labels: Version: Patch

#3350 #trivial data-test attrs for SignUpForm
  src/Components/Authentication/Desktop/SignUpForm.tsx
  src/Components/Authentication/Mobile/SignUpForm.tsx
Labels: Merge On Green, Version: Patch

#3352 [Clientside Nav] Clear cache on mutation
  src/Artsy/Relay/createRelaySSREnvironment.ts
Labels: Version: Patch

#3348 Adds the Art Keeps Going feature app + content
  data/schema.graphql
  src/Apps/FeatureAKG/Components/Feature.tsx
  src/Apps/FeatureAKG/Components/FeaturedArticles.tsx
  src/Apps/FeatureAKG/Components/FeaturedArtists.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedAuctions.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedCollections.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedFairs.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/index.tsx
  src/Apps/FeatureAKG/Components/FeaturedThisWeek.tsx
  src/Apps/FeatureAKG/Components/SelectedWorks.tsx
  src/Apps/FeatureAKG/FeatureApp.tsx
  src/Apps/FeatureAKG/__tests__/FeatureAKGRoute.test.tsx
  src/Apps/FeatureAKG/routes.tsx
  src/Apps/getAppRoutes.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Artsy/Router/buildServerApp.tsx
  src/Artsy/SystemContext.tsx
  src/DevTools/MockBoot.tsx
  src/__generated__/FeatureAKGRoute_Test_Query.graphql.ts
  src/__generated__/FeatureApp_viewer.graphql.ts
  src/__generated__/Feature_viewer.graphql.ts
  src/__generated__/FeaturedArticles_articles.graphql.ts
  src/__generated__/FeaturedAuctions_auctions.graphql.ts
  src/__generated__/FeaturedCollections_collections.graphql.ts
  src/__generated__/FeaturedFairs_fairs.graphql.ts
  src/__generated__/FeaturedRails_viewer.graphql.ts
  src/__generated__/SelectedWorks_selectedWorks.graphql.ts
  src/__generated__/routes_FeatureQuery.graphql.ts
Labels: Version: Minor

#3354 Adds video support for the Art Keeps Going campaign
  src/Apps/FeatureAKG/Components/Feature.tsx
  src/Apps/FeatureAKG/__tests__/FeatureAKGRoute.test.tsx
Labels: Merge On Green, Version: Patch

#3353 Update `back to <artist>` links to point directly to the overview page
  src/Apps/Artist/ArtistApp.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#3281 [MX-216] - Sign in with apple
  .storybook/webpack.config.js
  src/Components/Authentication/Desktop/LoginForm.tsx
  src/Components/Authentication/Desktop/ModalManager.tsx
  src/Components/Authentication/Desktop/SignUpForm.tsx
  src/Components/Authentication/Footer.tsx
  src/Components/Authentication/FormSwitcher.tsx
  src/Components/Authentication/Mobile/LoginForm.tsx
  src/Components/Authentication/Mobile/SignUpForm.tsx
  src/Components/Authentication/Types.ts
  src/Components/Authentication/__tests__/Desktop/ModalManager.test.tsx
  src/Components/Authentication/__tests__/Desktop/SignUpForm.test.tsx
  src/Components/Authentication/__tests__/FormSwitcher.test.tsx
  src/Components/__stories__/Authentication.story.tsx
  typings/sharify.d.ts
Labels: Version: Minor

#3356 Visual fixes based on QA
  src/Apps/FeatureAKG/Components/Feature.tsx
  src/Apps/FeatureAKG/Components/FeaturedArticles.tsx
  src/Apps/FeatureAKG/Components/FeaturedArtists.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedAuctions.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/index.tsx
  src/Apps/FeatureAKG/FeatureApp.tsx
  src/Apps/FeatureAKG/__tests__/FeatureAKGRoute.test.tsx
  src/Apps/FeatureAKG/routes.tsx
  src/__generated__/FeatureAKGRoute_Test_Query.graphql.ts
  src/__generated__/FeatureApp_viewer.graphql.ts
  src/__generated__/Feature_viewer.graphql.ts
  src/__generated__/FeaturedArticles_articles.graphql.ts
  src/__generated__/FeaturedRails_viewer.graphql.ts
  src/__generated__/routes_FeatureQuery.graphql.ts
Labels: Version: Patch

#3357 Add desktop menu item for navigating to conversations
  src/Components/NavBar/Menus/UserMenu.tsx
  src/Components/NavBar/Menus/__tests__/UserMenu.test.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/__tests__/NavBar.test.tsx
Labels: Version: Minor

#3358 Sync schema
  data/schema.graphql
Labels: Version: Patch

#3359 Add inbox to mobile nav menu
  src/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
  src/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.test.tsx
Labels: Jira Synced, Version: Minor

#3361 Adds tracking for Art Keeps Going + some other visual improvements
  src/Apps/FeatureAKG/Components/Feature.tsx
  src/Apps/FeatureAKG/Components/FeaturedArticles.tsx
  src/Apps/FeatureAKG/Components/FeaturedArtists.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedAuctions.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedCollections.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedFairs.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/index.tsx
  src/Apps/FeatureAKG/Components/FeaturedThisWeek.tsx
  src/Apps/FeatureAKG/Components/SelectedWorks.tsx
  src/Apps/FeatureAKG/__tests__/FeatureAKGRoute.test.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/FeatureAKGRoute_Test_Query.graphql.ts
  src/__generated__/FeaturedArticles_articles.graphql.ts
  src/__generated__/routes_FeatureQuery.graphql.ts
Labels: Version: Patch

#3362 Sync schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3365 Convert images to JPG and add poster for video
  src/Apps/FeatureAKG/Components/Feature.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/index.tsx
  src/Utils/resizer.ts
Labels: Merge On Green, Version: Minor

#3351 Search bar artist results link to works-for-sale page
  src/Components/Search/SearchBar.tsx
Labels: Jira Synced, Version: Minor

#3360 Add log out link back to mWeb
  src/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
  src/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.test.tsx
Labels: Version: Patch

#3364 [Consignments] Update ArtistConsignButton with targetSupply check
  data/schema.graphql
  src/Apps/Artist/Components/ArtistConsignButton.tsx
  src/Apps/Artist/Components/__tests__/ArtistConsignButton.test.tsx
  src/Apps/Artist/Routes/Overview/__tests__/index.test.tsx
  src/__generated__/ArtistConsignButtonQuery.graphql.ts
  src/__generated__/ArtistConsignButton_Test_Query.graphql.ts
  src/__generated__/ArtistConsignButton_artist.graphql.ts
  src/__generated__/routes_OverviewQuery.graphql.ts
Labels: Merge On Green, Version: Minor

#3367 #trivial - add data-test attrs
  src/Components/FollowButton/Button.tsx
  src/Components/FollowButton/ButtonDeprecated.tsx
  src/Components/FollowButton/__tests__/__snapshots__/Button.test.tsx.snap
  src/Components/Publishing/ToolTip/ArtistToolTip.tsx
  src/Components/Publishing/ToolTip/GeneToolTip.tsx
  src/Components/Publishing/ToolTip/LinkWithTooltip.tsx
  src/Components/Publishing/ToolTip/ToolTip.tsx
Labels: Merge On Green, Version: Patch

#3368 Revert /works-for-sale redirect
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Components/NavigationTabs.tsx
  src/Apps/Artist/__tests__/routes.test.tsx
  src/Apps/Artist/routes.tsx
  src/__generated__/routes_ArtistTopLevelQuery.graphql.ts
Labels: Merge On Green, Version: Patch

#3366 Use auth helpers for minimalCTABanner tracking args
  src/Artsy/Analytics/v2/Schema/Authentication.ts
  src/Artsy/Analytics/v2/Schema/ContextModule.ts
  src/Components/MinimalCtaBanner.tsx
  src/Components/Publishing/Banner/Banner.tsx
  src/Components/Publishing/Banner/__tests__/Banner.test.tsx
Labels: Version: Patch

#3371 Sync schema
  data/schema.graphql
  src/Apps/Collect/Routes/Collection/Components/Header/__tests__/__snapshots__/DefaultHeader.test.tsx.snap
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
Labels: Version: Patch

#3372 Fix snapshots
  src/Apps/Collect/Routes/Collection/Components/Header/__tests__/__snapshots__/DefaultHeader.test.tsx.snap
  src/Components/Publishing/EditorialFeature/Components/Vanguard2019/__tests__/__snapshots__/index.test.tsx.snap
Labels: Version: Patch

#3375 Remove inbox icon from menu
  src/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
  src/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.test.tsx
Labels: Merge On Green, Version: Patch

#3374 Bump timeout
  src/Artsy/Router/NetworkTimeout.tsx
Labels: Version: Patch

#3377 [Clientside Nav] Move Pageloader from Palette
  src/Artsy/Router/PageLoader.tsx
  src/Artsy/Router/RenderStatus.tsx
Labels: Version: Patch

#3379 Use logger instead of console.error to capture missing data reports
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
Labels: Merge On Green, Version: Patch

#3380 Bump palette
  package.json
  yarn.lock
Labels: Version: Patch

#3345 Make Artwork Bid Actions Identity Verification Aware
  .env.oss
  src/Apps/Artwork/ArtworkApp.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarBidAction.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__stories__/ArtworkSidebarBidActionStory.story.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarBidAction.test.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/Apps/Artwork/routes.tsx
  src/Apps/__stories__/ArtworkApp.story.tsx
  src/Apps/__tests__/Fixtures/Artwork/ArtworkSidebar/ArtworkSidebarBidAction.ts
  src/Apps/__tests__/Fixtures/Auction/Routes/Register/index.ts
  src/Utils/identityVerificationRequirements.ts
  src/__generated__/ArtworkApp_me.graphql.ts
  src/__generated__/ArtworkSidebarBidAction_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebarBidAction_artwork.graphql.ts
  src/__generated__/ArtworkSidebarBidAction_me.graphql.ts
  src/__generated__/ArtworkSidebarQuery.graphql.ts
  src/__generated__/ArtworkSidebarStoryQuery.graphql.ts
  src/__generated__/ArtworkSidebar_Test_Query.graphql.ts
  src/__generated__/ArtworkSidebar_me.graphql.ts
  src/__generated__/routes_ArtworkQuery.graphql.ts
Labels: Version: Minor

#3384 Add data-test attribute on ForgotPassword forms
  src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
  src/Components/Authentication/Mobile/ForgotPasswordForm.tsx
Labels: Merge On Green, Version: Minor

#3385 #trivial Add integrity data attrs
  src/Apps/Collect/Routes/Collection/Components/Header/index.tsx
  src/Components/Artwork/GridItem.tsx
  src/Components/Artwork/Save.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
Labels: Merge On Green, Version: Patch

#3386 Remove ENABLE_REQUEST_CONDITION_REPORT feature flag
  .storybook/webpack.config.js
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAdditionalInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/__tests__/ArtworkDetails.test.tsx
  typings/sharify.d.ts
Labels: Version: Minor

#3388 Upgrade storybook and related dependencies
  package.json
  yarn.lock
Labels: Version: Trivial

#3390 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Minor

#3389 Update conversations UI to be closer to design spec
  src/Apps/Conversation/Components/Conversation.tsx
  src/Apps/Conversation/Components/Message.tsx
  src/Apps/Conversation/Components/TimeSince.tsx
  src/__generated__/Conversation_conversation.graphql.ts
  src/__generated__/routes_DetailQuery.graphql.ts
Labels: Version: Minor

#3387 Add 2FA user settings component
  src/Components/UserSettingsTwoFactorAuthentication/__stories__/UserSettingsTwoFactorAuthentication.story.tsx
  src/Components/UserSettingsTwoFactorAuthentication/index.tsx
  src/__generated__/UserSettingsTwoFactorAuthenticationQuery.graphql.ts
  src/__generated__/UserSettingsTwoFactorAuthenticationStoryQuery.graphql.ts
  src/__generated__/UserSettingsTwoFactorAuthentication_me.graphql.ts
Labels: Merge On Green, Version: Minor

#3391 Remove trailing separator char from Storybook story path
  src/Components/Publishing/__stories__/ToolTip.story.tsx
Labels: Merge On Green, Version: Trivial

#3392 #trivial Add test attr for integrity
  src/Apps/Collect/Routes/Collection/Components/Header/index.tsx
Labels: Merge On Green, Version: Patch

#3396 [Consignments] Add `flow: consignments` to tracking
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/index.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
  src/Artsy/Analytics/Schema/Values.ts
Labels: Merge On Green, Version: Patch

#3397 [PURCHASE-1852] Add checkbox and filtering for lots with nil date information
  data/schema.graphql
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/AuctionFilters/YearCreated.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResultsFilterContext.test.tsx
  src/__generated__/ArtistAuctionResultsQuery.graphql.ts
  src/__generated__/ArtistAuctionResults_artist.graphql.ts
Labels: Version: Minor

#3398 Add mocked enrollment UI for the 2FA App Authenticator method
  package.json
  src/Components/UserSettingsTwoFactorAuthentication/Components/AppSecondFactorMethod.tsx
  src/Components/UserSettingsTwoFactorAuthentication/Components/AppSecondFactorSetupModal.tsx
  src/Components/UserSettingsTwoFactorAuthentication/Components/__stories__/AppSecondFactorMethod.story.tsx
  src/Components/UserSettingsTwoFactorAuthentication/UserSettingsTwoFactorAuthentication.tsx
  src/Components/UserSettingsTwoFactorAuthentication/__stories__/UserSettingsTwoFactorAuthentication.story.tsx
  src/Components/UserSettingsTwoFactorAuthentication/__tests__/UserSettingsTwoFactorAuthentication.test.tsx
  src/Components/UserSettingsTwoFactorAuthentication/__tests__/Utils/UserSettingsTestPage.tsx
  src/__generated__/UserSettingsTwoFactorAuthenticationTestQuery.graphql.ts
  yarn.lock
Labels: Merge On Green, Version: Minor

#3402 Bump timeout of "ArtworkFilter/desktop/renders default UI items" spec
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
Labels: Version: Trivial

#3403 Expose static pages in search results/autocomplete
  src/Apps/Search/Components/NavigationTabs.tsx
  src/Apps/Search/routes.tsx
Labels: Merge On Green, Version: Minor

#3399 Add mocked UI for the 2FA backup codes
  src/Components/UserSettingsTwoFactorAuthentication/Components/BackupSecondFactorMethod.tsx
  src/Components/UserSettingsTwoFactorAuthentication/Components/__stories__/BackupSecondFactorMethod.story.tsx
  src/Components/UserSettingsTwoFactorAuthentication/UserSettingsTwoFactorAuthentication.tsx
Labels: Merge On Green, Version: Minor

#3393 Update artwork preview in conversation
  src/Apps/Conversation/Components/Conversation.tsx
Labels: Version: Minor

#3405 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3407 [Clientside Nav] Fix referrer edgecase
  src/Apps/Artwork/ArtworkApp.tsx
  src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
  src/Artsy/Analytics/trackExperimentViewed.tsx
  src/Artsy/Analytics/trackingMiddleware.ts
Labels: Version: Patch

#3408 Rollback JSDOM v16 upgrade
  package.json
  src/Components/UserSettingsTwoFactorAuthentication/__tests__/UserSettingsTwoFactorAuthentication.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilter.test.tsx
  yarn.lock
Labels: Merge On Green, Version: Trivial

#3373 [AUCT-952] Bidder sees copy in "about to register" and "registration pending" modals with information about identity verification
  src/Apps/Auction/Routes/Register/index.tsx
  src/Components/Auction/AuctionRegistrationModal.tsx
  src/Components/Auction/PostRegistrationModal.tsx
  src/Components/Auction/__stories__/AuctionRegistrationModal.story.tsx
  src/Components/Auction/__tests__/AuctionRegistrationModal.test.tsx
  src/Components/Auction/__tests__/PostRegistrationModal.test.tsx
  src/Utils/identityVerificationRequirements.ts
Labels: Version: Patch

#3406 Fix conversation page from erroring out due to null timestamp
  src/Apps/Conversation/Components/Conversation.tsx
  src/Apps/Conversation/Components/TimeSince.tsx
Labels: Version: Patch

#3411 Use @artsy/cohesion
  package.json
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Apps/Artist/Routes/Overview/Components/WorksForSaleRail.tsx
  src/Apps/Artist/Routes/Overview/Components/ZeroState.tsx
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkActions.tsx
  src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/index.tsx
  src/Apps/Collect/Routes/Collection/Components/Header/index.tsx
  src/Artsy/Analytics/v2/Events/AuthImpression.ts
  src/Artsy/Analytics/v2/Events/__tests__/AuthImpression.test.ts
  src/Artsy/Analytics/v2/Events/index.ts
  src/Artsy/Analytics/v2/Schema/ActionType.ts
  src/Artsy/Analytics/v2/Schema/Authentication.ts
  src/Artsy/Analytics/v2/Schema/ContextModule.ts
  src/Artsy/Analytics/v2/Schema/Events.ts
  src/Artsy/Analytics/v2/Schema/index.ts
  src/Artsy/Analytics/v2/index.ts
  src/Components/ArtistCard.tsx
  src/Components/Artwork/Fillwidth.tsx
  src/Components/Artwork/FillwidthItem.tsx
  src/Components/Artwork/GridItem.tsx
  src/Components/Artwork/Save.tsx
  src/Components/Artwork/__tests__/FillwidthItem.test.tsx
  src/Components/ArtworkGrid/ArtworkGrid.tsx
  src/Components/Authentication/FormSwitcher.tsx
  src/Components/Authentication/Types.ts
  src/Components/Authentication/__tests__/Desktop/ModalManager.test.tsx
  src/Components/Authentication/__tests__/FormSwitcher.test.tsx
  src/Components/Follow.tsx
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/FollowButton/FollowGeneButton.tsx
  src/Components/Gene/ArtistRow.tsx
  src/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/Publishing/Banner/Banner.tsx
  src/Components/RecentlyViewed.tsx
  src/Components/Tag/TagArtworks.tsx
  src/Components/__stories__/Authentication.story.tsx
  src/Components/__stories__/Carousel.story.tsx
  src/Components/__stories__/Fillwidth.story.tsx
  src/Components/__tests__/ArtistCard.test.tsx
  src/Utils/__tests__/openAuthModal.test.ts
  src/Utils/openAuthModal.ts
  yarn.lock
Labels: Version: Minor

#3404 Update conversation inbox visuals on mobile
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/AuctionResults/Components/ImageWithFallback.tsx
  src/Apps/Conversation/Components/ConversationSnippet.tsx
  src/Apps/Conversation/Components/Conversations.tsx
  src/Apps/Conversation/__tests__/ConversationApp.test.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#3369 Update desktop nav menu
  src/Components/NavBar/Menus/DropDownMenu.tsx
  src/Components/NavBar/Menus/DropDownSection.tsx
  src/Components/NavBar/Menus/TwoColumnDropDownSection.tsx
  src/Components/NavBar/Menus/__tests__/DropDownMenu.test.tsx
  src/Components/NavBar/Menus/__tests__/DropDownSection.test.tsx
  src/Components/NavBar/Menus/index.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
  src/Components/NavBar/menuData.ts
Labels: Version: Minor

#3412 Fix conversation page layout, link off to image
  src/Apps/Conversation/Components/Conversation.tsx
  src/Apps/Conversation/Routes/Conversation/index.tsx
  src/__generated__/Conversation_conversation.graphql.ts
  src/__generated__/routes_DetailQuery.graphql.ts
Labels: Version: Patch

#3413 Reverts Hotfix; Brings back dynamic nav bar on /news pages
  src/Components/Publishing/Nav/NewsNav.tsx
  src/Components/Publishing/Nav/__tests__/__snapshots__/NewsNav.test.tsx.snap
Labels: Version: Patch

#3417 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3420 Add data-test attrs for artist page
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Apps/Artist/Routes/Overview/Components/WorksForSaleRail.tsx
  src/Components/Carousel.tsx
Labels: Version: Patch

#3421 Add whitespace to before/after FAQ link
  src/Components/Auction/PostRegistrationModal.tsx
Labels: Merge On Green, Version: Patch

#3416 Style updates to new nav drop down menu
  src/Components/NavBar/Menus/DropDownMenu.tsx
  src/Components/NavBar/NavBar.tsx
  src/__generated__/SearchResultsEntityQuery.graphql.ts
  src/__generated__/routes_SearchResultsEntityQuery.graphql.ts
Labels: Version: Patch

#3424 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3423 [FX-1905] Fix notification badge placement
  src/Components/NavBar/NotificationsBadge.tsx
  src/Components/NavBar/menuData.ts
Labels: Merge On Green, Version: Patch

#3425 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Minor

#3427 #trivial - Artist page data-test attrs
  src/Apps/Artist/Components/NavigationTabs.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
Labels: Version: Patch

#3431 Move cohesion to be a dev dep of reaction
  package.json
Labels: Merge On Green, Version: Trivial

#3433 Auction results auth intent conforms to schema
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
Labels: Version: Patch

#3419 [Consignments] Add context path query param
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/index.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
  src/Apps/Artist/Routes/Consign/Components/Utils/__tests__/getConsignSubmissionUrl.test.ts
  src/Apps/Artist/Routes/Consign/Components/Utils/getConsignSubmissionUrl.ts
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
  src/Apps/Artist/Routes/Consign/index.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/ArtistConsignFAQ_artist.graphql.ts
  src/__generated__/ArtistConsignHeader_artist.graphql.ts
  src/__generated__/ArtistConsignHowToSell_artist.graphql.ts
  src/__generated__/ArtistConsignSellArt_artist.graphql.ts
  src/__generated__/ConsignRoute_Test_Query.graphql.ts
  src/__generated__/Consign_artist.graphql.ts
  src/__generated__/routes_ArtistConsignQuery.graphql.ts
Labels: Version: Minor

#3436 [Refactor] Modernize SystemContext, make app shell width configurable
  package.json
  src/Apps/Components/AppContainer.tsx
  src/Artsy/Router/Boot.tsx
  src/Artsy/Router/RenderStatus.tsx
  src/Artsy/Router/__tests__/buildClientApp.test.tsx
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Artsy/Router/buildAppRoutes.tsx
  src/Artsy/Router/interceptLinks.ts
  src/Artsy/SystemContext.tsx
  src/Artsy/__tests__/SystemContext.test.tsx
  src/Artsy/__tests__/systemContextState.test.tsx
  src/Artsy/systemContextState.tsx
  yarn.lock
Labels: Merge On Green, Version: Minor

#3438 Fix useSystemContext invocation
  src/Artsy/Router/Boot.tsx
Labels: Version: Patch

#3439 Fixes collapsing container
  src/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/OtherCollectionsRail/OtherCollectionEntity.tsx
Labels: Merge On Green, Version: Patch

#3435 Add a header to the conversation view on mobile
  src/Apps/Conversation/Components/Conversation.tsx
Labels: Jira Synced, Version: Minor

#3440 [Consignments] Add full-screen support to /consign
  src/Apps/Artist/ArtistApp.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/ArtistConsignHeaderImages.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/__tests__/ArtistConsignHeaderImages.test.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/index.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/Apps/Artist/Routes/Consign/Components/SectionContainer.tsx
  src/Apps/Artist/Routes/Consign/Components/Subheader.tsx
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
  src/Apps/Components/AppContainer.tsx
  src/Apps/__tests__/Fixtures/Artist/Routes/ConsignRouteFixture.ts
  src/Artsy/Router/Boot.tsx
  src/Artsy/Router/RenderStatus.tsx
  src/Artsy/Router/__tests__/buildClientApp.test.tsx
  src/Artsy/Router/__tests__/buildServerApp.test.tsx
  src/Artsy/Router/buildAppRoutes.tsx
  src/Artsy/SystemContext.tsx
  src/Artsy/__tests__/SystemContext.test.tsx
  src/Artsy/__tests__/systemContextState.test.tsx
  src/Artsy/systemContextState.tsx
  src/Components/Footer.tsx
  src/__generated__/ArtistConsignRecentlySold_artist.graphql.ts
  src/__generated__/ConsignRoute_Test_Query.graphql.ts
  src/__generated__/routes_ArtistConsignQuery.graphql.ts
Labels: Version: Patch

#3442 Hide recently viewed on marketing page
  src/Apps/Artist/ArtistApp.tsx
Labels: Version: Patch

#3443 [Bugfix] Make /collection/id Header safer
  src/Apps/Collect/Routes/Collection/Components/Header/__tests__/Header.test.tsx
  src/Apps/Collect/Routes/Collection/Components/Header/index.tsx
Labels: Version: Patch

#3441 [FX-1908] Navbar menu qa
  src/Components/NavBar/Menus/DropDownMenu.tsx
  src/Components/NavBar/Menus/DropDownSection.tsx
  src/Components/NavBar/Menus/TwoColumnDropDownSection.tsx
  src/Components/NavBar/Menus/__tests__/DropDownMenu.test.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
Labels: Version: Patch

#3444 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3446 Make AKG page more resilient towards mismatched data
  src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedAuctions.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedCollections.tsx
  src/Apps/FeatureAKG/Components/FeaturedRails/FeaturedFairs.tsx
  src/Apps/FeatureAKG/__tests__/FeatureAKGRoute.test.tsx
Labels: Version: Patch

#3450 Improves Carousel typings
  src/Apps/Artist/Components/ArtistCollectionsRail/ArtistCollectionsRail.tsx
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Apps/Artist/Routes/Overview/Components/WorksForSaleRail.tsx
  src/Apps/Artist/Routes/Overview/index.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/ArtworkImageBrowser.tsx
  src/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/ArtistSeriesRail/index.tsx
  src/Components/Carousel.tsx
  src/Components/RecentlyViewed.tsx
  src/__generated__/ArtistSeriesRail_collectionGroup.graphql.ts
  src/__generated__/CollectionAppQuery.graphql.ts
  src/__generated__/CollectionsHubRailsStoryQuery.graphql.ts
Labels: Version: Patch

#3447 [NavBar Drop Down QA] add a new prop to control background color
  src/Components/NavBar/Menus/DropDownMenu.tsx
  src/Components/NavBar/Menus/DropDownSection.tsx
  src/Components/NavBar/Menus/TwoColumnDropDownSection.tsx
Labels: Version: Patch

#3452 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3453 [Consignments] Remove client-side tracking
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/index.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
Labels: Version: Patch

#3456 Revert "[Consignments] Remove client-side tracking"
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/index.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHowToSell.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignSellArt.tsx
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
Labels: Version: Patch

#3459 Ensure notification badge proprely aligned
  src/Components/NavBar/NavItem.tsx
  src/Components/NavBar/NotificationsBadge.tsx
Labels: Version: Patch

#3462 Update 2FA enrollment
  src/Components/UserSettings/TwoFactorAuthentication/ApiError.ts
  src/Components/UserSettings/TwoFactorAuthentication/Components/ApiErrorModal.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/Modal.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/Mutation/CreateAppSecondFactor.ts
  src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/Mutation/UpdateAppSecondFactor.ts
  src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/__stories__/AppSecondFactor.story.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/Mutation/CreateBackupSecondFactors.ts
  src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/__stories__/BackupSecondFactor.story.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/Mutation/DisableSecondFactor.ts
  src/Components/UserSettings/TwoFactorAuthentication/Components/Mutation/EnableSecondFactor.ts
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Modal.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Mutation/CreateSmsSecondFactor.ts
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Mutation/DeliverSecondFactor.ts
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Mutation/UpdateSmsSecondFactor.ts
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/__stories__/SmsSecondFactor.story.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
  src/Components/UserSettings/TwoFactorAuthentication/__tests__/TwoFactorAuthentication.test.tsx
  src/Components/UserSettings/TwoFactorAuthentication/__tests__/fixtures.ts
  src/__generated__/AppSecondFactorStorySuccessQuery.graphql.ts
  src/__generated__/CreateAppSecondFactorMutation.graphql.ts
  src/__generated__/CreateBackupSecondFactorsMutation.graphql.ts
  src/__generated__/CreateSmsSecondFactorMutation.graphql.ts
  src/__generated__/DeliverSecondFactorMutation.graphql.ts
  src/__generated__/DisableSecondFactorMutation.graphql.ts
  src/__generated__/EnableSecondFactorMutation.graphql.ts
  src/__generated__/SmsSecondFactorStoryErrorQuery.graphql.ts
  src/__generated__/SmsSecondFactorStorySuccessQuery.graphql.ts
  src/__generated__/SmsSecondFactorStoryUndeliverableQuery.graphql.ts
  src/__generated__/SmsSecondFactorStoryUpdateErrorQuery.graphql.ts
  src/__generated__/UpdateAppSecondFactorMutation.graphql.ts
  src/__generated__/UpdateSmsSecondFactorMutation.graphql.ts
Labels: Merge On Green, Version: Minor

#3451 [GALL-2778] - add a note about Covid-19 into status page
  src/Apps/Order/Routes/Review/index.tsx
  src/Apps/Order/Routes/Status/index.tsx
Labels: Version: Patch

#3457 [FX-1925] Fix some minor issues and launch nav drop down menus
  src/Components/NavBar/NavBar.tsx
  src/Components/NavBar/NavItem.tsx
  src/Components/NavBar/__tests__/NavBar.test.tsx
Labels: Version: Patch

#3445 [FX-1819] Links to consign page in mobile nav
  src/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
  src/Components/NavBar/Menus/MobileNavMenu/__tests__/MobileNavMenu.test.tsx
  src/Components/NavBar/menuData.ts
Labels: Merge On Green, Version: Patch

#3461 Add Empty conversations view
  src/Apps/Conversation/Components/Conversation.tsx
  src/Apps/Conversation/Components/Conversations.tsx
  src/Apps/Conversation/Components/NoMessages.tsx
  src/Apps/Conversation/ConversationApp.tsx
  src/Apps/Conversation/Routes/Conversation/index.tsx
  src/Apps/Conversation/__tests__/ConversationApp.test.tsx
  src/Apps/Conversation/routes.tsx
  src/Artsy/Router/Utils/findCurrentRoute.tsx
Labels: Version: Minor

#3463 Fixes relative paths for OSX
  src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/__stories__/AppSecondFactor.story.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/__stories__/BackupSecondFactor.story.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/__tests__/index.test.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/__stories__/SmsSecondFactor.story.tsx
  src/Components/UserSettings/TwoFactorAuthentication/__stories__/TwoFactorAuthenticationStory.story.tsx
  src/Components/UserSettings/TwoFactorAuthentication/__tests__/TwoFactorAuthentication.test.tsx
Labels: Merge On Green, Version: Trivial

#3460 Improves server-side render of collect header
  src/Apps/Collect/Routes/Collection/Components/Header/DefaultHeader.tsx
  src/Apps/Collect/Routes/Collection/Components/Header/DefaultHeaderArtwork.tsx
  src/Apps/Collect/Routes/Collection/Components/Header/__tests__/DefaultHeader.test.tsx
  src/Apps/Collect/Routes/Collection/Components/Header/__tests__/__snapshots__/DefaultHeader.test.tsx.snap
  src/Apps/Collect/Routes/Collection/Components/Header/__tests__/fixtures/artworks.ts
  src/Apps/Collect/Routes/Collection/Components/Header/index.tsx
  src/Apps/Collect/Routes/Collection/index.tsx
  src/Apps/__stories__/Collect.story.tsx
  src/Utils/typeSupport.ts
  src/__generated__/CollectionAppQuery.graphql.ts
  src/__generated__/DefaultHeaderArtwork_artwork.graphql.ts
  src/__generated__/DefaultHeader_headerArtworks.graphql.ts
Labels: Version: Patch

#3464 #trivial - Add test attrs for artwork page auth entrypoints
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/index.tsx
  src/Apps/Artwork/Components/OtherWorks/RelatedWorksArtworkGrid.tsx
  src/Apps/Artwork/Components/OtherWorks/index.tsx
  src/Components/ArtistCard.tsx
  src/Components/Artwork/Save.tsx
  src/Components/FollowIcon.tsx
Labels: Merge On Green, Version: Patch

#3465 [FX-1926] Minor ui dropdown fixes
  src/Components/NavBar/Menus/DropDownMenu/DropDownMenu.tsx
  src/Components/NavBar/Menus/DropDownMenu/DropDownSection.tsx
  src/Components/NavBar/Menus/DropDownMenu/TwoColumnDropDownSection.tsx
  src/Components/NavBar/NavItem.tsx
Labels: Version: Patch

#3467 [Toolchain] Replace TSLint with ESLint
  .eslintignore
  .eslintrc.js
  .gitignore
  package.json
  yarn.lock
Labels: Version: Minor

#3466 [FX-1894] change top artists
  src/Components/NavBar/menuData.ts
Labels: Version: Patch

#3469 Correct findCurrentRoute logic to unbreak artist page
  src/Artsy/Router/Utils/__tests__/findCurrentRoute.test.ts
  src/Artsy/Router/Utils/findCurrentRoute.tsx
Labels: Version: Patch

#3474 Use cohesion v1
  package.json
  src/Apps/Artist/Components/ArtistHeader.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/Overview/Components/RecommendedArtist.tsx
  src/Apps/Artist/Routes/Overview/Components/ZeroState.tsx
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarArtists.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Collect/Routes/Collection/Components/Header/index.tsx
  src/Components/ArtistCard.tsx
  src/Components/Artwork/Fillwidth.tsx
  src/Components/Artwork/Save.tsx
  src/Components/Authentication/__tests__/Desktop/ModalManager.test.tsx
  src/Components/Authentication/__tests__/FormSwitcher.test.tsx
  src/Components/Follow.tsx
  src/Components/FollowButton/FollowArtistButton.tsx
  src/Components/FollowButton/FollowGeneButton.tsx
  src/Components/NavBar/Menus/MobileNavMenu/MobileNavMenu.tsx
  src/Components/NavBar/NavBar.tsx
  src/Components/Publishing/Banner/Banner.tsx
  src/Components/__stories__/Authentication.story.tsx
  src/Utils/__tests__/openAuthModal.test.ts
  src/Utils/openAuthModal.ts
  yarn.lock
Labels: Merge On Green, Version: Patch
