Repository artsy/reaction, pull requests merged in 2020-05, with the labels that each got.

#3476 [mWeb] Support OTP prompt on mobile login modal via Formik setStatus
  src/Components/Authentication/Mobile/LoginForm.tsx
  src/Components/__stories__/Authentication.story.tsx
Labels: Version: Patch

#3477 [Consignments] Hide recently sold data point if missing
  package.json
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignRecentlySold.tsx
  src/Apps/Artist/Routes/Consign/__tests__/ConsignRoute.test.tsx
Labels: Version: Patch

#3455 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3478 Fixes for nullable artwork images
  src/Apps/Collect/Routes/Collection/Components/Header/DefaultHeader.tsx
  src/Apps/Collect/Routes/Collection/Components/Header/DefaultHeaderArtwork.tsx
  src/Apps/Collect/Routes/Collection/Components/Header/__tests__/DefaultHeader.test.tsx
  src/Apps/Collect/Routes/Collection/Components/Header/__tests__/fixtures/artworks.ts
  src/Apps/__stories__/Collect.story.tsx
Labels: Version: Patch

#3481 Fix Formik boolean handling
  src/Components/Authentication/Desktop/SignUpForm.tsx
  src/Components/Authentication/Mobile/SignUpForm.tsx
Labels: Merge On Green, Version: Patch

#3479 Fixes swallowed assertions in async tests
  src/Apps/Artist/Components/ArtistCollectionsRail/__tests__/ArtistCollectionsRail.test.tsx
  src/Apps/Artwork/Components/__tests__/PricingContext.test.tsx
  src/Apps/Artwork/Components/__tests__/PricingContextModal.test.tsx
  src/Apps/Order/Utils/__tests__/commitMutation.test.tsx
  src/Components/Auction/__tests__/AuctionRegistrationModal.test.tsx
  src/Components/Auction/__tests__/PostRegistrationModal.test.tsx
  src/Components/RelatedCollectionsRail/__tests__/RelatedCollectionsRail.test.tsx
  src/Components/Search/__tests__/SearchBar.test.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.test.tsx
  src/DevTools/RootTestPage.tsx
  src/DevTools/flushPromiseQueue.ts
  src/DevTools/index.ts
Labels: Version: Trivial

#3482 Fixes paths to flushPromiseQueue
  src/Components/Authentication/__tests__/Mobile/LoginForm.test.tsx
  src/Components/Authentication/__tests__/Mobile/SignUpForm.test.tsx
Labels: Version: Trivial

#3484 Deploys Storybook to S3
  .circleci/config.yml
  package.json
Labels: Version: Trivial

#3485 Move storybook behind queue
  .circleci/config.yml
Labels: Version: Trivial

#3483 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3486 Fix auction results layout on mobile
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
Labels: Merge On Green, Version: Patch

#3487 Downgrade storybooks
  package.json
  yarn.lock
Labels: Version: Patch

#3492 Ensure storybook build is gated behind queue
  .circleci/config.yml
Labels: Merge On Green, Version: Trivial

#3491 [ViewingRoom] Stub out viewing room
  src/Apps/ViewingRoom/Components/.gitkeep
  src/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/Apps/ViewingRoom/__tests__/.gitkeep
  src/Apps/ViewingRoom/routes.tsx
  src/Apps/__stories__/AppShell.story.tsx
  src/Apps/__stories__/ViewingRoom.story.tsx
  src/Apps/getAppRoutes.tsx
  src/__generated__/routes_ViewingRoomQuery.graphql.ts
Labels: Version: Patch

#3493 Enable faster PR builds
  .circleci/config.yml
Labels: Version: Patch

#3495 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3494 Updates mobile artwork filters layout
  src/Components/v2/ArtworkFilter/ArtworkFilterMobileActionSheet.tsx
  src/Components/v2/ArtworkFilter/__tests__/ArtworkFilterMobileActionSheet.test.tsx
Labels: Version: Minor

#3414 Change CTA and flow from "log in" to "sign-up" on auction results page
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
Labels: Jira Synced, Merge On Green, Version: Patch

#3497 [ViewingRoom] Break apart components
  src/Apps/ViewingRoom/Components/.gitkeep
  src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/Apps/ViewingRoom/Components/ViewingRoomTabBar.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomBottomImage.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomIntro.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomStatements.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx
  src/Apps/ViewingRoom/Routes/Statement/index.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
  src/Apps/ViewingRoom/Routes/Works/index.tsx
  src/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/Apps/ViewingRoom/routes.tsx
  src/Artsy/Router/useRouter.tsx
Labels: Version: Patch

#3498 [ViewingRoom] Make responsive
  src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/Apps/ViewingRoom/Components/ViewingRoomTabBar.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomIntro.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomStatements.tsx
  src/Apps/ViewingRoom/Routes/Statement/index.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
  src/Apps/ViewingRoom/Routes/Works/index.tsx
Labels: Version: Patch

#3499 [ViewingRoom] Connect to data
  src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/Apps/ViewingRoom/Components/ViewingRoomTabBar.tsx
  src/Apps/ViewingRoom/Components/__tests__/ViewingRoomHeader.test.tsx
  src/Apps/ViewingRoom/Components/__tests__/ViewingRoomTabBar.test.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomBottomImage.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomIntro.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomStatements.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomSubsections.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx
  src/Apps/ViewingRoom/Routes/Statement/ViewingRoomStatementRoute.tsx
  src/Apps/ViewingRoom/Routes/Statement/__tests__/ViewingRoomStatementRoute.test.tsx
  src/Apps/ViewingRoom/Routes/Statement/index.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
  src/Apps/ViewingRoom/Routes/Works/ViewingRoomWorksRoute.tsx
  src/Apps/ViewingRoom/Routes/Works/__tests__/ViewingRoomWorksRoute.test.tsx
  src/Apps/ViewingRoom/Routes/Works/index.tsx
  src/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/Apps/ViewingRoom/__tests__/.gitkeep
  src/Apps/ViewingRoom/__tests__/ViewingRoomApp.test.tsx
  src/Apps/ViewingRoom/routes.tsx
  src/Apps/__stories__/ViewingRoom.story.tsx
  src/Artsy/Router/useRouter.tsx
  src/__generated__/ViewingRoomApp_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomArtworkDetails_artwork.graphql.ts
  src/__generated__/ViewingRoomCarousel_artwork.graphql.ts
  src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomIntro_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomStatementRoute_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomSubsections_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomWorksRoute_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomWorks_viewingRoom.graphql.ts
  src/__generated__/routes_ViewingRoomQuery.graphql.ts
  src/__generated__/routes_ViewingRoomStatementRouteQuery.graphql.ts
  src/__generated__/routes_ViewingRoomWorksRouteQuery.graphql.ts
Labels: Version: Patch

#3501 Bump yarn orb to ensure forks still aren't failing
  .circleci/config.yml
Labels: Version: Trivial

#3504 Fallback to base route if no route found through index
  src/Artsy/Router/Utils/findCurrentRoute.tsx
Labels: Version: Patch

#3500 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3502 adding pullQuote to VR
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomPullQuote.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomSubsections.tsx
  src/Apps/ViewingRoom/Routes/Statement/ViewingRoomStatementRoute.tsx
  src/__generated__/ViewingRoomPullQuote_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomStatementRoute_viewingRoom.graphql.ts
  src/__generated__/routes_ViewingRoomStatementRouteQuery.graphql.ts
Labels: Version: Patch

#3503 Build conversation text input
  src/Apps/Conversation/Components/Conversation.tsx
  src/Apps/Conversation/Components/Reply.tsx
Labels: Jira Synced, Version: Patch

#3509 Responsive conversations layout
  src/Apps/Conversation/Components/Conversation.tsx
  src/Apps/Conversation/Components/ConversationSnippet.tsx
  src/Apps/Conversation/Components/Conversations.tsx
  src/Apps/Conversation/Components/Details.tsx
  src/Apps/Conversation/Components/InboxHeaders.tsx
  src/Apps/Conversation/Components/Reply.tsx
  src/Apps/Conversation/Components/TimeSince.tsx
  src/Apps/Conversation/ConversationApp.tsx
  src/Apps/Conversation/Routes/Conversation/index.tsx
  src/Apps/Conversation/__tests__/ConversationApp.test.tsx
  src/Apps/__tests__/Fixtures/Conversation.ts
  src/__generated__/ConversationAppTestQuery.graphql.ts
  src/__generated__/ConversationApp_me.graphql.ts
  src/__generated__/ConversationSnippet_conversation.graphql.ts
  src/__generated__/Conversation_me.graphql.ts
  src/__generated__/ConversationsQuery.graphql.ts
  src/__generated__/Conversations_me.graphql.ts
  src/__generated__/routes_ConversationQuery.graphql.ts
  src/__generated__/routes_DetailQuery.graphql.ts
Labels: Merge On Green, Version: Minor

#3510 Readd mobile inbox header
  src/Apps/Conversation/Components/Conversations.tsx
  src/Apps/Conversation/Components/InboxHeaders.tsx
  src/Apps/Conversation/ConversationApp.tsx
  src/__generated__/ConversationAppTestQuery.graphql.ts
  src/__generated__/ConversationApp_me.graphql.ts
  src/__generated__/routes_ConversationQuery.graphql.ts
Labels: Version: Patch

#3508 [Viewing Room] Add carousel support
  src/Apps/Artist/routes.tsx
  src/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
  src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/Apps/ViewingRoom/Components/ViewingRoomMeta.tsx
  src/Apps/ViewingRoom/Components/ViewingRoomTabBar.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomSubsections.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx
  src/Apps/ViewingRoom/Routes/Statement/ViewingRoomStatementRoute.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
  src/Apps/ViewingRoom/Routes/Works/ViewingRoomWorksRoute.tsx
  src/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/Apps/ViewingRoom/routes.tsx
  src/Apps/__stories__/AppShell.story.tsx
  src/Apps/__stories__/ViewingRoom.story.tsx
  src/Artsy/Router/Utils/shouldUpdateScroll.tsx
  src/Artsy/Router/buildClientApp.tsx
  src/Components/Carousel.tsx
Labels: Version: Patch

#3515 Conversations view unread indicator
  src/Apps/Collect/Routes/Collection/Components/CollectionsHubRails/FeaturedCollectionsRails/__tests__/FeaturedCollectionsRails.test.tsx
  src/Apps/Conversation/Components/ConversationSnippet.tsx
  src/Apps/Conversation/Components/Conversations.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/Modal.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/index.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Modal.tsx
Labels: Jira Synced, Version: Patch

#3517 Roughs in Feature app UI
  src/Apps/Feature/Components/FeatureFeaturedLink.tsx
  src/Apps/Feature/Components/FeatureHeader.tsx
  src/Apps/Feature/Components/FeatureSet.tsx
  src/Apps/Feature/Components/__stories__/FeatureFeaturedLink.story.tsx
  src/Apps/Feature/Components/__stories__/FeatureHeader.story.tsx
  src/Apps/Feature/Components/__tests__/fixtures.ts
  src/Apps/Feature/FeatureApp.tsx
  src/Apps/__stories__/FeatureApp.story.tsx
  src/__generated__/FeatureApp_feature.graphql.ts
  src/__generated__/FeatureHeader_feature.graphql.ts
  src/__generated__/routes_FeatureQuery.graphql.ts
Labels: Version: Patch

#3521 Removes placeholders to fix build
  src/Apps/Feature/FeatureApp.tsx
Labels: Merge On Green

#3523 [Viewing Room] QA
  src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/Apps/ViewingRoom/Components/ViewingRoomMeta.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
  src/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/Components/Carousel.tsx
  src/__generated__/ViewingRoomApp_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomMeta_viewingRoom.graphql.ts
  src/__generated__/routes_ViewingRoomQuery.graphql.ts
Labels: Version: Patch

#3514 Move tracking code for buyers premium link click
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarAuctionPartnerInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCurrentBidInfo.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCurrentBidInfo.test.tsx
  src/index.ts
Labels: Version: Patch

#3511 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3526 Fix carousel init
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
  src/Components/Carousel.tsx
Labels: Version: Patch

#3525 [Viewing Room] Add tests
  .eslintrc.js
  src/Apps/ViewingRoom/Components/__tests__/ViewingRoomHeader.test.tsx
  src/Apps/ViewingRoom/Components/__tests__/ViewingRoomTabBar.test.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx
  src/Apps/ViewingRoom/Routes/Statement/__tests__/ViewingRoomStatementRoute.test.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/Apps/ViewingRoom/Routes/Works/__tests__/ViewingRoomWorksRoute.test.tsx
  src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomAppFixture.ts
  src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomStatementRouteFixture.ts
  src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomWorksRouteFixture.ts
  src/Apps/ViewingRoom/__tests__/ViewingRoomApp.test.tsx
  src/Artsy/Router/RouterLink.tsx
  src/__generated__/ViewingRoomApp_Test_Query.graphql.ts
  src/__generated__/ViewingRoomStatementRoute_Test_Query.graphql.ts
  src/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts
Labels: Version: Patch

#3528 additional_information should be displayed for artworks in VR
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomWorksRouteFixture.ts
  src/__generated__/ViewingRoomArtworkDetails_artwork.graphql.ts
  src/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts
  src/__generated__/routes_ViewingRoomWorksRouteQuery.graphql.ts
Labels: Version: Patch

#3527 Wires up OrderedSets and FeaturedLinks to real data
  src/Apps/Feature/Components/FeatureFeaturedLink.tsx
  src/Apps/Feature/Components/FeatureHeader.tsx
  src/Apps/Feature/Components/FeatureSet.tsx
  src/Apps/Feature/Components/__tests__/fixtures.ts
  src/Apps/Feature/FeatureApp.tsx
  src/__generated__/FeatureApp_feature.graphql.ts
  src/__generated__/FeatureFeaturedLink_featuredLink.graphql.ts
  src/__generated__/FeatureHeader_feature.graphql.ts
  src/__generated__/FeatureSet_set.graphql.ts
  src/__generated__/routes_FeatureQuery.graphql.ts
Labels: Version: Patch

#3533 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3534 Restore accidentally deleted index.ts entrypoint file
  src/index.ts
Labels: Version: Patch

#3529 Show complete modal conditionally showing reauth prompt
  src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
  src/__generated__/AppSecondFactorStorySuccessQuery.graphql.ts
  src/__generated__/AppSecondFactor_me.graphql.ts
  src/__generated__/SmsSecondFactorStoryErrorQuery.graphql.ts
  src/__generated__/SmsSecondFactorStorySuccessQuery.graphql.ts
  src/__generated__/SmsSecondFactorStoryUndeliverableQuery.graphql.ts
  src/__generated__/SmsSecondFactorStoryUpdateErrorQuery.graphql.ts
  src/__generated__/SmsSecondFactor_me.graphql.ts
  src/__generated__/TwoFactorAuthenticationQuery.graphql.ts
  src/__generated__/TwoFactorAuthenticationRefetchQuery.graphql.ts
  src/__generated__/TwoFactorAuthenticationTestQuery.graphql.ts
Labels: Version: Minor, canary

#3518 Purchase auth triggers use Sign up rather than Log in form
  src/Apps/Artwork/Components/ArtworkSidebar/ArtworkSidebarCommercial.tsx
  src/Apps/Artwork/Components/ArtworkSidebar/__tests__/ArtworkSidebarCommercial.test.tsx
Labels: Version: Patch

#3536 Artwork appears stretched in conversation thread
  src/Apps/Conversation/Components/Conversation.tsx
  src/__generated__/Conversation_conversation.graphql.ts
  src/__generated__/routes_DetailQuery.graphql.ts
Labels: Jira Synced, Version: Patch

#3535 replace endAt with formatted value for endAt
  src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/Apps/ViewingRoom/Components/ViewingRoomMeta.tsx
  src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomAppFixture.ts
  src/Apps/ViewingRoom/__tests__/ViewingRoomApp.test.tsx
  src/__generated__/ViewingRoomApp_Test_Query.graphql.ts
  src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomMeta_viewingRoom.graphql.ts
  src/__generated__/routes_ViewingRoomQuery.graphql.ts
Labels: Version: Patch

#3538 Redirect to /log_in vs reloading upon initial 2FA setup
  src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
Labels: Version: Patch, canary

#3541 #trivial - data-test attrs for Artwork auth
  src/Apps/Artwork/Components/ArtistInfo.tsx
  src/Apps/Artwork/Components/ArtworkDetails/ArtworkDetailsAboutTheWorkFromPartner.tsx
  src/Apps/Artwork/Components/ArtworkDetails/RequestConditionReport.tsx
  src/Apps/Artwork/Components/ArtworkDetails/index.tsx
  src/Apps/Artwork/Components/ArtworkImageBrowser/index.tsx
  src/Apps/Artwork/Components/ArtworkRelatedArtists.tsx
Labels: Merge On Green

#3542 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3543 Make tracking exclusion more robust
  package.json
  src/Artsy/Analytics/__tests__/trackingMiddleware.test.ts
  src/Artsy/Analytics/trackingMiddleware.ts
  src/Artsy/Router/buildClientApp.tsx
  yarn.lock
Labels: Version: Patch

#3544 [COM-20] - handle missing data and include pricing info on VR artwork
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomIntro.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomPullQuote.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomSubsections.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/Apps/ViewingRoom/Routes/Works/__tests__/ViewingRoomWorksRoute.test.tsx
  src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomWorksRouteFixture.ts
  src/__generated__/ViewingRoomArtworkDetails_artwork.graphql.ts
  src/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts
  src/__generated__/routes_ViewingRoomWorksRouteQuery.graphql.ts
Labels: Version: Patch

#3545 Fix carousel
  package.json
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
  src/Apps/__stories__/ViewingRoom.story.tsx
  src/Components/Carousel.tsx
  yarn.lock
Labels: Version: Patch

#3549 Minor Feature page Q/A
  data/schema.graphql
  src/Apps/Feature/Components/FeatureFeaturedLink.tsx
  src/Apps/Feature/Components/FeatureHeader.tsx
  src/Apps/Feature/Components/FeatureSet.tsx
  src/Apps/Feature/Components/__stories__/FeatureFeaturedLink.story.tsx
  src/Apps/Feature/Components/__tests__/fixtures.ts
  src/Apps/Feature/FeatureApp.tsx
  src/Apps/Feature/__tests__/fixtures.ts
  src/__generated__/FeatureApp_Test_Query.graphql.ts
  src/__generated__/FeatureApp_feature.graphql.ts
  src/__generated__/FeatureFeaturedLink_featuredLink.graphql.ts
  src/__generated__/FeatureHeader_feature.graphql.ts
  src/__generated__/routes_FeatureQuery.graphql.ts
Labels: Version: Patch

#3548 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3551 [Viewing Room] Ensure fixed widths present
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
  src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomWorksRouteFixture.ts
  src/Apps/__stories__/ViewingRoom.story.tsx
  src/__generated__/ViewingRoomCarousel_artwork.graphql.ts
  src/__generated__/ViewingRoomWorksRoute_Test_Query.graphql.ts
  src/__generated__/routes_ViewingRoomWorksRouteQuery.graphql.ts
Labels: Version: Patch

#3550 Ensure test checks don't validate actual dates
  src/Apps/Conversation/__tests__/ConversationApp.test.tsx
Labels: Merge On Green, Version: Patch

#3552 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3539 Update a conversation to be read once it's opened
  src/Apps/Conversation/Components/Conversation.tsx
  src/Apps/Conversation/Mutation/UpdateConversationMutation.ts
  src/__generated__/UpdateConversationMutation.graphql.ts
Labels: Jira Synced, Version: Patch

#3555 [Viewing Room] Add tracking
  src/Apps/Feature/Components/FeatureMeta.tsx
  src/Apps/Feature/FeatureApp.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx
  src/Apps/ViewingRoom/Routes/Statement/__tests__/ViewingRoomStatementRoute.test.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/Apps/ViewingRoom/Routes/Works/__tests__/ViewingRoomWorksRoute.test.tsx
  src/Artsy/Analytics/Schema/Values.ts
  src/__generated__/FeatureApp_Test_Query.graphql.ts
  src/__generated__/FeatureApp_feature.graphql.ts
  src/__generated__/FeatureMeta_feature.graphql.ts
  src/__generated__/ViewingRoomApp_Test_Query.graphql.ts
  src/__generated__/ViewingRoomHeader_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomIntro_viewingRoom.graphql.ts
  src/__generated__/ViewingRoomStatementRoute_Test_Query.graphql.ts
  src/__generated__/routes_FeatureQuery.graphql.ts
Labels: Version: Patch

#3557 [Consignments] Swap masonry component
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignFAQ.tsx
  src/Apps/Artist/Routes/Consign/Components/ArtistConsignHeader/ArtistConsignHeaderImages.tsx
Labels: Version: Patch

#3556 [Feature] Add meta tags
  src/Apps/Feature/Components/FeatureMeta.tsx
  src/Apps/Feature/__tests__/fixtures.ts
  src/Apps/ViewingRoom/Routes/Statement/__tests__/ViewingRoomStatementRoute.test.tsx
  src/Apps/ViewingRoom/Routes/Works/__tests__/ViewingRoomWorksRoute.test.tsx
  src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomAppFixture.ts
  src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomStatementRouteFixture.ts
  src/Apps/ViewingRoom/__tests__/Fixtures/ViewingRoomWorksRouteFixture.ts
  src/Apps/ViewingRoom/__tests__/ViewingRoomApp.test.tsx
  src/__generated__/FeatureApp_Test_Query.graphql.ts
  src/__generated__/FeatureMeta_feature.graphql.ts
  src/__generated__/routes_FeatureQuery.graphql.ts
  tsconfig.json
  typings/sharify.d.ts
Labels: Merge On Green, Version: Patch

#3560 Add Conversations storybook
  src/Apps/__stories__/ConversationApp.story.tsx
Labels: Version: Trivial

#3553 Fix contextModule on /Tag page, Forgot link includes existing query params
  src/Components/Authentication/Mobile/LoginForm.tsx
  src/Components/Authentication/__tests__/Mobile/LoginForm.test.tsx
  src/Components/Tag/TagArtworks.tsx
Labels: Version: Patch, canary

#3561 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3562 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3563 [ViewingRoom] Make sure width is auto on carousel
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
Labels: Version: Patch

#3564 Fix vertical alignment of CountrySelect ::after element
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Modal.tsx
Labels: Merge On Green, Version: Patch

#3565 Autofocus 2FA authentication code fields
  src/Components/Authentication/Desktop/LoginForm.tsx
  src/Components/Authentication/Mobile/LoginForm.tsx
Labels: Merge On Green, Version: Minor

#3566 Add responsive styles to 2FA Enrollment UI
  src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/Modal.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/index.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/Modal.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
  src/Components/UserSettings/TwoFactorAuthentication/index.tsx
Labels: Version: Minor

#3567 2FA enrollment responsive fix: switch to maxWidth
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
Labels: Merge On Green, Version: Patch

#3568 [Thread Preview] style tweaks
  src/Apps/Conversation/Components/ConversationSnippet.tsx
Labels: Jira Synced, Version: Patch

#3573 Forgot password form can switch to signup form
  src/Components/Authentication/Desktop/ForgotPasswordForm.tsx
  src/Components/Authentication/__tests__/Desktop/ForgotPasswordForm.test.tsx
Labels: Version: Patch

#3571 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Patch

#3577 Update BorderBoxProps import
  src/Components/UserSettings/TwoFactorAuthentication/Components/AppSecondFactor/index.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/BackupSecondFactorModalContent.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/BackupSecondFactor/index.tsx
  src/Components/UserSettings/TwoFactorAuthentication/Components/SmsSecondFactor/index.tsx
Labels: Merge On Green, Version: Trivial

#3570 Feature landing page Q/A
  src/Apps/Feature/Components/FeatureFeaturedLink.tsx
  src/Apps/Feature/Components/FeatureHeader.tsx
  src/Apps/Feature/Components/FeatureSet.tsx
  src/Apps/Feature/FeatureApp.tsx
  src/Apps/__stories__/FeatureApp.story.tsx
Labels: Merge On Green, Version: Patch

#3578 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ArtistSearchResultsArtistMutation.graphql.ts
  src/__generated__/BudgetUpdateMyUserProfileMutation.graphql.ts
  src/__generated__/CCPARequestMutation.graphql.ts
  src/__generated__/CollectorIntentUpdateCollectorProfileMutation.graphql.ts
  src/__generated__/ConfirmBidCreateBidderPositionMutation.graphql.ts
  src/__generated__/FollowArtistButtonMutation.graphql.ts
  src/__generated__/FollowArtistMutation.graphql.ts
  src/__generated__/FollowArtistPopoverRowMutation.graphql.ts
  src/__generated__/FollowGeneButtonMutation.graphql.ts
  src/__generated__/FollowProfileButtonMutation.graphql.ts
  src/__generated__/GeneSearchResultsFollowGeneMutation.graphql.ts
  src/__generated__/IdentityVerificationAppStartMutation.graphql.ts
  src/__generated__/PaymentFormCreateCreditCardMutation.graphql.ts
  src/__generated__/PaymentPickerCreateCreditCardMutation.graphql.ts
  src/__generated__/PopularArtistsFollowArtistMutation.graphql.ts
  src/__generated__/RegisterCreateBidderMutation.graphql.ts
  src/__generated__/RegisterCreateCreditCardAndUpdatePhoneMutation.graphql.ts
  src/__generated__/SaveArtworkMutation.graphql.ts
  src/__generated__/SavedCreditCardsDeleteCreditCardMutation.graphql.ts
  src/__generated__/SendConversationMessageMutation.graphql.ts
  src/__generated__/SendFeedbackSearchResultsMutation.graphql.ts
  src/__generated__/SuggestedGenesFollowGeneMutation.graphql.ts
  src/__generated__/UpdateConversationMutation.graphql.ts
  src/__generated__/createTestEnvCreditCardMutation.graphql.ts
Labels: Merge On Green, Version: Minor

#3579 [Viewing Room] QA
  src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewWorksButton.tsx
  src/Apps/ViewingRoom/Routes/Statement/Components/ViewingRoomWorks.tsx
  src/Apps/ViewingRoom/Routes/Statement/Utils/scrollToId.tsx
  src/Apps/ViewingRoom/Routes/Statement/ViewingRoomStatementRoute.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomArtworkDetails.tsx
  src/Apps/ViewingRoom/Routes/Works/Components/ViewingRoomCarousel.tsx
  src/Apps/ViewingRoom/Routes/Works/ViewingRoomWorksRoute.tsx
  src/Apps/ViewingRoom/ViewingRoomApp.tsx
  src/Apps/__stories__/ViewingRoom.story.tsx
  src/Components/Footer.tsx
Labels: Version: Patch

#3582 Minor fixes for legacy feature pages
  src/Apps/Feature/Components/FeatureSet.tsx
  src/Apps/__stories__/FeatureApp.story.tsx
Labels: Version: Minor

#3583 add unstable_trackIn to titles in VR, feature and featured Link
  src/Apps/Feature/Components/FeatureFeaturedLink.tsx
  src/Apps/Feature/Components/FeatureHeader.tsx
  src/Apps/ViewingRoom/Components/ViewingRoomHeader.tsx
Labels: Version: Minor

#3558 Convert price filter to radio [FX-1944]
  package.json
  src/Components/v2/ArtworkFilter/ArtworkFilters/PriceRangeFilter.tsx
  src/Components/v2/ArtworkFilter/ArtworkFilters/__tests__/PriceRangeFilter.test.tsx
  yarn.lock
Labels: Version: Patch

#3569 Conversation not updated correctly when new messages is entered by collector
  src/Apps/Conversation/Components/Reply.tsx
Labels: Jira Synced, Version: Patch

#3584 Update metaphysics schema
  data/schema.graphql
Labels: Merge On Green, Version: Minor

#3572 Show prices on default view of artist auction results.
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResultItem.tsx
  src/Apps/Artist/Routes/AuctionResults/ArtistAuctionResults.tsx
  src/Apps/Artist/Routes/AuctionResults/AuctionResultsFilterContext.tsx
  src/Apps/Artist/Routes/AuctionResults/__tests__/AuctionResults.test.tsx
Labels: Version: Minor

#3576 email confirmation message banner
  src/Components/FlashBanner.tsx
  src/Components/MinimalCtaBanner.tsx
  src/Components/__stories__/CtaBanner.story.tsx
  src/Components/__stories__/FlashBanner.story.tsx
  src/Components/__tests__/FlashBanner.test.tsx
Labels: Version: Patch

#3589 Email confirmation message copy updates
  src/Components/FlashBanner.tsx
Labels: Jira Synced, Version: Minor

#3585 Update metaphysics schema
  data/schema.graphql
  src/__generated__/ArtistConsignMarketTrends_artist.graphql.ts
  src/__generated__/ArtistConsignPageViews_artist.graphql.ts
  src/__generated__/ConsignRoute_Test_Query.graphql.ts
  src/__generated__/routes_ArtistConsignQuery.graphql.ts
Labels: Merge On Green, Version: Minor

#3591 Remove tracking calls for now
  src/Apps/Artwork/ArtworkApp.tsx
  src/Artsy/Analytics/trackingMiddleware.ts
  src/Components/Publishing/RelatedArticles/Canvas/RelatedArticleCanvasLink.tsx
  src/Components/Publishing/RelatedArticles/Canvas/RelatedArticlesCanvas.tsx
  src/Components/Publishing/RelatedArticles/Canvas/__tests__/RelatedArticleCanvasLink.test.tsx
  src/Components/Publishing/RelatedArticles/Canvas/__tests__/RelatedArticlesCanvas.test.tsx
  src/Components/Publishing/RelatedArticles/Canvas/__tests__/__snapshots__/RelatedArticlesCanvas.test.tsx.snap
  src/Components/Publishing/RelatedArticles/Panel/RelatedArticlesPanel.tsx
  src/Components/Publishing/RelatedArticles/Panel/RelatedArticlesPanelLink.tsx
  src/Components/Publishing/RelatedArticles/Panel/__tests__/RelatedArticlesPanel.test.tsx
  src/Components/Publishing/RelatedArticles/Panel/__tests__/RelatedArticlesPanelLink.test.tsx
  src/Components/Publishing/RelatedArticles/Panel/__tests__/__snapshots__/RelatedArticlesPanel.test.tsx.snap
Labels: Version: Minor
